### ISSUE TITLE
GPS instead of markers?

### ISSUE THREAD

**Issue by ScottBeeson** [jeromeetienne/AR.js#102]
Any chance of ar.js implementing GPS "markers" instead of physical markers?

**Comment by blq** [comment]
You mean walking into a zone (geofence) and a marker shows up? 
Plain geolocation lookup is quite simple to add I'd say, see for example:
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by ScottBeeson** [comment]
I'll take that as a no :)
