### ISSUE TITLE
Use mjpg stream or canvas instead of the 'local' camera

### ISSUE THREAD

**Issue by WayneKeenan** [jeromeetienne/AR.js#103]
Hi,

Instead of using the local camera is it possible to use a (mjpg) stream coming from a remote camera? or, perhaps use an html5 canvas (which happens to have a camera image rendered to it) ?

Thanks
wayne

**Comment by blq** [comment]
Yes. Many of the demos has that as an in-code setting already. See for example markerroot.html

**Comment by WayneKeenan** [comment]
Hi,
Thank you for the pointer, I can get the markerroot sample to work and then modify it to point to my camera stream using:

```javascript
	var arToolkitSource = new THREEx.ArToolkitSource({
		sourceType : 'image',
		sourceUrl : 'http://raspberrypi.local:8080/stream/video.mjpeg',
	})
```

AR.js is being served up from a HTTP server running at `raspberrypi.local:8000` and although the web streaming software, [UV4L](https://www.linux-projects.org/uv4l/) on port 8080 allows hosting user apps,  it would only stream WebRTC so I'm still left with a cross domain issue trying to get from the HTTP app on 8000 to the mjpeg stream 8080.
 
I had to disable CORS in Chrome because I've not yet found a way to enable sending a CORS HTTP header in UVL4 :
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security --user-data-dir`

So, back to AR.js...     after overcoming the UV4L imposed issues, cross domain errors are gone and there are no errors in the JS console, I only see the video stream, but no object recognition.   Any ideas?

Thanks
Wayne

**Comment by WayneKeenan** [comment]
Hi,

With no CORS tricks or workarounds and changing from UV4L to [RasPiCam](http://elinux.org/RPi-Cam-Web-Interface) where earthing can be hosted in Apache, I still can't get a mjpeg stream to work.   

I modified: http://raspberrypi.local/AR.js/three.js/examples/markerroot.html

To point to :  `sourceUrl : '/html/cam_pic_new.php?time=1498467261019&pDelay=40000',`

I tried setting `sourceType` to `image` and in hope `video`, only `image displays the streamed vide but not the Hiro overlay object.

Should I be creating my own canvas (and updating it via `setInterval`) and passing that to  `ArToolkitSource`  somehow?  

When the Cross domain error occurred it was obvious the AR.js was attempting to access the MJPEG underling canvas and now that CORS is no longer an issue that exception has gone away, so I assume AR.js is reading the data ok.   

Could this be a data/pixel format issue?

Thanks
Wayne

**Comment by DJviolin** [comment]
Maybe I have a related issue: https://codepen.io/DJviolin/pen/xryMNj

I also want to have an image or a video as a webcam source for testing purposes, but the following example still wants to open my webcam (which I don't have). Is it possible to turn off the webcam lookup?

**Comment by WayneKeenan** [comment]
Has anyone else had the time to take a look at this or might have any suggestions?
Thanks, Wayne

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
