### ISSUE TITLE
Support ARKit thru phonegap plugin

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#104]
- it is possible - sketchfab did it - https://twitter.com/Sketchfab/status/875399739797364737

**Comment by jeromeetienne** [comment]
# interested people
- https://twitter.com/karanganesan
- @darasat who worked on webrtc on ios before ios11
- @revolunet with https://github.com/revolunet/ios-webrtc

**Comment by karanganesan** [comment]
What about the other side ? Android ?

**Comment by jeromeetienne** [comment]
@karanganesan ARKit is apple ios only. im not sure i understand. what do you mean ?

**Comment by karanganesan** [comment]
I know ARKit is iOS only ! What will be some equivalent for it on Android ?

**Comment by jeromeetienne** [comment]
oh i see. sorry lack of sleep here. on tango android, AR.js will provide tango tracking. on non-tango android, AR.js will provide a tracking using webstandard (getUserMedia+artoolkit)

About AR.js and various tracking, The current plane is ..  :)

- on android/ios with web technologies, we can use the webcam and provide pure web tracking with getUserMedia. Aka artoolkit kind of thing
- on ios, provide ARKit with a phonegap app. in any case, people willing to use ARKit will have to install an apps. No matter how they wrote the apps. AR.js, native, unity.
- on tango, provide tango tracking. Currently only available via chromium-webar. it will likely be included in chrome later.

So ar.js will provide the various trackings available on the device you are running. and you will be able to pick the one that fit your need.

i hope this help

**Comment by karanganesan** [comment]
ARKit + Hydra 3D engine (internal framework of Active Theory + Three JS) WebGL JS :heart:

https://twitter.com/active_theory/status/883326502850314240

Tweet was posted today !

**Comment by jcyh0120** [comment]
Where can I follow the updates of this feature?

**Comment by nicolocarpignoli** [comment]
@jcyh0120 i dont think someone is working on this :(
