### ISSUE TITLE
Load multiple NFTMarker

### ISSUE THREAD

**Issue by densetsughem** [jeromeetienne/AR.js#107]
hi. how can i load a multiple nftmarker in nft_threejs.html and nft_worker_threejs.html

I encountered errors when i tried to add multiple nftmarker, encountered below error:
artoolkit.js:2500 Uncaught 20966600 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.

**Comment by jeromeetienne** [comment]
sorry nft marker is not supported in ar.js. what you are running is experimental code.
