### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by HelloDeadline** [jeromeetienne/AR.js#11]
Hi! 
I like the idea. I wonder what maximum browser support can be achieved? 

So far I tested the demo on:
**Desktop Chrome with webcam and 2 tabs (one for Hero, one for result)** (works!)
**Android native 4.4.2**  (doesn't work, doesn't ask for permission to use camera. I see white background and text)
**Android native 5.0** (doesn't work, doesn't ask for permission, I see white background and text)
**Chrome on Android 4.4.2** (works!)
**Chrome on Android 5.0** (doesn't work, **asks** for permission, I see black background, text and a chart)
**Safari and Chrome on iOS 8.2 (iPad)**  (doesn't work, doesn't ask for permission, I see white background and text)

Why this may happen? 
Ok, webgl is not supported in native Android up to 4.*, WebRTC  is not supported on Safari.
I still don't get why it doesn't work in Chrome on Android 5.0. 

Any ideas? :)

It would be great to have a list of browsers that can run this demo right after a user gives a permission to use the camera. Let me know if I can help.

**Comment by sorianog** [comment]
@jeromeetienne What format would you like the "Browser Support" list to be in (i.e. txt, md, part of the README? I volunteer myself to maintain the list! 😄

**Comment by sorianog** [comment]
Just did a test and saw the following work with the basic demo:
**Microsoft Edge on Windows 10** (Chrome on Google Pixel phone to view hologram)

I pulled down the code and made a branch. Attempted to push my changes to that branch but...

`ERROR: Permission to jeromeetienne/AR.js.git denied to sorianog.`
`fatal: Could not read from remote repository.`

`Please make sure you have the correct access rights`
`and the repository exists.`
 
🙁

**Comment by jeromeetienne** [comment]
hey @sorianog, i think you are trying to push on my repository, you would need to first fork it, and then do a pull request.

**Comment by sorianog** [comment]
@jeromeetienne Ah, that makes sense! I forgot about the "forking". Here is the PR for this issue: #32

**Comment by jeromeetienne** [comment]
Merged, thanks to both of you :)

we can close this one now.

**Comment by darioodiaz** [comment]
Hi @jeromeetienne this project is awesome I love your work and I wish I can contribute, so I was testig the framework on differente devices and you can update the browser support list

I have a LG g3 d693ar with hasn't gyroscope and has Android 4.4.2 so the camera feature dont work but I test it with Chrome for Android and said "cant access user media" I test it with Chrome Canary and works but doesn't show the <a-text> (I will test with a-text-geometry) but I install Firefox for Android and it works so Firefox for this Android version works (still not showing the text)

A friend has a Sony z2 with Android 6.0.1 with normal Chrome and it works

I will test in other Android version with Firefox to see if works and I notify you.

Amazing work!

**Comment by sorianog** [comment]
@darioodiaz Thank you for the new information and your testing! Keep 'em coming!

**Comment by darioodiaz** [comment]
After a few tests @jeromeetienne  @sorianog this is the results:

iOS with Chrome: works nice but a-text dont show (amazing fps)

Android 4.4.2:
- Chrome: idem iOS with Chrome so I think that is a Chrome webGL bug (40 - 60 fps) but dont use the accelerometer for the camera
- Chrome canary: a-text dont work, 35 - 60 fps, use the accelerometer to change the camera orientation
- Firefox: a-text works but low fps (35 - 45)

Android 5.X:
- Maybe works better

Android 6.0.1:
- Chrome works with a-text but was tested on Sony Z2 I dont know if other brands has the same feature

**Comment by fed2186** [comment]
Hi dear friends, i had tested on honor 8 / 10 (android 8) and an old asus zenphone (android 6). The video ar with firefox browser go if enable auto media reproductions in settings....do you have a solution to bypass this problem? With chrome browser i have always problem to load the page in all smartphones
