### ISSUE TITLE
Strange gyroscope issue on Firefox Android

### ISSUE THREAD

**Issue by riechi** [jeromeetienne/AR.js#110]
Hi, i'm using ar.js and aframe to test a project on my Nexus 5, and on Firefox (ver 54.0) I can't get aframe default camera controls (gyro-based on mobile) to work. If I open the console (only on Firefox Android) I see this error repeated continuously: "Invalid timestamps detected. Time step between successive gyroscope sensor samples is very small or not monotonic", even on the ar.js examples that are listed on the readme. This error doesn't occur on PC. 
Any insights? Is this an issue with aframe or ar.js itself? I need camera and gyro controls working for my scenes on mobile, thanks in advance.

**Comment by jeromeetienne** [comment]
It isnt ar.js errors. it is from webvr-polyfill https://github.com/googlevr/webvr-polyfill/issues/201

It is part of webvr-polyfill is part of aframe https://github.com/aframevr/aframe/issues/856

i hope this helps
