### ISSUE TITLE
Image Recognition

### ISSUE THREAD

**Issue by juanmiimaxina** [jeromeetienne/AR.js#112]
Hi, and first of all, thanks you for your amazing work here.

I'm playing a bit with AR.js and it's awesome. But, I want to know if is possible to make some kind of image recognition (Like Vuforia or CraftAR).

JSArToolKit only works with markers (Or at least, that's what I understand), but for example [Traking.js](https://trackingjs.com) or other libraries can recognize images or other thinks. Maybe can we use this libraries to improve AR.js?

Thanks you.

BTW: Sorry for my poor english.

**Comment by jeromeetienne** [comment]
Thanks for your suggestion, im talking actively with tracking.js maintener, so i clearly agree :)

**Comment by davidj-bbc** [comment]
Hey Jerome, did this go anywhere?

**Comment by zyadmardini** [comment]
Hey Jerome , Any updates on this ?

**Comment by Zurdge** [comment]
Lots of demand for this image tracking software. Does anyone know if it developed into something we can use with AR.js?
