### ISSUE TITLE
GET https://jeromeetienne.github.io/AR.js/data/data/camera_para.dat 404 (Not Found)

### ISSUE THREAD

**Issue by pratiksampat** [jeromeetienne/AR.js#113]
The issue arised about 15-20 mins ago and none of my experiences work anymore.
it says 
> GET https://jeromeetienne.github.io/AR.js/data/data/camera_para.dat 404 (Not Found)

Can somebody please help me out here please?

**Comment by jeromeetienne** [comment]
It was a temporary issue due to website update. sorry about that

**Comment by pratiksampat** [comment]
No issues. Closed it as soon as it was fixed. 
Thanks.
