### ISSUE TITLE
trigger a function if camera access is refused.

### ISSUE THREAD

**Issue by pikilipita** [jeromeetienne/AR.js#114]
Would be great to be able to trigger a function if the user do not allow access to the camera, for example to display infos why the page need the camera.

I think it could be done with something like this:
if (typeof cameraAccessRefused == 'function')cameraAccessRefused();

function cameraAccessRefused()
{
...
}

this function being defined out of ar.js, so it can be different for each project

unstead of the javascript alert poping up at the moment

**Comment by abbazabacto** [comment]
Would love to not have this alert as well, to show a more gracefull method. Maybe we some promise which either resolves or rejects.

**Comment by jeromeetienne** [comment]
i just added a onError in source.init(). it is called on error, and if you define this function, no alert() will be done. i hope this help

https://github.com/jeromeetienne/AR.js/blob/master/three.js/threex-artoolkitsource.js#L26

**Comment by abbazabacto** [comment]
awesome!! thanks a million
