### ISSUE TITLE
the back  carmera is not Available

### ISSUE THREAD

**Issue by junzhaok** [jeromeetienne/AR.js#117]
I've already seen the 86 post, but I have some questions about the front and rear cameras, Could you give me some files that help me upload the related files?    
I tested my own app, and it always showed that the front-camera was not available, and the rear camera. 

I am a beginner of the program, hope to get the help of everyone. Could you give me a demo of 86#  THX

**Comment by tetreault** [comment]
@jeromeetienne

**Comment by patricknelson** [comment]
I'd recommend closing this issue in favor of #96 since I think this is probably a duplicate.

**Comment by patricknelson** [comment]
@junzhaok @tetreault  Try my fixes mentioned here: https://github.com/jeromeetienne/AR.js/issues/96#issuecomment-316549132

**Comment by jeromeetienne** [comment]
following @patricknelson recomendation
