### ISSUE TITLE
make video play triggers listen only once

### ISSUE THREAD

**Issue by blq** [jeromeetienne/AR.js#12]
`threex-artoolkitsource.js`
Not a biggie, but I think the "trick to trigger the video on android" event listeners should be turned into listen-once style. I.e `removeEventListener` on the first click.

**Comment by jeromeetienne** [comment]
@blq thanks for spoting this! fixed :)

**Comment by jeromeetienne** [comment]
btw do you have an url for this demo ? https://twitter.com/snigelpaogat/status/835825095184625664

i love the effect :)

**Comment by blq** [comment]
Not online atm. I can send you a msg or gist maybe? I had the idea of donating something similar actually.  Agree that rendering AR-holes is a great party trick :)

**Comment by jeromeetienne** [comment]
hehe exactly, i would like an example like that in AR.js :) yeah put it in a gist, i port it to ar.js repo and put your name in the info <div> ?
