### ISSUE TITLE
Custom Marker Training - Downloaded Pattern not working

### ISSUE THREAD

**Issue by markleeyw** [jeromeetienne/AR.js#127]
https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html

Used the default AR.js image, downloaded the pattern. 

Code:
<script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
	<a-scene embedded arjs='sourceType: webcam;'>
		<a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
		<a-marker-camera type='pattern' patternUrl='http://xxxx/pattern-marker.patt'></a-marker-camera>

	</a-scene>
</body>

Marker not detected. Does anyone get the same problem?

**Comment by MrRaam** [comment]
@markleeyw I think the best option is to train that and include its path in the source code. I did that manually and its working.

**Comment by markleeyw** [comment]
@MrRaam  Any sample on what you did?

**Comment by Dinkelborg** [comment]
I'm getting the same error 
I tried to create a customer marker with the website and get: 
"Pattern Data read error!!
aframe-ar.js:2843 loadMarker(): Error loading pattern file /marker_0.
aframe-ar.js:2843 ARToolKitJS(): Unable to set up AR marker.
aframe-ar.js:2843 Out of memory!!"

I'm also stuck on what to try as I already tried a smaller marker its now less than 400x400 px

**Comment by MrRaam** [comment]
Where are you storing the pattern ? & are you changing the path files in
the ar.js ?

**Comment by markleeyw** [comment]
@MrRaam could you hare how to did yours. It would be helpful

**Comment by Dinkelborg** [comment]
I generated the pattern [here](https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html) where the pdf generation doesn't work btw... but whatever 

I then stored that as "pattern-marker.patt" in the root folder of my site (next to index.html) and then changed the example maker from 
<a-marker-camera preset='hiro'></a-marker-camera> 
to
<a-marker-camera type='pattern' patternUrl='pattern-marker.patt'></a-marker-camera>
I also tried
<a-marker type='pattern' patternUrl='pattern-marker.patt'></a-marker>

Both cause the above mentioned errors - the patt-file looks normal to me - exact same amount of lines as the hiro example pattern and I can clearly see my marker logo in the numbers.

I followed [these steps](https://medium.com/arjs/how-to-create-your-own-marker-44becbec1105) but it's just not working

**Comment by markleeyw** [comment]
@Dinkelborg yup .. i think the code <a-maker-camera> does not work somehow. .. i used their default marker too.

**Comment by markleeyw** [comment]
@Dinkelborg Found this but not time to try ... if you get it to work do let me know https://github.com/jeromeetienne/AR.js/issues/61
Thank you!

**Comment by Dinkelborg** [comment]
@markleeyw 
Awesome man! Thanks a lot, it took quite a while to dig into the aframe-ar.js file, but if you create your own preset, as descried in the post you linked, it does work! 

Now I still hope that they fix the regular <a-marker-camera> tag implementation using the "type='pattern'" and "patternUrl" parameters since that wouldn't require changing the source of the library every time you want to use a custom marker.

**Comment by Dinkelborg** [comment]
You don't have to create your own data folder btw I kept everything as it is, created a custom variable (line 865)
`THREEx.ArToolkitContext.hostURL = './' ` 
directly under (line 864) `THREEx.ArToolkitContext.baseURL = 'https://jeromeetienne.github.io/AR.js/three.js/'`

then I changed the Reset paragraph (line 1195 to 1217) to: 
```
//////////////////////////////////////////////////////////////////////////////
//		Code Separator
//////////////////////////////////////////////////////////////////////////////

/**
 * reset all parameters
 */
THREEx.ArToolkitProfile.prototype.reset = function () {
	this.sourceParameters = {
		// to read from the webcam 
		sourceType : 'webcam',
	}

	this.contextParameters = {
		cameraParametersUrl: THREEx.ArToolkitContext.baseURL + '../data/data/camera_para.dat',
		detectionMode: 'mono',
	}
	this.defaultMarkerParameters = {
		type : 'pattern',
		patternUrl : THREEx.ArToolkitContext.hostURL + 'pattern-marker.patt'
	}
	return this
};
```
(basically only change is under "this.defaultMarkerParameters" where you change the patternUrl)

and then I created a new Marker under (line 1255 to 1280): 
```
//////////////////////////////////////////////////////////////////////////////
//		Marker
//////////////////////////////////////////////////////////////////////////////
THREEx.ArToolkitProfile.prototype.kanjiMarker = function () {
	this.contextParameters.detectionMode = 'mono'

	this.defaultMarkerParameters.type = 'pattern'
	this.defaultMarkerParameters.patternUrl = THREEx.ArToolkitContext.baseURL + '../data/data/patt.kanji'
	return this
}

THREEx.ArToolkitProfile.prototype.hiroMarker = function () {
	this.contextParameters.detectionMode = 'mono'

	this.defaultMarkerParameters.type = 'pattern'
	this.defaultMarkerParameters.patternUrl = THREEx.ArToolkitContext.baseURL + '../data/data/patt.hiro'
	return this
}

THREEx.ArToolkitProfile.prototype.myCustomMarker= function () {
  this.contextParameters.detectionMode = 'mono'
  
  this.defaultMarkerParameters.type = 'pattern'
  this.defaultMarkerParameters.patternUrl = THREEx.ArToolKitContext.hostURL+ 'pattern-marker.patt'
  return this
}
```
(see the last marker was added the rest is default)

and the last step is to add your marker preset to the init function (line 2729) preset check (line 2737 to 2752):
```
		// honor this.data.preset
		if( this.data.preset === 'hiro' ){
			this.data.type = 'pattern'
			this.data.patternUrl = THREEx.ArToolkitContext.baseURL+'examples/marker-training/examples/pattern-files/pattern-hiro.patt'
		}else if( this.data.preset === 'kanji' ){
			this.data.type = 'pattern'
			this.data.patternUrl = THREEx.ArToolkitContext.baseURL+'examples/marker-training/examples/pattern-files/pattern-kanji.patt'
		}else if( this.data.preset === 'area' ){
			this.data.type = 'area'
			// fall through
		}else if( this.data.preset === 'myCustomMarker'){
      this.data.type = 'pattern'
      this.data.patternUrl = THREEx.ArToolkitContext.hostURL+'pattern-marker.patt'
    } else {
			console.assert( this.data.preset === '', 'illegal preset value '+this.data.preset)
		}
``` 
(see the pre-last statement if(this.data.preset === 'myCustomMarker')... ) 


After all of that you can just use your custom preset like the hiro preset so in the html, in the <a-scene> just swap the <a-marker-camera> 'preset' value from 'hiro' to 'myCustomMarker' (or whatever you called yours 

When you try, make sure to clear cache if it doesn't work instantly - but that was all works like a charm for me now

**Comment by MrRaam** [comment]
Sorry couldn't get back on time,

for people who are not able link the pattern url properly, try uploading
the pattern file in Github and then use that file link in the ar.js file.

**Comment by imehrotra** [comment]
@MrRaam were you able to just upload the patt file and add this
`<a-marker-camera type='pattern' patternUrl='https://raw.github.com/username/project/master/pattern-marker.patt'></a-marker-camera> `
to your code and have it recognize it?  As of now, I am just trying to get it to work with the provided new Ar.js marker and I get the console output:

"Pattern Data read error!!
aframe-ar.js:2843 loadMarker(): Error loading pattern file /marker_0.
aframe-ar.js:2843 ARToolKitJS(): Unable to set up AR marker.
aframe-ar.js:2843 Out of memory!!"

**Comment by Dinkelborg** [comment]
@imehrotra 
You are experiencing the same problem I had. 
The steps I describe above should work for you, can you explain what went wrong when you tried changing the code? 
I was going to try and find out where the <a-marker-camera> tag recognition is broken in the aframe-ar.js file, but for once it's kinda huge and I didn't make it, besides that I didn't have the time yet. 
I think that they expect the custom maker pattern files in a specific folder, but that isn't really stated clearly - it might as well be that it's just broken

**Comment by imehrotra** [comment]
When I change the code, I don't get any errors, but it just doesn't detect the marker.  I think there might be something wrong with my script urls in the html ar.js file.  What did you change the scripts too?  Right now, mine are set as
```
  <script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
  <script src="ar/aframe/build/aframe-ar.js"></script> // this is my local copy of the edited code
```

**Comment by Dinkelborg** [comment]
I went over the changes I made in the aframe-ar.js file step by step and pointed out what exactly I changed... I don't think I could make that any clearer ... 
Your urls look fine these are in the head-section of my index.html: 
`  <script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
  <script src="js/aframe-ar.js"></script>//My changed local copy
  <script>THREEx.ArToolkitContext.baseURL = 'https://rawgit.com/jeromeetienne/AR.js/master/three.js/'</script>
  <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">`

**Comment by MrRaam** [comment]
@imehrotra <https://github.com/imehrotra> you are almost there, I didn't
use the pattern url like as you did instead i referenced a my own marker
variable by making changes in aframe-ar.js, you have to change in
aframe-ar.js just like @Dinkelborg did, i think it's almost the same which
i did with few variations. Let me know if you are still not able to get
that.

ᐧ

**Comment by imehrotra** [comment]
I'm not sure what the issue was originally, but I redid the steps and it works now - thanks for your help! @Dinkelborg  @MrRaam

**Comment by machenmusik** [comment]
Looks like the syntax for `<a-marker-camera>` is something like
`<a-marker-camera type='pattern' url='your-url-here'></a-marker-camera>`

**Comment by khookeiwai** [comment]
@machenmusik it works for me! thanks!

**Comment by kumarahir** [comment]
@machenmusik following code works for me too !

Looks like the syntax for `<a-marker-camera>` is something like
`<a-marker-camera type='pattern' url='your-url-here'></a-marker-camera>`
(not patternURL)

**Comment by machenmusik** [comment]
Great!  Perhaps this issue can be closed then.

**Comment by Dinkelborg** [comment]
Hi @achatt89 , I believe I worked with version 1.0.0 my files are from the 12th of July. 
Yeah at least with my work-around only one marker could be trained, but seeing that several other users like @machenmusik report the a-marker-camera tag to be working I believe my fix should no longer be necessary

I didn't try their solution, does <a-marker-camera type='pattern' url='your-url-here'></a-marker-camera> 
Work for you? The docs say patternURL but apparently it's just url instead

**Comment by achatt89** [comment]
Hi..
Thanks for the reply mate :)
Nope patternUrl doesn't work.. Haven't tried just URL though...
Following your method, it does work fine for just one custom marker... But
the project I am trying to implement requires multiple custom markers to be
trained. I also noticed that the latest version of aframe-ar.js has Kanji
marker removed for some reason..

Anyways...thank you very much for the original assist with the custom
marker training.. it worked just fine..

Cheers.. :)
P.S. I will keep digging for multiple custom marker training and will keep
you posted if I am successful..

**Comment by sonalranjit** [comment]
@kumarahir which version of the aframe-ar.js are you using, im following the latest 1.5.0 but using url for the marker is not working for me.

**Comment by achatt89** [comment]
@jeromeetienne / @Dinkelborg / @MrRaam:
the <a-marker-camera> tag doesn't seem to be working for using custom patterns. I have tried with both patternUrl & url. 
I am using version 1.5.1.

@machenmusik : It seems to be working for you. Can you confirm on how you achieved it?

Regards..

**Comment by MrRaam** [comment]
@Abhijit can i see the error log if there is any?

**Comment by achatt89** [comment]
@MrRaam / @jeromeetienne 
Here's the code what I am using: 
`
<a-scene embedded arjs='sourceType: webcam;'>
    <a-assets>
        <img id="building_info" src="./images/building_info.png">
    </a-assets>
    <a-image src="#building_info" position="0 0 0" scale="2.5 2.5 2.5" rotate="0 0 90"></a-image>

    
    <a-marker-camera type='pattern' url='./patterns/green-triangle-marker.patt'></a-marker-camera>

</a-scene>`

There's no console error.
The pattern doesn't even load nor is recognised while trying to scan.
Its not shown in the network/sources tab.

Regards..

**Comment by MrRaam** [comment]
Hi,

Please upload that .patt files in github and place that link in the url. it
should work. Cheers !

**Comment by achatt89** [comment]
@MrRaam : 
Hi..
That doesn't work. I have tried it before..
Here's the link to my patt file:

https://github.com/achatt89/abhijitchatterjee.com/blob/master/green-triangle-marker.patt
Cheers.. :)

**Comment by wimvdc** [comment]
Hi guys,

I think I solved the issue in #164 (check the PR).

**Comment by kumarahir** [comment]
@sonalranjit using latest 0.6.0 version of aframe and aframe-ar is directly being loaded from https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js

This is working perfectly
```
<script src="../lib/0.6.0/aframe.min.js"></script>
<!-- include ar.js for A-Frame -->
<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs>
	<a-assets>
		<a-asset-item id='wolf' src='Wolf.obj'></a-asset-item>
	</a-assets>
   
	<!-- define a camera which will move according to the marker position -->
	<a-marker type='pattern' url='letterk.patt'>
		<a-obj-model src="#wolf" scale="0.01 0.01 0.01"></a-obj-model>
	</a-marker>
	<a-entity camera></a-entity>
  </a-scene>
</body>
```

**Comment by sonalranjit** [comment]
@kumarahir i tired your way still only triggering for the default Hiro pattern. 
`<html>

<head>
    
    <script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
    <script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
    
    <title>Patio AR</title>
</head>

<body style='margin : 0px; overflow: hidden;'>
   
    <a-scene embedded arjs>
        <a-assets>
            <a-asset-item id="nike-waffle-obj" src="data/models/nike.obj"></a-asset-item>
            <a-asset-item id="nike-waffle-mtl" src="data/models/nike.mtl"></a-asset-item>
        </a-assets>
        <a-marker type='pattern' url='nike-pattern.patt' >
            <a-entity obj-model="obj: #nike-waffle-obj; mtl: #nike-waffle-mtl" scale="0.3 0.3 0.3" rotation="0 0 0" position="0 0 0">
            </a-entity>
        </a-marker>
        <a-entity camera></a-entity>

</body>

</html>`

will checkout @wimvdc 's fix

**Comment by vin-ni** [comment]
I made it work with these instructions:
https://github.com/jeromeetienne/AR.js/issues/164#issuecomment-332065686

**Comment by machenmusik** [comment]
Looking at what @vin-ni used,

It seems as though the common mistake is trying to use `a-marker` when the correct primitive to use is `a-marker-camera` - I am pretty sure that I didn't need to change to light grey etc.

**Comment by saurabh183** [comment]
After following instructions mentioned in #164, I have created custom marker (dd.patt) but still facing the problem of marker detection. 

Code is -  
`<a-scene embedded arjs>
      <a-box position='0 0.5 0' color="blue"></a-box>
      <a-marker-camera preset='custom' type='pattern' url='dd.patt'></a-marker-camera>
      <a-marker-camera preset='hiro'></a-marker-camera>
  </a-scene>`

[sadigitaldiaries.com](url)

Opened above url in mobile. It is able to detect hiro, but not custom(dd). Kindly assist to resolve the issue. 

Markers: 
![ar](https://user-images.githubusercontent.com/20523391/32187114-00627ade-bdca-11e7-8523-7766b25ecee0.jpg)

**Comment by IgorDePaula** [comment]
Nothing this work for me =/

**Comment by Kimara5** [comment]
> You don't have to create your own data folder btw I kept everything as it is, created a custom variable (line 865)
> `THREEx.ArToolkitContext.hostURL = './' `
> directly under (line 864) `THREEx.ArToolkitContext.baseURL = 'https://jeromeetienne.github.io/AR.js/three.js/'`
> 
> then I changed the Reset paragraph (line 1195 to 1217) to:
> 
> ```
> //////////////////////////////////////////////////////////////////////////////
> //		Code Separator
> //////////////////////////////////////////////////////////////////////////////
> 
> /**
>  * reset all parameters
>  */
> THREEx.ArToolkitProfile.prototype.reset = function () {
> 	this.sourceParameters = {
> 		// to read from the webcam 
> 		sourceType : 'webcam',
> 	}
> 
> 	this.contextParameters = {
> 		cameraParametersUrl: THREEx.ArToolkitContext.baseURL + '../data/data/camera_para.dat',
> 		detectionMode: 'mono',
> 	}
> 	this.defaultMarkerParameters = {
> 		type : 'pattern',
> 		patternUrl : THREEx.ArToolkitContext.hostURL + 'pattern-marker.patt'
> 	}
> 	return this
> };
> ```
> (basically only change is under "this.defaultMarkerParameters" where you change the patternUrl)
> 
> and then I created a new Marker under (line 1255 to 1280):
> 
> ```
> //////////////////////////////////////////////////////////////////////////////
> //		Marker
> //////////////////////////////////////////////////////////////////////////////
> THREEx.ArToolkitProfile.prototype.kanjiMarker = function () {
> 	this.contextParameters.detectionMode = 'mono'
> 
> 	this.defaultMarkerParameters.type = 'pattern'
> 	this.defaultMarkerParameters.patternUrl = THREEx.ArToolkitContext.baseURL + '../data/data/patt.kanji'
> 	return this
> }
> 
> THREEx.ArToolkitProfile.prototype.hiroMarker = function () {
> 	this.contextParameters.detectionMode = 'mono'
> 
> 	this.defaultMarkerParameters.type = 'pattern'
> 	this.defaultMarkerParameters.patternUrl = THREEx.ArToolkitContext.baseURL + '../data/data/patt.hiro'
> 	return this
> }
> 
> THREEx.ArToolkitProfile.prototype.myCustomMarker= function () {
>   this.contextParameters.detectionMode = 'mono'
>   
>   this.defaultMarkerParameters.type = 'pattern'
>   this.defaultMarkerParameters.patternUrl = THREEx.ArToolKitContext.hostURL+ 'pattern-marker.patt'
>   return this
> }
> ```
> (see the last marker was added the rest is default)
> 
> and the last step is to add your marker preset to the init function (line 2729) preset check (line 2737 to 2752):
> 
> ```
> 		// honor this.data.preset
> 		if( this.data.preset === 'hiro' ){
> 			this.data.type = 'pattern'
> 			this.data.patternUrl = THREEx.ArToolkitContext.baseURL+'examples/marker-training/examples/pattern-files/pattern-hiro.patt'
> 		}else if( this.data.preset === 'kanji' ){
> 			this.data.type = 'pattern'
> 			this.data.patternUrl = THREEx.ArToolkitContext.baseURL+'examples/marker-training/examples/pattern-files/pattern-kanji.patt'
> 		}else if( this.data.preset === 'area' ){
> 			this.data.type = 'area'
> 			// fall through
> 		}else if( this.data.preset === 'myCustomMarker'){
>       this.data.type = 'pattern'
>       this.data.patternUrl = THREEx.ArToolkitContext.hostURL+'pattern-marker.patt'
>     } else {
> 			console.assert( this.data.preset === '', 'illegal preset value '+this.data.preset)
> 		}
> ```
> (see the pre-last statement if(this.data.preset === 'myCustomMarker')... )
> 
> After all of that you can just use your custom preset like the hiro preset so in the html, in the just swap the 'preset' value from 'hiro' to 'myCustomMarker' (or whatever you called yours
> 
> When you try, make sure to clear cache if it doesn't work instantly - but that was all works like a charm for me now
> 
> //PS//
> Btw the pattern-marker.patt I downloaded from the website is in my root folder, that's why "hostURL" for me is "./" if you store your pattern file somewhere else, change this to the according path

Hi!! I'm facing the same issue, and tried to follow this steps, but it looks like de aframe-ar.js code has changed?? 
In my case, this exactly my error:
```
components:gltf-model:warn Failed to load glTF model browser.js:111:7
Pattern Data read error!! aframe-ar.js:2:23001
loadMarker(): Error loading pattern file /marker_0. aframe-ar.js:2:23001
ARToolKitJS(): Unable to set up AR marker. aframe-ar.js:2:23001
Out of memory!! aframe-ar.js:2:23001
ExitStatus: Program terminated with exit(1)
```
I have a local server, and there is working perfect, even from a mobile accessing from network.
But when I upload it to my webServer and try to run it online, this happens... from android, iphone or computer (with Firefox 'cause of the https limitations).

Is there something to do with this? Please I'm stuck with this since 3 days ago.

Thanks in advice!! :)
