### ISSUE TITLE
Wrong rotation under safari ios11 beta2 

### ISSUE THREAD

**Issue by maximilianberndt** [jeromeetienne/AR.js#128]
Camera rotation is wrong under safari ios11 beta2.
I am using an iPhone 6s if that is of any help.

![img_2505b32c6997-1](https://user-images.githubusercontent.com/28513397/28125667-8c613cf4-6727-11e7-97e3-7de08a5aa031.jpeg)

**Comment by DanielePetrarolo** [comment]
I’ve found this issue to on my iPhone 6s and ios11 beta.
Try to play in landscape and seems to work but it seems that the perspective is stretched.

**Comment by jeromeetienne** [comment]
the upside down issue is iphone specific. aka the same code works well on ipad.

the strech in portrait is my bad. it is a long lasting bug. i didnt have time to work on it.

**Comment by IIIMaxIII** [comment]
Just tried landscape and it works just like you said. 

So every iphone has the upside down problem?

**Comment by gftruj** [comment]
@IIIMaxIII I have the same problem on my old Huawei ascend G620s, landscape works well, portrait messes up the rotation/perspective, so i'm not sure if its iphone specific

**Comment by DanielePetrarolo** [comment]
Installed beta2 and portrait camera is ok. At the moment the only problem is with stretched camera objects.

**Comment by user972611** [comment]
I got the same issue for both Samsung S7 edge and Note 3 (tested on Chrome and Firefox, rear camera)

ARToolKit.js work well on both phone (but using front camera)

**Comment by javismiles** [comment]
Folks, this is still happening , distorted perspective, upside down etc, any tips to fix it Jerome? All best ;)

**Comment by AndreaMonzini** [comment]
@jeromeetienne i have similar problem with my iPad® Air and iOs 11:
-in portrait mode, if the iPAd®is Vertical and the marker is on the wall: wrong rotation and stretched
- in portrait mode, if the iPAd®is Vertical and the marker is on the table: correct rotation, only stretched
