### ISSUE TITLE
Sketchfab example not working

### ISSUE THREAD

**Issue by DJviolin** [jeromeetienne/AR.js#131]
The following example:
https://github.com/jeromeetienne/AR.js/blob/c859246ee0988917abdf13d2eb08a097683de8fc/three.js/examples/sketchfab/examples/viewer.html

Not showing anything, including with the video and image source.

**Comment by DJviolin** [comment]
Looks like the problem is that the following files are missing:

```html
<script src='../../vendor/three.js/examples/js/loaders/OBJLoader.js'></script>
<script src='../../vendor/three.js/examples/js/loaders/MTLLoader.js'></script>
```

**Comment by yuen33** [comment]
I got the same problem too.... @DJviolin In the file viewer.html, Line 6 and Line 7 are what you provided above. I got nothing to show with the hiro marker
