### ISSUE TITLE
ar.js + a-frame - Not having the objects removed when marker is out of sight

### ISSUE THREAD

**Issue by FrederikNordahl** [jeromeetienne/AR.js#132]
Hey everyone

Is there a way for me to keep the objects in the scene of the a-frame, so that I for instance can place a scene of elements, relative to a marker, but if the marker leaves the camera scope my objects stay at the last known position?

/Frederik

**Comment by jeromeetienne** [comment]
just set the object to visible = true at each frame ?

**Comment by FrederikNordahl** [comment]
Thanks, it got me some of the way =)

I have an additional question in the same category, when I inserted my own model, the checking of marker became quite heavy. Do you have an idea as to why these two correlated ?

**Comment by jeromeetienne** [comment]
what do you mean by 'checking of the marker' ?

**Comment by FrederikNordahl** [comment]
Basically the functions run on "getMarker" event =)
