### ISSUE TITLE
in AR mode allow mouse click on object / user touch on object (mobile phone)

### ISSUE THREAD

**Issue by markleeyw** [jeromeetienne/AR.js#133]
Would like to check if this is possible?
So far I have to do this in order to see the cursor .. but it follows the camera and not mouse click
<a-marker-camera preset='hiro'>
			<a-cursor></a-cursor>

**Comment by JonathanWade** [comment]
I was trying to do this using the camera cursor component that is in A-Frame 0.6.1

`<a-camera>
  <a-entity cursor="fuse: false; rayOrigin: mouse">
</a-camera>`

But ran into issues. On page load I get the following: 
![screen shot 2017-08-02 at 5 18 30 pm](https://user-images.githubusercontent.com/6645170/28895502-a5fbf656-77a6-11e7-9118-c09b8d3d919e.png)

**Comment by nicolocarpignoli** [comment]
yes it is possible. see https://medium.com/chialab-open-source/how-to-handle-click-events-on-ar-js-58fcacb77c4

**Comment by maltekosian** [comment]
That is not the general solution for touch control. Imagine a scene where you have 4 images, one North one South, one West and one East, You want to see them one by one on your white wall. So you try to try to turn around the scene. That does not work with ARJS.
