### ISSUE TITLE
Does this work in any AR devices?

### ISSUE THREAD

**Issue by trusktr** [jeromeetienne/AR.js#137]
f.e. Hololens, Metavision, etc?

**Comment by jeromeetienne** [comment]
some people made it work on hololens already but more as a toy. You can see ar.js here running in the browser inside a hololens :) https://www.youtube.com/watch?v=AsDs1BVOH24

AR.js doesnt support hololens at the moment. it does support tango tho, and will support arkit shortly

**Comment by trusktr** [comment]
Maybe HoloJS can be of help here, it takes single-shader webgl apps and runs them full view, instead of in a window like that video.

**Comment by jeromeetienne** [comment]
as soon as i got a hololens and the time to work on it. i would love to support hololens

**Comment by trusktr** [comment]
I am going to try HoloJS soon, and see if I can get Infous running in it.

**Comment by jeromeetienne** [comment]
infous ? what is it ?

**Comment by trusktr** [comment]
Oops, I meant [infamous](http://GitHub.com/trusktr/infamous).

**Comment by trusktr** [comment]
The WebGLRenderer is brand new and messy, don't look!

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
