### ISSUE TITLE
Hole in the wall example?

### ISSUE THREAD

**Issue by FrederikNordahl** [jeromeetienne/AR.js#139]
Hey, is it possible to see the code for the hole-in-wall example =) ??

**Comment by anthonybudd** [comment]
FFS, why are they just linking to tweets and youtube videos?

**Comment by tocapixels** [comment]
Yes please!

**Comment by deep42** [comment]
Yes, I am interested too.

**Comment by nicolocarpignoli** [comment]
https://github.com/jeromeetienne/AR.js/issues/15
