### ISSUE TITLE
Do a "portal" demo

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#14]
With @blq, we talked thru private emails about various augmented reality effects which are cool. I thought it would be better to chat here. Thus people can join us or learn from it.

example of the concept on hololens https://twitter.com/VoxelKei/status/830796899913396227

**Comment by jeromeetienne** [comment]
maybe we should do a special geometry of (a plan minus a circle) and set a material without colorWrite: false. i think that's would work for the cache

can we avoid to do a special geometry ?

**Comment by jeromeetienne** [comment]
the youtube from Kei voxel is impressive too https://www.youtube.com/user/VoxelKei

**Comment by jeromeetienne** [comment]
# Possible tech
- do a square cache - aka 4 plane leaving only a small rectangular hole at the center
- behind do an half sphere with a equirectangular textures. [three.js examples](https://threejs.org/examples/?q=equi#webgl_panorama_equirectangular)
- if one want real photo of real places in equirectangular, google street view can help

**Comment by jeromeetienne** [comment]
@blq i implemented the half sphere + equirectangular texture in [hold-in-the-wall](https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/hole-in-the-wall.html#L157)

but some how it render weirdly, i likely have missed something :)

**Comment by Utopiah** [comment]
Close?

**Comment by nicolocarpignoli** [comment]
update the readme with @stemkoski examples. they are very good and helpful. close as obsolete and not needed anymore
