### ISSUE TITLE
Any thoughts on ARKit-like analysis of video to detect surroundings?

### ISSUE THREAD

**Issue by trusktr** [jeromeetienne/AR.js#140]
From what I've read so far, it seems like ARKit analyzes video from the phone's camera in order to map the environment (without the need for markers).

Any thought on that? Maybe it can be done in AR.js!

**Comment by jeromeetienne** [comment]
good news it is already done :) if you are running ar.js on tango using chromium-webar, it is possible to do 'hittest' aka to put virtual objects in the real world.

Similar in principle to this api - https://developer.apple.com/documentation/arkit/arframe/2875718-hittest - but in ar.js tango

ar.js support for arkit is being implemented but not yet completed at the moment. we aims to have it when arkit is publicly released

**Comment by trusktr** [comment]
Hey hey, I mean without special hardware like Tango requires. I believe ARKit doesn't require any special hardware, it just analyzes the video from the camera. That's the kind of feature I'm wondering about, without a requirement like Tango.

**Comment by jeromeetienne** [comment]
then unfortunatly no :( slam isnt yet supported on pure javascript
