### ISSUE TITLE
Loading an .obj/.mtl with aframe

### ISSUE THREAD

**Issue by metamorphious** [jeromeetienne/AR.js#141]
Hi,

first of all thanks very much for this nice library. I'm trying to display an .obj on a marker but it does not show anything. Does someone have an idea why?

The marker is recognized, testing with a simple box works. Path to the model is correct too.

```
<script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
<script src="https://rawgit.com/jeromeetienne/ar.js/master/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
        <a-scene embedded arjs='sourceType: webcam;'>
                <a-assets>
                        <a-asset-item id="ship-obj" src="ship_model/ship.obj"></a-asset-item>
                        <a-asset-item id="ship-mtl" src="ship_model/ship.mtl"></a-asset-item>
                </a-assets>
                <!-- Using the asset management system. -->
                <a-entity obj-model="obj: #ship-obj; mtl: #ship-mtl"></a-entity>
                <a-marker-camera type='pattern' url='patt.ship'></a-marker-camera>
        </a-scene>
</body>
```

**Comment by metamorphious** [comment]
nevermind.. I had wrong pathes in the .mtl file
Works now

**Comment by Guim17** [comment]
Hey dude I'm having the same problem doesn't show anything can you help me?

**Comment by WayneKeenan** [comment]
from the a-fram docs:

> If you don’t see your model, try scaling it down. OBJ models generally have extremely large scales in comparison to A-Frame’s scale.

**Comment by rupakchaulagain** [comment]
Hi, can you please tell me how to load different .obj and .mtl  by id with the help of javascript and display in ascene?.

**Comment by Siva-SteamRollEast** [comment]
Is there a way to load .fbx

**Comment by mnutsch** [comment]
@Siva-SteamRollEast
You will want to convert your Fbx file to Obj. Software like Blender or Clara.io will let you convert it.
