### ISSUE TITLE
Custom Marker

### ISSUE THREAD

**Issue by boxgames1** [jeromeetienne/AR.js#144]
Hi, 

I am using AR.js with Hiro marker, however I would like to try with a custom marker. 

So there are 2 questions here:

1- How to create the patt from a cutted image?
2- How to use my marker instead of Hiro Marker?

Many thanks.

**Comment by u4bi** [comment]
Look at this repository.

[https://github.com/u4bi/simple-ar.js](https://github.com/u4bi/simple-ar.js)

**Comment by boxgames1** [comment]
Thanks. I was trying with https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html to create a custom marker.

Must the selected image to have low detailing?

**Comment by jeromeetienne** [comment]
Here is a post explaining how to create your own markers. i hope this helps.

https://medium.com/arjs/how-to-create-your-own-marker-44becbec1105

**Comment by vin-ni** [comment]
I made it work with this instructions. You need to edit some code.
https://github.com/jeromeetienne/AR.js/issues/164#issuecomment-332065686

**Comment by fredodi** [comment]
i'd like to use a image but don't want the black outline
any idea?
thanks!

**Comment by mnutsch** [comment]
Yes, it is possible to use an image as a target marker. See this example,
which was made with AR.js: https://youtu.be/pTITrp_xOis

**Comment by testica** [comment]
@mnutsch I think in the video is using a QR code as marker

**Comment by mnutsch** [comment]
@testica Oh, you may be right. AR.js is a combination of ARToolkit and Aframe.js/Three.js. ARToolkit's website only shows recognition of black and white markers.
