### ISSUE TITLE
Enable A-Frame AR.js to turn on and off on demand 

### ISSUE THREAD

**Issue by flowerio** [jeromeetienne/AR.js#145]
Jerome requested I post this here... 
THREEx.ArMarkerControls() should respect the .enabled flag, so that it can be loaded in a page and turned on and off on demand. 

I am using AR.js in a project to view any Google Blocks model, but resorted to switching the main client back and forth another page with AR.js by itself. 

https://fasility.com/beblock

**Comment by jeromeetienne** [comment]
NOTE to self: it should be added in all controls
- THREEx.ArSmoothedControls
- THREEx.ArMarkerControls
- THREEx.ArBaseControls
- THREEx.ArMultiMarkerControls

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
