### ISSUE TITLE
sourceType=video in not working

### ISSUE THREAD

**Issue by runningo** [jeromeetienne/AR.js#147]
Hello ! thanks for your nice library.

When i first downloaded the AR.js rep on july 3, "sourceType="video" worked well, by local video source. But after re-applying your recent "aframe-ar.js", this is not working.

just used sample code and added my local video.

`<a-scene embedded artoolkit="sourceType:video; sourceUrl:./localvideo.mp4;">
		<a-marker preset="hiro">
			<a-box position="0 0 0" material="opacity: 0.5; side: double"></a-box>
		</a-marker>
		<a-entity camera></a-entity>
	</a-scene>`

always thanks.!

**Comment by jeromeetienne** [comment]
im refactoring a lot. how recent was the aframe-ar.js ?

Do you have a examples of the version that worked ?

**Comment by runningo** [comment]
https://github.com/runningo/testing

you can find two files named "aframe-ar.js", "aframe-ar1.js".

"aframe-ar.js" is the file that video tag works well and "aframe-ar1.js" is not.

thanks

**Comment by jeromeetienne** [comment]
Could you push the video file too, thanks ?

**Comment by runningo** [comment]
sure. i uploaded local video file on url now.

https://github.com/runningo/testing

thanks

**Comment by runningo** [comment]
how works? done well? 
thanks :)
