### ISSUE TITLE
How to scan an image without the black border for marker? 

### ISSUE THREAD

**Issue by aditivy** [jeromeetienne/AR.js#149]
Hello, I am implementing an application using AR.js where users can scan a brand image and get an AR experience? For that, I need to be able to recognize the brand logo which would not have a black marker border around it. Is it possible to do that in AR.js? What would be the best way to implement a solution like that while still using AR.js? Thanks!!

**Comment by jeromeetienne** [comment]
what you are describing is known as 'image-based marker' .. and unfortunatly it isnt supported by AR.js at the moment :(

**Comment by aditivy** [comment]
Thank you for your response. We do need this functionality how would you recommend we should go about augumenting AR.js (or some other solution) in order for us to scan an image.  Our company is building an advanced AR application for the web.

**Comment by yuccai** [comment]
Hello,
Focus on features 2D, features matching and homography. [Here](http://docs.opencv.org/trunk/d1/de0/tutorial_py_feature_homography.html) is an opencv example and a [list](http://docs.opencv.org/trunk/db/d27/tutorial_py_table_of_contents_feature2d.html) of related tutorials.

**Comment by alvarogarmig** [comment]
Hi, I need the same function, There is something planned to implement it.

Thanks!

**Comment by aditivy** [comment]
Thanks!! So cool. Is there any expected date when this function will be implemented? 

Aditi Madane
CEO Upsilon Labs

**Comment by corbinyo** [comment]
bump

**Comment by meizano** [comment]
For now, it's not possible to remove black border completely because it's based on ARToolkit, but it can be modified. Angelo888 explain how it can be done in https://github.com/jeromeetienne/AR.js/issues/296.

**Comment by Esmolan** [comment]
Hi! does AR.js suppor and image-based marker now? Thanks

**Comment by nicolocarpignoli** [comment]
closed, see related PRs.
