### ISSUE TITLE
getUserMedia isnt well detected on some old android

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#150]
bug description this [twitter thread](https://twitter.com/jerome_etienne/status/893390865422569472)

**Comment by kumarahir** [comment]
Tested on Moto E (2nd gen) XT1506
Android 5.1

Following url works without problem
https://webrtc.github.io/samples/src/content/devices/input-output

Following url is giving problem
https//jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html
Problem description
Webcam Error
Name: WebRTC issue!
navigator.mediaDevices.enumerateDevices not present in your browser

Tried following url
https//jeromeetienne.github.io/AR.js/three.js/examples/dev.html
It's also giving same above problem

**Comment by Hodapp87** [comment]
Running into this same issue on a Galaxy S7 with Android 6.0.1, even though the https://webrtc.github.io/samples/ examples work

**Comment by nicolocarpignoli** [comment]
the error `navigator.mediaDevices.enumerateDevices` is pretty self-explained, such property is not available in your browser version. Maybe the working example works because doesn't use such property
