### ISSUE TITLE
Readme "Full Featured Marker based" links not working

### ISSUE THREAD

**Issue by goldingdamien** [jeromeetienne/AR.js#154]
https://github.com/jeromeetienne/AR.js/
The following links in the top page above are not working.

https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training
https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_barcode
https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_multi

**Comment by sloschi** [comment]
try these:

https://archive.artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training
https://archive.artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_barcode
https://archive.artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_multi

**Comment by mrmookie** [comment]
Thanks sloschi.

I've submitted a pull request for an updated version of the README file that has these fixes in it..

https://github.com/jeromeetienne/AR.js/pull/163/files

**Comment by nicolocarpignoli** [comment]
duplicate https://github.com/jeromeetienne/AR.js/issues/362
