### ISSUE TITLE
Make an easily accessible tango example

### ISSUE THREAD

**Issue by richardanaya** [jeromeetienne/AR.js#155]
Putting a link in README to an online accessible example of tango and any instructions on how to use it would be cool.

**Comment by jeromeetienne** [comment]
It is in aframe/examples

**Comment by richardanaya** [comment]
Cool! I was suggesting more adding a link in the README to it: it appears it might be accessable by this link, but i'm really not clue what is the best thing to be linking.

https://rawgit.com/jeromeetienne/AR.js/master/aframe/examples/tango-demo.html

The reasoning is that people with tango enabled mobile devices might find it easier to just hit a link on your github readme than setup a local website from git.

**Comment by mrmookie** [comment]
I've submitted a pull request for an updated version of the README. I too had a tough time finding all the info as it's moving fast so I'm trying to contribute by finding and updating the docs!

https://github.com/jeromeetienne/AR.js/pull/163

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
