### ISSUE TITLE
Do a multimarker setup to get more range in marker detections

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#16]
TODO: describe what this title means :)

**Comment by blq** [comment]
This I assume :) https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_multi

**Comment by blq** [comment]
I envision ad-hoc multimarker detection.

**Comment by Utopiah** [comment]
Link and close?

**Comment by jeromeetienne** [comment]
thanks for pinging me. this is implemented now :) 
https://github.com/jeromeetienne/AR.js/tree/master/three.js/examples/multi-markers

artoolkit multi marker was static and was super buggy.

So i implemented my own multimarker. With a very nice workflow to dynamically learn new area of multi markers.
