### ISSUE TITLE
3D object exist although marker leave camera

### ISSUE THREAD

**Issue by Ruion** [jeromeetienne/AR.js#160]
![screenshot 270](https://user-images.githubusercontent.com/20848849/29251447-79e92ed2-8087-11e7-9a6a-e0b0000355c6.png)

marker enter camera once and sphere pop up. But sphere doesn't disappear when marker not visible to webcam.

**Comment by mrmookie** [comment]
Same issue as #159?

**Comment by Ruion** [comment]
I encountered this issue and #159

**Comment by javismiles** [comment]
this really needs fixing I agree 

when using a-entity camera, 3D object disappears when marker is not recognized 

when using a-marker-camera , 3D object remains after we move away from marker

problem is  a-marker camera works great, much better than a-entity camera, but this is a real problem that the projected object doesnt disappear after you move away, big bug

#159 and #160

thank u

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
