### ISSUE TITLE
pose/normal incorrect

### ISSUE THREAD

**Issue by makslevental** [jeromeetienne/AR.js#165]
any idea why this happens? i experience on it all of my devices. haven't dug in to the code but just wanted to start the conversation

![screenshot_20170819-122526](https://user-images.githubusercontent.com/5657668/29488891-2336b1d6-84e2-11e7-870a-0dee10773593.png)

**Comment by makslevental** [comment]
the strange thing is that on my laptop it works fine 
![image](https://user-images.githubusercontent.com/5657668/29489271-d236fbde-84ea-11e7-8a0b-45528a6b3249.png)

**Comment by indus** [comment]
on my smartphone only landscape orientation worked - portrait gave me the same result as you described.

**Comment by makslevental** [comment]
It has something to do with canvas element and how video is being drawn into it

**Comment by rremigius** [comment]
It's been long since the last comment here, but this is still an issue with aframe-ar.js.
Interestingly, it seems to be solved in [this example](https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html) but I have not yet found the difference that makes it work or break.
