### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by LLTommy** [jeromeetienne/AR.js#167]
I stumbled across some dead links (at least at the moment?) in the documentation, in this part:

It is marker based. It supports a wide range of markers: multiple types of markers **pattern/barcode** multiple independent markers at the same time, or **multiple markers acting as a single marker** up to you to choose.

**Comment by sloschi** [comment]
[#163](https://github.com/jeromeetienne/AR.js/pull/163)

**Comment by pwdonald** [comment]
Most of the interesting examples are dead (404) links still.

**Comment by nicolocarpignoli** [comment]
duplicate https://github.com/jeromeetienne/AR.js/issues/362
