### ISSUE TITLE
How does it work? Any API available?

### ISSUE THREAD

**Issue by Lenndev** [jeromeetienne/AR.js#169]
Hi, 
I like the idea of a simple open source AR SDK-ish library.. but reading your README doesn't really give me an idea of how to work with it... I'm looking for a solution where i have my dashboard in which i can add an image (which is uploaded/converted into a Marker, underwater) and a mobile app (Appcelerator Titanium and cordova based for now) that can scan the same image printed on a info sign i.e.  a zoo... 

I have taken a look at the AR Marker Training (https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html) but i don't want a marker with the big fat black border... it just needs to be the image... is that possible with this library? 

Any leads are appreciated.

**Comment by jeromeetienne** [comment]
yes there is an API avaible. it is an opensource project

here is a link with a tutorial on how to use it https://aframe.io/blog/arjs/

**Comment by Lenndev** [comment]
Wow, quick response! nice! So if I understand correctly, it is not possible to create image markers without the big fat black border... which is a shame since Wikitude can. (kind of looking for a cheaper solution with sort of the same features, at least for the looks of the markers... )

**Comment by jeromeetienne** [comment]
You are correct, currently image based marker arent supported by AR.js.

**Comment by lcb931023** [comment]
Are there any three.js arjs API documentations?
