### ISSUE TITLE
Do a demo like the reverse wii mote

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#17]
It gives some 3d to normal screens - it is nice augmented reality

- well known from the famous ["Head Tracking for Desktop VR Displays using the WiiRemote"](https://www.youtube.com/watch?v=Jd3-eiid-Uw) video by the excelent JohnnyLee
- i started one in [head-tracking.html from jsartoolkit-experiments](https://github.com/jeromeetienne/jsartoolkit-experiments/blob/master/head-tracking.html)
- it may be adapted to ar.js

**Comment by jeromeetienne** [comment]
Other videos doing the same effect

- https://www.youtube.com/watch?v=h9kPI7_vhAU
- https://www.youtube.com/watch?v=bBQQEcfkHoE

**Comment by jeromeetienne** [comment]
How different it is from a portal ?

**Comment by nicolocarpignoli** [comment]
same as portal in my opinion. closing for now, we can re-open it if we need a slight different demo than portal one.
