### ISSUE TITLE
Markerless Location based AR. 

### ISSUE THREAD

**Issue by raynt** [jeromeetienne/AR.js#171]
Does or will AR.JS support markerless location based AR (eg. model appearing at certain gps coordinates)? If so could you point me in the right direction. I'm by no means a developer but very interested in figuring this out. 

Very excited about what you have achieved so far to create an accessible open AR standard removing apps from the equation. Thanks for all you and contributors have done.

**Comment by wimvdc** [comment]
Wouldn't that be very hard?
Lets take a smartphone as example.
Your smartphone will probably have a GPS sensor so you would be able to get your own location.
But your camera should somehow be able to measure the distance to certain object (for example a house or traffic sign) in its view to be able to calculate the GPS coordinates of that object.

**Comment by raynt** [comment]
Thanks for your reply wimvdc.
The usage that I'm imagining would be pretty basic in the fact that the model would not interact with the local environment, just be floating at a certain GPS position. I had seen a youtube video over a year ago of this being done in I believe artoolkit. I would love to know if this could be possible through AR.JS and a browser. This is a video showing it done with Unity and Kudan https://www.youtube.com/watch?v=7-SiR_qJwaU

**Comment by jarodium** [comment]
LLA Markers
https://en.wikipedia.org/wiki/LLA_Marker

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
