### ISSUE TITLE
A-Frame VR mode integration issue

### ISSUE THREAD

**Issue by AndresCuervo** [jeromeetienne/AR.js#173]
When entering VR mode (e.g. pressing the bottom right icon in an A-Frame scene) the camera doesn't split. This is to be expected, taking a look at the code, so the video feed should probably by split appropriately when the `.enter-vr` button is pressed, to at least fake stereo?

Also, the black VR border added by the VR polyfill in VR mode, along with the underlying scenes canvas, seems to be displaced half way up the screen. This was tested on an iPhone 7, iOS 11.0.6

**Comment by gabrielgrant** [comment]
I _think_ this is a duplicate of #125 , right?

**Comment by AndresCuervo** [comment]
Ah you're right @gabrielgrant will close this one now that there's a reference to it from your comment!

**Comment by gabrielgrant** [comment]
I don't think the second issue re: the black VR border is covered by #125, though, so maybe open a new issue for that? I don't totally follow what the problem is that you're trying to describe there, though, so it would be helpful if you could explain it more thoroughly (and possibly include a screenshot?)

**Comment by erikloaiza** [comment]
Hello, in case someone still needs to solve it, this is my approach:
It's a bit forced.
it works in landscape (on mobile) but not on portrait, it should be improved for it.
setTimeout(() => { var vidCam = document.body.lastElementChild; vidCam.setAttribute('id','arVideo') var camera = document.querySelector('[camera]') webCamSource = document.createElement('a-entity') webCamSource.setAttribute('geometry','primitive: plane;') webCamSource.setAttribute('material','shader: flat; src: #arVideo') webCamSource.setAttribute('position','0 0 -50') webCamSource.setAttribute('scale','54 36 1') camera.insertBefore(webCamSource, camera.firstChild); document.querySelector('.a-enter-vr-button').addEventListener('clik',()=>{ camera.object3D.position.set(0,0,0) }) }, 2000);
