### ISSUE TITLE
Marker without margins

### ISSUE THREAD

**Issue by PiotrKlys** [jeromeetienne/AR.js#174]
Hello,

is it possible to have a marker without black and white margins for example a simple photo? I've change https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/marker-training/threex-arpatternfile.js to have that type of marker but it is not recognized by AR.js.  Should I change something in https://github.com/jeromeetienne/AR.js/blob/master/aframe/build/aframe-ar.js? I know that markers without black and white margins work in vuforia and they are recognized pretty well.

**Comment by jeromeetienne** [comment]
sorry AR.js doesnt support image based marker at the moment.
