### ISSUE TITLE
Example application does not work with Google Pixel in portrait mode

### ISSUE THREAD

**Issue by BenBergman** [jeromeetienne/AR.js#175]
When I tested the basic example app from the README with my phone it works as expected with the phone held in landscape orientation, but in portrait mode it seems as though it is not rotating the camera image prior to processing for orientation data - the cube is being shown but it seems very distorted. I am using a Google Pixel but I imagine that any phone would reproduce the issue.

**Comment by JonathanWade** [comment]
This is probably the same as #60 ?

**Comment by BenBergman** [comment]
Yeah, looks like it. I'll close this issue.
