### ISSUE TITLE
[New Idea] Using three.js device motion events

### ISSUE THREAD

**Issue by darioodiaz** [jeromeetienne/AR.js#176]
Hi @jeromeetienne  ! I'm returning to AR stuffs and I see that example with threejs

https://threejs.org/examples/misc_controls_deviceorientation.html

It uses de device motion events to move the camera in the 3d world, so I was wondering if AR.js can use this to create new experiencies with phones that not have gyroscope, and I was thinking that if we put objects in the 3d worlds (with an isometric view or camera) and use this devices events we can "walk" in the real world and see things getting far o near like some AR games or apps that I saw.

I explain myself? I saw that all examples use markers, but if we put objects in 3d world and use this features to create anothe ar experiencies? I take a look the code but I'm noob with threejs so I put all scripts together but nothing happens, I guess that artoolkit renderer and device renderer was colliding so I dont see the 3d world but I see the camera.

**Comment by darioodiaz** [comment]
I was experimenting with react-vr that now support LiveCameraEnv which use the camera as world background (thats its what I want to do and want to explain in the above comment) and take care about device sensors, its move the camera as the phone moves its using webvr spec? or using that device motion events that I told? thats the feature I want to recreate with AR.js and will be amazing build a pokemon go like game with AR.js, react-vr is nice but AR.js support marker detection :) I explain myself?

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
