### ISSUE TITLE
Markers without borders

### ISSUE THREAD

**Issue by benxtan** [jeromeetienne/AR.js#177]
Hi there, is it possible to have markers without the thick black borders?

**Comment by zspringer** [comment]
Would love to find this out as well!!!

**Comment by zspringer** [comment]
The InkHunter app is interesting as it uses a hand-drawn marker.  I was trying to replicate that marker process and haven't figured out a way to do so.  Any ideas would be great...

**Comment by marijaerjavec** [comment]
Yes please! And photos for markers?

**Comment by rustynymph** [comment]
Any progress on this?

**Comment by javismiles** [comment]
There is an NFT branch of artoolkit where NFT is working. Remains the work of integrating it into ar.js:

https://github.com/artoolkit/jsartoolkit5/tree/nft/examples
https://github.com/artoolkit/jsartoolkit5/blob/nft/examples/nft_threejs.html

also interesting:
https://jensgrubert.wordpress.com/research/natural-feature-tracking-in-javascript/

**Comment by derzu** [comment]
@javismiles Did you tried to integrate that with AR.js?

**Comment by nicolocarpignoli** [comment]
not possible now with actual artoolkit specs
