### ISSUE TITLE
Support AR cube with artoolkit barcode

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#179]
# Needed to support default artookit cube
- https://github.com/artoolkit/artoolkit5/tree/master/doc/patterns/Cubes

# Steps
- need to add artoolkit+barcode in my test suite
- i need to test the multi markers with barcode - around [here](https://github.com/jeromeetienne/AR.js/blob/master/three.js/src/markers-area/threex-armultimarkerutils.js#L248)
- i need a way to specify if multimarker artookit is using pattern or barcode

**Comment by jeromeetienne** [comment]
cc @alfa256

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
