### ISSUE TITLE
Do a "floating Jewel" demo

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#18]
- some tuning can be found [here](https://twitter.com/RahmanNasimiAsl/status/834124405626241024)
- we could add some shaddow as in [shadow.html](https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/shadow.html)

![c5nnkpswcam1kms](https://cloud.githubusercontent.com/assets/252962/23577806/affb0f6e-00c0-11e7-924f-6280937069a0.jpg)

**Comment by blq** [comment]
![screenshot_20170304-214510](https://cloud.githubusercontent.com/assets/193049/23583225/f76e901e-013d-11e7-986d-51dfeec2b9f5.png)
One small step.. :)

**Comment by jeromeetienne** [comment]
@blq a very beautiful step tho :)

**Comment by jeromeetienne** [comment]
similar as #25

**Comment by nicolocarpignoli** [comment]
demo is the same as #25 in fact. I closed as we have already a lot of obsolete TODO demo issues :)
