### ISSUE TITLE
Slow tracking performances on Wechat Browser

### ISSUE THREAD

**Issue by dotgreg** [jeromeetienne/AR.js#181]
Tested on Wechat Browser on Android with many phones, I noticed a massive difference of performance between chrome and wechat browser. 

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/5bij0B91RuI/0.jpg)](https://www.youtube.com/watch?v=5bij0B91RuI)

As you see, the 3D part is running smoothly (60fps), but the tracking position updates every 1-2 seconds, which let me thinking that it is not due to limitation from the browser side, but the library should be tested and optimized to support Wechat Browser.

As I know it is very chinese-centric one, I think it would be hard for the core developers to work on that, so I can help, but seeing the video, if you could give me some clues on what part is slowing down. 

I suppose from the code that maybe the image analysis is not finished when the `THREEx.ArToolkitContext.update` is triggered for the next frame and somehow delete the last result?

**Comment by lslzl3000** [comment]
(^_^) I'm going to give more tests on Wechat as well.
About performance, I think put some work in worker may give some help.

**Comment by webgameone** [comment]
@lslzl3000 可以加下你的微信探讨下吗

**Comment by webgameone** [comment]
@lslzl3000 可以加下你的微信或者qq聊下么   这个AR我也只能调用前摄像头来着

**Comment by michael829** [comment]
同样的...只能调起前摄像头..也是相当郁闷...

**Comment by webgameone** [comment]
@michael829 我成功调用微信的后置摄像头了   可惜这个玩意不好用   一点也不准   我就懒得弄了   没意思

**Comment by fourWoods** [comment]
@webgameone 你好，可以请教一下是怎么调用的吗

**Comment by dotgreg** [comment]
@fourWoods 
Line 182 in three.js/src/threex/threex-artoolkitsource.js
```
navigator.mediaDevices.enumerateDevices().then(function(devices) {

  var backVideoInputId = false
  for (var i = devices.length - 1; i >= 0; i--) {
    if(
         devices[i].kind === 'videoinput' &&
         devices[i].label.indexOf("back") !== -1
    ) { 
      backVideoInputId = devices[i].deviceId;
    }
  }

  var userMediaConstraints = {
    audio: false,
    video: {
        facingMode: 'environment',
        deviceId: backVideoInputId,
        width: {
            ....
        }
    }
```

**Comment by fourWoods** [comment]
@dotgreg 
Thank you！
But I got an accident that in our phone the devices that printed by our wechat，its label is blank.

**Comment by handrianj** [comment]
@dotgreg is this fix still working? I just tried to implement it but somehow wechat keep using the front camera

**Comment by reyoung2017** [comment]
@handrianj    try this , forward to the backVideo
var userMediaConstraints = {
			audio: false,
			video: {
				facingMode: 'environment',
				deviceId: devices[1].deviceId,//宗瑞阳修改--手机端默认打开后置摄像头
				width: {
					ideal: _this.parameters.sourceWidth,
					// min: 1024,
					// max: 1920
				},
				height: {
					ideal: _this.parameters.sourceHeight,
					// min: 776,
					// max: 1080
				}
	  	}
    }

**Comment by handrianj** [comment]
@reyoung2017 Just tried, same results :/ Always the face camera...

Somehow I can't use 
>  devices[i].label.indexOf("back")
It looks that devices[i].label always return an empty string :/

**Comment by zaixia2008** [comment]
Im facing the same issue with you, have you found the solusion? @dotgreg

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
