### ISSUE TITLE
How can I get the positions of markers?

### ISSUE THREAD

**Issue by mkokubun** [jeromeetienne/AR.js#182]
In the following case, how can I get the positions of markers?
I would like to measure the distance between two markers (hiro and kanji).

---
<a-scene embedded arjs>

  <a-marker preset="hiro">
    <a-box></a-box>
  </a-marker>

  <a-marker preset="kanji">
    <a-box></a-box>
  </a-marker>

  <a-entity camera></a-entity>

</a-scene>
---

**Comment by aj019** [comment]
@mkokubun Were you able to achieve this ?

**Comment by liyasthomas** [comment]
Is there an A-Frame version of this example? Or is it even possible to do so with A-Frame? https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/measure-it.html
