### ISSUE TITLE
How can I get positions of markers

### ISSUE THREAD

**Issue by mkokubun** [jeromeetienne/AR.js#183]
In the following case, how can I get the positions of markers?
I would like to measure the distance between two markers ("hiro" and "kanji").

```
<a-scene>
  <a-marker preset="hiro">
    <a-box></a-box>
  </a-marker>
  <a-marker preset="kanji">
    <a-box></a-box>
  </a-marker>
  <a-entity camera></a-entity>
</a-scene>
```

**Comment by jeromeetienne** [comment]
Take the box, computer the world position

It select the market entity and look at the position of the 3d object

**Comment by RandomCouch** [comment]
I'm looking for a solution to this as well, not sure I understand the solution posted @jeromeetienne - I've been trying to get the position of a marker and the position of the camera using getAttribute('position') and both are returning 0,0,0 - Is there a way to get the camera's position in relation to the markers position?

**Comment by stemkoski** [comment]
My understanding, at least for the three.js version of these applications, is that the camera is always at (0,0,0) and the rest of the scene is rotated according to the position of the marker. For the position of the marker, you could try the function getWorldPosition() -- perhaps (0,0,0) is its local position?

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity. Please open a new, updated issue if the problem or the question is still relevant.
