### ISSUE TITLE
Error when viewing demo on iPad Air - WebRTC issue! navigator.getUserMedia not present in your browser 

### ISSUE THREAD

**Issue by gitinthehole** [jeromeetienne/AR.js#186]
Related to #65 

Has anyone tried with iOS 11 Beta? I'm still getting the error.

**Comment by MaffooBristol** [comment]
On an iPhone SE (iOS 9) I get `navigator.mediaDevices not present in your browser`, which is similar. Both mobile Chrome and Safari

**Comment by leinims** [comment]
Me too. On Huawei G Play Mini: 

> navigator.mediaDevices not present in your browser

**Comment by JinXJinX** [comment]
I installed iOS 11 today. However, I still got the error message: "Webcam Error, Name: Message: WebRTC issue-!navigator.mediaDevices not present in your browser" 

Device version: iphone 6S
ios: 11.0(15A372)    (latest version)
chrome version: 61.0.3163.73 (latest version)

**Comment by ZoltanVeres** [comment]
@JinXJinX I tried on iPad mini2 using the Safari browser and it worked. With Chrome i had the same isuue as you, maybe Chrome needs to switch over to the new Safari JS and rendering engine. (Chrome is basically an extended Safari browser on iOS devices)

**Comment by JinXJinX** [comment]
@ZoltanVeres Thank! on safari, AR.js works very well

**Comment by ThibaultAr** [comment]
Hi everyone, I encounter the same issue.
II use Cordova to build web app and when I launch it with iOS 11 it's not working.
Maybe you have a solution ? 

For information, I use a-frame maybe it's the problem and I should go pure-ARjs ?

**Comment by ultradyran** [comment]
strange because on iOS11 safari, both my ipad and iphone are not working.

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.

**Comment by JamesBotterill** [comment]
@nicolocarpignoli this has now been reported on ar.js
