### ISSUE TITLE
ios 10 artoolkit not render object on source image

### ISSUE THREAD

**Issue by StrikerUnit** [jeromeetienne/AR.js#187]
Hi,

I try to implement ar.js on iPhone SE ios 10 cordova wrapper with this example
https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/mobile-performance.html

I try this with cordova-iosrtc but not working so I think if it's not video might works. 
I try to use image as a source for 'arToolkitSource' in the example

```
// to read from an image
sourceType : 'image',
sourceUrl : THREEx.ArToolkitContext.baseURL + '../data/images/img.jpg',
```

once run... the image is showing but still the cube is not rendered like it should.

How should I debug this or just using image is not supported too?

any recommend is really appreciated.

**Comment by Niranjan-J007** [comment]
Me too facing the same issue!

Were you able to make the cube render on source image?

**Comment by nicolocarpignoli** [comment]
closing as now answer from author for a long time
