### ISSUE TITLE
Few issues with the new-api

### ISSUE THREAD

**Issue by xseignard** [jeromeetienne/AR.js#188]
hello there
I'm trying to do my own patterns, and stuff, so far so good
I'm trying to use the "new-api", based on the following examples:
https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/arjs-session.html
https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/dev.html
You can check here
https://xseignard.github.io/jeunes-exiles/
I have 2 problems
- First once the marker is detected, the object3d of the anchor never disappear??!!
- How can I detect a click on the object3d of the anchor? Or at least know which anchor is detected when a click occurs.

Regards,

Xavier

**Comment by nicolocarpignoli** [comment]
First question: https://github.com/jeromeetienne/AR.js/issues/313 here you can found how to make the object disappear or hide when the camera lose focus of the marker

second question: see https://medium.com/chialab-open-source/how-to-handle-click-events-on-ar-js-58fcacb77c4
