### ISSUE TITLE
tutorial code does not work:  Augmented reality for the web in less than 10 lines of html

### ISSUE THREAD

**Issue by lidymonteirowm** [jeromeetienne/AR.js#189]
how to run this example? I followed the steps in the tutorial, but the code does not work: https://medium.com/arjs/augmented-reality-in-10-lines-of-html-4e193ea9fdbf

What's the difference to this implementation that works? https://codepen.io/jeromeetienne/pen/mRqqzb

which of the two is the recent and correct way to do it?

(1) uses artoolkit (does not work) and (2) arjs (works).

**Comment by tetreault** [comment]
@jeromeetienne I also first ran into this issue, which is why more concise documentation might attract more and more people

**Comment by nicolocarpignoli** [comment]
A better documentation is the next step, i totally agree :)

**Comment by nicolocarpignoli** [comment]
https://github.com/jeromeetienne/AR.js/issues/377
https://github.com/jeromeetienne/AR.js/issues/377
