### ISSUE TITLE
helpfull error messages

### ISSUE THREAD

**Issue by pikilipita** [jeromeetienne/AR.js#19]
Since demos only work on few Android devices, on devices not able to run them, it would be great to display a alert box with few details about what required features the phone is missing

**Comment by jeromeetienne** [comment]
it is supposed to work on all devices with webgl and webrtc. 

Could you be more specific in which case you would like a error messagve ?

**Comment by pikilipita** [comment]
I meant that on phone that can't run the app you have no error message displayed, just either a full black or a full white screen with stats in the corner. 
It would be helpfull to display error messages when the device is not able to run the AR app.

**Comment by blq** [comment]
Maybe initially just a simple hook to window.onerror ?
I've been using basically this code: 
https://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onerror
(with a two-error-popup max counter).
Once things start to "appify" need more user friendly messages of course ;)

**Comment by jeromeetienne** [comment]
i added a alert() if the browser doesnt support webrtc

**Comment by pikilipita** [comment]
Just checked the mobile peformance example on android 4.3 and android 6.0 stock browsers: it's a white page showing only the top texts.

No camera feed displayed, no camera autorization asked, but no alert box is displayed.

**Comment by jeromeetienne** [comment]
just pushed, try now :)

**Comment by pikilipita** [comment]
yes, I see alert warnings poping up now, much helpful!

And I see the demo is now working on Chrome on android 4.4, that's new :)

**Comment by jeromeetienne** [comment]
@pikilipita cool for the error message.

Nothing new on the core of ar.js in the past few days, when did you try ?

**Comment by pikilipita** [comment]
I tested the demos about 10 days ago

**Comment by josephrocca** [comment]
@jeromeetienne Just a heads up, after clicking "allow camera" I get a black screen on:

Android 5.1.1
Chrome 57.0
Samsung Note 2

Not sure what error is causing this or how to find out :S

**Comment by jeromeetienne** [comment]
No idea either :(
