### ISSUE TITLE
Barcode patterns don't seem to scan

### ISSUE THREAD

**Issue by j1mie** [jeromeetienne/AR.js#192]
The 3x3 barcode patterns don't seem to be working anymore, even when trying with your provided examples.

**Comment by tawasee** [comment]
me too.
I tried to use custom pattern and barcode. But it doesn't work with latest aframe-ar.js.
No matter I specified type or preset, a-maker only recognized "hiro" marker.
It seems latest release is wrong to switch marker pattern....
Is there any solution?

**Comment by clavis-magna** [comment]
Looking at issue #54 it looks like this was fixed and then broken again. 3x3 barcodes are working for me in the July 1 commit ( e9aea5deb0ee010ece3e2ab07d84b587c374b66b ) but no longer work from the next commit ( bb72f755f85d253fdac482b59309fe071eeb099b ) on July 5. I have been trying to see if I can find why they stopped working, but a lot of code changed in that commit and I haven't been able to get to the bottom of it. (testing on the multiple-independent-markers.html example and my own test scene)

**Comment by calderonsteven** [comment]
a quick fix for me was use the version ( https://github.com/jeromeetienne/AR.js/commit/e9aea5deb0ee010ece3e2ab07d84b587c374b66b )  and yes there is a lot of code changed between these two commits.

**Comment by ZoltanVeres** [comment]
Apparently  #260 fixes this issue:
Get latest version of AR.js and change `barcodeValue` to `value` 
`<a-marker type='barcode' value='5'></a-marker>`
Please get back to us if this is still not working for you, until then the issue remains closed.

**Comment by clavis-magna** [comment]
@ZoltanVeres  Confirming #260 fixes the issue in the 'dev' branch where it was merged to, is the intention to merge this back into master now?

**Comment by dburongarcia** [comment]
I've tried master and dev branches, but none of them works with barcode markers. As other users said, the commit ( [e9aea5d](https://github.com/jeromeetienne/AR.js/commit/e9aea5deb0ee010ece3e2ab07d84b587c374b66b) ) works.

**Comment by ZoltanVeres** [comment]
Hi @clavis-magna , yes this will be merged back to master. Not sure when tough, this is for @jeromeetienne  to decide, since he is more qualified to make this decision then me.

**Comment by ZoltanVeres** [comment]
Hi @dburongarcia, Can you please open up an issue with some more details, please also state that this happening on the dev branch as well, also if you provide a steps to reproduce that will be great!

**Comment by chtidusud** [comment]
Hi

Any update on this please ? 
I confirm that rolling back to e9aea5d works for barcode markers ... but not the current version :-(
If someone has a quickfix tu apply to current version, would be appreciated !
Thanks

Julien

**Comment by julianfrank** [comment]
Not working for me too

**Comment by IntegersOfK** [comment]
Commit 7cb6ea5 broke it.

**Comment by javismiles** [comment]
If we  use  aframe-ar, where would this have to be fixed? thank you

**Comment by nicolocarpignoli** [comment]
I can't make barcode markers working with releases 1.5.5 or 1.6.0 please someone help

**Comment by mnutsch** [comment]
The AFrame barcode functionality was broken in some later release. An easy way to get using it is to download the version of AR.js (incl. the Aframe library) found here: https://github.com/jeromeetienne/AR.js/archive/e9aea5deb0ee010ece3e2ab07d84b587c374b66b.zip
