### ISSUE TITLE
Webcam Error Name: NotAllowedError

### ISSUE THREAD

**Issue by WaveF** [jeromeetienne/AR.js#193]
iOS11 released, and this message shows when running examples, it seems need user click a play button before rendering?

**Comment by Mine-Dr3am** [comment]
Exactly the same thing ! on my iphone and google chrome browser too. I just put the same exemple code on my ftp server.

**Comment by tetreault** [comment]
I have run into this issue with another library, yahoo's Gifshot library. Wouldn't work at all on mobile safari until I added a user gesture and ran it inside there which made it work.

**Comment by WaveF** [comment]
I fixed the problem by using "https" instead of "http".

**Comment by Mine-Dr3am** [comment]
It's work thank you very much !

**Comment by leeprobert** [comment]
This shouldn't be closed. I still get this error with the A-Frame examples.

**Comment by tetreault** [comment]
mind tossing us a little more info @leeprobert maybe theres somethign we can do to help troubleshoot for you

**Comment by JGL** [comment]
Did you get it working @leeprobert - amazing that we are both working on web-based AR!

**Comment by prakashsaran** [comment]
> I solved the problem by use "https" instead of "http".

thanks bro 

I wasted my two hours time. To understand what is the issue ?

**Comment by michaellehmkuhl** [comment]
When troubleshooting these types of errors, be sure not to overlook the importance of the `Feature-Policy` HTTP header. If it's set to a restrictive setting for the camera, Chrome will throw an error before even attempting to ask the user for permission.

https://developers.google.com/web/updates/2018/06/feature-policy

**Comment by sanctifyZhan** [comment]
Maybe, i can open it on iphone, but can't open it on android ver7.0? How i can to fix it?
