### ISSUE TITLE
Possible to run off local file storage on Chrome (Android)?

### ISSUE THREAD

**Issue by Jzege** [jeromeetienne/AR.js#197]
Trying to run three.js>mobile-performance.html. The camera works, but does not recognize the hiro marker. 

For ease of testing I would prefer to have a local test environment, unless I must run your code from a https server as https://github.com/jeromeetienne/AR.js/issues/45 suggests?

**Comment by ZoltanVeres** [comment]
I would suggest to set up an https certificate for your dev machine @mritzco kindly provided a Gist on how to set this up [https://gist.github.com/mritzco/18dfe13096294592d5eb53e7e1a5f63c](url)
For more info head to #45 issue
