### ISSUE TITLE
Front Camera loaded by defaults on Android/Samsung Galaxy

### ISSUE THREAD

**Issue by loretoparisi** [jeromeetienne/AR.js#198]
Hi, the demo works, but by defaults the test phone opens the front camera while the camera app opens with the rear camera. (Android 5.0.2, Samsung Galaxy)

**Comment by xcchcaptain** [comment]
gotach the same problem ,XIaoMi 4s Andorid 7.0

**Comment by yqqyuqiangqiang** [comment]
how to solve this problem?

**Comment by AndreaMonzini** [comment]
i saw similar experience in Samsung S6

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
