### ISSUE TITLE
Freezing on Nexus 6P

### ISSUE THREAD

**Issue by hamza765** [jeromeetienne/AR.js#20]
So i noticed you tested this on a 6P. I tried it out, and it works great! I get what looks like 60fps, but after about 5 seconds, it'll freeze. What's weird is that the animation will keep working, and the little graph on the top right keeps tracking, but my camera is frozen.

**Comment by leemark** [comment]
I'm seeing this same issue as well on a Nexus 5x.

**Comment by jeromeetienne** [comment]
unfortunatly this is a bug from android. and i cant do much at ar.js level.
