### ISSUE TITLE
Object(CubeGeometry) in orientation portrait elongated!

### ISSUE THREAD

**Issue by Den-web** [jeromeetienne/AR.js#201]
Hello everyone! I encountered an incorrect display of the object in portrait mode. My cube is elongated. Who can help me in solving this problem? Thank you in advance

**Comment by pikilipita** [comment]
This issue is already discussed here:
https://github.com/jeromeetienne/AR.js/issues/60

**Comment by Den-web** [comment]
Sanks i see this issues before!
