### ISSUE TITLE
Could this be adopted to read QR value live as well?

### ISSUE THREAD

**Issue by SaKKo** [jeromeetienne/AR.js#208]
I saw a QR demo but that QR is used to open AR web.

I wonder if we could make AR.js be able to read QR from web browsers as well.

Use case,

1. Customer login to Shopping mall website.
2. Customer scan QR to check-in to an event through that website.
3. Customer then get some rewards for checking in.

In this case, customer doesn't have to install any application to their phone.

**Comment by lslzl3000** [comment]
+1

**Comment by anx-mwutte** [comment]
+1

**Comment by nicolocarpignoli** [comment]
I don't think AR.js has to have this kind of feature. This is interesting but not "AR-related". You could for sure add an external QR-reader library and embed it on your web app that also uses AR.js.

Also, I suggest you to see this post where I explain how to use QR codes and AR.js. Maybe such proposal could be suitable also for your needs :)
