### ISSUE TITLE
Error While (cd aframe && make minify) && (cd webvr-polyfill && make minify)

### ISSUE THREAD

**Issue by eadistar** [jeromeetienne/AR.js#21]
@jeromeetienne 
(cd aframe && make minify) && (cd webvr-polyfill && make minify)
cat ../three.js/threex*.js aframe-ar.js \
	../three.js/vendor/jsartoolkit5/build/artoolkit.min.js \
	../three.js/vendor/jsartoolkit5/js/artoolkit.api.js \
	> build/aframe-ar.js 
uglifyjs build/aframe-ar.js > build/aframe-ar.min.js
Parse error at build/aframe-ar.js:170,49
MarkerCloak.markerSpaceShaderFunction = `    
                                        ^
SyntaxError: Unexpected character '`'

is anything that am i missing?

**Comment by jeromeetienne** [comment]
hmm ok so minify is chocking on the shader multi line es6 string in threex-armarkercloak.jshttps://github.com/jeromeetienne/AR.js/blob/master/three.js/threex-armarkercloak.js#L170

**Comment by jeromeetienne** [comment]
short term solution seems to be using harmony branch for uglifyjs - https://www.npmjs.com/package/uglify-js-es6#harmony

the other possibility is to change the strings into something more es5

**Comment by jeromeetienne** [comment]
fixed :)
