### ISSUE TITLE
Dynamic marker detection

### ISSUE THREAD

**Issue by anesumuz** [jeromeetienne/AR.js#210]
I have a case where I need users to create their own custom markers and share them for others to scan. I would essentially need to `POST` metadata of the detected marker or barcode first before returning the AR projection from a back end. In essence having to create a new `<a-marker>` dynamically.

Is there a way to return metadata from a AR.js marker or AR.js barcode without a pre-existing `<a-marker>`  so I can use this to query a remote server?

Else, is there a way to embed meta in a `.patt` while creating custom markers, so I can read the meta and use it to query db.

**Comment by nicolocarpignoli** [comment]
Hi @anesumuz, 
I don't fully understand what you mean. I can tell you that you can of course append to the DOM, dynamically, every HTMLElement (so even an 'a-marker' element) and use custom attribute on the element (data-*) https://www.w3schools.com/tags/att_global_data.asp.

Here's the specific documentation for a-frame component like <a-marker> https://github.com/jeromeetienne/AR.js/tree/master/aframe. 

Feel free to ask me more :)
