### ISSUE TITLE
A-Frame build doesn't work when included with webpack due to require statement in build file

### ISSUE THREAD

**Issue by RSpace** [jeromeetienne/AR.js#211]
When I do this:

```
import AFRAME from 'aframe/src'
require('ar.js/aframe/build/aframe-ar')
```

I get this error:

```
Uncaught ReferenceError: require is not defined
    at Object.663 (aframe-ar.js:3836)
```

Line 3836 is:

```
var THREE = THREE || require("three");
```

I've had to fork and outcomment that line to get things working: https://github.com/RSpace/AR.js/commit/158a3550fd88901a5b66adfa3b87ecf3f87109bd

I don't understand what that require statement is doing in a build file?

**Comment by RSpace** [comment]
The only way I can get your build to work is to do exactly as in the examples: Include first A-Frame and then the AR.js build file in the <head> section. I'm loading things in dynamically, so I can't do it that way in my app.

**Comment by paztis** [comment]
Hi. I encounter this problem also.
To resolve it there's 2 solutions:
- use the script-loader plugin. (require('script-loader!at.js/aframe/build/aframe-ar')l. It will load you without webpack parsing
- use https://www.npmjs.com/package/asm-async-loader a loader I've developed specially for this that do the same but in async mode to activate the asm compile mode of the browser and increase perfs.

```
var promise =require('asm-async-loader!at.js/aframe/build/aframe-ar');
promise.then....

```
