### ISSUE TITLE
Event emitted when marker is recognized?

### ISSUE THREAD

**Issue by donmccurdy** [jeromeetienne/AR.js#217]
Does the `<a-marker/>` primitive emit any events?

I'm responding to a [question on aframe-extras](https://github.com/donmccurdy/aframe-extras/issues/180), and not sure what if any events are fired, or if there's another way to trigger something happening when marker is scanned. Thanks!

**Comment by karneaud** [comment]
Does this still hold true? I'm seeing becameVisible and makerVisible....which one?

**Comment by donmccurdy** [comment]
I see mentions of both [in search](https://github.com/jeromeetienne/AR.js/search?utf8=%E2%9C%93&q=becameVisible&type=), but no code that would emit them and no documentation about it. If someone has tested and they're working, that would be great.

**Comment by karneaud** [comment]
@donmccurdy actually there is a commit [branch](https://github.com/jeromeetienne/AR.js/pull/303/commits/2e61cdc43b2a9cf30f1abb3e754c8381730cb7e8) by @nikolaymihaylov that I tried out and it works perfectly so far using the `emitevents="true"` attribute. However it seems it is yet to be merged. perhaps a petition should be done to make this merge happen

**Comment by jeromeetienne** [comment]
events arent settled in the three.js API, and even less in the aframe api.

In fact i just looked https://github.com/jeromeetienne/AR.js/blob/master/aframe/src/component-anchor.js

and no event is emitted at all

**Comment by donmccurdy** [comment]
Thanks @jeromeetienne! I think https://github.com/jeromeetienne/AR.js/pull/303 would fix this, do you want a version of that PR that excludes the build files?

**Comment by peterlunglum** [comment]
@donmccurdy @jeromeetienne ,

Is the emitevents officially part of the main code base?

**Comment by donmccurdy** [comment]
No, the official codebase does not emit any events when a marker is recognized. While the API may not be settled, I think some event or other will be important for many use cases and would recommend #303 or something like it.

**Comment by donmccurdy** [comment]
Is an event emitted now, or is this not feasible?

**Comment by nicolocarpignoli** [comment]
this is merged https://github.com/jeromeetienne/AR.js/pull/303 and works with <a-marker/> (not with a-marker-camera apparently) :)

**Comment by donmccurdy** [comment]
Awesome, thanks!
