### ISSUE TITLE
Positioning issues when ar.js and aframe cursor interact

### ISSUE THREAD

**Issue by javismiles** [jeromeetienne/AR.js#219]
Good day,
when combining ar.js and aframe there seem to be weird issues with the position parameters, what they are relative to,
how can I make sure that whatever I activate, an image, text, or a 3D shape appears in front of, frontal when looking frontally at the marker?
using position 0,0,0 gives different results depending on the elements being used, if cursor is or is not active, etc, 
how can I make positioning consistent?

for example the presence or not of <a-marker  , makes the positioning of elements change completely,
etc, etc

thanks a lot

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
