### ISSUE TITLE
Support video in webgl

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#22]
# todo
- get object in proper position
- handle resize
- keep the plane in front of the camera
- i got that in webvr experiments -  https://github.com/jeromeetienne/webvr-experiments/blob/master/seethru.html

## advantage
- allow webvr effect in three.js 
- so it would provide stereo and get a phone-in-hmd - google cardboard ar

**Comment by jeromeetienne** [comment]
work is happenning here - https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/video-in-webgl.html

it is going good. still some calibration issues. the 3d is a bit off on the video

**Comment by nicolocarpignoli** [comment]
As I'm cleaning old issues, I will close this as obsolete. If we need something like this, we can reopen it :)
