### ISSUE TITLE
is a-frame-camera y cursor not compatible

### ISSUE THREAD

**Issue by javismiles** [jeromeetienne/AR.js#221]
so I have a code like this (I show just the ending part for brevity)

` ..................

...........a-image id="image-360" scale=".3 .3 .3" position="0 0 0" rotation="0 0 90" src="#city">

      
      <a-entity id="links" scale=".5 .5 .5" layout="type: line; margin: 1.5" position="-1 1 0">
        <a-entity template="src: #link" data-src="#cubes" data-thumb="#cubes-thumb"></a-entity>
        <a-entity template="src: #link" data-src="#city" data-thumb="#city-thumb"></a-entity>
        <a-entity template="src: #link" data-src="#sechelt" data-thumb="#sechelt-thumb"></a-entity>
      </a-entity>

        <a-entity position="0 1.8 4">
        <a-entity camera look-controls mouse-cursor>
          <a-cursor fuse="true" color="yellow"></a-cursor>
        </a-entity>
      </a-entity>
      
    </a-scene>`

which works all well, it allows me to use the cursor to choose the option and change the image below,all good

but I want to use tracking and ar.js ! so I want to add the marker stuff

 <a-marker-camera preset='custom' url='n2.patt'></a-marker-camera>

but whenever I add the marker stuff, in whichever way , it always spoil the cursor thing,
If I take the cursor thing out and use  just the marker then all great, but no cursor.

its like I either have a cursor but no marker stuff or marker stuff but no cursor

can I have both the marker stuff and the cursor working?

thank you so much

**Comment by javismiles** [comment]
I found this way to preserve both marker and cursor, but it has this big problem, i cannot use marker-camera, because i have to handle separately marker and camera and this works way worse than when using marker-camera and putting the elements outside of it

`	.....a-marker preset='custom' url='n2.patt'>
         <a-image id="image-360" scale=".3 .3 .3" position="0 0 0" rotation="0 0 0" src="#city">
           
        <a-entity id="links" scale=".5 .5 .5" layout="type: line; margin: 1.5" position="-1 1 0">
        <a-entity template="src: #link" data-src="#cubes" data-thumb="#cubes-thumb"></a-entity>
        <a-entity template="src: #link" data-src="#city" data-thumb="#city-thumb"></a-entity>
        <a-entity template="src: #link" data-src="#sechelt" data-thumb="#sechelt-thumb"></a-entity>
      </a-entity>
         
            
  	</a-marker>
  	<a-entity camera>
  		<a-cursor fuse="true" color="yellow"></a-cursor>
  	</a-entity>
    </a-scene>`

so this is not a solution,  I need a way to use marker-camera, have the triggered elements outside of it and somehow be able to have the cursor functional to choose things

**Comment by dreinstein10** [comment]
#148
