### ISSUE TITLE
I can't seem to make custom marker work

### ISSUE THREAD

**Issue by Marisannn** [jeromeetienne/AR.js#226]
I've tried everything that the other issues have said but it still won't work. I'm lost on how to make this work.

Here is my code:
```
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/examples/vendor/aframe/build/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js"></script>
<body style="margin : 0px; overflow: hidden;">
	<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;'> 
		<a-marker preset="custom" url="{{ url('/build/images/ar/pattern-marker.patt') }}"> 
			<a-sphere position="0 0.5 0" radius="0.5" color="#EF2D5E"></a-sphere>
			<a-plane position="0 0 0" rotation="-90 0 0" width="1" height="1" color="#7BC8A4"></a-plane>
		</a-marker> 
	</a-scene>
</body>
```

I've tried the AR.js [custom marker](https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html) but it still won't work.

**Comment by shahidul56** [comment]
First go there: https://github.com/u4bi/simple-ar.js

upload custom picture generate your won marker (download .patt file): https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html

Now edit read mark place with your won .patt file name(don't forget to place your .patt file to data folder)

![git](https://user-images.githubusercontent.com/11449967/31724952-f0ae0a9c-b444-11e7-9b98-ac2a42f29b5b.PNG)

Now run index.html done :)

**Comment by Marisannn** [comment]
@shahidul56 Hello, thank you it works! One problem is that the box rotates continuously. How can i change it?

**Comment by Marisannn** [comment]
@shahidul56 thank you. it works!

**Comment by ThibaultAr** [comment]
Hi, I have the same problematic with aframe, th eonly question I have is:
How you call your marker in aframe ? does it take 'u4bi' like 
```
<a-marker preset="u4bi"> 
```
?

Thanks

**Comment by ClementTrois** [comment]
It work for me too !
But know we have customs markers how we can use different objects for each one?
I mean a plane for marker one and an image for marker two 

ThibaultAr : The index.js put the marker in index.html

**Comment by ClementTrois** [comment]
It work for me too !
But now we have customs markers how we can use different objects for each one?
I mean a plane for marker one and an image for marker two

ThibaultAr : The index.js put the marker in index.html

**Comment by ClementTrois** [comment]
It work for me too !
But now we have customs markers how we can use different objects for each one?
I mean a plane for marker one and an image for marker two
I see that it use newMesh ? 

ThibaultAr : The index.js put the marker in index.html

**Comment by ClementTrois** [comment]
before use the tips of shahidul56 my code was like this :

 <a-scene>
      
      <a-marker type='custom' url='https://raw.githubusercontent.com/jeromeetienne/AR.js/master/data/multimarkers/multi-abcdef/patt.a'>
       <a-plane width="1" height="1" position="0 0 0" scale="1" rotation="-90 0 0" src="http://78.media.tumblr.com/4e1c235b28d7f9cbd4ff4f3a5e290d5a/tumblr_ozefe4VTRz1rb7ns9o1_1280.jpg"></a-plane></a-marker>

      
      <a-marker preset="kanji">
      <a-image src="http://78.media.tumblr.com/4e1c235b28d7f9cbd4ff4f3a5e290d5a/tumblr_ozefe4VTRz1rb7ns9o1_1280.jpg"></a-image>
      </a-marker>

**Comment by ClementTrois** [comment]
Before use this tips my code was like this : 

 
<a-marker type='custom' url='https://raw.githubusercontent.com/jeromeetienne/AR.js/master/data/multimarkers/multi-abcdef/patt.a'>
<a-plane width="1" height="1" position="0 0 0" scale="1" rotation="-90 0 0" src="http://78.media.tumblr.com/4e1c235b28d7f9cbd4ff4f3a5e290d5a/tumblr_ozefe4VTRz1rb7ns9o1_1280.jpg"></a-plane></a-marker>


 <a-marker preset="kanji">
<a-image src="http://78.media.tumblr.com/4e1c235b28d7f9cbd4ff4f3a5e290d5a/tumblr_ozefe4VTRz1rb7ns9o1_1280.jpg">
</a-image>
</a-marker>

How to apply it?

**Comment by ClementTrois** [comment]
Before my code was like this, how to apply it?

**Comment by shahidul56** [comment]
ClementTrois


![capture](https://user-images.githubusercontent.com/11449967/33483805-b44dbfe6-d6c9-11e7-872d-ea053b1cffa5.jpg)

edit and add code to this marked area 


Make new scene and cemera for showing different obj in different marker
` scene2 = new THREE.Scene();
 camera2 = new THREE.Camera();
  scene2.add(camera);
  scene2.visible = false;`



Now create a new mesh "mesh2" for different color cube (This time it's color i yellow)

`  mesh2 = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial({
          color: 0xFFFF00,
          transparent: true,
          opacity: 0.5
     }));
`

Now add this new "mesh2" to "scene2"

`scene2.add(mesh2);` 

![cscas](https://user-images.githubusercontent.com/11449967/33484355-13627ccc-d6cc-11e7-84a6-63a4e0151790.PNG)


NOW again edit and add this with this marked area 

` arContext.init(function onCompleted(){
        
        camera2.projectionMatrix.copy(arContext.getProjectionMatrix());

    });
render2();  
`

    

Now we are calling rander 2 for  showing mesh2

Make render2 function


`function render2(){
    requestAnimationFrame(render);
    renderer.render(scene,camera);                

    if(arSource.ready === false) return;

    arContext.update(arSource.domElement);
    scene2.visible = camera2.visible;


    mesh2.rotateX(.1);

}          `

**Comment by ClementTrois** [comment]
Don't work I missed something?

`var renderer,
    scene,
    camera,
    container;
var arSource,
    arContext,
    arMarker = [];
var 
    mesh;
init();
function init(){

    container = document.getElementById('container');
    renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    scene = new THREE.Scene();
    camera = new THREE.Camera();
   
    scene2 = new THREE.Scene();
    camera2 = new THREE.Camera();

    renderer.setClearColor(0x000000, 0);
    renderer.setSize(window.innerWidth, window.innerHeight);
    container.appendChild(renderer.domElement);
    scene.add(camera);
    scene.visible = false;
    
    scene2.add(camera); 
    scene2.visible = false;

    mesh = new THREE.Mesh(new THREE.BoxGeometry(1,1,1), new THREE.MeshBasicMaterial({
        color: 0xFF00FF,
        transparent: true,
        opacity: 0.5
    }));
    scene.add(mesh);
    
    mesh2 = new THREE.Mesh(new THREE.BoxGeometry(1,1,1), new THREE.MeshBasicMaterial({
        color: FFF,
        transparent: true,
        opacity: 0.5
    }));
    scene2.add(mesh2);

    arSource = new THREEx.ArToolkitSource({
        sourceType : 'webcam',
    });

    arContext2 = new THREEx.ArToolkitContext({
        cameraParametersUrl: './assets/data/camera_para.dat',
        detectionMode: 'mono',
    });
    
    arMarker[0] = new THREEx.ArMarkerControls(arContext, camera, {
        type : 'pattern',
        patternUrl : './assets/data/patt.hiro',
        changeMatrixMode: 'cameraTransformMatrix'
    });

    arMarker[1] = new THREEx.ArMarkerControls(arContext2, camera2, {
        type : 'pattern',
        patternUrl : 'a.patt',
        changeMatrixMode: 'cameraTransformMatrix'
    });

    /* handle */
    arSource.init(function(){
        arSource.onResize();
        arSource.copySizeTo(renderer.domElement);

        if(arContext.arController !== null) arSource.copySizeTo(arContext.arController.canvas);

    });

    arContext.init(function onCompleted(){
        
        camera.projectionMatrix.copy(arContext.getProjectionMatrix());
camera2.projectionMatrix.copy(arContext.getProjectionMatrix());

});

    render();   
    render2();
}   

function render(){
    requestAnimationFrame(render);
    renderer.render(scene,camera);                

    if(arSource.ready === false) return;

    arContext.update(arSource.domElement);
    scene.visible = camera.visible;

    mesh.rotateX(.1);

}

function render2(){
requestAnimationFrame(render);
renderer.render(scene,camera);

if(arSource.ready === false) return;

arContext.update(arSource.domElement);
scene2.visible = camera2.visible;

mesh2.rotateX(.1);
}
`

**Comment by shahidul56** [comment]
![fef](https://user-images.githubusercontent.com/11449967/33494382-47628a6e-d6ed-11e7-9f61-d934e02f2b1f.PNG)

declare 
`cemera2`   and `scene2`  

like this

**Comment by ClementTrois** [comment]
I have a white screen 

`var renderer,
    scene,
    camera,
    scene2,
    camera2,

    container;

var arSource,
    arContext,
    arMarker = [];

var 
    mesh;

init();

function init(){



    container = document.getElementById('container');

    renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    scene = new THREE.Scene();
    camera = new THREE.Camera();
    
    scene2 = new THREE.Scene();
    camera2 = new THREE.Camera();

    renderer.setClearColor(0x000000, 0);
    renderer.setSize(window.innerWidth, window.innerHeight);

    container.appendChild(renderer.domElement);
    scene.add(camera);
    scene.visible = false;
    
    scene2.add(camera); 
    scene2.visible = false;


    mesh = new THREE.Mesh(new THREE.BoxGeometry(1,1,1), new THREE.MeshBasicMaterial({
        color: 0xFF00FF,
        transparent: true,
        opacity: 0.5
    }));
    scene.add(mesh);
    
    mesh2 = new THREE.Mesh(new THREE.BoxGeometry(1,1,1), new THREE.MeshBasicMaterial({
        color: FFF,
        transparent: true,
        opacity: 0.5
    }));
    scene2.add(mesh2);



    arSource = new THREEx.ArToolkitSource({
        sourceType : 'webcam',
    });

    arContext2 = new THREEx.ArToolkitContext({
        cameraParametersUrl: './assets/data/camera_para.dat',
        detectionMode: 'mono',
    });
    
  
    

    arMarker[0] = new THREEx.ArMarkerControls(arContext, camera, {
        type : 'pattern',
        patternUrl : './assets/data/patt.hiro',
        changeMatrixMode: 'cameraTransformMatrix'
    });

    arMarker[1] = new THREEx.ArMarkerControls(arContext2, camera2, {
        type : 'pattern',
        patternUrl : 'a.patt',
        changeMatrixMode: 'cameraTransformMatrix'
    });





    /* handle */
    arSource.init(function(){
        arSource.onResize();
        arSource.copySizeTo(renderer.domElement);

        if(arContext.arController !== null) arSource.copySizeTo(arContext.arController.canvas);

    });

    arContext.init(function onCompleted(){
        
        camera.projectionMatrix.copy(arContext.getProjectionMatrix());
camera2.projectionMatrix.copy(arContext.getProjectionMatrix());

});


    render();   
    render2();
}   




function render(){
    requestAnimationFrame(render);
    renderer.render(scene,camera);                

    if(arSource.ready === false) return;

    arContext.update(arSource.domElement);
    scene.visible = camera.visible;


    mesh.rotateX(.1);

}

function render2(){
requestAnimationFrame(render);
renderer.render(scene,camera);

if(arSource.ready === false) return;

arContext.update(arSource.domElement);
scene2.visible = camera2.visible;


mesh2.rotateX(.1);
}
`

**Comment by ClementTrois** [comment]
Declare mesh2; too? It don't change nothing

**Comment by ClementTrois** [comment]
My first custom marker work but the second marker Hiro don't work

this is my code, I have made some change 
![capture d ecran 2017-12-02 a 18 43 53](https://user-images.githubusercontent.com/34157290/33518198-6443cba8-d791-11e7-9690-e9875b50f4db.png)

What we put in artcontext2 ? it's the same of artcontext 
`  arContext2 = new THREEx.ArToolkitContext({
        cameraParametersUrl: './assets/data/camera_para.dat',
        detectionMode: 'mono',
    });
`
I don't found

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
