### ISSUE TITLE
Question about natural feature tracking in ar.js

### ISSUE THREAD

**Issue by OmranAbazid** [jeromeetienne/AR.js#227]
Hello, 

does following this tutorial:
[natural feature tracking](https://archive.artoolkit.org/documentation/doku.php?id=7_Examples:example_nftsimple)
will enable me to have image tracking?

Thanks

**Comment by bethannezink** [comment]
@OmranAbazid Did you end up trying it? If so, I'd love to know how it turned out.

**Comment by OmranAbazid** [comment]
@bethannezink No, because I've read in multiple places that Natural feature tracking(NFT) is not integrated into AR.js yet. Artoolkit GitHub project has a branch with NFT implemented but I think it is still not implemented in AR.js.

**Comment by mikegoodstadt** [comment]
@jeromeetienne Hi! Can you update us on NFT? 
We need AR on Open Access research papers so OSS / MIT licence code is required ie. we love ARToolkit/AR.js :)
However publishers will not permit Hiro-style markers so we need NFT as already avaible in ARToolkit. Is there a particular limitation for NFT implementation in AR.js?
Many thanks.

**Comment by javismiles** [comment]
I agree, would be great to see this implemented in ar.js

**Comment by kaypea** [comment]
@jeromeetienne Is there any way to implement Natural feature tracking in Ar.js

**Comment by Erniastukas** [comment]
Hey, have one more request to do that too!

@jeromeetienne - any chance you could update us on the status of it?

**Comment by javismiles** [comment]
I agree, could somebody update status on this please? thank you very much

**Comment by jeromeetienne** [comment]
AR.js do not handle NFT at the moment. sorry about that

**Comment by javismiles** [comment]
yes, we know that Jerome, but is there a plan to incorporate it in the future? and if so, any forecast? thanks a lot for the update, all best ;)

**Comment by jeromeetienne** [comment]
Sure, if somebody implements it :)

**Comment by javismiles** [comment]
I wish I was an expert in that to help with it myself ;), so that doesn't sound like it will happen anytime soon then :D well at least now we know :D thank you for the update ;)

**Comment by jeromeetienne** [comment]
me too i wish i could do it... so many people ask for it.

**Comment by Whiteaw2** [comment]
Would it be possible to leverage some of OpenCV.js to integrate NFT tracking? If so, I'd be willing to work on it. 

Trying to wrap my head around how to implement it into ar.js for mobile web.

**Comment by evaristoc** [comment]
@Whiteaw2: it would be easier by using artoolkit instead, which is already the base of ar.js.
