### ISSUE TITLE
Random change of orientation, default orientation and overheating/slow

### ISSUE THREAD

**Issue by javismiles** [jeromeetienne/AR.js#228]
Couple of things

1) When I use anything, simple, like:
a-box position='0 0 0.5' material='opacity: 0.5;'

or an image,
It appears one way and suddenly it may go upside down, and later revert again and then
go upside down again

how can I prevent this from happening? it`s a real problem, how can I make sure that the orientation of the box or image  or whatever stays correct always?

Also when  I use an image with a-image  it always appears upside down, how can I make  it appear right?

2) If I use a-box with position  0,0,0 and rotation  0,0,0 it doesnt appear facing me frontally, it appears rotated,  why? and how can I make it truly 0,0,0 in all axis?

3) finally, I have a Nexus 5X, not the best phone but quite good. Using AR.js will make the phone go crazy slow and super hot very fast, so that it becomes unusable after reloading the simplest code 2 or 3 times. I get it, AR requires power, is this supposed to improve in the future soon?
I´m using Android in Nexus 5X

best

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
