### ISSUE TITLE
The Upside Down issue

### ISSUE THREAD

**Issue by javismiles** [jeromeetienne/AR.js#229]
The Upside Down issue is really causing me trouble, anybody has any tips?
Whatever I put in a scene, a video, an image, a box, a sphere, etc, whatever
sometimes, often it appears upside down, down what should be up, and then it randomly reverts
the right side up and then  again goes upside down, randomly, unpredictable,
for all types of objects, 

any tips?
best

**Comment by javismiles** [comment]
This issue is the main issue  that remains for me to fix for my current  phase in my project, any tips?
whatever object I put, i keeps flipping randomly upside down and back to normal depending on I dont know what, how can I force it  to always have the up  looking up

**Comment by javismiles** [comment]
any help about this? all is working well except that when I use images or videos, they appear upside down very often, its kind of random, sometimes they appear the right side up and sometimes upside down, and I cant control it, how can I ensure that they always appear the right side up? thank you

**Comment by OmranAbazid** [comment]
It depends on how you are doing it, im using pictures and it is working fine for me
Make sure your marker looks different when it is flipped 
Here is my code for adding image instead of 3d object, im using plane geometry:

```
var imgTexture = THREE.ImageUtils.loadTexture("images/old-aja.jpg");
var imgMaterial = new THREE.MeshBasicMaterial({ map: imgTexture });
var geometry = new THREE.PlaneGeometry(5, 5);
var mesh = new THREE.Mesh(geometry, imgMaterial);

mesh.position.y = 0;
mesh.position.x = 0;
mesh.rotation.x = 1.5 * Math.PI;
scene.add(mesh);
```

**Comment by javismiles** [comment]
Hey Omran, thank  you very much for your comment, there are a few things to consider here:

- Yes, my marker is different upside down, and I have also just now tried the same thing with the original HIRO marker and the problem is the same. And the problem happens with images and videos.

- Look the thing  is that I have to scan my marker frontally. If you scan it with the marker on a table and you looking from above towards it then probably this problem does not happen. But when you point at a marker frontally, the marker in front of you and you scanning it frontally, then this problem happens with both HIRO Marker and my custom marker. 

- I use a-Frame with ar.js therefore I don´t use  Three.js code directly, I use a-image  and a-video to embed images and videos. But it´s nice to learn some three.js code also, could you also tell me what would be the code to add a video instead of an image? thanks a lot Omran

Thank you again ;)

**Comment by nicolocarpignoli** [comment]
@javismiles is this solved?

**Comment by nicolocarpignoli** [comment]
closing as now answer from author for a long time
