### ISSUE TITLE
Different behavior in desktop, mobile vs. aframe, three.js

### ISSUE THREAD

**Issue by PyryM** [jeromeetienne/AR.js#23]
If the sourceWidth, sourceHeight, displayWidth, and displayHeight are set the same in the aframe wrapper and the pure three.js version, in desktop (win10 x64, chrome 56.0.2924.87) both produce nearly identical outputs as you would expect (3js on left, aframe on right):
![aframe_vs_3js](https://cloud.githubusercontent.com/assets/3202276/24064533/60ca9c0e-0b3b-11e7-885a-876785fa9431.PNG)

In mobile (OnePlusOne, android 6.0.1), however, the same two webpages produce drastically different outputs (3js on left, aframe on right):
![aframe_vs_3js_mobile](https://cloud.githubusercontent.com/assets/3202276/24064549/706f8a70-0b3b-11e7-9542-dfa8e75126a5.jpg)

Note that, in addition to the different aspect ratio and cropping, the aframe version seems to be at a lower resolution.

The two webpages are:
https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html
https://hypogeum.info/misc/aframe_arjs_lowquality.html

The aframe example is exactly the example code from the readme, except with the settings changed to mirror the three.js mobile example:
```html
<a-scene stats embedded artoolkit='sourceType: webcam; sourceWidth: 240; sourceHeight: 180; maxDetectionRate: 30; detectionMode: mono'>
```

**Comment by jeromeetienne** [comment]
i think i understand what is happening. 

three.js examples got the display issue fixed (cc @blq) but the aframe doesnt have it yet.

**Comment by jeromeetienne** [comment]
- Discussion with fredrick - open the webcam with the displayWidth, not the sourceWidth
  - this.parameters.displayWidth
  - maxWidth: this.parameters.sourceWidth
  - source is influence resolution/performance of videoTexture (e.g. refraction, marker cloak)
  - so full screen for normal demo, but when performance related (aka when using video as texture) then tune down the resolution

**Comment by jeromeetienne** [comment]
*TODO* in context, change sourceWidth/sourceHeight by canvas height

- reevaluate all the options in aframe-ar

**Comment by jeromeetienne** [comment]
@PyryM it should work now. tell me how it goes

```<a-scene stats embedded artoolkit='sourceType: webcam; sourceWidth: 240; sourceHeight: 180; maxDetectionRate: 30; detectionMode: mono'>```

change sourceWidth into canvasWidth, and the same for canvasHeight

**Comment by jeromeetienne** [comment]
i did a mobile-performance for a-frame too 

https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/mobile-performance.html

**Comment by PyryM** [comment]
Now it looks pretty similar in both threejs vs aframe on mobile: in landscape they are identical, and in portrait they seem to be at the same base resolution, but with slightly different cropping.

**Comment by jeromeetienne** [comment]
perfect. thanks for reporting this
