### ISSUE TITLE
Clicking on object

### ISSUE THREAD

**Issue by javismiles** [jeromeetienne/AR.js#231]
Good day
Using a-cursor on a normal entity camera and scene
I want to be able to detect click on an object, but its not working,
I can create a cursor no probs, but i cant detect a click, any tips? thank u

AFRAME.registerComponent('cursor-listener', {
  schema: {
    on: { type: 'string' },
    target: { type: 'selector' },
    src: { type: 'string' },
    dur: { type: 'number', default: 300 }
  },

  init: function() {
    var vid = document.getElementById('video');
    this.el.addEventListener('click', function(evt) {
      window.open("https://www.whateverwebsite.com");
    });
  }
});

**Comment by javismiles** [comment]
fixed getting rid of fuse and look controls

**Comment by perrychen901105** [comment]
@javismiles Hello, I am facing the same problem that I cannot click on object, here are my code
`<a-marker preset='custom' type='pattern' url='./assets/pattern-marker.patt'>
          <a-obj-model class="link" src="#object" mtl="#material" color="#FF0000" scale="0.02 0.02 0.02" position="0 0 0" rotation="-90 0 0" changescene__click="event: mouseenter; linkto: page"></a-obj-model>        
      </a-marker>

      <a-entity camera look-controls>
        <a-cursor id="cursor"
          animation__click="property: scale; startEvents: click; from: 0.1 0.1 0.1; to: 1 1 1; dur: 150"
          animation__fusing="property: fusing; startEvents: fusing; from: 1 1 1; to: 0.1 0.1 0.1; dur: 1500"
          event-set__1="_event: mouseenter; color: springgreen"
          event-set__2="_event: mouseleave; color: black"
          fuse="true"
          raycaster="objects: .link">
        </a-cursor>
      </a-entity>`
Can you give me some more details about how you fixed the problems.
