### ISSUE TITLE
Can Marker Pattern Size be different than 16x16 ?

### ISSUE THREAD

**Issue by dreinstein10** [jeromeetienne/AR.js#234]
This is not really an issue, but I didn't know where else to ask.

 I read [here](https://archive.artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training) that the default size for the custom markers (.patt files) is 16x16 and I can make custom markers work fine with the current setup. 

However, if I create a 32x32 .patt file of the exact same image, then the marker is not recognized. I guess only 16x16 works, which is fine, but I was wondering if anybody knows where to modify the setup or the initial parameters to recognize custom markers with a higher resolution?  I have been looking at the "aframe-ar.js" file, but I still don't have a clue :(

Thanks in advance

[ I created the .patt files with a modified version of [this tool](https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html) ]

**Comment by jeromeetienne** [comment]
this is a limitation deep inside artoolkit. so unfortunatly it isnt possible :(

sorry about that

**Comment by dreinstein10** [comment]
That's unfortunate. 
Well, thanks for the clarification and hard work :)
