### ISSUE TITLE
multiple-independent-markers.html do not recognize barcode

### ISSUE THREAD

**Issue by calderonsteven** [jeromeetienne/AR.js#235]
but when I use the kanji marker show the object in the entity
`<a-marker type='barcode' barcodeValue='5'>`

It worked well in old versions of ar.js (aframe)

Thanks and awesome work.

**Comment by ZoltanVeres** [comment]
Get latest version of AR.js and change `barcodeValue` to `value` 
`<a-marker type='barcode' value='5'></a-marker>`
Please get back to us if this is still not working for you, until then the issue remains closed.
