### ISSUE TITLE
mouse-cursor / click is triggered on the whole scene instead of the specified element

### ISSUE THREAD

**Issue by javismiles** [jeromeetienne/AR.js#237]
good day, mouse cursor triggering works all well with aframe. In combination with ar.js, the event attached to an object, for example a box which inside a-marker, is triggered when  you click the box but also when  you click the background. It should be triggered only when you click the box

`    <a-box position="0 0 0" rotation="0 0 0" color="skyblue"
             event-set__enter="_event: mouseenter; material.color: yellowgreen; scale: 3 1 1"
             event-set__leave="_event: mouseleave; material.color: skyblue; scale: 1 1 1">
        <a-animation attribute="rotation" begin="click" dur="500" fill="backwards" to="30 30 360"></a-animation>
      </a-box>`

using

`<a-entity camera mouse-cursor>`

**Comment by nicolocarpignoli** [comment]
same (sort of) discussion here: https://github.com/jeromeetienne/AR.js/issues/249
