### ISSUE TITLE
Require.js / can not load ar.js

### ISSUE THREAD

**Issue by pixue** [jeromeetienne/AR.js#238]
Hello,

Is it posible  to load ar.js using require.js?  

When loading the modules the application stops working and by consulting the Firefox console I can see the following error:
Error: Script error for: WebAR
http://requirejs.org/docs/errors.html#scripterror

Looks like I forget to add WebAR but in the project that I created to test ar.js, it works without problems and does not request any WebAR file. The scripts of this project are loaded using the <script> tag.

Then I leave the file main.js (removed a lot of stuff), in case it clarifies something. If you need more info feel free to ask for it.

Thanks in advance.

*three.js loading looks strange because require.js is not loading it out of the box and so I have to use the workaround ar https://stackoverflow.com/questions/30358323/require-js-not-loading-three-js. 

```javascript
var mediator = new Mediator();

define("three-glue", ["three"], function (three) {
    window.THREE = three;
    return three;
});

//Configuración de require.js
require.config({
    baseUrl: 'js',
    paths: {
	// Paths to libraries
        "three": '../js/lib/three',
        "orbitControl": '../modules/engine3d/OrbitControls',
        /*"arjs": '../modules/augmentedReality/ar.min',*/ //NOT WORKING
 	"arHelper": '../modules/augmentedReality/arHelper',
     
        // Project HTML       
        "augmentedRealityHtml": '../modules/augmentedReality/augmentedReality.html'
    },
    map: {
        '*': {
            three: 'three-glue',     
        },
        'three-glue': {
            three: 'three'
        }
   },
    shim: {
        //3D libraries  
        "orbitControl": {
            deps: ['three']},
        "arHelper": {
            deps: ['three']},
        /*arjs: {
         deps: ['three']},*/ //NOT WORKING
    }
});

//
require(["../modules/mediatorSubscriptions/mediator", "domReady"], function (m) {
    m.start();
});
```

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
