### ISSUE TITLE
Attach video to specified tag

### ISSUE THREAD

**Issue by anesumuz** [jeromeetienne/AR.js#239]
It seems the webcam feed is hard coded to append to the body of the webpage. Is there any means of rather appending to other than thee body? e.g a specific div?

**Comment by jeromeetienne** [comment]
In this case the easiest is to use an iframe . I hope this helps

**Comment by anesumuz** [comment]
Ok thanks..I'm looking at using AR.js with Ionic so having the video in body overflows all other UI. Any particular reason to appenddl to body and not a target element? Would like to chime in and  contribute toallow for targeting an element

**Comment by jeromeetienne** [comment]
No specific reason. Just the most common case
