### ISSUE TITLE
parameter, threshold to change precision of marker detection

### ISSUE THREAD

**Issue by javismiles** [jeromeetienne/AR.js#240]
Im doing a project in which the shape of the marker can change a bit sometimes, there must be a parameter somewhere in the ar.js code or in the artoolkit code, a threshold of some kind
that sets the sensitivity of the detection algorythm to detect the marker, so that its more or less precise, so that there are more or less chances of false positives,
where is that parameter in the code? I need to change it, where in the code is it? 
thanks a lot

**Comment by javismiles** [comment]
in the aframe-ar code I find functions like 'setThresholdMode','setThreshold','setPatternDetectionMode',etc,the question is if any of them or anhy other can allow me to change the threshold of confidence to declare an event as a successful detection

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
