### ISSUE TITLE
Feature request: Render an iframe or canvas element on marker

### ISSUE THREAD

**Issue by DJviolin** [jeromeetienne/AR.js#241]
Is it possible somehow to render an iframe or canvas element on marker? It opens up the possibility to project 3D buildings from the Google Maps API on marker.

**Comment by ZoltanVeres** [comment]
This can be done with A-Frame, using a canvas (iframes cannot be rendered in WebGL or at least is extremely complicated) from more info check [How do I display <iframe>s or render HTML in A-Frame](https://aframe.io/docs/0.7.0/introduction/faq.html#how-do-i-display-lt-iframe-gt-s-or-render-html-in-a-frame)
