### ISSUE TITLE
ExitStatus Program terminated with exit(0)

### ISSUE THREAD

**Issue by T1l3** [jeromeetienne/AR.js#245]
Hi,

I have this error when I deploy on server (platform.sh), I got this error after accepting camera :
```

Uncaught ExitStatus ar.js:19
message: "Program terminated with exit(0)"
name: "ExitStatus"
status:    0
__proto__: Error at https://xxx.eu.platform.sh/assets/js/ar.js:19:2247
   constructor: ƒ ExitStatus(status)
     arguments:    null
     caller:    null
     length:    1
     name:    "ExitStatus"
     prototype: Error at https://xxx.eu.platform.sh/assets/js/ar.js:19:2247
    __proto__: ƒ ()
    [[FunctionLocation]]:  ar.js:19
    [[Scopes]]: Scopes[1]
   stack: "Error↵    at https://xxx.eu.platform.sh/assets/js/ar.js:19:2247"
```

How to fix that ?

Thanks,

PS: This happen on latest versions of Chrome, Safari and Firefox
PS2: SO link: https://stackoverflow.com/questions/47269591/uncaught-exitstatus-with-ar-js-on-server

**Comment by ZoltanVeres** [comment]
@T1l3 Are you using AR.js in a node environment?

**Comment by runningo** [comment]
@ZoltanVeres Hi,
me also has same ploblem.
when i tested only in browser side, everything looks well, but
when i tested on node environment, "program terminated with exit(0)" error message comes out.
Do you know how to resolve this problem?
thx.

**Comment by ericflyfly** [comment]
I have the same problem when I use it on node environment. Anyone able to solve it?

**Comment by nicolocarpignoli** [comment]
solved
