### ISSUE TITLE
Video sourceType

### ISSUE THREAD

**Issue by martynvandijke** [jeromeetienne/AR.js#247]
I have a video inside the browser (from a webrtc connection) where i want to detect an marker and display something above it.
I searched the docs but I am not sure how to implement this. 
According to the docs it should be possible to have `sourceType:video`
But then how to I specify wich video element it has to take ?

**Comment by OmranAbazid** [comment]
go to This link : [basic.html demo](https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/basic.html)
and look at section 'handle arToolkitSource'

you will find what you want
