### ISSUE TITLE
Front and Retro Camera issues

### ISSUE THREAD

**Issue by AndreaMonzini** [jeromeetienne/AR.js#248]
Hello,

i was searching a solution for automatic retro camera selection but i have found many solutions, so i try to organize all the issues related to the topic:

Front or Rear Camera Selection ----> https://github.com/jeromeetienne/AR.js/issues/86
Upgrade Browser or use a Polyfill --> https://github.com/jeromeetienne/AR.js/issues/96
Automatic Camera Selection -------> https://github.com/jeromeetienne/AR.js/issues/178 , https://github.com/jeromeetienne/AR.js/pull/180

Related to https://github.com/jeromeetienne/AR.js/issues/74 , https://github.com/jeromeetienne/AR.js/issues/86 , https://github.com/jeromeetienne/AR.js/issues/96, https://github.com/jeromeetienne/AR.js/issues/117 , https://github.com/jeromeetienne/AR.js/issues/178 , https://github.com/jeromeetienne/AR.js/pull/180 , https://github.com/jeromeetienne/AR.js/issues/198

**Comment by nicolocarpignoli** [comment]
I close as not a real issue, but thanks for this, it will be helpful for people struggling with this :)
