### ISSUE TITLE
do a cristal skull demo

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#25]
- for refraction example, use shaddow and remove shaddow.html
- super nice refraction example - https://youtu.be/fhFzStkoE50?t=35
- for refraction example, use a skull, aka crustal skull
  - http://tf3dm.com/download-page.php?url=cranio-11055
  - https://www.yobi3d.com/q/skull
  - good model - see if you can get this one https://www.yobi3d.com/i/ieAvsKA6d2

**Comment by nicolocarpignoli** [comment]
update the readme with @stemkoski examples. they are very good and helpful. close as obsolete and not needed anymore
