### ISSUE TITLE
Npm package takes 250Mb

### ISSUE THREAD

**Issue by paztis** [jeromeetienne/AR.js#250]
Hi
The npm published package contains all your examples. They are very heavy cause of the videos, ...
All time I want to install a project that refers to yours, I'll takes 5 mn to download.
We don't really need the examples on npm. We can look at them on github.
Is it possible to create a .npmignore file on project root level and fill inside all the path of your example folders ? Like this the will not be published on npm.

Thanks

**Comment by ZoltanVeres** [comment]
@paztis That's a wonderful idea! Pull requests are welcome!

**Comment by paztis** [comment]
PR available here: #256

**Comment by ZoltanVeres** [comment]
@paztis PR was merged, it will be released in 1.5.5 version. Thank you for your contribution! :100:
