### ISSUE TITLE
Publish latest release on NPM

### ISSUE THREAD

**Issue by paztis** [jeromeetienne/AR.js#251]
Hi,

It seems that npm publication is still in version 1.4.10 while your last git version is 1.5.1.
I'm not working with the git repository, only with npd packages
Can you publish it on each release ?

**Comment by ZoltanVeres** [comment]
@paztis Based on discussion with @jeromeetienne we want to automate the npm publishing. So on each release the npm publishing should be triggered by a webhook. Can you point us to a solution? What's the common practice?

**Comment by AVGP** [comment]
How about using Travis? https://docs.travis-ci.com/user/deployment/npm/

**Comment by paztis** [comment]
Hi all,

I never automate it, but is seems that Travis is one of the most used solutions

**Comment by AVGP** [comment]
I'm happy to set it up, if nobody else wants to do it 🙃

**Comment by ZoltanVeres** [comment]
@AVGP Pullrequests with some setup instructions are very welcome!

**Comment by AVGP** [comment]
Well no PR needed, really:

* go to travisci.org
* login with your Github account
* Click "+" on the left side next to "My repositories"
* Click on the repository you wanna add to Travis and activate it
* Follow instructions at https://docs.travis-ci.com/user/deployment/npm/
That's all folks :)

**Comment by lcb931023** [comment]
Has there been any progress on automating this via Travis? Looks like we have a good solution pending implementation :)

**Comment by leon4992** [comment]
Hello, i'm interested in this too, it would be great to have an up to date npm package.

**Comment by nicolocarpignoli** [comment]
@jeromeetienne i think this is important. can we resolve this?

**Comment by mustafasaifee42** [comment]
Hey,

Is this issue resolved because I tried importing ar.js using npm but it didn't work for me. I am using the create-react-app to create a react app and then import ar.js using import or require but it doesn't seem to work :(. Also when testing with runkit it show error '_Error: Cannot find module 'ar.js'_'

**Comment by logiclogue** [comment]
Very surprised this hasn't been sorted yet

**Comment by sn3p** [comment]
When can we expect an updated npm package?

**Comment by joestrong** [comment]
I think this issue should be closed. The latest release (1.6.2) is on NPM. 

Any issues about using it as an NPM module should be a separate issue
