### ISSUE TITLE
Need a way stop AR on a-scene unloading

### ISSUE THREAD

**Issue by paztis** [jeromeetienne/AR.js#255]
Currently, when we remove the dom element, all 3d is stopped.
But the video and the overlay helpers (markersAreaEnabled and
trackingBackend) are still present.
If I restart again the AR, new overlay helpers arppears near the first one.

Is there a way to stop properly the AR (ie stop video, remove overlays, destroy ARController, ...) ? I really need it to display/hide the AR in an applicaiton lifetime.

**Comment by paztis** [comment]
I was trying to access to the ARCotroller without success on my code (because it's created automatically by the a-frame tag. No root accessor of the arController instance on window)

But I just found an accessor :
aSceneEl.systems.arjs._arSession.arContext.arController.dispose()

Hard to access it ^^
I try to access to the video also now.

But the graphic helpers are still on the screen.

The library is not really planned to do this. Everything is accessible to start AR, but then nothing during its lifetime...

**Comment by paztis** [comment]
another problem is the video resize interval continue to run:
`var timerId = setInterval(function(){
    if( Date.now() - startedAt > 10000*1000 ){
        clearInterval(timerId)
        return
    }
    // onResize()
    window.dispatchEvent(new Event('resize'));
}, 1000/30)`

So if I remove manually the video element, it crashes. And more after AR suppression it continues to run

Is it possible to reflect about a proper way to load / unload the controller ?

**Comment by paztis** [comment]
In fact it seems that all the window resize handlers are persistant. On each window resize (real ones or triggered ones) there's multiple functions that tries to exec on already deleted obejcts, (dom, video element, canvas, ...) and it always throws exceptions
So there's really no way to stop properly an instance here

**Comment by Vamoss** [comment]
I am also looking for it, the component doesn't seem to be built for single page apps. I also couldn't find a way to trigger the capture start, once you add `aframe-ar.js` in your html, it start capturing. Even when you don't have the `<a-scene arjs>` instantiated.
So, we will move forward to change the component itself to add these features. I am not will be a solution.

**Comment by letsrock85** [comment]
Yep, I looking for it as well. Any updates/luck to have this be solved?

**Comment by AndiDomi** [comment]
I'm using Vue.js 2 and had the exact same problem.
The way I did it was to create an iframe pragmatically with `<component v-bind:is="get_iframe"></component>`
which resides inside a `<div v-if='create_iframe_true'><div>`.
If `create_iframe_true` is `true` the component gets created and you can access it (also a good solution to resize the video) if not then the iframe is destroyed and the video goes away.
Hope this helps

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.

**Comment by frederic-bonjour** [comment]
Hi!
Same problem here: I need to remove the scene/camera from the DOM after the marker has been detected.
I'm using Vue.
Thank you very much!

**Comment by SadmanYasar** [comment]
I am developing with Nextjs and AR.js and was facing this issue. But I took it a step further by generating html with dynamic image source and then setting it to an iframe src. And when it's not visible, a message is send to the script which gets the scene and camera then turns it off. Not sure if it's a good practice but I couldn't think any other solution. This is the code that is working using jsx with AR.js:

```tsx
import { useEffect, useState, useRef } from "react";
import { Show, useShow, Title, TextField, ImageField } from "@refinedev/antd";
import { Button, Modal } from "antd";

// Generate the HTML content for the iframe with a robust stop mechanism
const generateARHtml = (imageSrc: string) => `
<!doctype html>
<html>
<head>
  <script src="https://raw.githack.com/AR-js-org/studio-backend/master/src/modules/marker/tools/gesture-detector.js"></script>
  <script src="https://raw.githack.com/AR-js-org/studio-backend/master/src/modules/marker/tools/gesture-handler.js"></script>
  <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
  <script src="https://raw.githack.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js"></script>
  <script src="https://raw.githack.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
  <script>
    // Listen for a message to stop the camera stream
    window.addEventListener('message', function(event) {
      if (event.data === 'stopCamera') {
        const scene = document.querySelector('a-scene');
        const video = document.querySelector('video');
        if (video && video.srcObject) {
          const stream = video.srcObject;
          stream.getTracks().forEach(track => track.stop());
          video.srcObject = null;
        }
        if (scene && scene.camera) {
          scene.camera.stop(); // Attempt to stop A-Frame/AR.js camera
        }
      }
    });
  </script>
</head>
<body style="margin: 0; overflow: hidden;">
  <a-scene vr-mode-ui="enabled: false;" loading-screen="enabled: false;"
    arjs="trackingMethod: best; sourceType: webcam; debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 3x3;"
    id="scene" embedded gesture-detector>
    <a-marker id="animated-marker" type="barcode" value="10">
      <a-image src="${imageSrc}" scale="10 10 10" class="clickable" rotation="-90 0 0" gesture-handler></a-image>
    </a-marker>
    <a-entity camera></a-entity>
  </a-scene>
</body>
</html>
`;

export default function ProductShow() {
  const { queryResult } = useShow({});
  const { data, isLoading } = queryResult;
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [iframeSrc, setIframeSrc] = useState("");
  const iframeRef = useRef(null);

  const record = data?.data;

  const handleOpenModal = () => {
    setIsModalVisible(true);
  };

  const handleCloseModal = () => {
    // Send the stop message to the iframe before closing
    if (iframeRef.current && iframeRef.current.contentWindow) {
      iframeRef.current.contentWindow.postMessage("stopCamera", "*");
    }
    // Delay closing the modal slightly to ensure the message is processed
    setTimeout(() => {
      setIsModalVisible(false);
      setIframeSrc(""); // Clear the iframe source
    }, 100); // 100ms delay
  };

  useEffect(() => {
    let url;
    if (isModalVisible) {
      const imageSrc = record?.image && JSON.parse(record?.image)?.[0]?.url;
      const html = generateARHtml(imageSrc);
      const blob = new Blob([html], { type: "text/html" });
      url = URL.createObjectURL(blob);
      setIframeSrc(url);
    }
    // Cleanup function to revoke the blob URL when the modal closes or component unmounts
    return () => {
      if (url) {
        URL.revokeObjectURL(url);
      }
    };
  }, [isModalVisible, record]);

  return (
    <>
      <Button onClick={handleOpenModal}>Preview</Button>
      <Show isLoading={isLoading}>
        <Title level={5}>{"ID"}</Title>
        <TextField value={record?.id} />
        <Title level={5}>{"Name"}</Title>
        <TextField value={record?.name} />
        <Title level={5}>{"Image"}</Title>
        <ImageField
          width={500}
          height={500}
          value={record?.image && JSON.parse(record?.image)?.[0]?.url}
        />
      </Show>
      <Modal
        title="AR View"
        open={isModalVisible}
        onCancel={handleCloseModal}
        footer={null}
        width="100%"
        style={{ top: 0 }}
        bodyStyle={{ height: "100vh", padding: 0 }}
      >
        {iframeSrc && (
          <iframe
            ref={iframeRef}
            src={iframeSrc}
            style={{ width: "100%", height: "100%", border: "none" }}
            title="AR View"
            allow="camera"
          />
        )}
      </Modal>
    </>
  );
}
```
