### ISSUE TITLE
What about CSS3D scene rendering in Three.js ar version?

### ISSUE THREAD

**Issue by polyzer** [jeromeetienne/AR.js#262]
Hello! It's possible to render Three.js CSS3D scenes in AR? And how we can render html dom elements in AR?

**Comment by ZoltanVeres** [comment]
@polyzer Have you tried using AR.js with A-Frame?

**Comment by polyzer** [comment]
No, only Three.js. There is way - using A-Frame? Could you, please, post a link on example?

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
