### ISSUE TITLE
iOS11 Safari Crashing Frequently

### ISSUE THREAD

**Issue by FuzzyWobble** [jeromeetienne/AR.js#264]
Not sure what is causing it yet... Will follow up with some details shortly. 
Does not crash on Android. 
The crash typically happens immediately during launch but also sometimes during use. 
Anyone else having this?

**Comment by ZoltanVeres** [comment]
@FuzzyWobble Please specify what browser and device you experiencing this. Can you reproduce the crash in one of our demo pages?

**Comment by ZoltanVeres** [comment]
No further info provided about the error.
