### ISSUE TITLE
baseUrl problems

### ISSUE THREAD

**Issue by paztis** [jeromeetienne/AR.js#268]
There's a lot of hardcoded url in the delivery (camera_para.dat, patt.hiro, ...) and all of them are based on baseURL.

First problem is baseurl reference is not the root of your project, but the three.js subfolder: 
ARjs.Context.baseURL = 'https://jeromeetienne.github.io/AR.js/three.js/'. It works when we let the default value (https://jeromeetienne.github.io/AR.js/three.js/) but it's hard to manage it locally on our own project.

Second problem isthat most of the parameters are pointing to examples folders:
`var learnerBaseURL = ARjs.Context.baseURL + 'examples/multi-markers/examples/learner.html'`
`file.subMarkersControls[0].parameters.patternUrl = absoluteBaseURL + 'examples/marker-training/examples/pattern-files/pattern-hiro.patt'`
...
These folders are now removed from distributions (lighweight distribution that remove all the examples).

Is it possible to centralize all the real resources that are used by the delivery (ar.js) on the /data folder and only these ones ?
Like this we can keep the real useful data in the distribution (camera, patterns, ...) and remove all the others (example videos, examples images, ...)

Globally, I think a real industrialisation process is needed here about build process, resources and deliveries.

**Comment by nicolocarpignoli** [comment]
This is a very good point. Do you have time for a PR for that? It would be awesome. Also I would like to hear @jeromeetienne opinion on that

**Comment by bigvanstudio** [comment]
no comment from Jerome?..

**Comment by nicolocarpignoli** [comment]
He probably have other priorities right now. Please take a look here:https://github.com/jeromeetienne/AR.js/issues/469
