### ISSUE TITLE
how to run multi-markers > learner.html?

### ISSUE THREAD

**Issue by Jzege** [jeromeetienne/AR.js#271]
If I simply open the file, it will say "no urlOption - should not happen'. 

Peering at the code, it seems like the demo requires some url options to tell it what patterns are present. May I know what is the syntax for that?

**Comment by Jzege** [comment]
That was based on using release 1.5.1, which I think is broken? At any rate, the source code seems different from https://jeromeetienne.github.io/AR.js/three.js/examples/multi-markers/examples/player.html and I think I can infer the syntax from that working copy.

**Comment by chrigu** [comment]
Took me some time to figure it out. Basically you add an URL encoded JSON object to the url.

```learner.html?%7B"backURL"%3A"http%3A%2F%2F127.0.0.1%3A8080%2Fplayer.html%23%257B%2522trackingBackend%2522%253A%2522aruco%2522%257D"%2C"trackingBackend"%3A"aruco"%2C"markersControlsParameters"%3A%5B%7B"type"%3A"barcode"%2C"barcodeValue"%3A1001%7D%2C%7B"type"%3A"barcode"%2C"barcodeValue"%3A1002%7D%2C%7B"type"%3A"barcode"%2C"barcodeValue"%3A1003%7D%2C%7B"type"%3A"barcode"%2C"barcodeValue"%3A1004%7D%2C%7B"type"%3A"barcode"%2C"barcodeValue"%3A1005%7D%2C%7B"type"%3A"barcode"%2C"barcodeValue"%3A1006%7D%5D%7D```

I found it out when I went to `player.html` first and pressed the stop button.

**Comment by Jzege** [comment]
Just want to reiterate that I think release 1.5.1's multi-marker example is broken, but I'm not skilled enough to figure out why. Guess I will play around with the simpler examples first and wait for the api to stabilize before diving in.

**Comment by mariovde** [comment]
Steps to get the learner working:
1) lay out the markers, on the floor for example, like this
A           B
     Hiro
C           F

2) host the file on a https server.
https://(yourip):8080/three.js/examples/multi-markers/examples/player.html#%7B%22trackingBackend%22%3A%22artoolkit%22%7D

3) open this url on your phone/tablet/laptop
4) click on the stop icon, this will initiate the learner.html
5) try to film all the markers, all at once. You should see the position controls and the number 0 2 3 etc. over the markers.
6) in the lower left corner, you'll see the green check markers when the position calculation is done for each marker. When you see "done" or all the green check markers, you are good to go.
7) hit the pause button and start filming the markers. You should see the hiro marker even when the hiro marker is not fully in view.

**Comment by edsilv** [comment]
I'm trying to use aruco markers and it's saying it can find 1001 - 1006, however the reference points don't seem to be getting added correctly.

https://www.youtube.com/watch?v=avuMzGDqnC0&feature=youtu.be

**Comment by edsilv** [comment]
It looks like it might be related to the camera rotation? https://www.youtube.com/watch?v=191Tq3fonGM&feature=youtu.be
