### ISSUE TITLE
Wrong orientation detection on DEXP XL 145 and Samsung Galaxy S5

### ISSUE THREAD

**Issue by polyzer** [jeromeetienne/AR.js#275]
Hello! I tested AR.js examples, and all of them have problems with orientation on this phones.
![screenshot_2017-12-07-02-34-50](https://user-images.githubusercontent.com/10620596/33687627-84173db8-dafa-11e7-9ebb-a17d938f9d52.png)
![screenshot_2017-12-07-02-35-36](https://user-images.githubusercontent.com/10620596/33687628-843b3dd0-dafa-11e7-987d-b8e5a69f228b.png)
On these screens Camera is in front of ArMarker, but Green arrow indicates to top of screen, but not to camera! How I can fix it? (on videos in YouTube it works fine)
May be we need to calibrate camera?

**Comment by AndreaMonzini** [comment]
https://github.com/jeromeetienne/AR.js/issues/242

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
