### ISSUE TITLE
multiple-indepandent-markers with THREE.js ?

### ISSUE THREAD

**Issue by Milewski** [jeromeetienne/AR.js#28]
is there any way of getting multiple-indepandent-markers with THREE.js?

**Comment by jeromeetienne** [comment]
yes, look at markerroot.html and create several markers

**Comment by Milewski** [comment]
i did and ended up with something like this

```
let root = new THREE.Group()
let markers = ['../../data/data/patt.hiro', '../../data/data/patt.kanji'].map(marker => {
    return new THREEx.ArMarkerControls(this.arToolkitContext, root, {
        type: 'pattern',
        patternUrl: marker,
        changeMatrixMode: 'cameraTransformMatrix'
    })
})
```

however how do i determine which obj is currently being scanned?

**Comment by jeromeetienne** [comment]
this is ```root``` in your example

**Comment by Milewski** [comment]
But in my example i end up with a group with 0 children

![image](https://cloud.githubusercontent.com/assets/2874967/24088711/a86a2988-0d68-11e7-98d1-e9dd7a57b1da.png)

shouldnt it contain each **ArMarkerControls.object3D** as a children? so then i could test:

```
root.children.forEach(child =>{
   child.visible??
})
```
