### ISSUE TITLE
Loading Animated FBX model

### ISSUE THREAD

**Issue by DenisG0** [jeromeetienne/AR.js#284]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
 I am attempting to load a animated model, one created in FBX one is a json-model. On the browser there are no errors in the settings, however the marker only triggers a colored block as oppose to the animated character. 
Current Code:
` 
  <a-scene embedded arjs rjs='trackingMethod: best;'>
      <a-marker-camera preset="custom" type='pattern' url='./customMarker/pattern-marker3.patt'>
       <a-entity
         id="Gunnar"
         geometry="primitive: box; width: 20; height: 0.01; depth: 20"
         scale="0.5 0.5 0.5"
         fbx-model="src: url(./Models/Gunnar-Happy2018.fbx);"
           >
       </a-entity>
     </a-marker-camera>
  </a-scene>
`
I am aware i would need to switch out the "fbx-model=" to "json-model=" when working with different model types. 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
  It is suppose to run a short holiday animation of around 10 seconds. Any help would be greatly appreciated!
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Running on MacOS Sierra 10.12.6 Chrome Browser.

**Comment by aj019** [comment]
@DenisG0  Were you able to animate the fbx model ? And how ?

**Comment by Esmolan** [comment]
Hi! Where you able to load the FBX model? Need help!!

**Comment by DenisG0** [comment]
Hey, not sure how much i can help.  It ended up working when i re-exported it as a json file while playing around with the settings on how i exported it. This is the current working code we had 
`       <a-entity
                animation-mixer="loop: repeat"
                shadow="cast: true"
                id="Gunnar"
                scale="0 0 0"
                position="0 0 0"
                json-model="src: url(assets/model/newyear/Gunnar2.json);">
        </a-entity>
`
This is wrapped in the <a-marker> tag.  I hope that helps alittle.

**Comment by Esmolan** [comment]
Hii!!

Thanks that helps. Were you able to animate it also and add a texture to
the 3d model. Thank you so much for responding.

Best,
Juan Molina

**Comment by DenisG0** [comment]
Hey Juan, 
Not a problem, i just wished i remembered more. Yes i was able to animate it on a loop and the texture was showing as well. If its playing and showing the texture for you in the software you're using(i used blender) then i would guess it has to be how you're exporting it. Good luck!

**Comment by DenisG0** [comment]
I would also make sure the json file is in the same folder as the avatar png or else it would show without the texture.

**Comment by jamess922** [comment]
Still get problem with loading a animated FBX file,and did you use FBXLoader.js and inflate.js ?

**Comment by janpio** [comment]
@jamess922 You should create a new issue and describe your problem properly, with code and all other information you can provide. Then we can try to help you.
