### ISSUE TITLE
a-marker-camera barcode doesn't work on master and dev branch

### ISSUE THREAD

**Issue by dburongarcia** [jeromeetienne/AR.js#286]
Hi, on master branch a-marker doesn't work with barcodes, although it's solved on dev branch. But on neither of them a-marker-camera works using barcode type.

This works:
`<a-marker-camera preset='hiro'></a-marker-camera> `

But this doesn't:
`<a-marker-camera type='barcode' value='5'></a-marker-camera>`

Maybe I'm doing something wrong, but using barcodes with a-marker works well on dev, even with multiple on sight. Not sure if multi-marker works.

**Comment by morandd** [comment]
possibly this is related to issue #192, that 192 is a partial fix or actually broke a-marker-camera

**Comment by mnutsch** [comment]
The AFrame barcode functionality was broken in some later release. An easy way to get using it is to download the version of AR.js (incl. the Aframe library) found here: https://github.com/jeromeetienne/AR.js/archive/e9aea5deb0ee010ece3e2ab07d84b587c374b66b.zip
