### ISSUE TITLE
How can I replace the 3D model in the example with a custom 3D model

### ISSUE THREAD

**Issue by liuqz2016** [jeromeetienne/AR.js#288]
hi!
I want to display a custom 3D model after the marker is identified. Is there any example?
thanks！

**Comment by lolcol11** [comment]
They say there is but the truth is they don't even know it.
I've followed every damn tutorial on the internet and used this code:

`<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/examples/vendor/aframe/build/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs='trackingMethod: best;'>
      <a-anchor hit-testing-enabled='true'>
      <a-gltf-model src="https://lolcol11.github.io/roadrunner.gltf" scale="0.10 0.10 0.10"></a-gltf-model>
           
      </a-anchor>
        <a-camera-static/>
    </a-scene>
</body>`

and still got nothing. It quite hard and nearly to impossible to achieve that, at least not the way they explain it to you, which really sucks

**Comment by prashant-andani** [comment]
https://github.com/prashant-andani/AR-Alphabets-words
Here i have implemented with the custom models
This should help!

**Comment by nicolocarpignoli** [comment]
closed as @prashant-andani showed how to do that.

also, you can check this articles:

https://medium.com/chialab-open-source/ar-js-the-simpliest-way-to-get-cross-browser-ar-on-the-web-8f670dd45462
https://medium.com/@akashkuttappa/using-3d-models-with-ar-js-and-a-frame-84d462efe498
