### ISSUE TITLE
markerless ar.js is not working without marker. Only when marker is show model is loaded. Can you help ?

### ISSUE THREAD

**Issue by rhonip** [jeromeetienne/AR.js#292]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment]
closed as not contains any detail about issue. please fill all informations required on the template
