### ISSUE TITLE
querySelector / appendChild ... not working inside .ajax success function

### ISSUE THREAD

**Issue by niallmca** [jeromeetienne/AR.js#298]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by niallmca** [comment]
Hi,
I can successfully appendChild with Javascript:
    
   var scene2 = document.querySelector('a-entity');
    var myimg = document.createElement('a-image');
    myimg.setAttribute('src', 'computer.png');
    myimg.setAttribute('height', '.5');
    myimg.setAttribute('width', '.5');
    myimg.setAttribute('position', '-0.6 -1.0 -1');
    scene2.appendChild(myimg);

But, if I try to do this after loading data with .ajax, then it doesn't work.  

$.ajax({
                type: "GET",
                url: "https://localhost:8443...",
                cache: false,
                success: function (devdata) {
                    macdata = devdata;
                     var scene2 = document.querySelector('a-entity');
                     var myimg = document.createElement('a-image');
                     myimg.setAttribute('src', 'computer.png');
                     myimg.setAttribute('height', '.5');
                     myimg.setAttribute('width', '.5');
                     myimg.setAttribute('position', '-0.6 -1.0 -1');
                     scene2.appendChild(myimg);   
                }
            });
}

If I look in 'developer tools', I can see that everything seems to work.  
But in the .ajax code, the object doesn't appear on screen.
(it appears on screen in the other example, above)

Thanks.
Best regards,
Niall.

**Comment by jeromeetienne** [comment]
this is related to aframe, not to ar.js. you are more likely to get an answer from aframe. thanks
