### ISSUE TITLE
Rename to WebARToolKit?

### ISSUE THREAD

**Issue by mrdoob** [jeromeetienne/AR.js#3]
There are currently many people working hard on designing WebVR. A good proof of this is this video from a workshop organised by the W3C some months ago:

https://www.youtube.com/watch?v=3vWf_jxoirI

 * This library is not AR, this library is [ARToolKit](https://en.wikipedia.org/wiki/ARToolKit) which is now a thing of the past (1999).
 * It's likely that WebAR is going to be a thing in the future, so right now you're creating "noise" for the future, when people search about the real WebAR and ending here.
 * By using "WebAR" one may think that you're trying to steal the well earned buzz that WebVR is achieving.

Please, be mindful and respectful of others when naming your libraries.

**Comment by mrdoob** [comment]
Also, you should check out this talk from Hirokazu Kato (inventor of ARToolKit). Hatsune Miku on a tracker is not what he wanted ARToolKit to be about.

https://www.youtube.com/watch?v=b33eqcVz7X8&t=57

**Comment by jeromeetienne** [comment]
You said quite harsh words. here and on twitter. https://twitter.com/mrdoob/status/833768609423855616 

I wanted to clarify. Here nobody tries to be disrespectful. i never pretended to be w3c. i dont plan to either. i am even collaborating with various actors to make it happen (at spec level to implementors in mozilla and google).

Last week the name of this repo changed 3 times. and i coded 36h saturday/sunday to gain another 40% on the library. For me the latter is more important. This is how much i cared about the repo name before releasing and be sure i didnt forsee such a backlash just on this :)

**Comment by mrdoob** [comment]
I don't think working 36h over the weekend entitles you of the WebAR name. Regardless of that, as I said, this has nothing to do with what AR is in 2017 (or will be in 2018). This is AR in 1999.

**Comment by jeromeetienne** [comment]
# What is WebAR as i see it.
 
To me, this repository is about making WebAR a reality. Here i talk about WebAR the concept. Not the implementation. This repository is only one implementation of this concept.

This project is about making it possible and easy for people to do Augmented reality on the web. I did this implementation to enable those people. So now everybody with a phone with webgl/webrtc can do AR. They can do so with opensource, using WebVR standard API, and all that crossplateform without installation. 

THIS and only THIS is my goal with this project.

**Comment by jeromeetienne** [comment]
i am renaming for project.

i just understood the misleading part. It make it impossible to distinguish WebAR, the concept and later the standard, and this project which is just an  implementation of what i believe to be AR.

Btw next time, It would have been nicer by just a "i think the name of the repo is confusing, maybe you should change it?" instead of bunch of unfounded accusations.

**Comment by mrdoob** [comment]
> Btw next time, It would have been nicer by just a "i think the name of the repo is confusing, maybe you should change it?" instead of bunch of unfounded accusations.

I'll try. As a human, sometimes I have emotions that I can't contain.

**Comment by bit2shift** [comment]
@jeromeetienne bullies are everywhere, lurking, in search for their next victim.
@mrdoob don't you have CancerScript repos to maintain?
<details>
<img src="https://cloud.githubusercontent.com/assets/6282023/23144993/4374e8e8-f7c3-11e6-82d1-990f3dfa05b2.png"/>
</details>

**Comment by jeromeetienne** [comment]
"AR.js - Efficient Augmented Reality for the web using ARToolKit"

im considering this. Any strong feeling against this one ?

**Comment by jeromeetienne** [comment]
glad this got resolved.
