### ISSUE TITLE
Wanted to play a video when marker is visible, and hide only when video has ended.

### ISSUE THREAD

**Issue by cmmiller80** [jeromeetienne/AR.js#302]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

I could not find a way to keep a video visible that was only shown/played when a marker was seen by the camera.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Keep video shown when marker is lost.

I modified the code in aframe-ar.js as follows:

I set window.videoEnded = false on video 'playing', and window.videoEnded = true when video 'ended'.

This assumes you are using `<a-video>` primitive in your `<a-marker>`
(line 8144) . replace w/ the following block:

search for: honor visibility

`if (_this._arAnchor.parameters.changeMatrixMode === 'modelViewMatrix') {

  var arVideoEl = document.querySelector('a-video');
  if (_this.el.contains(arVideoEl)) {
    // if video is playing, keep visible
    if (!_this.el.object3D.visible && !window.videoEnded) {
      _this.el.object3D.visible = this._arAnchor.object3d.visible;
    } else if (_this.el.object3D.visible && window.videoEnded == true) {
      _this.el.object3D.visible = false;
      window.videoEnded = null;
    }
  } else {
    _this.el.object3D.visible = this._arAnchor.object3d.visible;
  }

  if (_this.el.object3D.visible && !_this.markerFound) {
    this.el.emit('marker-found');
    _this.markerFound = true;
  } else if (!_this.el.object3D.visible && _this.markerFound) {
    this.el.emit('marker-lost');
    _this.markerFound = false;
  }
} else if (_this._arAnchor.parameters.changeMatrixMode === 'cameraTransformMatrix') {
  _this.el.sceneEl.object3D.visible = this._arAnchor.object3d.visible
} else console.assert(false)
`

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by MrRaam** [comment]
@cmmiller80 Any update on this ?

**Comment by oninross** [comment]
@cmmiller80, I found the solution from this issue https://github.com/jeromeetienne/AR.js/issues/249#issuecomment-394087628.  Tweak it to your requirements.  I have managed to play a video when the marker is visible
