### ISSUE TITLE
How to play animation built into GLTF model

### ISSUE THREAD

**Issue by digitalmaniak** [jeromeetienne/AR.js#304]
I've downloaded this gltf model with built in animation: https://sketchfab.com/models/8d06874aac5246c59edb4adbe3606e0e#

link to this project:
https://3ckid.com/01/AR_Mech_Drone.html

I got the model showing up and working properly but i cannot seem to figure out how to call and play the animation.

Using these two libraries
https://aframe.io/releases/0.7.1/aframe.min.js
https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js

This is how I'm loading the gltf model and calling the animation

`<a-gltf-model src="https://3ckid.com/01/assets/mech_drone/scene.gltf" position="0 2 0.25" rotation="90 180 0" scale="0.01 0.01 0.01" animation-mixer="clip: Take 001; loop:once">
</a-gltf-model>`

Can anyone help me figure out how to make this guy animate. Any help would be much appreciated.

Thanks in Advanced,
Angel :)

**Comment by digitalmaniak** [comment]
I actually figured it out. 
It must've been playing the animation before I used the marker.
I realized you do not have to specify a clip name, and I changed loop to repeat.
Additionally I had to include aframe-extras-loaders.min.js

**Comment by hexaconnect** [comment]
what is your marker?

**Comment by digitalmaniak** [comment]
im using the Hiro marker

**Comment by Saad29** [comment]
hi @digitalmaniak  , can you share your code please? I am failing to load a model in my code

**Comment by Saad29** [comment]
Hi @digitalmaniak  , can you please share your code? I am having a tough time loading models

**Comment by digitalmaniak** [comment]
Hey @Saad29 
Here is preview link to the Demo (works using hiro marker):
https://3ckid.com/01/AR_Mech_Drone.html

Download link to that demo:
https://3ckid.com/01/MechDrone_Demo.zip

Also important to have a secure host "https" for this to run smoothly.

**Comment by Saad29** [comment]
thanks a lot @digitalmaniak

**Comment by vettorazi** [comment]
nice work!
question about the loop:
if you choose to not repeat, it will even play without the marker? or it just play when the marker are recognized?

**Comment by digitalmaniak** [comment]
@vettorazi Yes it WILL play even before it identifies the marker. 

I know that there was another thread that explains how to set up some sort of listener for the marker and then you can play animations or other things you may want to do once the marker is recognized.

Try this:
https://github.com/jeromeetienne/AR.js/issues/111

**Comment by vettorazi** [comment]
Oh thanks! This is helpfull!

Em qui, 12 de abr de 2018 17:14, Angel <notifications@github.com> escreveu:

**Comment by crmun** [comment]
Add this if you missed.

**<script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>**

**Comment by nicolocarpignoli** [comment]
closed as resolved

**Comment by willxvi** [comment]
Can you send the example again ? Link is broken.

**Comment by nicolocarpignoli** [comment]
What link in particular?

**Comment by willxvi** [comment]
These links: https://3ckid.com/01/AR_Mech_Drone.html

https://3ckid.com/01/MechDrone_Demo.zip

**Comment by nicolocarpignoli** [comment]
maybe something useful here before  @digitalmaniak  answers? https://github.com/digitalmaniak/webAR

**Comment by digitalmaniak** [comment]
> These links: https://3ckid.com/01/AR_Mech_Drone.html
> 
> https://3ckid.com/01/MechDrone_Demo.zip

Sorry for late response I had a hard time searching for these but heres what I found:
http://lgadftp.com/Preview/AR/AR_Mech_Drone.html
http://lgadftp.com/Preview/AR/AR_Mech_Drone1.5.html

Here is everything I worked on. Html files + model files:
ftp://lgadftp.com/Preview/AR/all_demos.zip  (310MB)

**Comment by droid001** [comment]
@digitalmaniak I'm gettting WebRTC errors on these links as they aren't served with https. Any chance you could setup SSL for your site?

**Comment by kalwalt** [comment]
@droid001 @digitalmaniak i can confirm this,  I'm gettting WebRTC errors too.

**Comment by CamiloB** [comment]
the errors is chrome they put something you need a https request to acces any hardware im mounting this on my server if this works ill put the response here thanks
