### ISSUE TITLE
why stop update?what happened?

### ISSUE THREAD

**Issue by linweiwei123** [jeromeetienne/AR.js#309]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment]
Recently this project has became more open to collaborators, as me :) So maybe from now on we hope to see more maintenance, and more features to come.
