### ISSUE TITLE
Question about React Native + iOS

### ISSUE THREAD

**Issue by armenr** [jeromeetienne/AR.js#31]
Hello! Thank you for this wonderful library. Would this work with React Native + iOS, by any chance?

**Comment by jeromeetienne** [comment]
unfortunatly it doesnt work in IOS browser at the moment. But apple is working on supporting WebRTC - [here](https://github.com/jeromeetienne/AR.js#try-it-on-mobile)

and i dunno react native

**Comment by blq** [comment]
I know there are couple of native camera access modules for iOS for React Native. Not sure whether they can expose the video stream to common js though.

**Comment by jeromeetienne** [comment]
btw some people are trying to use phonegap to run it on IOS. apparently it would be possible. i hope this helps, i dunno phonegap either :)

https://twitter.com/astraccia/status/846494423735263232

**Comment by armenr** [comment]
Thanks for the really, really helpful replies! You guys really went above and beyond :D ... unlike most StackOverflow threads. 

Appreciate it!

**Comment by armenr** [comment]
I've found the world's crappiest hack for making this work. 

It goes as follows: 

In a world where time didn't matter, I could implement this shit.

Code a react-native app--> then use the following:

1_ https://github.com/axemclion/react-native-cordova-plugin --> extends the ability to use Cordova plugins in React-Native.

2_ Pull in the following plugin: https://www.npmjs.com/package/cordova-plugin-iosrtc

This makes the following possible in React-Native on IOS --->

3_ https://github.com/jeromeetienne/AR.js

So in the most jerry-rigged, daisy-chained way, you could actually get this running in iOS...theoretically 😆

**Comment by jeromeetienne** [comment]
Who is game to try ?

**Comment by armenr** [comment]
I am actually going to attempt it! I'll see what I can report back :)

**Comment by evhan55** [comment]
:( I want to get this working for students in iOS but this hack seems too hard for them :( I cannot believe this iOS problem, so silly

**Comment by sorianog** [comment]
@armenr Status on that report? I'm excited to see what you found!

**Comment by samparsky** [comment]
@armenr How are you making use of this library with react native
