### ISSUE TITLE
video in pause

### ISSUE THREAD

**Issue by barrasylvain** [jeromeetienne/AR.js#310]
**Do you want to request a *feature* or report a *bug*?**
 I have a feature to request.

**What is the current behavior?**
i have implant a video and it woks fine but only with a desktop computer. Indeed, when I use a mobile, the video is paused. Is there something to add ?

<a-scene embedded arjs='sourceType: webcam;'>
	  <a-marker preset='hiro'>
	    <a-video id="inputVideo" autoplay="true" scale="3 3 3" src="test.webm" width="2" height="2" position="3 0 0"></a-video>
	  </a-marker>
	  <a-entity camera> </a-entity>
	</a-scene>
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by vincentfretin** [comment]
On mobile, autoplay video doesn't work on purpose, you need to play your video from a click listener. 
```
someElement.addEventListener('click', evt => document.querySelector('video').play());
```

**Comment by barrasylvain** [comment]
I am novice and i try to do but There is a lack of informations for me.
Can you explain with an exemple, please.
Thank you for all.

**Comment by vincentfretin** [comment]
Really it depends on your project, if you use aframe, you can look at the source of this example https://aframe.io/examples/showcase/videosphere/
but at the end, it's just to call `play()` on your video like I said.

**Comment by nicolocarpignoli** [comment]
solved
