### ISSUE TITLE
Keeping the object on the screen even when the camera is not focusing the marker

### ISSUE THREAD

**Issue by MrRaam** [jeromeetienne/AR.js#313]
Is there any way to retain the object after moving the camera away from the marker once scanned? so that the user need not focus his camera continuously?

**Comment by chznbaum** [comment]
Using the marker camera is more stable than the entity camera if the camera's going to be moving around.

For example, instead of this:

```html
<a-marker preset="hiro"></a-marker>
```

Try this:

```html
<a-marker-camera preset="hiro"></a-marker-camera>
```

And remove this:

```html
<a-entity camera></a-entity>
```

**Comment by MrRaam** [comment]
@chznbaum Thank you, I understand what you are saying. I also wanted to know, say if we remove the camera away from the marker ( not focusing the marker ) after the scan can the model still stay on the screen?

**Comment by chznbaum** [comment]
@MrRaam Yes, if you're using the marker camera. The model's position will adjust once the marker's back in view/focus.

**Comment by ht44** [comment]
@chznbaum Can you have multiple <a-marker-camera> in the same scene, so that you can have multiple independent markers that all use the camera transform matrix?

**Comment by lambda100** [comment]
Is it possible to move the model to the centre of the screen/camera when it lost focus on the marker?

**Comment by sjraziva** [comment]
> Using the marker camera is more stable than the entity camera if the camera's going to be moving around.
> 
> For example, instead of this:
> 
> ```
> <a-marker preset="hiro"></a-marker>
> ```
> 
> Try this:
> 
> ```
> <a-marker-camera preset="hiro"></a-marker-camera>
> ```
> 
> And remove this:
> 
> ```
> <a-entity camera></a-entity>
> ```
> 
> [Link to docs](https://github.com/jeromeetienne/AR.js/tree/master/aframe)
hello eveybody
I have a question, i want to keep object not onlyon screen but in the same position (old position of marker) sthing like vuforia option? i didnt find anysolotion until now ? does somebody know ? please say

**Comment by sjraziva** [comment]
hello everybody
I have a question, I want to keep object not only on screen but in the same position (old position of marker) thing like vuforia option? I didn't find any solution until now? does somebody know? please say

**Comment by meizano** [comment]
> 
> 
> Is it possible to move the model to the centre of the screen/camera when it lost focus on the marker?

Yes, it possible. Manipulate the model using DOM with markerFound and markerLost like this:
```
<script>
        // a-scene
        var scene = document.querySelector("a-scene");

        // a-marker
        var m = document.querySelector("a-marker");

        // Create object bola
        var bola = document.createElement('a-sphere');
        bola.setAttribute('color', 'yellow');
        bola.setAttribute('radius', 0.5);

        m.addEventListener("markerFound", (e) => {
            scene.removeChild(bola);
            m.appendChild(bola);
        });

        m.addEventListener("markerLost", (e) => {
            m.removeChild(bola);
            scene.appendChild(bola);
        });
    </script>
```
You can see the full script [here](https://github.com/meizano/AR/blob/master/aframe/AR-event-marker-lost-object-stay.html)

**Comment by meizano** [comment]
> 
> 
> hello everybody
> I have a question, I want to keep object not only on screen but in the same position (old position of marker) thing like vuforia option? I didn't find any solution until now? does somebody know? please say

Manage to do this accidentaly. Only works in Chromium based browser. Here it is:
```
<a-scene embedded vr-mode-ui="enabled: false" arjs='debugUIEnabled: false;'>

        <a-plane position="0 0 0" rotation="-90 0 0" width="1" height="1" color="blue"></a-plane>

        <a-marker-camera preset="hiro"></a-marker-camera>
    </a-scene>
```
It seems to be working when the entity was put outside a-marker by using a-marker-camera. You can see the code [here](https://github.com/meizano/AR/blob/master/aframe/AR-custom-marker.html)

**Comment by droid001** [comment]
Guess it would be a nice feature to be able to use the device's sensors (gyroscope,magnetometer,accelerometer) to continue the tracking when the marker is lost. If one has to [understand the transformation matrix](https://www.3dgep.com/understanding-the-view-matrix/) to get this working then maybe someone else will have to give this proposal a shot.

**Comment by rileypaik** [comment]
@meizano I copied your script I found [here](https://github.com/meizano/AR/blob/master/aframe/AR-event-marker-lost-object-stay.html) and I tried displaying it on a github web page [here,](https://rileypaik.github.io/A1/) but all I see is a blank screen. Do you know how I should fix this? Thanks!

**Comment by felipenmoura** [comment]
Yes, 👍 +1 on this feature!

When loosing the marker, it makes total sense to have an option to change its children to a global (gyroscope based) position. It's very useful when you have bigger objects or animations that might move away from the marker.

I do believe this would become a MUST, to add so many different effects, demos and tools!

I even looked a little into the code to see if it could be "easy" to implement some basic behavior like that, but had a hard time finding documentation on how to contribute to this (amazing) project!

**Comment by nicolocarpignoli** [comment]
we can continue here: https://github.com/AR-js-org/AR.js/issues/23

**Comment by ZetShock** [comment]
Has a-marker-camera been deprecated? I have been using a-marker tracking before without issues, but now using a-marker-camera and placing my entities at scene origin, the models skew on mobile devices as soon as gyroscope and accelerometer access is granted, while on desktop webcam they align properly to the marker.
The marker is being detected and tracked in position, but rotated at weird angles depending on device orientation. Not sure what is going on
