### ISSUE TITLE
Marker tracking isn't proper

### ISSUE THREAD

**Issue by siddhartpai** [jeromeetienne/AR.js#317]
**Do you want to request a *feature* or report a *bug*?**
A bug

When the phone is hovered over the marker , the model shows up but the position is very jittery , 
Also when the phone is moved around the marker , it doesn't show the object properly , rather rotates the object towards the camera. 
The behaviour is demonstrated in the below video . I've also added a link below where this demo can be checked out , with a HIRO marker . 
**What is the current behavior?**
https://imgur.com/a/zo7r5
**If the current behavior is a bug, please provide the steps to reproduce.**
https://unsuitable-bed.surge.sh

**What is the expected behavior?**
 The expected behaviour would be to show the different sides of the object as it . This has been done using  JSARToolkit ,THREE.JS and a demo can be checked out at https://cric-scapic.surge.sh.

Even though AR.JS runs with JSARToolkit backend, why is the stability so bad ? Is there some thing that I'm missing here  ? 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by jeromeetienne** [comment]
It was due to a bug when the phone is in portrait, it has been fixed now. can you please retry ?

**Comment by lewisoaten** [comment]
I can recreate this even on 1.6.0. I'm also having this issue with my own project.

**Comment by 544531645** [comment]
@jeromeetienne I also happent this (the model shows up but the position is very jittery )  , how do I can slove ?
