### ISSUE TITLE
How to add a virtual button?

### ISSUE THREAD

**Issue by vmazevedo** [jeromeetienne/AR.js#321]
**Do you want to request a *feature* or report a *bug*?** feature

**What is the current behavior?** none

**If the current behavior is a bug, please provide the steps to reproduce.** none

**What is the expected behavior?** none

**If this is a feature request, what is motivation or use case for changing the behavior?** i want to know if it is possible to add a virtual button. My idea is to create a Augmented reality comic book, with small animations on it, add this virtual button is to turn the page.

**Please mention other relevant information such as the browser version, Operating System and Device Name** Android

**Comment by spartalis** [comment]
I recommend that you print a personalized book and on each page you can use multi-bookmarks. So the person will have a book that to read will have to use the AR. I'm doing something like that.

**Comment by nicolocarpignoli** [comment]
you can show, on marker detection, a UI element encapsulated in a <a/> tag. Then you have to handle click events on it. I never actually played with click events on Aframe / Ar.js, you can check here https://github.com/jeromeetienne/AR.js/issues?utf8=✓&q=click+events for a starting point.
