### ISSUE TITLE
I want to handle clicks on objects on a-marker.

### ISSUE THREAD

**Issue by shigenobu-kondo** [jeromeetienne/AR.js#328]
Hi.

I have a question.

I want to execute something action when I tap the object displayed on the marker in AR.js. (For example, moving to an external website)
I implemented it as below and tried to handle click event of a-box, but event did not occur.
If you set an event handler on a-scene, not a-box, you can handle it, but click will be detected even if you click on a place other than a-box.
※ "console.log ('box click')" was not executed.

How can I handle handling that only a-box was clicked?

```html
<!doctype HTML>
<html>
  <head>
    <title>Hello. WebAR!</title>
    <script src="https://aframe.io/releases/0.8.2/aframe.js"></script>
    <script src="https://unpkg.com/aframe-animation-component@4.1.2/dist/aframe-animation-component.js"></script>
    <script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"> </script>
</head>

  <body style='margin : 0px; overflow: hidden;'>

    <a-scene embedded arjs="sourceType:webcam; maxDetectionRate:30; debugUiEnabled:false;">
        <a-marker preset="hiro">
            <a-entity 
                animation="property: rotation; dur: 3000; easing: linear; loop: true; from:0 0 0; to: 0 360 0;"
                >

                <a-box cursor-listener position="0 0.5 0" rotation="0 0 0" scale="0.5 0.5 0.5" color="blue"></a-sphere>
            </a-entity>
        </a-marker>


        <a-entity camera>
            <a-entity cursor="fuse: true; fuseTimeout: 500">
            </a-entity>            
        </a-entity>
    </a-scene>

    <script src="sample.js"></script>
  </body>
</html>
```

```javascript
AFRAME.registerComponent('cursor-listener', {
    init: function () {
      this.el.addEventListener('click', function (event) {
        console.log('box click');
      });
    }
  });
```

For the mounting method, I referred to the following site.
https://aframe.io/docs/0.8.0/components/cursor.html#intersection-data

Please mention other relevant information such as the browser version, Operating System and Device Name 
* Android
* Windows 10 & Chrome

Thank you.

**Comment by javismiles** [comment]
Ive been trying to solve that for months, nobody is able to do that yet, hopefully somebody fixes that soon!

**Comment by shigenobu-kondo** [comment]
To. javismiles 

Thank you for your early reply.
I understood that it is not compatible with the current version.
I also try various challenges. I will share a good idea.

**Comment by javismiles** [comment]
Great shigenobu-kondo  , yes please share any good idea because Ive been trying to do that for months

**Comment by MirkoAlo** [comment]
Hi guys!
There is any solution for this issues??

Thanks!

**Comment by ak-uow** [comment]
If anyone is interested, my solution has been to bind click events in JavaScript to my 3D entities and and a cursor attribute to the a-marker-camera: 
```<a-marker-camera preset='custom' type='pattern' url='/other/fave-pattern-marker.patt' cursor="rayOrigin: mouse" > </a-marker-camera>```

This has allowed me to pick up the correct events, with the targetEl value being that of the entity that was clicked and events not being fired when other entities are clicked. I really wanted a 'follow the nose' cursor implementation but this will suffice.

**Comment by nicolocarpignoli** [comment]
I collect what i learned about events on ar.js in this article. It contains a full working example for click events. Hope it helps! 

https://medium.com/chialab-open-source/how-to-handle-click-events-on-ar-js-58fcacb77c4

**Comment by debayanj** [comment]
as far i get at with ar js , i found that ar js may have some limitations but if we try to make it work through aframe js onclick events are working

this code is allowing me change the opacity of other element when another element is clicked.
thats i found that with triggering aframe js events it is working,
smoothly

<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script> <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script> <script> AFRAME.registerComponent('change-opacity', { schema: { opacity: {default: '0.5'} }, init: function(){ const anew = document.querySelector("#ch"); var data = this.data; this.el.addEventListener('click', function(){ anew.setAttribute('opacity', data.opacity); }) } }); </script>
	<a-marker preset='hiro'>

  
  <a-box
position="0 1 -5"
color="#6173F4"
rotation=""
opacity=" 0.2"
depth="0.1"
change-opacity="opacity: 1"
change-color="color: #f00"
material="src: url(https://i.imgur.com/wjobVTN.jpg)"

        <a-box
id="ch" position="0 0.5 -3"
color="#6173F4"
rotation=""
opacity=" 0.2"
depth="0.1"
change-opacity="opacity: 1"
change-color="color: #f00"

        <a-camera position="0 -0.5 0">
