### ISSUE TITLE
Different aspect rations on Desktop and Mobile.

### ISSUE THREAD

**Issue by polyzer** [jeromeetienne/AR.js#331]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Hello, guys! There is a problem with displaying Three.js Scene at the may be it's a bug.
[There is a Desktop view](https://i.stack.imgur.com/dCyqQ.png)
[There is Mobile view](https://i.stack.imgur.com/PHas1.jpg)

**If the current behavior is a bug, please provide the steps to reproduce.**
Open this [website](https://www.polyzer.org/portals/scenes/ar_fox_sitting/) and use this [marker](https://ibb.co/dj9a7S)

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by vettorazi** [comment]
seems normal here.
can you share your code?

**Comment by polyzer** [comment]
Did you open website and detect marker?

**Comment by vettorazi** [comment]
yeah

**Comment by polyzer** [comment]
Do they have similar aspect ration? Could you post your screens from desktop and mobile?

**Comment by andreyrd** [comment]
It seems like AR.js makes assumptions about aspect ratio which causes the 3D content to stretch at certain screen sizes. We fixed it by overriding `ARjs.Source.prototype.copyElementSizeTo` with:

```
ARjs.Source.prototype.copyElementSizeTo = function (otherElement){

	if (window.innerWidth > window.innerHeight) {
		//landscape
		otherElement.style.width = this.domElement.style.width;
		const height = parseInt(otherElement.style.width) * 3/4;
		otherElement.style.height = height + 'px';
		otherElement.style.marginLeft = 0;
		otherElement.style.marginTop = ((window.innerHeight- height)/2) + 'px';
	} else {
		//portrait
		otherElement.style.height = this.domElement.style.height;
		const width = parseInt(otherElement.style.height) * 4/3;
		otherElement.style.width = width + 'px';
		otherElement.style.marginLeft = ((window.innerWidth- width)/2) + 'px';
		otherElement.style.marginTop = 0;
	}
}
```

Credit to @Interrorbang for this patch :)
