### ISSUE TITLE
the application stopped working with no changes. what could be?

### ISSUE THREAD

**Issue by vettorazi** [jeromeetienne/AR.js#332]
Hey guys, i uploaded my a.r application in heroku, and after some hours i tried the application (that was working) and seems broked.
i tried in my local machine again, and still nothing.
i didn't change anything!

i am loading a-frame and ar.js locally. someone knows if have some .js been loading in jeromeetienne repo?
all files that i am using are in my github:
https://github.com/vettorazi/a-frame-ar

**Comment by vettorazi** [comment]
https://jeromeetienne.github.io/AR.js/data/images/HIRO.jpg
and  https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html
are offline.
idk if this has something related?

**Comment by spartalis** [comment]
I'm having the same problem. I'm using mozilla thimble and glitch and it just stopped working. I believe the files are offline or offline.

What can we do to make sure this does not happen? an alternative would be to store the ar.js in another repository?


ar.js can not stop it has grown and become of paramount importance for diverse people, as students, teachers, entrepreneurs we have to be strong and united to solve these problems and guarantee the future of AR.JS

**Comment by vettorazi** [comment]
OMG THANK YOU. I was going crazy here!  i am loading everything in my local machine. but it seems not help. i didn't figure out yet why it's happening.

**Comment by spartalis** [comment]
let's wait for the @jeromeetienne   maybe he's altering something. Even so, this is very strange. I have several experiments with AR.JS and they all stop.

**Comment by vettorazi** [comment]
yeah. i am still trying to figure out how to load all files to my local machine. but no sucess here.. maybe it's something with this:
`ARjs.Context.baseURL = 'https://jeromeetienne.github.io/AR.js/three.js/'` in aframe-ar.js
idk..

**Comment by vettorazi** [comment]
i searched all internet. the only example that still work is 
this from @polyzer:
https://www.polyzer.org/portals/scenes/ar_fox_sitting/
marker:
https://ibb.co/dj9a7S

**Comment by vettorazi** [comment]
Came back! But i am still wondering how to put all files locally.
I hope that @jeromeetienne see this issue.

**Comment by jeromeetienne** [comment]
This is not really to arjs. All is hosted on GitHub. I'm guessing they got some issues yesterday. Nothing too be wired about.

You can download the library and run it look locally to about this kind of issue in the future if needed
