### ISSUE TITLE
Model is not rendered after rotating the phone

### ISSUE THREAD

**Issue by germanviscuso** [jeromeetienne/AR.js#334]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When changing the phone rotation the model is not rendered. Sometimes it works fine for the 1st rotation but it never works for a 2nd rotation. See video: https://youtu.be/EMfvZMGPqrA

**If the current behavior is a bug, please provide the steps to reproduce.**
Load https://jeromeetienne.github.io/AR.js/three.js/examples/basic.html on a phone an point to a hiro marker. Rotate the phone 90 degrees a few times while still pointing at the marker

**What is the expected behavior?**
The model should be shown on the marker even after the phone rotation

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Latest Chrome on Samsung Galaxy S8

**Comment by nicolocarpignoli** [comment]
duplicate
