### ISSUE TITLE
Custom Marker not working

### ISSUE THREAD

**Issue by peterlunglum** [jeromeetienne/AR.js#336]
I am trying to add a custom marker into my site. I have the following code:

```
<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;';>
       <a-assets>
            <audio id="sound" src="audio.mp3" preload="auto"></audio>
        </a-assets>
	    <a-marker preset="custom" type="pattern" url="img/pattern-marker.patt">
        <!--<a-marker preset="hiro">-->

                <a-box position='0 0.5 0' material='color: black;' soundhandler> 
                </a-box>
        </a-marker>
        <a-entity sound="src: #sound" autoplay="false"></a-entity>
        <a-entity camera></a-entity>
</a-scene>
```

The marker doesn't work though. I followed the steps from Alexandra Etienne's medium post but that doesn't appear to be correct. Seems to need something else included in a script to register a custom marker. What else needs to be written to properly register a custom marker? Moreover is the above correct? I've seen both url vs patternURL and I'm unsure of what is proper usage here.

**Comment by nicolocarpignoli** [comment]
in this brief article I tried to collect all that I learned about custom marker, and how to make them working with the last release of AR.js (1.5.5)
https://medium.com/chialab-open-source/ar-js-the-simpliest-way-to-get-cross-browser-ar-on-the-web-8f670dd45462

Let me know if it helps

**Comment by nicolocarpignoli** [comment]
close as author's has not replied anymore and valid solutions were offered

**Comment by IgorDePaula** [comment]
Its not work for me too =/

**Comment by Mamboman** [comment]
I had a hard time getting my custom marker to work. I think my problem was, that I changed the "Pattern Ratio" and didn't set it in my marker like so:
```
<a-marker type="pattern" url="url/to/myMarker.patt" patternRatio="0.5">
    <a-box position='0 0.5 0' material='color: yellow;'></a-box>
</a-marker>
```
