### ISSUE TITLE
Rotate 3d object towards camera when camera moving around marker.

### ISSUE THREAD

**Issue by aj019** [jeromeetienne/AR.js#337]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**If this is a feature request, what is motivation or use case for changing the behavior?**
I want the 3d object to be always face the camera. One possible way is to rotate the 3d object along with the camera motion but how to get the position of the camera relative to the marker ?

**Comment by ericflyfly** [comment]
You can try ctrl-alt-i to use the visual inspector build by A-frame.

**Comment by aj019** [comment]
@ericflyfly I meant when the user is moving the camera around the marker to view the 3d model.

**Comment by vettorazi** [comment]
i don't know if this would be called a 'feature'...
although there's a component for this: https://github.com/matrix-org/aframe-look-at-component
