### ISSUE TITLE
How to make a gif work?

### ISSUE THREAD

**Issue by jhonyxf** [jeromeetienne/AR.js#339]
I got an image, but when I replace the image with a gif it does not work. Has it solved this problem yet?

**Comment by Angelo8828** [comment]
If you are using A-Frame, AFAIK, it won't work. You need to use this [package](https://github.com/mayognaise/aframe-gif-shader) to have GIFs running.

You can see [my sample project](https://github.com/Angelo8828/sample-arjs-implementation) on how to make a GIF work on your project.

**Comment by jhonyxf** [comment]
@Angelo8828 It worked, thank you very much for the help.

**Comment by jhonyxf** [comment]
@Angelo8828 I tried to use another marker, but it did not work. Do I have to implement something to work?

**Comment by vettorazi** [comment]
same probs here... did you find out @jhonyxf ?
