### ISSUE TITLE
marker support

### ISSUE THREAD

**Issue by todrobbins** [jeromeetienne/AR.js#34]
Which markers are currently supported by AR.js? I may have missed that documentation elsewhere, but would like to know what I can build for.

cheers!

**Comment by jeromeetienne** [comment]
it is able to support all artoolkit markers. you can find docs on the artoolkit.org site

https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training

**Comment by todrobbins** [comment]
Thank you!
