### ISSUE TITLE
AR.js on iPhone version 11.3.1

### ISSUE THREAD

**Issue by lolblat** [jeromeetienne/AR.js#343]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Hello all, when i'm trying to access a web application that run AR.js on my iPhone version 11.3.1 on Safari web browser, i get this following error: "Webcam Error name: message: WebRTC issue navigator.mediaDevices not present in your browser"
ScreenShot:
![photo from orr](https://user-images.githubusercontent.com/17991071/39744328-8b573cca-52ac-11e8-971b-66f2155feb51.jpg)

How can i fix it? :(

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to look at the application with iPhone version 11.3.1 and Safari web browser, URL: 
https://out4in.github.io/onlinear/EranShowUp/

**Please mention other relevant information such as the browser version, Operating System and Device Name**
iPhone version 11.3.1 and Safari web browser.

**Comment by nicolocarpignoli** [comment]
The error is pretty self-explained: AR.js app cannot detect `navigator.mediaDevices` on your browser, hence it cannot do anything.
I just looked on Safari Desktop 11.1 and Safari Technology Preview 11.2  for `navigator.mediaDevices` and it's available. I can't reproduce it on Safari Mobile 11.3, sorry.

**Comment by lolblat** [comment]
Ok, Thank you :)
I will send message to apple to see why it's not working.

**Comment by PierreFritsch** [comment]
Works fine for me with iOS 11.3.1.

Maybe check if Settings > Safari > Camera & Microphone Access is enabled.

**Comment by deadderek** [comment]
I have had this issue as well, and it had to do with very specific circumstances. 

Basically, Apple is very strict with WebRTC data: any and all calls to WebRTC need to be coming from a secure (i.e. loading with HTTP instead of HTTPS) document. You can check by connecting your iPhone to your Mac and checking with the dev tools in Safari if there is a insecure file being loaded. After I fixed that issue, AR.js loaded fine on my iPhone.

**Comment by nich008** [comment]
Exact same problem here with Safari on  iPhone 6s with iOS 11.4
Tested using demo at: https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html
Safari has Camera and Microphone Access.
Error:

Webcam Error
Name:
Message:WebRTC issue-!
navigator.mediaDevices not
present in your browser

**Comment by leeprobert** [comment]
I think this is an issue with old demo code. If you run the demos directly from Github they tend to work. It is when you pull the code from master and run it that the camera permissions aren't called.
