### ISSUE TITLE
nft_threejs.html run on android mobile browser ,the FPS is very very low

### ISSUE THREAD

**Issue by reyoung2017** [jeromeetienne/AR.js#345]
hi all
     as the title . did anyone have the same problem?
     nft_threejs.html is run OK on the PC browser(google),but on the mobile browser, the FPS is very very low.
      is there any suggestion?

      thanks !

**Comment by Lucreitus** [comment]
@javismiles 
here you go
https://github.com/dragonHu/ar_test_demo

**Comment by YannKlein** [comment]
@Lucreitus can you be more specific? What html contains your NFT example code?

**Comment by YannKlein** [comment]
@javismiles @Lucreitus the NFT working example seem to have disappeared so I recreated in the below repo:
https://github.com/YannKlein/NFT_test

**Comment by kalwalt** [comment]
@YannKlein i get a 404 page with that link, do you moved the repo in another location?

**Comment by YannKlein** [comment]
Hi @kalwalt somehow my repo became private (because of github policy change?). Anyway, you should be able to access it now!
And here is the running code, if I’m not mistaken: https://yannklein.github.io/NFT_test/nft_threejs.html

**Comment by kalwalt** [comment]
thank you @YannKlein i see it now! i think that it is related to the example in jsartooolkit5 https://github.com/artoolkit/jsartoolkit5/blob/nft/examples/nft_threejs.html
and also the artoolkitx repo (more updated):
https://github.com/artoolkitx/jsartoolkit5/blob/nft/examples/nft_threejs.html
unfortunately the nft branch in each of these repo don't receive any update.
I would like to improve it but it's no so easy...

**Comment by YannKlein** [comment]
@kalwalt same here! Let’s give it a try :)

**Comment by kalwalt** [comment]
@YannKlein i'm working on jsartoolkit5 -> artoolkitx because most updated, i created this [issue](https://github.com/artoolkitx/jsartoolkit5/issues/78).
If you are interested we can continue to discuss there, Also because is more related to jsartoolkit5 than AR.js

**Comment by jamess922** [comment]
The example is working ,but FPS is too slow any good news ?

**Comment by kalwalt** [comment]
@jamess922 any good news... i hadn't the time to look time deeper, Sorry!

**Comment by breezeLoganGithub** [comment]
I get the same problem, I use the iPhone X 64GB. But it still very very slow.
has any good news?

**Comment by kalwalt** [comment]
@breezeLoganGithub no any news, but maybe it will be an emscripten version of ArtoolkitX, it should integrate NFT see this issue https://github.com/artoolkitx/artoolkitx/issues/83

**Comment by nicolocarpignoli** [comment]
discussion about NFT is going on in another issue, referring to separate repository.
Please take a look at: https://github.com/jeromeetienne/AR.js/issues/544
