### ISSUE TITLE
Click events not returning properly on AR.JS objects

### ISSUE THREAD

**Issue by ChanceTheMaker** [jeromeetienne/AR.js#349]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When clicking on an entity (object) with a cursor, no id returns to the event listener, producing no behavior.
**If the current behavior is a bug, please provide the steps to reproduce.**
Click the link below, point camera to a Hiro marker and try LMB while gazing at the AR object (an orange).

https://lookit.io/webar/ARJS/AO/scenes/ar_test.html

**What is the expected behavior?**
The object should be detected  (return an event.target.id) and should scale up. 

*Note: The object does spin when the cursor is over the object (so events are working to some degree), using begin="mouseenter", but click does not.

**If this is a feature request, what is motivation or use case for changing the behavior?**
No.
**Please mention other relevant information such as the browser version, Operating System and Device Name**
OS: Win10
Device: Desktop
Browser: Chrome 66.0.3359.139

**Comment by nicolocarpignoli** [comment]
Although you mark it as bug, this is a feature that has to be implemented

see https://github.com/jeromeetienne/AR.js/issues/328
and https://github.com/jeromeetienne/AR.js/issues/335

**Comment by nicolocarpignoli** [comment]
try looking at : 

https://medium.com/chialab-open-source/how-to-handle-click-events-on-ar-js-58fcacb77c4

**Comment by ChanceTheMaker** [comment]
Did you just post that today?

Thanks!

**Comment by debayanj** [comment]
as far i get at with ar js , i found that ar js may have some limitations but if we try to make it work through aframe js onclick events are working 

this code is allowing me change the opacity of other element when another element is clicked.
thats i found that with triggering aframe js events it is working,
smoothly



<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script>
<script>
  AFRAME.registerComponent('change-opacity', {
    
    
    
  schema: {
    opacity: {default: '0.5'}
  },
  init: function(){
    const anew = document.querySelector("#ch");
    var data = this.data;
    this.el.addEventListener('click', function(){
      anew.setAttribute('opacity', data.opacity);
    })
  }                
});
</script>
<body style='margin : 0px; overflow: hidden;'>
	<a-scene embedded arjs='sourceType: webcam;'>

		<a-marker preset='hiro'>

      
      <a-box
   position="0 1 -5"
   color="#6173F4"
   rotation=""
   opacity=" 0.2"
   depth="0.1"
     change-opacity="opacity: 1"         
   change-color="color: #f00"
   material="src: url(https://i.imgur.com/wjobVTN.jpg)"
   >
        
        
</a-box>
      
            <a-box
   id="ch" position="0 0.5 -3"
   color="#6173F4"
   rotation=""
   opacity=" 0.2"
   depth="0.1"
     change-opacity="opacity: 1"         
   change-color="color: #f00"
 
   >
        
        
</a-box>
      
      
      
      
            <a-camera position="0 -0.5 0">
  <a-cursor scale="0.5 0.5" color="#fff"></a-cursor>
</a-camera>
      </a-marker>
	</a-scene>
</body>
