### ISSUE TITLE
[Beginner question] Is marker necessary?

### ISSUE THREAD

**Issue by geekplux** [jeromeetienne/AR.js#35]
Hi, I'd like to use AR.js to show something funny when the camera on a book which without any marker. But I don't know that is the marker necessary?

**Comment by sorianog** [comment]
@geekplux Would you be able to provide a screen shot of what you are seeing and what you are proposing?

**Comment by vishnu1991** [comment]
@geekplux may be you can but you have to code that book cover as the marker(which is difficult and complex maybe).As AR needs some physical space to show up.
In this project Jeromee has used a simple marker so that it becomes easy to understand.

**Comment by geekplux** [comment]
@sorianog @vishnu1991 thanks. I'll have a try and tell you result if it success. :)
