### ISSUE TITLE
IOS Crashing constantly, RE-open

### ISSUE THREAD

**Issue by Samsy** [jeromeetienne/AR.js#350]
I got it crashing 99% of time and it just reload automatically  on IOS devices, even when detecting no markers.

Just starting the thing. It crashes after few seconds, whereas on android phone it just run quite ok.
Iphone 5S / ios 11.0.3
Iphone SE / ios11.0.3

Has it something to do with the memory allocation ?

**Comment by Samsy** [comment]
It looks like, just opening a video stream on those devices using a local https url project, without AR.js crashes after a few seconds and trigger a reload.

**Comment by Samsy** [comment]
Maybe not a AR.js related issue then.

**Comment by nicolocarpignoli** [comment]
I do not think it's AR.js issue but as you suggested it's probably a memory related issue.

**Comment by Samsy** [comment]
Probably memory yes..
