### ISSUE TITLE
Hiro pattern color

### ISSUE THREAD

**Issue by matsyoman** [jeromeetienne/AR.js#351]
Hello,

 Is it possible to change te black border color to another color like red? 

Thanks in advance

**Comment by nicolocarpignoli** [comment]
As far as I know, .patt files are generated with a pattern that simplify the original symbols on the input image. It generates a file of ASCII characters like "255" and "0". I don't think markers are color-sensitive. You could [try uploading your pattern](https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html) with colorful background and try to use it.
