### ISSUE TITLE
is aframe ar still working?

### ISSUE THREAD

**Issue by guymcmusker** [jeromeetienne/AR.js#355]
I  know it is a weird question but I'm in a very weird situation:

I used aframe in one of my courses where I teach a few months ago and I was able to use Aframe AR.

Now, I'm trying to use it now for another course but it seems that the same codebase used before doesn't work anymore on my mac and on my phone.

I tried also to use the basic example on codepen (here: https://codepen.io/jeromeetienne/pen/mRqqzb but also other resources on the web) but still, it doesn't work.

Also this basic file doesn't work:

```
<!-- AR.js by @jerome_etienne - github: https://github.com/jeromeetienne/ar.js - info: https://medium.com/arjs/augmented-reality-in-10-lines-of-html-4e193ea9fdbf -->
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
	<a-scene embedded arjs='sourceType: webcam;'>
		<a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
		<a-marker-camera preset='hiro'></a-marker-camera>
	</a-scene>
</body>
```

```

So my ultimate question is: I'm pretty sure I'm doing something wrong but I don't understand what and how to fix. Could it depend on my browsers?

Thanks so much!

**Comment by nicolocarpignoli** [comment]
try with insert a-box inside a-marker instead of at the same level

```
<a-marker-camera preset='hiro'>
    <a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
</a-marker-camera>
```

**Comment by guidosegni** [comment]
I Did it but it doesn't work :-(
Here it is the full code:

<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
	<a-scene embedded arjs='sourceType: webcam;'>
		<a-marker-camera preset='hiro'>
			<a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
		</a-marker-camera>
	</a-scene>
</body>

I don't understand what am I doing wrong

**Comment by nicolocarpignoli** [comment]
For some unknown reason I'm having problems with `<a-marker-camera>` elements as well as you. Try with the following snippet to see if you can make it run anyway:

```
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
	<a-scene embedded arjs='sourceType: webcam;'>
             <a-marker preset='hiro'>
                     <a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
             </a-marker>
             <a-entity camera></a-entity>
	</a-scene>
</body>
 
```

**Comment by guidosegni** [comment]
Just did it but as you can see from this screenshot 
https://www.dropbox.com/s/q0wg6vu1ushenq2/Screenshot%202018-05-31%2016.07.11.png?dl=0

it doesn't work :-(

Does your example work on your side?

**Comment by nicolocarpignoli** [comment]
Try this example and if it works feel free to use it or copy from it: for me it's working.

barcode marker used: https://github.com/nicolocarpignoli/nicolocarpignoli.github.io/blob/master/ar-playground/06-barcode.png

html index https://github.com/nicolocarpignoli/nicolocarpignoli.github.io/blob/master/ar-playground/index.html

link to the AR webapp for test: https://nicolocarpignoli.github.io/ar-playground/

**Comment by guidosegni** [comment]
Thanks Nicolò,

your example works perfectly.
I saw your example doesn't use hiro marker and you used mono_and_matrix as detection mode.
Could be this the reason of the issue?

**Comment by nicolocarpignoli** [comment]
`mono_and_matrix as detection mode` is used for barcode markers. I don't think this matters. Can you please provide me your full .html?

**Comment by guidosegni** [comment]
Here it is

```
<!-- AR.js by @jerome_etienne - github: https://github.com/jeromeetienne/ar.js - info: https://medium.com/arjs/augmented-reality-in-10-lines-of-html-4e193ea9fdbf -->
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script>
<body style="margin : 0px; overflow: hidden;">
	<a-scene embedded arjs="sourceType: webcam;">
		<a-marker-camera preset="hiro">
			<a-box position='0 0.5 0' material="opacity: 0.5;"></a-box>
		</a-marker-camera>
	</a-scene>
</body>
```

**Comment by nicolocarpignoli** [comment]
@guidosegni solved?

**Comment by guidosegni** [comment]
Yes, 
sorry for not replying before.
I solved using your code.
But if I use the <a-marker-camera preset="hiro"> it doesn't work :-(

**Comment by nicolocarpignoli** [comment]
ok glad to help :)

**Comment by vin-ni** [comment]
I get this error:
![bildschirmfoto 2018-12-07 um 17 20 51](https://user-images.githubusercontent.com/9806572/49659379-7906a980-fa44-11e8-8e1a-a91b773520d0.png)
Any idea what this could be?

**Comment by vin-ni** [comment]
Found the solution. Needed to remove 'hidden' from `  <a-scene embedded arjs='trackingMethod: best; sourceType: webcam; debugUIEnabled: false; hidden>`
