### ISSUE TITLE
Maintenance: AR.js, we have a problem

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#356]
Hi everyone, this 'issue' is not intended to be polemic at all but I'm hoping someone will see this and give an answer (like @jeromeetienne  :)).

@jeromeetienne did an insane job on giving us this technology for free, and its potential is still growing. I'm playing with AR.js in the last weeks and I saw that it has a problem with maintenance.
There is an obsolete Readme with broken links, and with a great number of no longer working examples. I also see 142 open issues and 29 pull request, half of them are so trivial to close and merge, and others are 'de-facto' closed still waiting for a close.

So what I'm hoping is to have a little more maintenance over the project, maybe including more people on Issues and Pull requests managing.
I can offer myself for a little help of course: I know this is work for free and I'm offering for this, also hoping someone wants to help too.

I write this for the good of this marvellous project and for thousand of users trying to figure out how to start with it.

Thanks

**Comment by stemkoski** [comment]
I have recently started to create a collection of simple examples, built to learn from, based on @jeromeetienne's work.
Check out https://github.com/stemkoski/AR-Examples for source code and https://stemkoski.github.io/AR-Examples/ to view them.

**Comment by nicolocarpignoli** [comment]
@stemkoski Thanks! It doesn't fully answer my question, as I'm proposing more support, but this also helps. It will be interesting to use your working examples in AR.js repo :)

Apart from that, do you have a 'AR Portal' working demo as the one jeromeetienne has showed on Twitter updates? https://twitter.com/jerome_etienne/status/893217730517749760

**Comment by stemkoski** [comment]
@nicolocarpignoli I agree, more general support is always welcome. An AR portal is high on my list of priorities for this week. (My eventual plan is to recreate most of the AR.js demos.) I'll let you know as soon as it's up and running.

**Comment by jj-wd** [comment]
Thanks Nicolo for opening this - I fully agree with you. And even if I can't offer help (yet) as I'm just digging into the world of (Web-)AR now, I wanted to respond to this as well, primarily to tell anyone reading this that I find this project still the most promising over all the attempts I've tested during my research the last weeks, so I hope it continues.

__________

Slightly offtopic:
My 5 cents on why AR.js needs more attention (remember I just started so this might be wrong altogether):
- WebXR is simply not ready yet. The attempts they did with OpenCV for markers look a bit fiddly. But right now it's hard to foresee what will be working in which browser in one year anyway. Some stuff looks promising like the surface detection and i.e. keeping the position of objcts even if the marker disappears.
- Argon.js has an awesome image recognition (by Vuforia $ though) without those bulky markers but only works with their own browser.
- All the other attempts that I'm not mentioning now just don't get to the performance and compatibility of AR.js afaik.

But some of the things that worked in earlier versions seem to be broken meanwhile (I stumbled upon border thickness of the markers not working for example) which might get pretty demotivating if you try using AR.js for the first time. Along with the list of issues we have here...

I can already fill a book with what's not working easily on all the libraries after a few weeks! AR.js at least works pretty much out of the box as long as you don't ty anything fancy.

**Comment by nicolocarpignoli** [comment]
@jj-wd totally agree.
The fact is that, although AR.js is marker-based, at the moment there are still plenty of use cases very suitable for this technology. AR.js is CROSS-BROSWER and it is so easy to build simple but very useful AR web apps.

WebXR is not ready. ARcore and ARkit are not ready, they are promising but they are still working only on some browsers (also, not standard ones). Other Cross-Browser AR projects like ViroReact are 'web-based' but not in a native way, as they still need to build code as app in order to be launched on mobile.

I'm a little bit frustrated because this project is the most promising at the moment and it's not maintained, and what it needs is just to open contribution and managing to more people.

**Comment by javismiles** [comment]
Nicolo and friends, I fully agree with your comments, Im a big fan of this project and I've done a few things with it already, I think the potential of cross-platform AR is massive, I also wanna help keep this project alive

**Comment by stemkoski** [comment]
@nicolocarpignoli - a working AR portal demo is now available at https://stemkoski.github.io/AR-Examples/. The only feature that I didn't add was teleporting to the other side of the portal. It should be possible by switching which layers are rendered depending on the sign of the coordinates of the portal. If there is interest, I can have a go at the code.

**Comment by erikparr** [comment]
Hi - An interesting conversation going on here. I would like to ask you all a question regarding ar.js functionality moving forward. According to [this thread](https://github.com/google-ar/three.ar.js/issues/105) “AR.js uses getUserMedia to find a marker and updates per frame the relevant transform of the marker" and getUserMedia [is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia). Does AR.js require getUserMedia to work? Looking at those nice examples from @stemkoski I am guessing there is another way forward ? Any thoughts on the subject would be appreciated.

**Comment by nicolocarpignoli** [comment]
For those who wants to help with maintenance of this project, there is an interesting discussion going on here https://github.com/jeromeetienne/AR.js/issues/374

**Comment by jeromeetienne** [comment]
@stemkoski works was/is amazing in three J's examples, and it is on arjs examples, we should add that in the readme.md. 

Anybody send a PR for it

**Comment by nicolocarpignoli** [comment]
@javismiles and others who wanted to help, we have created a slack channel for collaborators. there we can chat and see how each of us can help and what contribute we can give :)

see @https://github.com/jeromeetienne/AR.js/issues/376

if you wanted to help, please write to me or @jeromeetienne your email privately and we will add you to slack channel

**Comment by ZoltanVeres** [comment]
I was thinking a lot weather or not i should reply to this thread, but i will do, going with the naive thinking that maybe somebody will learn about my experience and others won't do the same mistakes as i did.
Let me be clear that i admire what @jeromeetienne did with this repo, this is fantastic work, and about a half year ago i offered help to Jerome. I tried to reply all to issues on https://gitter.im/AR-js/Lobby trying to research questions even on stackoverflow, i even tried to add changes to the ReadMe file.
With my 8 total commits i'm the second highest contributor to this repo (not mentioned for bragging, just to demonstrate that there's still a lot of low hanging fruits).
After 2-3 months I gave up, because it felt AR.js is extremely complicated, and nobody is here to help.
Eventually what i concluded that AR.js is extremely complicated for newcomers, so there has to be a documentation which explains the inner workings of AR.js, without that we would be ALWAYS relying on Jerome's expertise. I would focus on that first, because that would help experienced devs speed up and  decide if a pull request is ok for mergeing in or not. AR.js has plenty of low level tutorials already.
I also think that we need somedoby who leads the community untill other devs can learn and understand AR,js.
That's just my 2 cents, good luck @nicolocarpignoli @stemkoski  @javismiles and @jeromeetienne and others !

**Comment by nicolocarpignoli** [comment]
Thanks everyone. I close this issue as "duplicate" of https://github.com/jeromeetienne/AR.js/issues/374 and in that there's more conversation going on with project's author too. We will use that as entry point for AR.js maintenance discussions.
