### ISSUE TITLE
What does the FPS here mean? Camera data FPS , rendering FPS or algorithm FPS ?

### ISSUE THREAD

**Issue by lz199144** [jeromeetienne/AR.js#357]
I have problem with android camera data capturing, using native android API,  the max fps I can get is 30 fps, even on  Sansung S8.
How it is possible to run this application on android mobile browser with 60 FPS? Can WebRTC get camera data 60 FPS?

**Comment by stemkoski** [comment]
If you are referring to the stats widget displayed in the upper-left corner, then I believe it is rendering FPS.

**Comment by lz199144** [comment]
close
