### ISSUE TITLE
is artoolkit.api.js redundant?

### ISSUE THREAD

**Issue by jonathanzhang99** [jeromeetienne/AR.js#36]
The compressed `artoolkit.min.js` contains all of the code in `artoolkit.api.js`. There doesn't seem to be a need to include the latter in the Makefile. The [jsartoolkit5 repository](https://github.com/artoolkit/jsartoolkit5) says that the `artoolkit.min.js` contains the JS API already.

It seems like all code runs fine without the API file and you can reduce your JS by 1500 or so lines of code. I may be missing something - was there a reason that `artoolkit.api.js` is included?

**Comment by jeromeetienne** [comment]
thanks for spotting this.

Yeah one reason is that the artoolkit.api.js is a modification of mine

**Comment by nicolocarpignoli** [comment]
this is interesting. can anyone make a PR for that?

**Comment by janpio** [comment]
> Yeah one reason is that the artoolkit.api.js is a modification of mine

Not really possible to create a PR if the `artoolkit.api.js` that is included here is modified, right?

**Comment by nicolocarpignoli** [comment]
right, close this for now

**Comment by janpio** [comment]
This also applies to https://github.com/jeromeetienne/AR.js/pull/461 then (although this has additional changes)
