### ISSUE TITLE
How can I close the camera?

### ISSUE THREAD

**Issue by frozenfung** [jeromeetienne/AR.js#360]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I think this is somehow related with #255 

I am using AR.js with a single page application. That's say I have two components, component A with AR.js and component B without AR.js. When I go through from component A to component B by state change, the camera and related html tags create automatically by AR.js will still there which is reasonable because this is not under control of my framework (React).
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Can access stream object somewhere.
**If this is a feature request, what is motivation or use case for changing the behavior?**
However, maybe it could be better if I can access stream object return by `navigator.mediaDevices.getUserMedia().then` at some scope. In that way I can have a better control in camera with React's lifecycle. 
**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment]
Can someone make a PR for this? It can be very useful for a great range of applications, e.g. using already opened camera stream to take pictures and so on.

**Comment by gafk** [comment]
Have the same problem where I need to access AR.js stream object. In my app I have a [vue-qrcode-reader](https://github.com/gruhn/vue-qrcode-reader) and AR.js. They're both creating stream objects. And now I'm struggling trying to make them use one.

**Comment by nicolocarpignoli** [comment]
Hi everybody, this is solved.

from version 1.7.5 (https://github.com/jeromeetienne/AR.js/blob/master/CHANGELOG.md) there is an event fired when the camera has been initialized. Its payload contains the camera stream. You can listen to `camera-init` event that is fired from the `window` component.

more details: https://github.com/jeromeetienne/AR.js/pull/549
