### ISSUE TITLE
Documentation: typos and broken links

### ISSUE THREAD

**Issue by omarojo** [jeromeetienne/AR.js#362]
Half of the Examples send to a 404 Not found page.

**Comment by nicolocarpignoli** [comment]
I close all other "documentation-like" issues regarding readme/dead links/typos. We will use this one as reminder of this problems.

**Comment by tetreault** [comment]
this amongst issues of some of the samples not working when tried out on the user ends were one of the big issues with the ARjs. Its such a cool library but docs definitely need work for wider adoption. Looking forward to seeing how this lib grows in the future!

**Comment by tetreault** [comment]
Also there's 19 PR's and some of them go back a full year, some of the issues would probably be resolved if those get merged

**Comment by nicolocarpignoli** [comment]
fixed readme on master (also on dev) branch
