### ISSUE TITLE
GET https://jeromeetienne.github.io/AR.js/data/data/camera_para.dat 0 ()

### ISSUE THREAD

**Issue by whilemouse** [jeromeetienne/AR.js#363]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I tried to 'Augmented Reality in 10 Lines of HTML'. But this is not working.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. npm ar.js to my local or see a codepen
https://github.com/jeromeetienne/AR.js#augmented-reality-for-the-web-in-less-than-10-lines-of-html
2. run(local, codepen)
3. Don't show 3d model on marker and show error message
![a](https://user-images.githubusercontent.com/16111790/41218986-ec600ee2-6d97-11e8-87bc-88bce5c98c17.png)
4. But it's working.
https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html

**What is the expected behavior?**
Show 3d model on marker

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
mac os 10.13.4
chrome 67.0.3396.79

**Comment by Danh-134** [comment]
Try to define in <head> 
    <script>
        THREEx.ArToolkitContext.baseURL = 'https://rawgit.com/jeromeetienne/ar.js/master/three.js/'
    </script>

I think it's a problem with your error in GET camera-para.dat ;)

**Comment by whilemouse** [comment]
It's working fine. You are best. Thanks @Danh-134

**Comment by firezxv** [comment]
> Try to define in 
> <script>
> THREEx.ArToolkitContext.baseURL = 'https://rawgit.com/jeromeetienne/ar.js/master/three.js/'
> </script>
> 
> I think it's a problem with your error in GET camera-para.dat ;)

Also you can do it offline by copying the node_modules folder to wwwroot (im using asp.net core)
and adding:

<script src="~/js/aframe.min.js"></script>
<script src="~/js/aframe-ar.js"></script>

<script>
    THREEx.ArToolkitContext.baseURL = '/node_modules/ar.js/three.js/'
</script>
