### ISSUE TITLE
Angular AR.js

### ISSUE THREAD

**Issue by Danh-134** [jeromeetienne/AR.js#364]
I tried to implements AR.js in angular project but i have a lot of problems with npm version. 

I managed to use camera in angular project but i can't to load tag markers because I have a detachedcallback error in aframe-ar.js

![captureerrordetachedcallback](https://user-images.githubusercontent.com/38311535/41223783-0e02b3ec-6d6b-11e8-82d8-120f7fc66fc1.PNG)

Everything works but this part of code it's essential in order to use tag <a-marker> or <a-marker-camera>
All AFRAME.registerPrimitive are in errors, i tried everything like:
 import 'aframe' before zone.js;
I use section script in angular.json for using aframe-ar.js and aframe-master.js.

If anyone has a solution to my problem :) 
Thank you for your attention

**Comment by jeromeetienne** [comment]
this doesnt seems to be a ar.js issue
