### ISSUE TITLE
Camera access denied error on Android 

### ISSUE THREAD

**Issue by DaniAframe** [jeromeetienne/AR.js#365]
Hey, i'm trying to see if my code works by using my android mobile, it works when i use the computer's camera. When I try to open the html file on my mobile this error appears:

![image](https://user-images.githubusercontent.com/39561960/41404457-2ab81b48-6fbf-11e8-8e09-1f0f9c73ee6d.png)

Does anyone knows why is this happening and how to solve it?
Thanks!

**Comment by nicolocarpignoli** [comment]
Try to close your browser and launch again the app. It happens sometimes when you do not give permission to camera to the website, and the browser stores your choice.

**Comment by kencessna** [comment]
Hi DaniAframe,

I figured out that it works on Android and Iphone when you launch your script from a https:// page.

**Comment by nicolocarpignoli** [comment]
@kencessna hits the point. solved
