### ISSUE TITLE
Video Issue

### ISSUE THREAD

**Issue by Siva-SteamRollEast** [jeromeetienne/AR.js#368]
I tried to play a video when marker is detected but in aframe the video started to play when the page loads. Due to this, when marker is detected the video is not playing from beginning. And also the auto play is not working in IOS safari (mobile). I also want to hide and stop the video when marker goes out of the screen.
Is there any working event listener when the marker is detected?
@jeromeetienne  @ZoltanVeres  @lloydwatkin  @gabrielgrant  @pra85

**Comment by SyedKabeer** [comment]
I am facing the same issue. Any update on this issue.?

**Comment by Siva-SteamRollEast** [comment]
<script>
        var place;
        AFRAME.registerComponent('markerhandler', {
            tick: function () {
                var entity1 = document.querySelector('#pattern1');
                var Video1 = document.getElementById('Video1');
                if(entity1.object3D.visible)
                {
                    Video1.play();
                }
                else
                {
                    Video1.pause();
                }
            }
        });
    </script>


This works me @SyedKabeer
