### ISSUE TITLE
Camera loading on full zoom

### ISSUE THREAD

**Issue by curtisboylan** [jeromeetienne/AR.js#369]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If I load the webpage on Android 7.0 on Huawei P8 Lite it zooms very far in meaning I cannot use the application correctly. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Just loading the page on the phone does it it, you don't need to do anything special. The camera will load with a full zoom.

**What is the expected behavior?**
I would expect that it does not zoom and works properly like on every other phone/device but unfortunately on this phone with Android 7.0 the camera is zooming in fully.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
android version 7.0 huawei p8 lite

**Comment by gabrielgrant** [comment]
@curtisboylan is it the real-world camera that is zoomed in, the 3D scene, or both? is this specific to AR.js, or does the same thing happen when viewing other web pages that use the camera on this device? It would be helpful if you could include screenshots to help diagnose

Thanks!

**Comment by manishbansal8843** [comment]
I am also facing this issue. Till date, i was building my application on glitch. But today i thought of opening that glitch live url on the phone. And to my surprise, the camera gets opened on full screen mode. I am also using Android 7.0 device. Earlier i was testing the application in windows 8.1.

**Comment by manishbansal8843** [comment]
phewww!! Issue is resolved. Just replace below line in index.html

`<meta name="viewport" content="width=device-width, initial-scale=1">
`

**with this.**

`<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">`

**Comment by curtisboylan** [comment]
@gabrielgrant This zooming issue I am having is real life with the camera.

**Comment by gabrielgrant** [comment]
Interesting, thanks for the workaround @manishbansal8843 

does that work for you, @curtisboylan ?

**Comment by curtisboylan** [comment]
@manishbansal8843 @gabrielgrant This is working for me but unfortunately is very very zoomed out. It looks like a desktop version is running on the android and also the "content" displays far away from the actual poster

**Comment by gabrielgrant** [comment]
Yes, it sounds like the original issue you reported is caused by the mobile browser trying to adjust the zoom/scale of pages to look better than just showing the entire desktop content. The workaround forces the browser to display the content without any zooming (ie showing the full content). If you want the content partially zoomed, I imagine you may able to set the `initial-scale`, `minimum-scale`, and/or `maximum-scale` to something greater than `1`, although it sounds like you may just want to explicitly add responsive CSS rules that adjust the styling to better suit the user's screen size.

**Comment by curtisboylan** [comment]
@gabrielgrant Is there any other solution? It is only on this certain android version. If I changed CSS etc it will effect all versions and all phones??

**Comment by gabrielgrant** [comment]
Without being able to see this issue reproduced, it's hard to give more advice here. If you'd like more help, please provide a [MCVE](https://stackoverflow.com/help/mcve) and some screenshots of the problem

**Comment by curtisboylan** [comment]
@gabrielgrant  I just got hold of that phone again and tried using @manishbansal8843 site. I will attach a screenshot of the issue. The same thing is happening on mine. The little "VR Goggle" is tiny and the marker projection is going off screen. Any ideas?

![screenshot_20180628-123222](https://user-images.githubusercontent.com/20846522/42031906-c42e275c-7acf-11e8-8a97-3130847d2ca1.png)

**Comment by manishbansal8843** [comment]
@curtisboylan For the issue in which AR content is being displayed away from marker, do you have any other HTML element inside body but outside a-scene element ? 
```
<body>
<div>Some content</div><!--This will move your AR-Image away from your marker.-->
<a-scene>
<!--Aframe code-->
</a-scene>
</body>
```
I also faced this issue. And i found out that one of the reason for this is having other HTML elements within your body tag.

**Comment by curtisboylan** [comment]
@manishbansal8843 Yeah one thing I have in there is a header div, I will try removing it but I have removed it before and it made no difference. I do see though that yours still has the same issue on my phone here with the issues when I browse to your site, do you know this or did you fix it somewhere else?

**Comment by curtisboylan** [comment]
@gabrielgrant @manishbansal8843 any update on a solution to this? Still the same issue on this device.

**Comment by gabrielgrant** [comment]
@curtisboylan thanks for the extra details. To confirm, this only happens with AR.js? or is does this also happen with other, non-AR.js-based A-frame content?

Also, mind showing what it looks like with `initial-scale`, `minimum-scale`, and `maximum-scale` set to 1?

**Comment by curtisboylan** [comment]
@Gabriel<mailto:notifications@github.com> yeah seems to only happen with ar.js but I haven’t noticed with any other web pages. Then screenshots are the scales set to 1, it looks ok with the scale set to 1 but the market images appear off the marker as the screenshot shows

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fariskas** [comment]
had the same issue on Android Samsung S7 on Chrome. 
but @manishbansal8843 solution worked for me.

**Comment by curtisboylan** [comment]
@fariskas could you show your whole code if possible?

**Comment by fariskas** [comment]
mine is just the basic demo setup for ar.js.
You can view the source here:
https://fariskassim.com/stage/rebel9/arjs/v1/index.html

**Comment by Vision-X** [comment]
I can confirm that @manishbansal8843 's meta tag solution works for the zooming issue.

As for the AR assets not appearing with the level of precision you'd want, I am experiencing that bug as well on my Samsung Note 8 running Android@8.0.0 and Chrome@68.0.3440.91

**Comment by poshaughnessy** [comment]
I do not see the same issue with the ['A-Frame basic' example here](https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/basic.html) though.

Here's how it looks in Samsung Internet v7:

<img alt="Screenshot" width="300px" src="https://user-images.githubusercontent.com/151207/47423343-ab05ca00-d77c-11e8-911b-ba1456f255ce.png">

And here's how it looks in Chrome 70:

<img alt="Screenshot" width="300px" src="https://user-images.githubusercontent.com/151207/47423404-d38dc400-d77c-11e8-92bb-4586a55ba91c.png">

(The debug elements are not visible in the former and the overlay elements are cut off on the left, but) there is no difference in zoom.

So now I'll compare this example with our code lab and figure out why ours isn't working...

**Comment by poshaughnessy** [comment]
So the difference between the two was that the [A-Frame basic example](https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/basic.html) does not have a viewport meta tag at all. I removed ours too and it solved the zoom issue in Chrome.

Unfortunately this does not solve the problem in Samsung Internet v8 on the Note 9, though. The A-Frame basic example has the same issue here:

<img alt="Screenshot" width="300px" src="https://user-images.githubusercontent.com/151207/47424749-5401f400-d780-11e8-9c65-920d34322f88.jpg">

But I realised that if I switch off the 'Manual Zoom' here in the settings menu...

<img alt="Screenshot" width="300px" src="https://user-images.githubusercontent.com/151207/47424758-5cf2c580-d780-11e8-81a4-3818604057ee.jpg">

...then (it's a bit pixellated but) it works:

<img alt="Screenshot" width="300px" src="https://user-images.githubusercontent.com/151207/47424914-b6f38b00-d780-11e8-999f-789700d276d5.jpg">

**Comment by tommensink** [comment]
Any progress on this?

It was working fine with my Android A5, but (I think) after the latest OS update of 1 january 2019 this issue appeared. (Also with the basic "try on mobile" example of jerommeetienne). My results so far:
- @poshaughnessy : Disabling manual zoom in the Internet settings solves the issue for me too. Of course we cannot ask our users to do this. 
- @manishbansal8843 : <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"> does correct the zoom behaviour, but AR content is being displayed away from marker
- @manishbansal8843 : Removing other content in the <body></body> tag does not solve this content displayment for me

Any further ideas?

**Comment by pierrevedel** [comment]
hello, I am experiencing this full zoom issue too but only with iOS/safari machines but works fine with android/ chrome/ samsung b(r)owser.
no A-frame, only AR.js and three.js in my code

**Comment by kageori** [comment]
I have the same problem on this.  Any progress on it...?
(use Android 9.0, AR.js & three.js)

**Comment by nachoaguirre** [comment]
I have the same problem with a huawei p30.

I discovered that the camera with the excess of zoom, is only one of the cameras that has the device.
on this site https://simpl.info/getusermedia/sources/ you can change the source of the camera, and indeed there is one that has a lot of zoom, but the others do not.

I ask, how could I change the origin of the camera in a-frame?

**Comment by nicolocarpignoli** [comment]
I found out that the error of showing debug messages  only for an half, is a matter of CSS style. I will make a simple MR to fix that for both desktop and mobile. Already tested it.

**Comment by SiaAf** [comment]
Hey All, 
I have made an AR page by angular. It opens the camera and show a model inside of it(similar to https://www.joshmorony.com/augmented-reality-in-an-ionic-angular-pwa/) and I want to show this page inside of mobile applications(The mobile applications developed by ionic). By saying this, I mean we have a button, if we click on it, it opens Safari(Chrome in android) outside of the application with the url of the AR page. This solution works for android devices but for iOS I have a zoom issue. When safari gets open the camera starts zooming till the page crashes. I
![IMG_0362](https://user-images.githubusercontent.com/25028701/61957894-8c10be80-afc0-11e9-8de5-0860a169eee7.PNG)
![IMG_0363](https://user-images.githubusercontent.com/25028701/61957900-8e731880-afc0-11e9-8ae6-fd894a5e3f18.PNG)
![IMG_0364](https://user-images.githubusercontent.com/25028701/61957908-929f3600-afc0-11e9-9311-d6cc942c6e7b.PNG)
![IMG_0365](https://user-images.githubusercontent.com/25028701/61957911-93d06300-afc0-11e9-86fc-c17c55baa593.PNG)



s there any solution for this problem?

**Comment by meronivalerio** [comment]
Hello,
any news about it? I have a Huawei p30pro smartphone and the problem persists.

**Comment by SiaAf** [comment]
Hey ,

This snippet works for me. hope it helps :) 
"<a-scene vr-mode-ui='enabled: false' arjs='trackingMethod: best; patternRatio: 0.75; debugUIEnabled: false;' renderer='logarithmicDepthBuffer: true;'>" +
				"<a-assets timeout='900000'>" +
					"<a-asset-item id='obj' src="xxxx"></a-asset-item>" +
					"<a-asset-item id='mtl' src="xxxx"></a-asset-item>" +
				"</a-assets>" +
				"<a-marker smooth='true' preset='custom' type='pattern' url='xxxx'>" +
					"<a-obj-model src='#obj' mtl='#mtl' rotation='-90 0 0' position='0 0 0' scale='0.0004 0.0004 0.0004'></a-obj-model>" +
				"</a-marker>" +
				"<a-entity id='rig' movement-controls='speed: 0.1'>" +
					"<a-entity camera></a-entity>" +
				"</entity>" +
			"</a-scene>"

**Comment by SiaAf** [comment]
Hey , this snippet works for me. hope it helps :) 

```  
<a-scene vr-mode-ui='enabled: false' arjs='trackingMethod: best; patternRatio: 0.75; 
     debugUIEnabled: false;' renderer='logarithmicDepthBuffer: true;'>`
	<a-assets timeout='900000'> 
		 <a-asset-item id='obj' src="xxxx"></a-asset-item> 
		 <a-asset-item id='mtl' src="xxxx"></a-asset-item>
	</a-assets> 		
	<a-marker smooth='true' preset='custom' type='pattern' url='xxxx'> 
		<a-obj-model src='#obj' mtl='#mtl' rotation='-90 0 0' position='0 0 0' scale='0.0004 0.0004 0.0004'></a-obj-model> 
	</a-marker> 
	<a-entity id='rig' movement-controls='speed: 0.1'><a-entity camera></a-entity></entity>
</a-scene>

**Comment by meronivalerio** [comment]
Hi @SiaAf 
unfortunately your method doesn't work for me

**Comment by hollytheghost** [comment]
Experiencing zoom issue with the examples. However, when decreasing system font size of Android device (Samsung Galaxy M20, Android Pie) the zoom level in the examples reduces too 🙃

**Comment by Darrel-Collinsworth** [comment]
I'm currently building an ar.js card game and I'm experiencing a similar issue. I'm currently using svelte to make the build dynamic. However, I was able to get the frame to fit the screen using !important on my css targeting the body and the video respectively. Indeed the video feed is WAY larger than the body, so i needed to move the video left with another !important. A third issue I noticed was using my phone (LG V30+) the opposite is happening and it's showing the feed from my wide angle lens which is distorting the marker and causing it to not show up. I got curious so I opened firefox which does ask which camera you'd like to use; and I was able to select the regular focal length camera and my AR.JS project worked. Like everyone else, it looks like my overall ar.js project is super zoomed or scaled in a weird way because the VR icon in the bottom right corner is super small.  Has there been any progress on this? Or is there a repo somewhere that shows how to manually switch cameras in chrome?

I can def post an example of my problem if it'll help.

**Comment by rcolepeterson** [comment]
Any word on this? I too have the zoomed camera issue.

**Comment by ybinstock** [comment]
I'm having the same issue.

**Comment by Zaniyar** [comment]
As @nachoaguirre  already mentioned: the problem occurs while AR.js is selecting the wrong camera! New phones have multiple back-cameras and I think somewhere in AR.js it takes the first one in the list. 

**The solution for this problem would be: Let the user switch between cameras!** 

Somewhere here in AR.js:

````
// get available devices
	navigator.mediaDevices.enumerateDevices().then(function(devices) {
                var userMediaConstraints = {
			audio: false,
			video: {
				facingMode: 'environment',
				width: {
					ideal: _this.parameters.sourceWidth,
					// min: 1024,
					// max: 1920
				},
				height: {
					ideal: _this.parameters.sourceHeight,
					// min: 776,
					// max: 1080
				}
		  	}
		}


		if (null !== _this.parameters.deviceId) {
			userMediaConstraints.video.deviceId = {
				exact: _this.parameters.deviceId
			};
		}
		// get a device which satisfy the constraints
		navigator.mediaDevices.getUserMedia(userMediaConstraints).then(function success(stream) {
			// set the .src of the domElement
            domElement.srcObject = stream;
			var event = new CustomEvent('camera-init', {stream: stream});
			window.dispatchEvent(event);
			// to start the video, when it is possible to start it only on userevent. like in android
			document.body.addEventListener('click', function(){
				domElement.play();
			});
			// domElement.play();
                         // TODO listen to loadedmetadata instead
			// wait until the video stream is ready
			var interval = setInterval(function() {
				if (!domElement.videoWidth)	return;
				onReady()
				clearInterval(interval)
			}, 1000/50);
		}).catch(function(error) {
			onError({
				name: error.name,
				message: error.message
			});
		});
	}).catch(function(error) {
		onError({
			message: error.message
		});
	});


How could we let the User toggle between available devices?

**Comment by nicolocarpignoli** [comment]
Guys which phone do you have? It's confirmed that this is caused by phones with multiple cameras?

**Comment by Zaniyar** [comment]
@nicolocarpignoli Mine is Huawei P20 pro - I can definitely confirm that the camera which got selected by AR.js is the wrong camera; it is the first one in the list of "facing back" cameras - On Huawei P20 pro there are 4 different facing back cameras and the first one is that one which is extremely zoomed in - same zoom level like in a simple AR.js demo.

**Comment by nicolocarpignoli** [comment]
I may include this feature in next version. We can do this way: show a dialog to select the camera only if more than 2 cameras are available. Otherwise act like now selecting rear camera

**Comment by nicolocarpignoli** [comment]
I can't test it, can anyone help me next days with a test for this new feature?

**Comment by Zaniyar** [comment]
@nicolocarpignoli please don't show a dialog, since this is disruptive for the user experience. Select the default camera, like now, and give the devs the possibility to handle this for their users. for example a small switcher in the corner (on click switch to next available camera; even front cam could be in the list, for augmented face masks in the future? :p )
thx

**Comment by Darrel-Collinsworth** [comment]
> Guys which phone do you have? It's confirmed that this is caused by phones with multiple cameras?

Yeah that's the main reason I'm having the issue. when I use a browser that lets me pick the camera, i choose the camera that is NOT my wide angle lens and the application works as intended.

**Comment by nicolocarpignoli** [comment]
I may have done some progress to this. Can anyone please test? See there: https://github.com/jeromeetienne/AR.js/pull/661#issuecomment-559787020

**Comment by kvabakoma** [comment]
Sharing an ugly fix for the multiple camera phones issue:

In aframe-ar.js (2.0.8) right after declaring `var userMediaConstraints` I check for an available camera with label "camera2 0, facing back".
If such a camera is available, I set it in the userMediaConstraints. 
I have just tested it with 19 different Android phones and it works (including Huawei P30 Pro and Mate 20 Pro).
Here's the full code:

`
var userMediaConstraints = {
	audio: false,
	video: {
		facingMode: 'environment',
		width: {
			ideal: _this.parameters.sourceWidth,
			// min: 1024,
			// max: 1920
		},
		height: {
			ideal: _this.parameters.sourceHeight,
			// min: 776,
			// max: 1080
		}
  	}
}

// CUSTOM CODE START
var backCam2 = devices.filter(d=>{
	return d.label && d.label == "camera2 0, facing back";
})
if (backCam2.length) {
	userMediaConstraints.video.deviceId = backCam2[0].deviceId
}
// CUSTOM CODE END
`

It's surely not bulletproof but so far I can't break it. It even fixed a Honor 8 problem where ARjs was using the front camera.

Hope it helps :)

**Comment by nicolocarpignoli** [comment]
Check my PR on pull requests it may help. I did the same thing of yours Sent from my Huawei phone-------- Original Message --------Subject: Re: [jeromeetienne/AR.js] Camera loading on full zoom (#369)From: Nikola Georgiev To: "jeromeetienne/AR.js" CC: Nicolò Carpignoli ,Mention Sharing an ugly fix for the multiple camera phones issue:
In aframe-ar.js (2.0.8) right after declaring var userMediaConstraints I check for an available camera with label "camera2 0, facing back".
If such a camera is available, I set it in the userMediaConstraints.
I have just tested it with 19 different Android phones and it works (including Huawei P30 Pro and Mate 20 Pro).
Here's the full code:
`
var userMediaConstraints = {
audio: false,
video: {
facingMode: 'environment',
width: {
ideal: _this.parameters.sourceWidth,
// min: 1024,
// max: 1920
},
height: {
ideal: _this.parameters.sourceHeight,
// min: 776,
// max: 1080
}
}
}
// CUSTOM CODE START
var backCam2 = devices.filter(d=>{
return d.label && d.label == "camera2 0, facing back";
})
if (backCam2.length) {
userMediaConstraints.video.deviceId = backCam2[0].deviceId
}
// CUSTOM CODE END
`
It's surely not bulletproof but so far I can't break it. It even fixed a Honor 8 problem where ARjs was using the front camera.
Hope it helps :)

**Comment by kvabakoma** [comment]
@tommensink - we found a workaround for the SamsungBrowser zooming && **3d offset**. 
If you place the ARjs in an iframe and both the parent and the iframe content files have `<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">` it seems to work properly. 
The canvas is no longer huge (we experienced 6000+ px width on protrait).
The augmented 3D content seems to be aligned properly.

**Comment by innovacioneleven** [comment]
in Samsung Internet Browser at Disabling the “control zoom in web pages” option removes the zoom scale as the displacement of the content to be displayed.
![Ajustes](https://user-images.githubusercontent.com/57809760/71212247-ef0c3600-227e-11ea-9f4d-2703e96f050e.png)
![Apariencia](https://user-images.githubusercontent.com/57809760/71212257-f6cbda80-227e-11ea-8ec6-7eb3b8520371.png)
![Zoom](https://user-images.githubusercontent.com/57809760/71212261-fa5f6180-227e-11ea-8be8-957d96bbaea2.png)

**Comment by dhaiduk** [comment]
> @tommensink - we found a workaround for the SamsungBrowser zooming && **3d offset**.
> If you place the ARjs in an iframe and both the parent and the iframe content files have `<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">` it seems to work properly.
> The canvas is no longer huge (we experienced 6000+ px width on protrait).
> The augmented 3D content seems to be aligned properly.

Show the code of how to use <ifame> with ar.js

**Comment by odiazjs** [comment]
> Sharing an ugly fix for the multiple camera phones issue:
> 
> In aframe-ar.js (2.0.8) right after declaring `var userMediaConstraints` I check for an available camera with label "camera2 0, facing back".
> If such a camera is available, I set it in the userMediaConstraints.
> I have just tested it with 19 different Android phones and it works (including Huawei P30 Pro and Mate 20 Pro).
> Here's the full code:
> 
> `var userMediaConstraints = {
> audio: false,
> video: {
> facingMode: 'environment',
> width: {
> ideal: _this.parameters.sourceWidth,
> // min: 1024,
> // max: 1920
> },
> height: {
> ideal: _this.parameters.sourceHeight,
> // min: 776,
> // max: 1080
> }
> }
> }
> 
> // CUSTOM CODE START
> var backCam2 = devices.filter(d=>{
> return d.label && d.label == "camera2 0, facing back";
> })
> if (backCam2.length) {
> userMediaConstraints.video.deviceId = backCam2[0].deviceId
> }
> // CUSTOM CODE END`
> 
> It's surely not bulletproof but so far I can't break it. It even fixed a Honor 8 problem where ARjs was using the front camera.
> 
> Hope it helps :)

lifesaver dude

**Comment by nicolocarpignoli** [comment]
feel free to re-open this discussion at: https://github.com/AR-js-org/AR.js if still needed help for someone

**Comment by eCronik** [comment]
Was this resolved within AR.js? I'm having Zoom-issues like described above on Samsung S8 and S10 - got it fixed with the workaround

`<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">`

but now the model spawns from out of the screen, and not from the marker anymore. Works flawlessly on iOS and other Android devices (i.e. Huawei).

Hoping somebody could help me out.

**Comment by rainerlonau** [comment]
Using an iframe helped me to fix it on my Samsung S6 (in the Samsung browser). Solution from here: https://stackoverflow.com/a/14738668/5028033

This is what I use now as iframe "container". Project code is in project.html then:
https://pastebin.com/EKRLwQEz

**Comment by alevillejo** [comment]
> Using an iframe helped me to fix it on my Samsung S6 (in the Samsung browser). Solution from here: https://stackoverflow.com/a/14738668/5028033
> 
> This is what I use now as iframe "container". Project code is in project.html then: https://pastebin.com/EKRLwQEz

That did it for me.
Thanks!

**Comment by LucasYuugi** [comment]
> @gabrielgrant I just got hold of that phone again and tried using @manishbansal8843 site. I will attach a screenshot of the issue. The same thing is happening on mine. The little "VR Goggle" is tiny and the marker projection is going off screen. Any ideas?
> 
> ![screenshot_20180628-123222](https://user-images.githubusercontent.com/20846522/42031906-c42e275c-7acf-11e8-8a97-3130847d2ca1.png)

@curtisboylan  Did you manage to solve this problem? Because I'm having the same problem?

**Comment by gabrielgrant** [comment]
@LucasYuugi wow, this is a throwback, haven't touched this in quite a while...

did you try @rainerlonau 's iframe workaround? any luck with that?

**Comment by LucasYuugi** [comment]
@gabrielgrant My problem is that in my code, when I remove the zoom with this code:
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
The object is off the center of the cell phone, and when I applied @rainerlonau  code it didn't work either. It started to slide the page instead of rotating the object (the object wasn't even in the center).
https://glitch.com/edit/#!/test12425

![pattern-qr-code (24)](https://github.com/jeromeetienne/AR.js/assets/149541454/c868bb09-49b3-44f4-89eb-62bda60a5d8b)

**Comment by LucasYuugi** [comment]
> can confirm that @manishbansal8843 's meta tag solution works for the zooming issue.
> 
> As for the AR assets not appearing with the level of precision you'd want, I am experiencing that bug as well on my Samsung Note 8 running Android@8.0.0 and Chrome@68.0.3440.91

@curtisboylan Can you did resolve this problem?

**Comment by LucasYuugi** [comment]
> Using an iframe helped me to fix it on my Samsung S6 (in the Samsung browser). Solution from here: https://stackoverflow.com/a/14738668/5028033
> 
> This is what I use now as iframe "container". Project code is in project.html then: https://pastebin.com/EKRLwQEz

@rainerlonau 
When I implemented this code, I managed to center the object, however, it stopped detecting the touch, causing the object to no longer rotate.
![image](https://github.com/jeromeetienne/AR.js/assets/149541454/0e81f676-0ee1-4b02-81be-d782efa0b9ea)

**Comment by rainerlonau** [comment]
@LucasYuugi Hi, sorry I can´t help atm. My solution is over two years old. I didn´t touch this framework since then. Also our project was only a prototype back then, so it´s not maintained.

Did you create a clean demo project using AR.js basic sample? Then apply my workaround with the iFrame? Does that still work?
Or did you directly use your code? Could be an issue with that?
