### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by pvnr0082t** [jeromeetienne/AR.js#37]
Hi @jeromeetienne ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
I'm not sure which files need to be hosted, could you please tell me? Thank you.

https://github.com/cdnjs/cdnjs/issues/10990

**Comment by jeromeetienne** [comment]
@pvnr0082t good question. let me think and get back to you

**Comment by jeromeetienne** [comment]
ok i will produce a single build file. like ar-build.js which contains everything for three.js. Thus it will be easier to host and include in the page.

I will update you when it is done

aframe-ar.js already contains every everything for aframe-binding.js - https://github.com/jeromeetienne/AR.js/tree/master/aframe/build

**Comment by zya** [comment]
@jeromeetienne is this issue resolved with this file?
https://github.com/jeromeetienne/AR.js/blob/master/three.js/build/ar.js
Meaning, does three.js/build/ar.js inculde everything you need to run all the examples?

**Comment by nicolocarpignoli** [comment]
@jeromeetienne is this solved?
