### ISSUE TITLE
Custom markers don't vanish when camera doesn't show the marker

### ISSUE THREAD

**Issue by harryIna** [jeromeetienne/AR.js#371]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

ar.js with aframe works well. I could add a custom marker, but the presentation of the model is different to models presented using hiro- or kanji-marker. The model doesn't vanish when the marker is no more visible in the camera. Working on an markerbased Indoor-Navigation it is important to use about 30 custom markers, but as soon as the marker leaves the camera view, the model may no longer be seen.

Any suggestions?

kind regands 
Hardy

**Comment by nicolocarpignoli** [comment]
see https://github.com/jeromeetienne/AR.js/issues/230

**Comment by nicolocarpignoli** [comment]
close as duplicate
