### ISSUE TITLE
Custom Smoothing code

### ISSUE THREAD

**Issue by Djinne** [jeromeetienne/AR.js#373]
Hi, when i add the following code it seems to smooth quite a bit. This code gets added in the gltf.load function after after the gltf model to the marker group.
This code works by storing the previous position and rotation of the model and applying a ratio (in the case 1:1. A 2:3 would have a multiplier of 2 and division of 3) of the new position and rotation. The bigger the ration the smoother it is. Some problems are is that the model can do a 360 flip. I did this because I was struggling to get the arsmoothing to work as it adds a copy of the scene and not the scene itself.  

Just wondering if this is a efficient way of doing it

What could cause that flip? Probably that I'm only adding the current rotation and should rather minus if the ration is less than the current models ration.

```
var previousrot={x:0,y:0,z:0}; //set initial rotation and position
var previouspos={x:0,y:0,z:0};

onRenderFcts.push(function(delta){  //render changes

previousrot.x=(previousrot.x*1+markerGroup4.rotation.x)/2; //update rotation on ratio
previousrot.y=(previousrot.y*1+markerGroup4.rotation.y)/2;
previousrot.z=(previousrot.z*1+markerGroup4.rotation.z)/2;
markerGroup4.rotation.set(previousrot.x,previousrot.y,previousrot.z); 

previouspos.x=(previouspos.x*1+markerGroup4.position.x)/2; //update position on ratio
previouspos.y=(previouspos.y*1+markerGroup4.position.y)/2;
previouspos.z=(previouspos.z*1+markerGroup4.position.z)/2;

//set calculated position and rotation on markergroup
markerGroup4.position.set(previouspos.x,previouspos.y,previouspos.z); 
markerGroup4.updateMatrix(); 
});
```

**Comment by Djinne** [comment]
`	var previousrot=[];
	var previouspos=[];
	markerGroup.forEach(function(e,i){
		previousrot.push({x:0,y:0,z:0});
		previouspos.push({x:0,y:0,z:0});
		onRenderFcts.push(function(){
			previousrot[i].z=(previousrot[i].z+markerGroup[i].rotation.z)/2;
			previousrot[i].x=(previousrot[i].x+markerGroup[i].rotation.x)/2;
			previousrot[i].y=(previousrot[i].y+markerGroup[i].rotation.y)/2;
			markerGroup[i].rotation.set(previousrot[i].x,previousrot[i].y,previousrot[i].z);
			previouspos[i].x=(previouspos[i].x+markerGroup[i].position.x)/2;
			previouspos[i].y=(previouspos[i].y+markerGroup[i].position.y)/2;
			previouspos[i].z=(previouspos[i].z+markerGroup[i].position.z)/2;
			markerGroup[i].position.set(previouspos[i].x,previouspos[i].y,previouspos[i].z);
			markerGroup[i].updateMatrix();
		});
	});`

**Comment by Djinne** [comment]
`
var previousrot=[];
var previouspos=[];
markerGroup.forEach(function(e,i){
previousrot.push({x:0,y:0,z:0});
previouspos.push({x:0,y:0,z:0});
onRenderFcts.push(function(){
previousrot[i].z=(previousrot[i].z+markerGroup[i].rotation.z)/2;
previousrot[i].x=(previousrot[i].x+markerGroup[i].rotation.x)/2;
previousrot[i].y=(previousrot[i].y+markerGroup[i].rotation.y)/2;
markerGroup[i].rotation.set(previousrot[i].x,previousrot[i].y,previousrot[i].z);
previouspos[i].x=(previouspos[i].x+markerGroup[i].position.x)/2;
previouspos[i].y=(previouspos[i].y+markerGroup[i].position.y)/2;
previouspos[i].z=(previouspos[i].z+markerGroup[i].position.z)/2;
markerGroup[i].position.set(previouspos[i].x,previouspos[i].y,previouspos[i].z);
markerGroup[i].updateMatrix();
});
});
`

**Comment by enquel** [comment]
Hi @Djinne, does this smoothing effectively flattens the jitters of marker-found objects?
About flip - I've no idea, but I guess you could include conditions for avoiding the flip (if total rotation ~ flip rotation). Maybe the tick should be smaller?

**Comment by Djinne** [comment]
Yes this smooths movement and rotation to stop jitters and positional snaps. 
The flipping is a rare occurrence which happens on faster devices while viewing directly above the marker so maybe the ticking could help. Just wanted an opinion on this solution :)

**Comment by enquel** [comment]
Thanks a lot for clarification! I'm a noob when it comes to JS (C#/Unity is my thing): where do you exactly add this code? (can't find that function in AR.js - do we add this to the .html file)?

**Comment by Djinne** [comment]
You can add it anywhere after declaring your marker. This is for threejs and not aframe by the way

**Comment by enquel** [comment]
Ok all clear, thanks!

**Comment by nicolocarpignoli** [comment]
solved
