### ISSUE TITLE
Demo enhancements

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#377]
Demos and examples are very important for this project. Actually there are a lot of dead links on examples. @stemkoski has done a terrific work on his repo working on examples based on AR.s ones. Can we replace AR.js dead examples with these new examples and collect them in a specific section of docs - and maybe, in the future, on a wiki?

Old demo issues: (we can decide what to keep, what to not implement/adapt)

https://github.com/jeromeetienne/AR.js/issues/56
https://github.com/jeromeetienne/AR.js/issues/25
https://github.com/jeromeetienne/AR.js/issues/15
https://github.com/jeromeetienne/AR.js/issues/14
https://github.com/jeromeetienne/AR.js/issues/171

**Comment by stemkoski** [comment]
#56 is "screen as portal" and #17 is "reverse wii mote". Aren't these basically the same thing? I started one of these at https://stemkoski.github.io/AR-Examples/screen-hole.html (uses multi-marker image at https://raw.githubusercontent.com/stemkoski/AR-Examples/master/markers/kanji-abcd.png) but never got it to work at a point where I was satisfied enough with the stability to list it on my collection of examples. It would be great to dig up Jerome's version of this to understand how it works a bit better. 

#25 is labelled as "crystal skull", but I think that the idea was to do a refraction demo (which Jerome did). I will try to figure this one out and post a simplified example.

#15 is "hole in the wall" (actually, in the floor), that's ready to go from my repository.
https://stemkoski.github.io/AR-Examples/hole-plane.html

#14 is "portal", that's also ready to go.
https://stemkoski.github.io/AR-Examples/portal-view-AR.html

#171 is "markerless location based AR" sounds amazing, but was it ever actually done? I wouldn't even know how to begin something like this.

I think a separate demo with just shadows would be useful; I'll add it to my to-do list.

**Comment by nicolocarpignoli** [comment]
I think we can not consider #17 anymore. I will close the issue and remove it from list. Agree with you.

Also, #171 is out of AR.js actual technology state of the art. We can start from the others, with that, we could have a very nice and updated list of examples :)

**Comment by nicolocarpignoli** [comment]
@stemkoski for #14, so the 'portal demo', I wonder if it's possible to go with the camera INTO the portal and see the 'other world' around when moving the camera, and switching back to 'real world' when entering on the portal again.

For now, on old jerome etienne example, as soon as you go into the other world, when you move camera off the marker, it loses focus and do strange things. Hope I explain well what i mean :)

**Comment by stemkoski** [comment]
@nicolocarpignoli absolutely. I'll add this to my list.

**Comment by nicolocarpignoli** [comment]
after re-ordering the readme, i will re-open this if it became important for someone. I see a lack of interests on specific examples so the ones that stemkoski has already done are enough for beginners - now they're clearly visible on the readme.
