### ISSUE TITLE
General AR events

### ISSUE THREAD

**Issue by fernans** [jeromeetienne/AR.js#378]
**Do you want to request a *feature* or report a *bug*?**
a feature

**What is the current behavior?**
currently only have A-Frame events and just marke detection event

**If this is a feature request, what is motivation or use case for changing the behavior?**
General AR system events, like... camera init.
scene.addEventListener("ar-camera-init", ...)
scene.addEventListener("ar-camera.error", ...)
...

If user doesn't give you camera permission, you can't know it to show some "splash content".

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Mainly for mobile platforms, but also on web is desirable.

**Comment by nicolocarpignoli** [comment]
This is an 'old' issue but still interesting and the request very useful, someone has time for this?

**Comment by kalwalt** [comment]
I agree with you @nicolocarpignoli @fernans we should have such feature...

**Comment by nicolocarpignoli** [comment]
I have made a PR for that, linked on this issue
