### ISSUE TITLE
Use AR.js in Angular Component

### ISSUE THREAD

**Issue by martynha** [jeromeetienne/AR.js#379]
Hi,
I have to implement an application in Angular 5 and I'm having difficulty using an a-frame scene (that embeds arjs) in an Angular Component.

The scenes of aframe work, but when I embeds arjs does not open the camera.

I have imported aframe following this guide:

https://medium.com/@pitipon/a-frame-with-angular-setup-project-5797b2f2a03b

and 

I have imported aframe-ar.js in index.html 

Can someone help me?

**Comment by nicolocarpignoli** [comment]
related to https://github.com/jeromeetienne/AR.js/issues/364. I can't help you as I never tried AR.js on Angular, maybe @jeromeetienne can

**Comment by reto88** [comment]
Is there a way to use arjstoolkit in angularjs without a frame?

**Comment by shawn-li-bj** [comment]
@reto88 If you want to use this library in a pure JS way, you can find some examples in path "/three.js/examples/".  In my opinion, Angular/Angularjs can integrate any content implemented in pure JS mode.

**Comment by stemkoski** [comment]
@reto88 For many more pure JS examples, check out https://stemkoski.github.io/AR-Examples/ & https://github.com/stemkoski/AR-Examples .

**Comment by reto88** [comment]
@stemkoski thank you for this nice example.did you already used ar.js in a framework like angular or react?

**Comment by eagor** [comment]
@reto88 you need aframe loaded before zone.js, and to achieve this I've found 2 options so far:
1. add the links to the aframe and arjs in index.html (so that it comes before polyfills.js)
2. move zone.js from polyfills to scripts, and load aframe and arjs in scripts before it:

```
"scripts": [
  "node_modules/aframe/dist/aframe-master.js",
  "node_modules/ar.js/aframe/build/aframe-ar.js",
  "node_modules/zone.js/dist/zone.js"
]
```

not sure if the 2nd options might cause some problems in future, but seems to work ok so far.

**Comment by BastianNotter** [comment]
None of these solutions seem to work for me on Angular 6. I've importet A-frame the same way as @martynha did but even with ar.js in my index.html it doesnt seem to work.
Does anyone have a working expample of ar.js in angular 6 because it seems nomatter what I try I cant get it to work.

**Comment by jsebrech** [comment]
I don't you need anything special to get it to run inside Angular. This works for me:

1. Generate a new Angular 6 app with angular-cli
2. In src/app/index.html add this at the bottom of the `<head>` section:
```
  <script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
  <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js"> </script>
```
3. In src/app/app.module.ts import CUSTOM_ELEMENTS_SCHEMA and add a schemas key to the NgModule directive
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
})
export class AppModule { }
```
4. Replace the contents of src/app/app.component.html with
```
<a-scene embedded arjs>
  <a-marker preset="hiro">
          <a-box position='0 0.5 0' material='color: black;'></a-box>
  </a-marker>
  <a-entity camera></a-entity>
</a-scene>
```
5. Run the app with `npm start`

Incidentally, I used ngrok to publish my localhost online as https and browse to it from my phone. It gave a NotAllowedError trying to access the camera over http.

**Comment by BastianNotter** [comment]
Well fuck that works for me too. I guess if you import Aframe the way the guide tells you to ar.js isnt gonna work instead. How odd.
By the guide I mean this one https://medium.com/@pitipon/a-frame-with-angular-setup-project-5797b2f2a03b

Thanks a lot @jsebrech !

**Comment by jsebrech** [comment]
`polyfills.ts` gets appended to the bottom of the `<body>` so ar.js and aframe load out of order that way. You could fix it by doing lazy loading of ar.js by [appending a script tag to the body](https://theinfogrid.com/tech/developers/angular/lazy-loading-scripts-and-styles-angular/) after the angular app initializes, but then you would have to wait until ar.js loads before the main app view can be bootstrapped, which would complicate things.

Realistically either you load both from URL with blocking script tags, or you load both from npm through the polyfills approach.

**Comment by reto88** [comment]
thanks, it works. do anyone now how you get the context of the a-frame canvas? in the dev mode of google chrome i can see a-canvas class but no id to get the context.

**Comment by johndpotts** [comment]
var scene = document.querySelector('a-scene');
    const foo = scene.components.screenshot.getCanvas('perspective');

**Comment by naonvl** [comment]
how about importing ar-threex to angular component?
