### ISSUE TITLE
Question: Showing videos with aframe or without

### ISSUE THREAD

**Issue by marcellkiss** [jeromeetienne/AR.js#38]
I'd like to show mp4 files based on the marker. I built a prototype based on aframe. I'm wondering, if I'm using just this 'feature' (a-video), isn't it a too big overhead? What should be the workaround?

**Comment by jeromeetienne** [comment]
playing a video in webgl has a cost. 

Try it yourself on the device you target. 

btw this seems independant to AR.js itself. it seems more of a a-frame question. Checkout their slack. it is pretty active https://aframe.io/community/#slack

**Comment by marcellkiss** [comment]
Thx!
