### ISSUE TITLE
"No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by curtisboylan** [jeromeetienne/AR.js#380]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When you load some images from online you receive a "No 'Access-Control-Allow-Origin' header is present on the requested resource." error, this does not happen on all websites but does happen on a huge majority. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Create marker with image with a no-access-control-allow-origin error such as https://gweb-earth.storage.googleapis.com/assets/earth_desktop.jpg

**What is the expected behavior?**
I would expect for this to display me with an alert instead saying the image cannot be allowed, or just for it to work. I am using another ajax request on my other web page on the same image and it allows me to get the sizing of the image so I have no idea why AR.JS cannot display this image.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Happens on all devices/browsers

**Comment by nicolocarpignoli** [comment]
Hi
try to upload your image on github and reference it with an url like ` https://rawgithub.com/ ` (...)

**Comment by curtisboylan** [comment]
@nicolocarpignoli Yes this will work but I want to be able to display images from any website, some websites like GitHub will work.

**Comment by nicolocarpignoli** [comment]
it's a CORS problem,  not related with AR.js.

**Comment by curtisboylan** [comment]
Any idea on how to fix it? I know it's a CORS problem but any solution I have used for CORS has not solved it. @nicolocarpignoli

**Comment by jwebking** [comment]
@curtisboylan adding crossOrigin="anonymous" to my asset items has seemed to help eliminate that issue for me, but I can't say whether or not that works in every case/situation. 

`<a-asset-item id="imgOne" src="your image source url" crossOrigin="anonymous"></a-asset-item>`

`<a-entity    your-entity-type="#imgOne"></a-entity>`

**Comment by curtisboylan** [comment]
@jwebking Unfortunately this does not work, tried it out there. Example image that will return black is https://techcrunch.com/wp-content/uploads/2017/01/2017-01-31_0935.png

**Comment by jwebking** [comment]
@curtisboylan , @nicolocarpignoli is right. Not something that could be implemented into AR.js to "fix."
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Best bet is to download the image and put it in your asset folder, or only link to images that you know you can use on other sites based on their header settings.

**Comment by anilachary** [comment]
It's CORS issue, not AR.js. When the resource been fetched from another region we need to implement CORS. If we fetch the data from AWS S3 Bucket hosted in another region then we need to Adde some config data to  AWS bucket.

Ref : https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

<CORSConfiguration>
 <CORSRule>
   <AllowedOrigin>http://www.example1.com (ENTER YOUR DOMAIN NAME)</AllowedOrigin>
   <AllowedMethod>PUT</AllowedMethod>
   <AllowedMethod>POST</AllowedMethod>
   <AllowedMethod>DELETE</AllowedMethod>
   <AllowedHeader>*</AllowedHeader>
 </CORSRule>
</CORSConfiguration>

**Comment by ronnielivingsince1994** [comment]
CORS! Argghh! It always tries to get under your nerves! But for me, after years of practice, I've now developed a fair understanding of how it works. 

Anyways for you I've another tip to share, Works like magic while trying out any new api's..

If you just temporarily want to tackle this, while trying to keep your focus on the code logic and dont want to get your hands dirty with those headers file, it would be a really easy solution to just start your chrome in dev mode with the following scipt:

**Win + R**, followed by  **chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security**
