### ISSUE TITLE
Markers without the black border

### ISSUE THREAD

**Issue by derzu** [jeromeetienne/AR.js#382]
**Do you want to request a *feature* or report a *bug*?**
I wanna to request a new feature: Customize the markers without the black border.
Are you planning to implement this feature?

**What is the current behavior?**
Currently, it is only possible to use markers with a black border.

**If this is a feature request, what is motivation or use case for changing the behavior?**

The motivation is to be possible to use any image as a marker, without the black border.

**Comment by nicolocarpignoli** [comment]
Unfortunately this is not related to AR.js as Ar.js it's "only" a layer upon other wonderful libraries. For patterns and pattern recognition, it uses artoolkit (https://github.com/artoolkit/artoolkit5). The feature you request is interesting but is related to artoolkit only. You could open an issue on their project but i think that it could be an already on-going discussion for this topic

**Comment by derzu** [comment]
Ok, thanks. Is ARTookit still being supported? I think the DAQRI stopped it.

**Comment by ShahriarVelayat** [comment]
no but there is a project qith name artoolkitx you can find it on artoolkitx.org

**Comment by derzu** [comment]
Ok, thanks again, I will try the artoolkitx.

**Comment by derzu** [comment]
Hi, I wanna try to develop the marker detection without the black border.

Where does the AR.js use the ARToolkit? With file? I looked at the ARToolkit project (https://github.com/artoolkit/artoolkit5) but I didn't find any javascript file?

Can you guide me where exactly the marker detection is being done now?

Thanks,

Derzu.
