### ISSUE TITLE
Display aframe-ar.js scripts on jquery window

### ISSUE THREAD

**Issue by osper66** [jeromeetienne/AR.js#384]
Hello.

  I'd like to call script susing aframe from my web app, but I couldn’t display this demo within jquery's window and still displayed webcam's image and not turned off this.

 Without webcam option, I could display aframe on jquery window .

 Could you tell me how to solve this?

 Thanks for advance.

**Comment by mnutsch** [comment]
The AR.js library combines image recognition with Aframe to position an
Aframe scene on top of a recognized target.

If you only want Aframe without the camera feed and image recognition, then
follow the examples at: https://aframe.io/docs/0.8.0/introduction/

**Comment by osper66** [comment]
@mnutsch thanks for your comment．

 I tried to display aframe on newly created tab in following code, but nothing displayed.

     var arTab = window.open ('about:blank');
     arTab.document.write("aframe test <a-scene embedded arjs></a-scene>");

**Comment by osper66** [comment]
Hi.

 I forgot to call aframe-ar related scripts, so I retry in following code. However browser returned error message "Webcam Error, Name: NotAllowedError, Message: Permission denied"

   arTab.document.write("<script src='https://aframe.io/releases/0.6.1/aframe.min.js'></script><script src='libs/location-based-ar-master/examples/vendor/ar.js/aframe/build/aframe-ar.js'></script><script>ARjs.Context.baseURL = 'libs/location-based-ar-master/examples/vendor/ar.js/three.js/'</script>aframe test <a-scene embedded arjs></a-scene>");
