### ISSUE TITLE
Dynamic Body support for AR.js

### ISSUE THREAD

**Issue by aj019** [jeromeetienne/AR.js#386]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
Currently the dynamic bodies float on the marker and doesn't implement gravity properly.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The behaviour should be similar as to that of Aframe.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment]
Sorry but I don't understand, can you explain better?

**Comment by aj019** [comment]
In Aframe using Canon.js  we have the concept of dynamic and static bodies. This is used to add physics to our 3d objects. For eg If i make a ball dynamic and the plane static . Then on loading the page the ball will fall towards the plane because of gravity. 

When you use the same properties using Ar.js the ball floats of the plane. We need to integrate Cannon.js so we can use concepts like gravity , friction , restitution etc.

**Comment by nicolocarpignoli** [comment]
Closing this issue due to dismission of this repository. New repository of AR.js will be up at https://github.com/AR-js-org/AR.js/

Feel free to re-open the issue there if still valid.
