### ISSUE TITLE
comma in the end of aframa-ar.min.js

### ISSUE THREAD

**Issue by 1flyby** [jeromeetienne/AR.js#387]
looks like, this comma doesn't need (end of tick)
![screenshot_16](https://user-images.githubusercontent.com/17343370/43190126-f67e2f72-9000-11e8-98c9-dd681b96c7c5.png)

**Comment by nicolocarpignoli** [comment]
Please, fill the given Issue template. I can't understand if this is a proposal of removing that comma or something else.
