### ISSUE TITLE
Front camera is used by default

### ISSUE THREAD

**Issue by zhengoogle** [jeromeetienne/AR.js#388]
On Android device phones, the front camera is used by default. The default should be modified to the rear camera.

**Comment by zhengoogle** [comment]
use this:
navigator.mediaDevices.enumerateDevices().then(function (devices) {
    var camreass=[];
    devices.forEach(function(e){
        console.log(e)
        if(e.kind=="videoinput")
        {
            camreass.push(e.deviceId)
        }
    })
    console.log(camreass)
    var userMediaConstraints = {
        audio: false,
        video: {
            facingMode: 'environment',
            deviceId:camreass[1],
            width: {
                ideal: _this.parameters.sourceWidth,
                // min: 1024,
                // max: 1920
            },
            height: {
                ideal: _this.parameters.sourceHeight,
                // min: 776,
                // max: 1080
            }
        }
    }

**Comment by nicolocarpignoli** [comment]
Hi,
is this a question or a proposal?
if it is a proposal as I guess, please make a PR :) We'll be glad to test it and eventually merge it
