### ISSUE TITLE
3d model will not upload

### ISSUE THREAD

**Issue by lajunex0** [jeromeetienne/AR.js#389]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Hi there! So I am trying to use Ar.js, but whenever I add a 3d model to the scene my project stops working. Can anyone help?
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs='sourceType: webcam;'>
        
        <a-assets>
            <a-asset-item id="NSLogo73" src="/models/gltf/NSLogo73.gltf"></a-asset-item>
        </a-assets>
        
        <a-entity gltf-model="#NSLogo73"></a-entity>
        
        
    <a-box position= ' 0 0.9 0' material opacity 0.5;'<a-box>
     <a-marker-camera preset='hiro'></a-marker-camera>    </a-scene>
</body>

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I want the model to appear when the hiro marker is used. Thanks! Also, none of the demos in the ar.js folder work for me? 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment]
hi @lajunex0 , try using a remote url for your src attribute. for example:  src="https://raw.githubusercontent.com/nicolocarpignoli/nicolocarpignoli.github.io/master/ar-playground/models/CesiumMan.gltf"></a-asset-item>

**Comment by lajunex0** [comment]
Thanks!! It works now. 

Best, 
LaJune
