### ISSUE TITLE
Idea: implement QR-code in marker image

### ISSUE THREAD

**Issue by Nirazul** [jeromeetienne/AR.js#39]
Really interesting project, thanks for sharing!

It'd be nice to implement a QR code into the marker image to simplify the startup process of a presentation. Then you only need to open the marker in your desktop browser, then scan it with your QR reader on mobile.

Btw, some years ago in 2012 there was a similar project called [Pointcloud browser](https://www.youtube.com/watch?v=NKt4GYQASB0). Maybe you could draw inspiration from it as it could work with arbitrary images as targets in addition to markers, that were analyzed by a server. 
Unfortunately the project was abandoned. Back then, I've done a project with a colleague, that showcases it's powers: [Amplex](https://vimeo.com/45510987).

**Comment by jeromeetienne** [comment]
good news! it is already done :)

here is the blog post - https://medium.com/arjs/ar-code-a-fast-path-to-augmented-reality-60e51be3cbdf
here is the builder - https://jeromeetienne.github.io/AR.js/three.js/examples/arcode.html

enjoy :)

**Comment by Nirazul** [comment]
Ha, what a coincidence. Nice!

**Comment by Diantha** [comment]
Hi, I am the only one that can't generate the ar-code? I only see "Info" and "PDF" button
