### ISSUE TITLE
Tango not working on Pixel 2 XL

### ISSUE THREAD

**Issue by RandomCouch** [jeromeetienne/AR.js#391]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When testing the A-Frame AR.js + Tango example found here: https://rawgit.com/jeromeetienne/AR.js/master/aframe/examples/tango-demo.html 
using Pixel 2 XL which is supposedly Tango supported but nothing happens, I get the camera display but tapping on the scene does not spawn any box on any surface. To be fair I have not found any information on if the pixel 2 XL supported Tango or not, but it did work with ARCore applications and there was no available information saying it did not support Tango. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://rawgit.com/jeromeetienne/AR.js/master/aframe/examples/tango-demo.html
Create a simple demo with the provided code in that link
Test it on a Tango enabled device.

**What is the expected behavior?**
Tapping on a surface should spawn a box in the scene, on the surface.

**If this is a feature request, what is motivation or use case for changing the behavior?**
This is not a feature request

**Please mention other relevant information such as the browser version, Operating System and Device Name**
I'm using the latest Chrome browser on Android, current chrome version is 68.0.3440.85 on Android 8.1.0 - Pixel 2 XL phone.

**Comment by RandomCouch** [comment]
Extra information, I had trackingMethod set to 'best' - when I set it to 'tango' I get a page with an image and the text "Remix" on top left.

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity. Please open a new, updated issue if the problem or the question is still relevant.
