### ISSUE TITLE
Only google chrome can smoothly carry out NFT

### ISSUE THREAD

**Issue by zonglang** [jeromeetienne/AR.js#394]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Other browsers than chrome are very slow when performing NFT recognition.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
NFT runs smoothly on every browser
**If this is a feature request, what is motivation or use case for changing the behavior?**
Make mobile phone webar widely used
**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by javismiles** [comment]
hey, do you have a demo example of NFT  working for chrome? thank you very much

**Comment by nicolocarpignoli** [comment]
ar.js is not supporting NFT at the moment
