### ISSUE TITLE
Packages are not specific for import in Node.js

### ISSUE THREAD

**Issue by josephrexme** [jeromeetienne/AR.js#396]
Is it just me or the major 3 classes cannot be imported in node.js i.e `THREEx.ArToolkitSource`, `THREEx.ArToolkitContext`, and `THREEx.ArMarkerControls`. @jeromeetienne it looks like the package was just published to npm without any actual exports of required modules. Is this something you're aware of? Is it open to contributions?

**Comment by josephrexme** [comment]
Made a node compatible version here https://www.npmjs.com/package/node-ar.js . @jeromeetienne I'd really love it to be one same thing as the ar.js package so I'll send in a PR and we can discuss how I can collaborate better if there's an issue with how I've structured the code

**Comment by evhan55** [comment]
+1. I would also like to use ar.js in Node.

**Comment by josephrexme** [comment]
I have never used A-Frame and I can't say for sure but I can look into that and get it to work for A-Frame

**Comment by evhan55** [comment]
Thanks for replying!
I actually ended up just putting the scripts in the head tag of my site, instead of using node.  That way I was able to use AR.js and AFrame together and not worry about including the modules with node for now.
