### ISSUE TITLE
Webcam Error NotSupportedError Only secure origins are allowed

### ISSUE THREAD

**Issue by filippomarra** [jeromeetienne/AR.js#399]
**Do you want to request a *feature* or report a *bug*?** 
Report a Bug

**What is the current behavior?** 
I made an example app following the tutorials found on this link: https://medium.com/chialab-open-source/how-to-deliver-ar-on-the-web-only-with-a-qr-code-e24b7b61f8cb.
The technologies I used are Ionic3 and AR.js. 
I'm having a problem with my camera acquisition on external link given by terminal when I do the command "ionic serve". 
In particular it gives me this error:
"Webcam Error 
Name: NotSupportedError 
Message: Only secure origins are allowed".

**If the current behavior is a bug, please provide the steps to reproduce.**
I did "Ionic serve" from my terminal and it works on my localhost from the PC, but with external links it gives me the error that I reported before.

**What is the expected behavior?**
The camera should open to scan a marker generated by me and it should open an image to test that the AR is working fine.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
I'm using Ionic3, Google Chrome from the PC and I have a Huawei P10 Lite device with Android 8 installed.

**Comment by mnutsch** [comment]
This error message occurs when trying to access user media without HTTPS. 

Try replacing HTTP with HTTPS in your URL and see if that resolves the issue.

**Comment by filippomarra** [comment]
I tried to replace HTTP with HTTPS in the URL but It doesn't work. I think that is needed to change some options in Ionic to serve my app in HTTPS instead of HTTP, does anyone know how can I do this?

**Comment by MVictorM** [comment]
@filippomarra it works on mozilla firefox, if you don't want to create a TSL/SSL certificate

**Comment by frontavity** [comment]
I found a really good solution fixing it. You can forward your localhost with ngrok.io to an only link, even with authentication. I works perfect when using https.
