### ISSUE TITLE
AR.js logo proposal

### ISSUE THREAD

**Issue by tentone** [jeromeetienne/AR.js#4]
Hi

I made this proposal for a logo for this library.

Any suggestions for improvement are welcome.

![capture](https://cloud.githubusercontent.com/assets/9158354/23149015/ff0f81d6-f7e0-11e6-839d-6efa52875318.JPG)

PNG file without background [here](https://cloud.githubusercontent.com/assets/9158354/23148913/6f3e4a2e-f7e0-11e6-98cc-a6feb0817c77.png)

Cumps

**Comment by bit2shift** [comment]
Needs more Hiro.

**Comment by jeromeetienne** [comment]
@tentone i love it! thanks for taking this initiative

yep if we could put a mention of hiro marker, it would be a nice touch. but no requirement here. 

hmm im wondering 'what if i put this logo, in my augmented reality content ?". The white of the letters may be hard to see, if you put reality video behind. Could we have an outlined version ?

**Comment by tentone** [comment]
@jeromeetienne 

Youre welcome, im here to help ;)

Changed to the hiro marker instead of the qr marker, and created an outined version of the logo for white backgrounds, what do you think? :)

![arjs_outline](https://cloud.githubusercontent.com/assets/9158354/23170617/c28ff1ca-f847-11e6-8d65-37b4c4303d5b.png)

![arjs](https://cloud.githubusercontent.com/assets/9158354/23170618/c2a08eae-f847-11e6-8507-cabc84092651.png)

**Comment by bit2shift** [comment]
RIP whoever opens this issue on mobile.
Those 20K though.

**Comment by tentone** [comment]
@bit2shift 

Sorry my bad, changed in the comment above to links instead!

**Comment by jeromeetienne** [comment]
seems perfect to me! merging it :)

**Comment by jeromeetienne** [comment]
Are you ok to release them under MIT license (license of this project) ?

i guess it was implict, but i have to ask :)

**Comment by tentone** [comment]
yes, of course :)
