### ISSUE TITLE
The video does not start

### ISSUE THREAD

**Issue by mariorossi2018** [jeromeetienne/AR.js#400]
I wrote this code:

<script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js"> </script>
  
    <a-scene embedded arjs>
         <a-assets>
                <video id="video" autoplay loop="true" src="./a.mp4">
         </a-assets>

  	<a-marker preset="hiro">
	  <a-video src="#video" width="8" height="4.5" position="0 1 -1"></a-video>
  	</a-marker>
  	<a-entity camera></a-entity>
    </a-scene>

Only one image appears but the video does not start.
What am I doing wrong?

Thank you in advance

**Comment by chan51** [comment]
Hey @anilachary, I tried your way. Still it's not working for me. I'm trying on mobile Mozilla Firefox. I'm getting black screen when getting camera over marker. No sound is coming and no video is playing.  Can you tell me what wrong I'm doing.

I'm attaching my html file with script tag in it.
[demo8.txt](https://github.com/jeromeetienne/AR.js/files/2712457/demo8.txt)

**Comment by anilachary** [comment]
> Hey @anilachary, I tried your way. Still it's not working for me. I'm trying on mobile Mozilla Firefox. I'm getting black screen when getting camera over marker. No sound is coming and no video is playing. Can you tell me what wrong I'm doing.
> 
> I'm attaching my html file with script tag in it.
> [demo8.txt](https://github.com/jeromeetienne/AR.js/files/2712457/demo8.txt)

> TRY THIS CODE

<!doctype HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

    <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
    <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script>
    <script src="https://cdn.rawgit.com/donmccurdy/aframe-extras/v4.1.2/dist/aframe-extras.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        AFRAME.registerComponent('vidhandler', {
            init: function() {
                this.toggle = false;
                this.vid = document.querySelector("#vid");
                this.vid.pause();
            },
            tick: function() {
                if (this.el.object3D.visible == true) {
                    if (!this.toggle) {
                        this.toggle = true;
                        this.vid.play();
                    }
                } else {
                    this.toggle = false;
                    this.vid.pause();
                }
            }
        });

        function refrespage() {
            location.reload();
        }

        function playvid() {
            vid.play();
        }
    </script>
    
</head>

<body style="margin : 0px; overflow: hidden;">
    <a-scene embedded artoolkit='sourceType: webcam; detectionMode: mono; maxDetectionRate: 60; canvasWidth: 200; canvasHeight: 200'>
        <a-assets>
            <video preload="auto" id="vid" poster="ANY IMAGE PATH (THUMBNAIL)" response-type="arraybuffer" loop="false" crossorigin webkit-playsinline playsinline controls>
                <source  src="VIDEO PATH">
                <img src="ANY IMAGE PATH (THUMBNAIL)"> Your browser does not support Or Else Please Click Reset Button.
            </video>
        </a-assets>
        <a-marker id="memarker" type="pattern" url="MARKER PATH (Eg:HIRO)" vidhandler>
            <a-plane position='0 0.1 0' rotation="-90 0 0" material='transparent:true;src:#vid' controls></a-plane>
        </a-marker>
        <a-entity camera></a-entity>
    </a-scene>
    <div class="footer">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pull-left">
                <div class="onebleft">
                    <button onclick="vid.playvid()" class="btn btnskips">Play (CHROME)</button>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pull-right">
                <div class="onebright">
                    <button onclick="refrespage()" class="btn btnskips">Refresh</button>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

**Comment by cann1132** [comment]
@anilachary I've tried on android, not working

**Comment by jamess922** [comment]
@anilachary  Hi, I made a webm video with alpha and tried out ,video could paly on android but no Transparent effect，and could not play on ios only black

**Comment by jacogaz** [comment]
I actually tried your code, @anilachary, it worked for a few times but then it displayed a black screen on android device on firefox. 
I tried on my local server, and on a remote server and it also works.
I also tried on mobile safari and it displays a black screen. On iOS (firefox) it throws me an WebRTC issue-! navigator.mediaDevices not present in your browser...
Do you know why this happens?
The code is the same I just added an alpha .webm video.

**Comment by nicolocarpignoli** [comment]
Try to run the app ALWAYS under HTTPS OR on localhost.
Maybe security policies from browsers.
If errors shows again, even on HTTPS, tell us

**Comment by jacogaz** [comment]
I did it, I run it under HTTPS and localhost, both, and it still happens... 

PS: I just realized the latest version of ar.js and a-frame does not support alpha video (.webm), it displays the video with a black background behind the sillouette. If I use ar.js (version: 1.6.0)and a-frame(version: 0.8.2) doesn't happen.

**Comment by jacogaz** [comment]
> I did it, I run it under HTTPS and localhost, both, and it still happens...
> 
> PS: I just realized the latest version of ar.js and a-frame does not support alpha video (.webm), it displays the video with a black background behind the sillouette. If I use ar.js (version: 1.6.0)and a-frame(version: 0.8.2) doesn't happen.


Update: On mac (Safari) It let me access to my camera but it displays a black screen instead of the video...
I solved the android issue that played the video with a black background by changing the version of ar.js and a-frame I was using...
Now I'm facing this black screen issue... any help?

Thank you

**Comment by debayanj** [comment]
the issues is on mobile its not detecting the marker on first time, it detects on third fourth time and then plays video . help me on this. 
by collecting all related implementation of ar js on desktop and mobile using camera this code is working..


<!doctype HTML>
<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

    <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
    <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script>
    <script src="https://cdn.rawgit.com/donmccurdy/aframe-extras/v4.1.2/dist/aframe-extras.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    


  <script src="https://rawgit.com/mayognaise/aframe-gif-shader/master/dist/aframe-gif-shader.min.js"></script>
  
  
    <script>
        AFRAME.registerComponent('vidhandler', {
            init: function() {
                this.toggle = false;
                this.vid = document.querySelector("#vid");
                this.vid.pause();
            },
            tick: function() {
                if (this.el.object3D.visible == true) {
                    if (!this.toggle) {
                        this.toggle = true;
                        this.vid.play();
                    }
                } else {
                    this.toggle = false;
                    this.vid.pause();
                }
            }
        });

        function refrespage() {
            location.reload();
        }

        function playvid() {
            vid.play();
        }
    </script>
    
</head>

<body style="margin : 0px; overflow: hidden;">
    <a-scene embedded artoolkit='sourceType: webcam; detectionMode: mono; maxDetectionRate: 60; canvasWidth: 200; canvasHeight: 200'>
        <a-assets>
            <video preload="auto" id="vid" poster="images/33.jpg" response-type="arraybuffer" loop="false" crossorigin webkit-playsinline playsinline controls>
                <source  src="videos/headvideo.webm">
                <img src="images/33.jpg"> Your browser does not support Or Else Please Click Reset Button.
            </video>
        </a-assets>
        <a-marker id="memarker" type="pattern" url="pat/pattern-logo.patt" vidhandler>
            <a-plane position='0 0.1 0' rotation="-90 0 0" material='transparent:true;src:#vid' controls></a-plane>
        </a-marker>
        <a-entity camera></a-entity>
    </a-scene>
    <div class="footer">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pull-left">
                <div class="onebleft">
                    <button onclick="vid.playvid()" class="btn btnskips">Play (CHROME)</button>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pull-right">
                <div class="onebright">
                    <button onclick="refrespage()" class="btn btnskips">Refresh</button>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

**Comment by merowell** [comment]
I've tried the code provided by @anilachary and it works great-- I can finally get the marker to trigger a video with alpha channels (with the exception of some CORS issues).

But how can I make this code work with multiple videos? I have three different markers that I'd like to trigger different movie files.

**Comment by Ajith-Kalyan** [comment]
@merowell  I have been trying the same.. did you find any solution ? @anilachary still I'm unable to display any video over the marker. can I find any demo ?
it'd be very helpful. Thanks.

**Comment by merowell** [comment]
@Ajith-Kalyan Sure! Let me know if this [glitch](https://glitch.com/~stack-57863016) helps. When I was having this problem, Piotr provided me with this code and it helped me a lot. If it's still not working for you I can direct you to my project file, I'll just have to update the readme real quick. Sorry, I'm pretty new to this stuff, but I hope I can help!

**Comment by E-Ismail** [comment]
@merowell What are the tracking images ? I want to try your application many thanks for sharing.

**Comment by asici2** [comment]
Please, can anyone help?
i am trying to use a-marker-camera instead of a-marker, because it is more stable and video keep on screen.
But when i use a-marker-camera, video doesn't autoplay and first frame is black. can anyone tell me what i'm doing wrong, please? here is the code:
        
```
<a-assets>
    <video crossorigin="anonymous" id="myvid" controls="true" loop="true" play="true" type="video/mp4" src="https://asici2.000webhostapp.com/video.mp4"> </video>
</a-assets>


<a-marker-camera vidhandler preset="custom" type="pattern" url="https://asici2.000webhostapp.com/PATT/marker.patt">
     <a-video  src="#myvid" position="0 0.3 0" rotation="-90 0 0" play="true"  width=2 height=1.3 >
     </a-video>
    </a-marker-camera>
<a-entity camera></a-entity>
</a-scene>
```
