### ISSUE TITLE
Detect Camera Position in the AR environment relative to the marker

### ISSUE THREAD

**Issue by aj019** [jeromeetienne/AR.js#402]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently there is no way to calculate the camera's coordinate relative to the marker
**If the current behavior is a bug, please provide the steps to reproduce.**

I am using a-camera-static that makes the center of my marker as the coordinate (0,0,0). Now if i place a 3d entity and set its position to (0,0,0). its going to load over the marker. But what if i want to place the object near the device through which the user is looking at the AR experience.

**What is the expected behavior?**

The expected behaviour would be to calculate the coordinate of the camera relative to the marker based on its position. And an update method that updates the coordinate when the user moves the camera. Once we know the coordinates of the camera we can position objects relative to the camera's position

**If this is a feature request, what is motivation or use case for changing the behavior?**
For eg :- i want to make a shooting game in which my monster is on the marker and i want to shoot bullets at it using my phone/device from different angles. If there is any way to achieve this please let me know.

**Please mention other relevant information such as the browser version, Operating System and Device Name**

Device Name : One Plus 6

**Comment by janpio** [comment]
Can't you give your camera an `id`, e.g. `camera` and then read its WorldPosition with `document.getElementById('camera').object3D.getWorldPosition()`? There is a `look-at` component with an example at https://github.com/supermedium/superframe/blob/master/components/look-at/examples/basic/index.html that has an object looking at the camera. Maybe this works in AR as well.

**Comment by Vitthal98** [comment]
@aj019 were you able to achieve what you mentioned above ?
We are trying to create a mobile based R platform that can be used to visualize MRI slices. For that, we need to calculate distance of phone from marker so that we can display the appropriate slice accordingly. We needed some help in that matter. Did the solution given by @janpio work?

**Comment by nicolocarpignoli** [comment]
Closing this issue due to dismission of this repository. New repository of AR.js will be up at https://github.com/AR-js-org/AR.js/

Feel free to re-open the issue there if still valid.
