### ISSUE TITLE
Are you planning on writing an Api document?

### ISSUE THREAD

**Issue by FateRiddle** [jeromeetienne/AR.js#404]
The Readme contains all sorts guides and examples, but surprisingly no official documentation.

Do you plan to write an official "getting started" guide + full api document?

**Comment by nicolocarpignoli** [comment]
Hi @FateRiddle 
Yes, we have in plan to release an official Wiki and a better Readme, with more working examples.
Unfortunately this takes time, but this is on top of our priorities. 
If someone is willing to help it is possible to show up here: https://github.com/jeromeetienne/AR.js/issues/376
