### ISSUE TITLE
Area marker type is not working

### ISSUE THREAD

**Issue by gftruj** [jeromeetienne/AR.js#405]
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**
Area marker in ar.js aframe build is not working.
Tried to make them work while anwsering[ this so question](https://stackoverflow.com/questions/51850930/a-frame-ar-js-multiple-markers-boxes).

**If the current behavior is a bug, please provide the steps to reproduce.**
I try making a `<a-marker type="area">`
This may be against the docs, but it triggers the `markersAreaEnabled :true` which seems to be a step in the right direction.

I click on `LEARN-NEW-MARKER-AREA` - it redirects me to the learner website.
If all presets (hiro, kanji, A, B, C, F) are present - learning switches from "in progress" to "DONE".
![image](https://i.stack.imgur.com/Ln0f2.png)

Then i click either on the "pause" icon, or just on the screen. It redirects me back to my website, while i think the JSON file with the area is stored in localStorage.

But when i click on the "toggle-marker-helper", ar.js seems to recognize ONLY the hiro marker.
Moreover, when my camera doesn't see the hiro marker (but sees the rest of them) the aframe entities dissapear, which seems to be proof only `hiro` is being the anchor.
![image2](https://i.stack.imgur.com/791Of.png)

My experiments were done on this [glitch](https://glitch.com/edit/#!/aframe-ar-area?path=index.html:18:0).

**What is the expected behavior?**
The aframe entity seen when any of the `area` elements are seen by the camera.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Windows 10, Firefox 61.0.2 (64 bit)

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity. Please open a new, updated issue if the problem or the question is still relevant.

**Comment by simonbq** [comment]
Please reopen this issue if nothing has been done to fix it. I subscribed to the thread last time I tried to use an area marker (v0.9.0) and it didn't work.

**Comment by simonbq** [comment]
Please reopen this issue if it hasn't been investigated and fixed. Last time I tried (aframe v0.9.0) I ended up at this thread and subscribed for updates since the issue was still in effect.

**Comment by gftruj** [comment]
I'll try repeating all steps again this week. Probably will end up making a new issue, but maybe some new pieces of information will pop up. Also i wanna check out what happens under the hood when the pattern is set to `area` (especially these settings: https://github.com/jeromeetienne/AR.js/blob/master/aframe/src/component-anchor.js#L101-L104)

**Comment by gftruj** [comment]
Took me a while + a long run of the GoTG soundtrack, but I think I've figured out why it wasn't working with the glitch example. The glitch is working properly now btw, same link but you can check it out [here](https://glitch.com/~aframe-ar-area).

 I wasn't quite aware, that the "area-learning" is happening and saving on another domain - `ARjs.Context.baseURL = 'https://jeromeetienne.github.io/AR.js/three.js/'` strictly speaking.

I had to override it:
`ARjs.AnchorDebugUI.MarkersAreaLearnerURL = "learner.html"`
and copy the learner html from the examples. Then the area save file will be properly read from the localStorage.

I've updated my SO anwser, though I think I may be overcomplicating this.

@nicolocarpignoli thanks, the issue can be closed 🎉

**Comment by nicolocarpignoli** [comment]
@gftruj I was aware of such references, maybe this new PR will help: https://github.com/jeromeetienne/AR.js/pull/549

**Comment by nicolocarpignoli** [comment]
which file contained the reference? is it in modified files on the PR linked above?

**Comment by gftruj** [comment]
@nicolocarpignoli i don't see the learner.html in [this](https://github.com/jeromeetienne/AR.js/pull/549/commits/2e8b5cfcb5e68168683ee2a455fe0e814d6e133e) commit. I can let you know when i get home, but i imagine two things could make things easier for the user:
- relative paths like you did in #549 - with addition to a custom learner URL in the aframe schema
- the area markers set seem to be fixed by now. Source [here](https://github.com/jeromeetienne/AR.js/blob/master/three.js/src/markers-area/threex-armultimarkerutils.js#L96-#L160). I would love to expose it, so the user could provide easily his own array of markers. Something like type + urlArray.

If these are not done (i may be missing something yet) I could try to make a PR. Or at least a decent tutorial on using this :smile: 

Also i may be too fixated on the learner site, maybe it would be easier to use the actual 'learning' code instead of the entire learner.html.

**Comment by gftruj** [comment]
I've found the reference [here](https://github.com/gftruj/AR.js/commit/a87aad24c3eae58ac7cb90441fe5aa138d931ae7).

**Comment by nicolocarpignoli** [comment]
If you can fix that on a PR it would be great!
