### ISSUE TITLE
Pass an HTML element to initialize AR.js container

### ISSUE THREAD

**Issue by b-z** [jeromeetienne/AR.js#407]
**Do you want to request a *feature* or report a *bug*?**

Yes, a feature 😃

**What is the current behavior?**

When using Three.js, the canvas and video tag are appended to `document.body` directly.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Pass an HTML element as a parameter to initialize the container of AR.js.

**If this is a feature request, what is motivation or use case for changing the behavior?**

To make it more flexible.

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by b-z** [comment]
And also, in `ARjs.Source.prototype.onResizeElement`,

> var screenWidth = window.innerWidth
> var screenHeight = window.innerHeight

Using `window` instead of a certain element is confusing..

**Comment by nicolocarpignoli** [comment]
"old" issue but still useful in my opinion..someone has time for this?

**Comment by cmcfadden** [comment]
Hey @nicolocarpignoli - I'm thinking about handling this request, as I need it for an app I'm working on.  Do you have any preferences on how it's implemented? I'm still getting familiar with A-frame and threeJS, so I'm not sure what the preferred way to handle configuration for something like this is.

**Comment by nicolocarpignoli** [comment]
Go forward as you like, I will review your PR eventually.

**Comment by nicolocarpignoli** [comment]
we can continue this discussion at: https://github.com/AR-js-org/AR.js/issues/22
