### ISSUE TITLE
Crashing with Array buffer allocation

### ISSUE THREAD

**Issue by RogelioHIT** [jeromeetienne/AR.js#409]
**Do you want to request a *feature* or report a *bug*?**
Hey guys, I Want to Report a bug.

**What is the current behavior?**
Crashes after refreshing the webpage, due to a Uncaught RangeError.

**If the current behavior is a bug, please provide the steps to reproduce.**
The steps are to just load the basic 10 lines example, on chrome for mobile devices, and in Android cellphones, I have a Moto g6 currently. Refresh the page several times, and the error will appear, I'm adding a screenshot of the error, I used the remote devices option on chrome.
![captura de pantalla 2018-09-06 a la s 10 13 06](https://user-images.githubusercontent.com/8886223/45171390-dd0c9e00-b1c7-11e8-975e-61a990caf56d.png)

As a note, it happens on both aframe-ar.js and ar.js

**What is the expected behavior?**
Not crashing or at least catch the error, and pop out an alert telling you what happened.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Browser: Chrome for mobile 68.0.3440.91
Operating system: Android 8.0.0
Device: Moto g6

**Comment by nicolocarpignoli** [comment]
obsolete, please re open if it shows up again

**Comment by deepakgd** [comment]
I am facing this issue right now. currently i am using 1.5.5 version
