### ISSUE TITLE
Rotating phone from portrait to landscape mode, AR object disappears.

### ISSUE THREAD

**Issue by rvisharma** [jeromeetienne/AR.js#411]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
 I am using Aframe 0.8.2 and aframe-ar.js 1.6 version. Facing issue while switching from portrait to landscape mode: - AR object (displayed on top of marker) disappears. However, if I move out the marker from the camera view and bring it back, the AR object appears again. (Present in all devices).

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Open https://jeromeetienne.github.io/AR.js/aframe/examples/mobile-performance.html on iPhone/Android phone in portrait mode and scan the marker.
2. Switch to landscape mode while the marker is in camera view.
3. The ar object which is displayed on top of the marker disappears.
(Attached screen recording- https://drive.google.com/file/d/1mesE4eVo4kf8TSoivCg8stHcoE2zcCZw/view)

**What is the expected behavior?**
While switching to landscape mode, the ar object should remain visible.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
aframe - version 0.8.2
aframe-arjs- version 1.6.0
iPhone (6Plus)
	Browser - Safari - (with multiple tabs open) Version - 11.4 and 11.4.1 
Android - OnePlus 5T
	Chrome - 68.0.3440.91

**Comment by nicolocarpignoli** [comment]
also: https://github.com/jeromeetienne/AR.js/issues/334

**Comment by nicolocarpignoli** [comment]
Is this still happening? otherwise I'll close
