### ISSUE TITLE
issue- navigator.mediadevices not present in your browser

### ISSUE THREAD

**Issue by chenyunbbs** [jeromeetienne/AR.js#415]
**Do you want to request a *feature* or report a *bug*?**
     Yes  Report error

**What is the current behavior?**
 I am browsing the webAr page error on WeChat : issue- navigator.mediadevices not present in your browser
**If the current behavior is a bug, please provide the steps to reproduce.**
  open webAr view  error :issue- navigator.mediadevices not present in your browser

**What is the expected behavior?**
Expect to open the camera

**If this is a feature request, what is motivation or use case for changing the behavior?**
Develop webAR
**Please mention other relevant information such as the browser version, Operating System and Device Name**
 iPhone : 11.4.1 version 
 Browser:  a Apple iPhone running IOS 11.4.1
WeChat ： 6.7.2  version

**Comment by nicolocarpignoli** [comment]
Hi
not related to AR.js. Please see https://stackoverflow.com/questions/49607086/unable-to-access-camera-feed-in-wechat-browser

**Comment by hanbi918** [comment]
@chenyunbbs  Hi, I meet same error ,do you solve this problem? Please tell me,thanks!

**Comment by humbertobeltrao** [comment]
@hanbi918 Hi, I've just added https:// followed by the URL itself, and it's worked properly.

**Comment by chloezql** [comment]
> @hanbi918 Hi, I've just added https:// followed by the URL itself, and it's worked properly.

This actually works!

**Comment by Binec** [comment]
Hello, I´ve already added the https:// in the url but it sends me a ERR_SSL_ERROR, I don´t know if I have to install a certificate  or something but the first time I did it it works perfectly. Please let me know what I'm missing.

**Comment by humbertobeltrao** [comment]
Have you tried to clear your browser's cookies and cache data?

**Comment by Binec** [comment]
> Have you tried to clear your browser's cookies and cache data?

yes I´ve already erased it, I´m using chrome in an android and it keeps me sending the ERR_SSL_ERROR with the https:// and with out the "s" the  webcam Error: issue- navigator.mediaDevices not present in your browser :/

**Comment by humbertobeltrao** [comment]
> > Have you tried to clear your browser's cookies and cache data?
> 
> yes I´ve already erased it, I´m using chrome in an android and it keeps me sending the ERR_SSL_ERROR with the https:// and with out the "s" the webcam Error: issue- navigator.mediaDevices not present in your browser :/

A solution to a similar issue was posted here: [https://www.gitmemory.com/issue/jeromeetienne/AR.js/463/503552278](url)
Hope it works for you as well.
