### ISSUE TITLE
a-marker-camera doesn't fire markerFound/markerLost events correctly.

### ISSUE THREAD

**Issue by LaurenceNairne** [jeromeetienne/AR.js#418]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
markerFound and markerLost events are only fired correctly by *a-marker* elements. *a-marker-camera* element incorrectly fires a markerFound event when the program starts, and never fires a markerLost event.

From digging, I believe the reason for this is that when `changeMatrixMode === cameraTransformMatrix`, it sets the parent to be `camera` instead of `scene`. In arjs-anchor.js, it sets `_this.object3d.visible` to equal `_this.object3d.parent.visible`, so `_this._arAnchor.object3d.visible` is never anything but true.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Open https://codepen.io/laurencenairne/full/MqLapN/
2. Check the log, you will see one entry for 'markerFound marker'
3. Bring a Hiro marker in front of your camera, then remove it out of frame
4. No further events are triggered.
5. To check what I'm saying about `_this.el.object3d.visible` and `_this.el.sceneEl.object3d.visible` not updating, I added a console log at line 157 of component-anchor.js in my local version of your repo:

`console.log(this._arAnchor + "'s object3D is visible:" + this._arAnchor.object3d.visible);`

With <a-marker> you'll see this change from false to true as you present a Hiro marker. With <a-marker-camera> it will remain true no matter what you do.

**What is the expected behavior?**
I'd expect <a-marker-camera> to fire markerFound and markerLost events consistently just like <a-marker>.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Operating System and Device Name**
- Desktop PC (Windows 10)
- Chrome (v.69)

**Comment by LaurenceNairne** [comment]
As a workaround I've used a-marker and just nested my a-video element inside it which localises it's position to said marker.

**Comment by nicolocarpignoli** [comment]
Hi
if you have found the bug, and tested it, you can make a PR for that! We'll be glad to look forward to it :)

**Comment by accbjt** [comment]
This is what worked for me. If you wrap it the marker around a camera entity it will work like the a-marker-camera.
```
<a-entity camera look-controls>
  <a-marker markerhandler preset='custom' type='pattern' url='assets/patterns/marker.patt'>
     <a-entity obj-model="obj: #tree-obj; mtl: #tree-mtl"></a-entity>
  </a-marker>
</a-entity>
```
