### ISSUE TITLE
Can i create ar without marker image?I want to tracking the corner to show my mesh,is it possible?

### ISSUE THREAD

**Issue by SeanSure** [jeromeetienne/AR.js#420]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment]
Hi
Not currently. See https://github.com/jeromeetienne/AR.js/issues/190
