### ISSUE TITLE
can't make gltf work

### ISSUE THREAD

**Issue by labriata** [jeromeetienne/AR.js#421]
Hello, I've tried to load gltf models on ar.js - aframe following examples from multiple resources, but I have only failed...

See for example: https://lucianoabriata.altervista.org/jsinscience/arjs/armodeling/testgltf.html
which should display the duck model on a Hiro marker.

I'm sourcing:

`<script src="https://aframe.io/releases/0.7.0/aframe.min.js" </script>`

`<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>`

And then doing this in the marker (which works because I have another marker with some stuff on it):

<a-entity gltf-model="src:url(https://lucianoabriata.altervista.org/jsinscience/arjs/armodeling/duck.gltf)">
</a-entity>

I get this in the console:
components:gltf-model:warn THREE.GLTFLoader: Unable to parse model.

I've tried with gltf models version 1 and 2, they all fail...

Thanks for any help !

**Comment by nicolocarpignoli** [comment]
< gltf-model="src:url(https://lucianoabriata.altervista.org/jsinscience/arjs/armodeling/duck.gltf)"></a-entity>

**Comment by nicolocarpignoli** [comment]
Hi!
This line:
`<gltf-model="src:url(https://lucianoabriata.altervista.org/jsinscience/arjs/armodeling/duck.gltf)"></a-entity>`

try using this way of loading gltf files instead of yours:

```
<a-scene>
  <a-assets>
    <a-asset-item id="tree" src="tree.gltf">
  </a-assets>

  <!-- Using the asset management system. -->
  <a-gltf-model src="#tree"></a-gltf-model>

</a-scene>
```

**Comment by labriata** [comment]
Mmm not yet... with what ar.js and aframe versions does this work for you?

**Comment by labriata** [comment]
And sorry, since we are talking, can you suggest a gltf +associated bin file that you know works? Thanks a lot!

**Comment by labriata** [comment]
That works! I'll now try to find out why then! Thank you very much!
Luciano
