### ISSUE TITLE
clicking sometimes not firing on mobile on 3d object

### ISSUE THREAD

**Issue by javismiles** [jeromeetienne/AR.js#425]
good day, thanks to Nicolo , clicking is working now, and using fuse:false makes it work fast on mobile,
but still a problem left.
Using a simple 3d object like a box:

<a-marker markerhandler emitevents="true" cursor="fuse: false;rayOrigin: mouse" id="animated-marker" type='barcode' value='6'>
                
          <a-box id="animated-model" position='0 0.5 0' material='color: yellow;'></a-box>
			
        </a-marker>`

sometimes you see 3 of the faces of the cube, and clicking on two of them triggers the click, but one of the faces doesnt!
sometimes the biggest top face will not trigger the click but the other side smaller one does

stuff like that, why is this happening?

**Comment by nicolocarpignoli** [comment]
Hi @javismiles,
 you use the code that I used in this article right ? (https://medium.com/@nicolcarpignoli/how-to-handle-click-events-on-ar-js-86ddefa75720)

I don't have much time to investigating, but maybe we can enhance the checks on `event.js`, that are firing the action after catching the event.

I recently changed that check. Can you try your example using new logic in here ?  https://github.com/nicolocarpignoli/nicolocarpignoli.github.io/blob/master/ar-playground/events.js

Thanks and let me know if it solves or it improves something

**Comment by javismiles** [comment]
hey @nicolocarpignoli , yes I used that code,
I will test soon with your new code, thank u Nicolo ;)
will report back in here ;)

**Comment by forestfruit** [comment]
Hey @nicolocarpignoli , 
I really appreciate your work but I have the same problem. It looks like there are some small areas in which the click event is not recognized. Here is a quick demo with a a-box :

![issue](https://user-images.githubusercontent.com/46477029/50822500-c8811380-1329-11e9-858e-66de5606b92c.gif)

**Comment by forestfruit** [comment]
Hey @nicolocarpignoli ,
I really appreciate your work but I have the same problem. It looks like there are some small areas in which the click event is not recognized. Here is a quick demo with a a-box:

![issuefinal](https://user-images.githubusercontent.com/46477029/50824353-49420e80-132e-11e9-9f4d-5a26eadb7bc5.gif)

**Comment by forestfruit** [comment]
Hey @nicolocarpignoli ,
I really appreciate your work but I have the same problem with the updated EventListener. It looks like there are some small areas in which the click event is not recognized. Here is a quick demo with a a-box:

![demo](https://user-images.githubusercontent.com/46477029/50824504-adfd6900-132e-11e9-9f68-6dc6b6778d7e.gif)

**Comment by BottlecapDave** [comment]
I am also having issues with click events on models. I have a scene with multiple models from a single marker. I'm wanting to click on the models to select data, but the click detection does not seem to be working properly. Is click detection limited to a part of the screen?

I'm using a-marker instead of a-marker-camera.

**Comment by droid001** [comment]
I've got a similar scenario, multiple objects on a single marker. I found that click events were functioning only really in the center of the screen and was less reliable to the edges. Had to abandon this approach and continued with a gaze cursor instead. Would be nice to have a working click event solution though.

**Comment by nicolocarpignoli** [comment]
Hi to everybody
you can see details about my custom solution for click event handling here.
https://github.com/nicolocarpignoli/nicolocarpignoli.github.io/blob/master/ar-playground/events.js

```
AFRAME.registerComponent('markerhandler', {

    init: function() {
        const animatedMarker = document.querySelector("#animated-marker");
        const aEntity = document.querySelector("#animated-model");

        // every click, we make our model grow in size :)
        animatedMarker.addEventListener('click', function(ev, target){
            const intersectedElement = ev && ev.detail && ev.detail.intersectedEl;
            if (aEntity && intersectedElement === aEntity) {
                const scale = aEntity.getAttribute('scale');
                Object.keys(scale).forEach((key) => scale[key] = scale[key] + 1);
                aEntity.setAttribute('scale', scale);
            }
        });
}});
```

I know it is not a perfect solution :) Unfortunately, I have no time for tuning this.
If someone has got time, hopefully the fix is not so hard as you can think

It is about changing 

```
  const intersectedElement = ev && ev.detail && ev.detail.intersectedEl;
            if (aEntity && intersectedElement === aEntity) {
```

investigate what data `ev.detail` contains and try to find out if there is some better data to use instead of `intersectedEl`. If you need support i can help but got no time to find the solution of this by myself

good luck!

**Comment by nicolocarpignoli** [comment]
Hi @droid001 , I am trying to enhance my click events implementation. In your post above, what you
with a solution with "gaze cursor " ? Can you tell me more and provide some example ?
Thank you very much

**Comment by droid001** [comment]
@nicolocarpignoli: What I meant about using a [gaze cursor](https://aframe.io/docs/0.9.0/components/cursor.html) is actually abandoning any attempts to catch click/tap events in 3D space. The cursor is attached to the camera which results it being in the centre of the screen and the user has to then click objects with her gaze.
Code for a gaze cursor would be:
```
<a-entity position="0 0 0">
  <a-entity camera look-controls wasd-controls>
    <a-entity position="0 0 -3"
              geometry="primitive: ring; radiusInner: 0.1; radiusOuter: 0.2;"
              material="color: #f04661; shader: flat; opacity:0.2;"
              cursor="maxDistance: 30; fuse: true">
      <a-animation begin="click" easing="ease-in" attribute="scale"
           fill="forwards" from="0.2 0.2 0.2" to="1 1 1" dur="150"></a-animation>
      <a-animation begin="fusing" easing="ease-in" attribute="scale"
           fill="backwards" from="1 1 1" to="0.2 0.2 0.2" dur="1500"></a-animation>
    </a-entity>
  </a-entity>
</a-entity>
```

**Comment by droid001** [comment]
Could be that my problem had to do with what @lcorbelino has mentioned about adding [the raycaster after the scene is loaded](https://github.com/jeromeetienne/AR.js/issues/439#issuecomment-479160954).

**Comment by nicolocarpignoli** [comment]
@droid001 sorry I don't understand. For 'gaze cursor' you men exactly the same approach I used [here](https://medium.com/chialab-open-source/how-to-handle-click-events-on-ar-js-58fcacb77c4)? Because I have exactly the same problems (the click are really only sensible on the centre of the screen).

**Comment by nicolocarpignoli** [comment]
https://github.com/jeromeetienne/AR.js/issues/249
