### ISSUE TITLE
get input stream with ar.js

### ISSUE THREAD

**Issue by tcwyjno1** [jeromeetienne/AR.js#43]
Sorry to disturb.
But I download the source code and try to run in local.
I put my code in a server just like tomcat or nodejs.
I visited 
http://localhost/ar-master/three.js/examples/worker_artoolkit/examples/cameratransform.html
It can open my computer camera and show how three.js works.
I still have a question.  If ar.js can analyse what my camera has shot.
Can I get the input stream which came from my camera  shot.
Thanks very much.

**Comment by jeromeetienne** [comment]
see arToolkitSource.domElement. this is the dom element which is the camera source for ar.js
