### ISSUE TITLE
Custom marker don`t work

### ISSUE THREAD

**Issue by devalexandre** [jeromeetienne/AR.js#434]
**bug**

**What is the current behavior?**
I'm try use a custom marker, and use a AR.js default for do teste, but don`t work

**If the current behavior is a bug, please provide the steps to reproduce.**
i'm generate a custom in [generator marker](https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html)
when I try use don't work

```js

<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false; patternRatio: 0.50' >
					<a-marker-camera type='pattern'  patternUrl="./assets/pattern-marker.patt">
						<a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
						</a-marker-camera>
				</a-scene>
```

**What is the expected behavior?**
use a custom marker

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Mac OS / google chrome

**Comment by nicolocarpignoli** [comment]
Hi,
I suggest you to use a-marker instead of a-marker-camera, and to use remote urls, for example for patternUrl property.
I make it simple giving you the example provided in this article I wrote: check the HTML embedded part and take inspiration on that working example :) Let me know if it helps


https://medium.com/chialab-open-source/ar-js-the-simpliest-way-to-get-cross-browser-ar-on-the-web-8f670dd45462

**Comment by devalexandre** [comment]
I read your article, congratulation , but I alter and don't work 

```html
			<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: true; patternRatio: 0.50' >
					<a-marker type='pattern'  patternUrl="https://raw.githubusercontent.com/devalexandre/arpreact/master/assets/indev.patt">
						<a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
						</a-marker>
						<a-entity camera></a-entity>
				</a-scene>
```

git of project (https://github.com/devalexandre/arpreact)

in src/assets have a indev.patt and png is indev.png, I try all but nothing work

**Comment by nicolocarpignoli** [comment]
I follow your link but I can't find the html that embeds a-marker elements. Can you please link me the direct resource (the .html?) thanks

edit: maybe you change the file. Anyway let me know so I Can try myself your code

**Comment by devalexandre** [comment]
Hi Nicolo, it is a code

https://github.com/devalexandre/arpreact/blob/master/index.js#L12

and .patt and .png in 
https://github.com/devalexandre/arpreact/tree/master/assets

this project  I`m using a preact if I use a hiro marker work, but if I try use a custom , dont work, you can run it project using npm i and after npm run dev

**Comment by nicolocarpignoli** [comment]
patternUrl='./assets/marker.patt' is still local. try removing patterRatio too.

**Comment by devalexandre** [comment]
don`t have patterRatio, I alter a url for git
but not work too
``` .html

			<a-scene embedded arjs='sourceType: webcam;'>
  	<a-marker type="pattern" patternUrl='https://raw.githubusercontent.com/devalexandre/arpreact/master/assets/marker.patt'>
            <a-box position='0 0.5 0' material='color: black;'></a-box>
  	</a-marker>
  	<a-entity camera></a-entity>
    </a-scene>

```

**Comment by droid001** [comment]
@devalexandre The marker seems to have low contrast. Maybe you can alter the background gray to rgb(240, 240, 240) as mentioned [here](https://github.com/jeromeetienne/AR.js/issues/216#issuecomment-346906569). That helped med with my custom markers.
Then I would change `patternUrl` to just `url`.
Example of my working code:
```
<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
    <a-marker type="pattern" url="/assets/static/images/markers/patt.g">
      <a-box position='0 0 0' material='opacity: 0.5; side:double; color:green;'></a-box>
    </a-marker>
    <a-camera-static/>
</a-scene>
```

**Comment by nicolocarpignoli** [comment]
yes also use 'url' instead of 'patternUrl' and add preset='custom' too. Marker is not good, removed that purple and use only black and grey as @droid001 suggested

**Comment by devalexandre** [comment]
thanks @nicolocarpignoli  and @droid001  it`s work I go write the article in pt-br show how use it, thank you boys :)

**Comment by PedroNan** [comment]
I'm trying to get a custom marker work but still can't. I considered using a gray background and type = "pattern" preset = "custom" but still not work. I'm using Glitch to host the code online, here is the code. I would appreciate some help! thanks.
````
<html>
  <head>
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>
    <script src="https://raw.githack.com/AR-js-org/studio-backend/master/src/modules/marker/tools/gesture-detector.js"></script>
    <script src="https://raw.githack.com/AR-js-org/studio-backend/master/src/modules/marker/tools/gesture-handler.js"></script>
    <script>
      AFRAME.registerComponent("videohandler", {
        init: function() {
          var marker = this.el;
          this.vid = document.querySelector("#vid");

          marker.addEventListener(
            "markerFound",
            function() {
              this.toggle = true;
              this.vid.play();
            }.bind(this)
          );

          marker.addEventListener(
            "markerLost",
            function() {
              this.toggle = false;
              this.vid.pause();
            }.bind(this)
          );
        }
      });
    </script>
  </head>

  <body style="margin: 0; overflow: hidden;">
    <a-scene
      vr-mode-ui="enabled: false"
      loading-screen="enabled: false;"
      arjs="sourceType: webcam; debugUIEnabled: false;"
      id="scene"
      embedded
      gesture-detector
    >
      <a-assets>
        <video
          id="vid"
          src="https://cdn.glitch.com/d23324f0-e4d7-494a-ac8b-e4262f2248c9%2Fasset.mp4?v=1601426344133"
          preload="auto"
          response-type="arraybuffer"
          loop
          crossorigin
          webkit-playsinline
          autoplay
          muted
          playsinline
        ></video>
      </a-assets>

      <a-marker
        type="pattern"
        preset="custom"
        url="https://cdn.glitch.com/d23324f0-e4d7-494a-ac8b-e4262f2248c9%2Fmarker.patt?v=1601426315869"
        videohandler
        smooth="true"
        smoothCount="10"
        smoothTolerance="0.01"
        smoothThreshold="5"
        raycaster="objects: .clickable"
        emitevents="true"
        cursor="fuse: false; rayOrigin: mouse;"
        id="markerA"
      >
        <a-video
          src="#vid"
          scale="1 1 1"
          position="0 0.1 0"
          rotation="-90 0 0"
          class="clickable"
          gesture-handler
        ></a-video>
      </a-marker>

      <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
```
`
