### ISSUE TITLE
Your webpage is error 404. on Readme.md

### ISSUE THREAD

**Issue by AlbirrKarim** [jeromeetienne/AR.js#436]
**Do you want to request a *feature* or report a *bug*?**
Link error
On readme.md section "Examples"

![selection_053](https://user-images.githubusercontent.com/29292018/48308748-a2472d80-e59d-11e8-9309-347fef8eb887.png)

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment]
yea there is a PR in order to fix this and enhance readme. hopefully we will merge this very very soon :)

https://github.com/jeromeetienne/AR.js/pull/429
