### ISSUE TITLE
Unable to create marker for custom marker using AR.js Marker Traning 

### ISSUE THREAD

**Issue by sskadit** [jeromeetienne/AR.js#437]
If I use this kind of image for the AR.JS Marker Training the Patt file is absolutely rubbish.

I have followed all the blogs like how to create a custom marker.

Tell me how could I get the perfect patt file where it can recognise the image properly. 

![screenshot 2018-11-12 at 3 46 31 pm](https://user-images.githubusercontent.com/24460900/48341499-347d2d80-e693-11e8-8886-e04b84c8ab69.png)

**Comment by droid001** [comment]
@sskadit : You should only be reporting bugs on AR.js here. Ask your question on [Stackoverflow](https://stackoverflow.com/) and I'll help you out.

**Comment by droid001** [comment]
The trick is that the background should be rgb(240,240,240) and you should have an eye on the grid which is going to be produced. As you can see from the produced .patt file there are 16 values per row so if you have an image which is hitting that grid well then you're more likely to get a good recognition result.

<img width="496" alt="screen shot 2018-11-12 at 11 55 47" src="https://user-images.githubusercontent.com/7068571/48343325-5f0abe80-e672-11e8-9e74-7e15ddf39e2f.png">
![marker](https://user-images.githubusercontent.com/7068571/48343341-6b8f1700-e672-11e8-960f-e610885ff0f6.png)

Here's the svg I use  as a template for markers:

[marker-trainer.svg.zip](https://github.com/jeromeetienne/AR.js/files/2571624/marker-trainer.svg.zip)

**Comment by sskadit** [comment]
> @sskadit : You should only be reporting bugs on AR.js here. Ask your question on [Stackoverflow](https://stackoverflow.com/) and I'll help you out.

Thanks I have asked the stackover flow question 

https://stackoverflow.com/questions/53260343/ar-js-marker-not-training-properly

**Comment by sskadit** [comment]
Is there any image recognition like Vuforia capability with AR.JS

**Comment by sskadit** [comment]
> The trick is that the background should be rgb(240,240,240) and you should have an eye on the grid which is going to be produced. As you can see from the produced .patt file there are 16 values per row so if you have an image which is hitting that grid well then you're more likely to get a good recognition result.
> 
> <img alt="screen shot 2018-11-12 at 11 55 47" width="496" src="https://user-images.githubusercontent.com/7068571/48343325-5f0abe80-e672-11e8-9e74-7e15ddf39e2f.png">
> 
> ![marker](https://user-images.githubusercontent.com/7068571/48343497-d04a7180-e672-11e8-8c13-85ba55a722ce.png)
> 
> Here's the svg I use as a template for markers:
> 
> [marker-trainer.svg.zip](https://github.com/jeromeetienne/AR.js/files/2571624/marker-trainer.svg.zip)

Thanks for the help!! @droid001

**Comment by droid001** [comment]
@sskadit Not what I've seen while looking in the source code, but maybe someone on [Gitter](https://gitter.im/AR-js/Lobby) would know more about it.

**Comment by nicolocarpignoli** [comment]
use grey instead of white colors (with the black of course) and maybe I guess the image is too complex. try with another simplier image like the apple without the leaf. if it works, it's surely the 'too complicated' shape that your image has

**Comment by commentatorboy** [comment]
I have the same problem. 
I am creating a extremly simple marker. 
![letter](https://user-images.githubusercontent.com/1793964/49368268-87745e80-f6ee-11e8-852e-eef959454e99.png)

This is the pattern file
![image](https://user-images.githubusercontent.com/1793964/49368318-a4a92d00-f6ee-11e8-9abe-27a0d74e784c.png)

But currently it does not work.
I am using the following code:


`<!doctype HTML>
<html>
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js"> </script>
<script src="//cdn.rawgit.com/donmccurdy/aframe-extras/v4.2.0/dist/aframe-extras.min.js"></script>
  <body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs>
	  <a-assets>
	    <a-asset-item id="tree" src="bench.glb">
	  </a-assets>
  	<a-marker type='pattern' url='test.patt'>
  	 	<a-entity rotation="-90 0 0" material="shader: flat; color: red;" scale="0.01 0.01 0.01" gltf-model="#tree">
			<a-animation attribute="rotation"
				       dur="10000"
				       fill="forwards"
				       to="0 360 0"
				       repeat="indefinite"></a-animation>
  	 	</a-entity>
    	</a-marker>
  	<a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
`

**Comment by nicolocarpignoli** [comment]
@commentatorboy although it seems a simple image, this is not a 'simple marker'. try using only one of the letters, i.e. only the 'E' letter. 
to learn more about markers, please have a look here: https://medium.com/chialab-open-source/ar-js-the-simpliest-way-to-get-cross-browser-ar-on-the-web-8f670dd45462

**Comment by commentatorboy** [comment]
I found out that if you use a pixelated text font it is more likely to work.
I would recommend other people using pixelated text font too.
![tt](https://user-images.githubusercontent.com/1793964/49942518-cd4ad700-fee5-11e8-86d3-29d89ed49a8b.png)

@nicolocarpignoli  Thanks for the link.

**Comment by nicolocarpignoli** [comment]
Yes, problem was with the original image, 'too complex'. Nice to know this "pixeled text" thing. Thanks! 

I close as solved
