### ISSUE TITLE
Add Support for aruco markers

### ISSUE THREAD

**Issue by frastlin** [jeromeetienne/AR.js#438]
**What is the current behavior?**

AR.js doesn't support it.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**

Be able to detect small markers from a distance at any orientation.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I would love to see AR.js support aruco markers:
https://docs.opencv.org/3.1.0/d5/dae/tutorial_aruco_detection.html
These allow for small markers to be placed around an environment, viewed from a distance, and recognized at any orientation.
With these markers, one can literally view a room completely in AR, give one information about the target marker (where it is and what direction it is facing), and if one attaches markers to a stylus, one can point that stylus at an object and trigger events based on where that stylus is pointing to or touching on the object.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
N/A

**Comment by nicolocarpignoli** [comment]
this is deprecated with latest versions

**Comment by frastlin** [comment]
Latest versions of AR.js? I am not aware of any marker that is as accurate as Aruco markers.

**Comment by nicolocarpignoli** [comment]
AR.js supports:

- Hiro markers (artoolkit based)
- Pattern markers (artoolkit based)
- Barcode markers (artoolkit based)
- Location based 

Soon: NFT (artoolkit based)


Aruco markers were in the plans in the first phase of the project. We are talking of ~2 years ago. I only deleted code that was making the project heavier, it was useless code.

You can use pattern markers and barcode markers, similar to aruco ones.
