### ISSUE TITLE
Click area out of object on portrait mode

### ISSUE THREAD

**Issue by wama19** [jeromeetienne/AR.js#439]
I’m trying to handle click events refer to below page.
[https://github.com/nicolocarpignoli/nicolocarpignoli.github.io/blob/master/ar-playground/events.js](https://github.com/nicolocarpignoli/nicolocarpignoli.github.io/blob/master/ar-playground/events.js)

And changing position of 3D object.
But if phone in portrait mode, click area out of object.

![3puxy](https://user-images.githubusercontent.com/32360591/48784729-9a6a5480-ed26-11e8-925e-439e5f87d119.jpg)

aframe - version 0.8.0
aframe-arjs- version 1.6.0
iPhone (6s)
Browser - Safari
iOS 12.1

`<a-entity
            id="animated-model"
            gltf-model="#animated-asset"
            scale="3"
            position="-3 0 1"
            rotation="-90 0 0">
            </a-entity>`

` <script>
        AFRAME.registerComponent('markerhandler', {
            init: function() {
                const animatedMarker = document.querySelector("#animated-marker");
                const aEntity = document.querySelector("#animated-model");
                animatedMarker.addEventListener('click', function(ev, target){
                    const intersectedElement = ev && ev.detail && ev.detail.intersectedEl;
                    if (aEntity && intersectedElement === aEntity) {
                        alert("test");
                    }
                });
            }
        });
    </script>`

**Comment by lcorbelino** [comment]
I solve this problem by setting raycaster attribute after all the scene been load, this happen because the raycaster function gets the limits off the scene before its been resize in the browser, so the command getBoundingClientRect() used in a-farme.js set worng position to the raycaster canvas.

**Comment by nicolocarpignoli** [comment]
@lcorbelino it will be of huge help if you can share your code, .html and js, even a snippet, in order to understand. I try so many different things in order to make click events reliable, maybe your contribute can help us :)

**Comment by jrhaff** [comment]
> I solved this problem by setting raycaster attribute after all the scene has been load, this happen because the raycaster function gets the limits off the scene before its been resize in the browser, so the command getBoundingClientRect() used in a-farme.js set worng position to the raycaster canvas.

I am currently having the same issue, any buttons I have moved on the X-axis seem to have their clickable areas slightly moved closer to the center of the marker. This then happens to any buttons I have moved on the Y-axis when I either change the orientation of the marker or from portrait to landscape. 

 
I would love to see where and how you set the raycaster attribute after the scene is loaded.

**Comment by lcorbelino** [comment]
In fact what i do is wait the video from camera gets set in the html, since this is the last thing happen.

` AFRAME.registerComponent('markerhandler1', {
                init: function() {
                    this.tick = AFRAME.utils.throttleTick(this.tick, 500, this);       
                    },
                    tick: function(t, dt) { 
                       if(document.querySelectorAll("video")[1] !== undefined && segundo == true){
                                segundo = false;
                                var vv = document.querySelector('a-marker');
                                vv.setAttribute('raycaster',"objects: .clickable");
                                vv.setAttribute( 'cursor',"rayOrigin: mouse");
                                vv.setAttribute( 'cursor',"fuse: false");
                        }`

**Comment by nicolocarpignoli** [comment]
duplicate https://github.com/jeromeetienne/AR.js/issues/249
