### ISSUE TITLE
10 lines of html example not working

### ISSUE THREAD

**Issue by kholmgre** [jeromeetienne/AR.js#44]
The example at https://codepen.io/jeromeetienne/pen/mRqqzb is no longer working. I noticed it on monday 2017/04/17. No 3d-model is displayed when i showed a hiro-marker. 

Interesting to note is that the example at https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html is still working.

**Comment by jeromeetienne** [comment]
thanks for notifying me. i fixed it, it is working again, sorry for the inconvenience.

be sure to refresh your cache. tell me if you run in any more issue
