### ISSUE TITLE
tracking not smooth.

### ISSUE THREAD

**Issue by trusktr** [jeromeetienne/AR.js#441]
The rendering is 60fps on my device, but the tracking is laggy (when I move the phone and the object moves to the new location of the HIRO image).

Is it possible to improve this? Or will the marker image recognition always be laggy on mobile?

**Comment by trusktr** [comment]
Is it possible to use this with workers for image recognition? Or does it already do that? Any guidance would be much appreciated! Maybe we can also update the README.

**Comment by andreyrd** [comment]
I've been looking into ways to improve this as well, and it looks like by far the slowest method is in [`ARController.prototype._copyImageToHeap`](https://github.com/jeromeetienne/AR.js/blob/master/three.js/vendor/jsartoolkit5/js/artoolkit.api.js#L1008):

Specifically the line:
```
var imageData = this.ctx.getImageData(0, 0, this.canvas.width, this.canvas.height);
```

Looks like there are two [experiments](https://github.com/jeromeetienne/AR.js/tree/master/three.js/experiments), "worker_artoolkit" and "worker_artoolkit2" that (attempt to?) implement all of that stuff in a web worker.

Which makes a lot of sense, and was actually what I was going to try next. The canvas used for converting image/video data into pixel data is the slowest part of the whole process and should be easy to move to a background worker.

I don't know what the exact status of those experiments is, but I'm going to start looking into that next myself.

**Comment by trusktr** [comment]
There's the new [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) that can run inside a Worker. Maybe that'll help make the `getImageData` call be in a separate thread.

**Comment by nicolocarpignoli** [comment]
closing as now answer from author for a long time
