### ISSUE TITLE
Shadow question 

### ISSUE THREAD

**Issue by 544531645** [jeromeetienne/AR.js#447]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I do webar, and I want the plane that receives the shadow to have no color and just the shadow, so what if I do that, now I have a gray plane that I want to show, and I want it to show only the shadow
How do you make a plane transparent? but can show shadow
I need help
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The model presented after marker recognition has shadow and does not need to show plane or plane transparency
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
iphone7p ios 12

**Comment by 544531645** [comment]
![1e3b118e0f642bbc2c1496c85ca0200](https://user-images.githubusercontent.com/15622364/49492158-1ff71400-f892-11e8-8bb7-ba094fd566a1.jpg)
I don't  want gray plan , only show shadow is okay .

**Comment by 544531645** [comment]
@nicolocarpignoli cou you help me ?

**Comment by nicolocarpignoli** [comment]
Hi, I never played with shadow but let me see if I understood: you want to show a shadow on a plane that has to be transparent, but instead is grey.
I don't see in your code where the plane is told to be grey. Can you please provide me the full code?
Is grey the default color?
And what is the 'entity' that is grey?

**Comment by 544531645** [comment]
@nicolocarpignoli I not set color , default show gray ...

**Comment by 544531645** [comment]
![image](https://user-images.githubusercontent.com/15622364/49787810-96988380-fd62-11e8-8963-0d462abb2c83.png)
yes I want this

**Comment by 544531645** [comment]
but don't know how to do

**Comment by 544531645** [comment]
@droid001

**Comment by pawcza** [comment]
@544531645 I've found [this](https://gist.github.com/urish/ca6e29ef8b42212ba0a74316c05105e4) gist by @urish that allows you to use THREE.ShadowMaterial() as an A-Frame component. You can later use it like this:
`<a-plane rotation="-90 0 0" shadow="receive: true" shadow-material></a-plane>`
