### ISSUE TITLE
Camera error in cordova app

### ISSUE THREAD

**Issue by LorenzoSimoncini** [jeromeetienne/AR.js#448]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

I'm creating a simple VR app with cordova but when I launch the .apk i get the error in the screenshot, while on browser it works well both on pc an android
![screenshot_20181210-151400](https://user-images.githubusercontent.com/45717910/49820334-ea619780-fd77-11e8-8d27-6a0fa936b649.png)
Here is the source code: https://github.com/LorenzoSimoncini/umARell/blob/master/in.txt

Any clue? Am I missing something obvious?

**Comment by chilidawid** [comment]
I had the same issue. Camera permission wasn't added to AndroidManifest.xml.
Logcat:

```
E/CameraService(4040): Permission Denial: can't use the camera
E/cr_VideoCapture(11751): java.lang.RuntimeException: Fail to connect to camera service
```

If  you're using Cordova 8+ you can add permission directly into config.xml:

```
    <platform name="android">
        <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/uses-permission" xmlns:android="http://schemas.android.com/apk/res/android">
            <uses-permission android:name="android.permission.CAMERA" />
        </edit-config>
    </platform>
```

**Comment by LorenzoSimoncini** [comment]
Thank you, it works now :)
