### ISSUE TITLE
Code generating marker

### ISSUE THREAD

**Issue by 544531645** [jeromeetienne/AR.js#452]
How to upload my own images with code or url interface to generate patt and PNG files.？I need to generate it in real time instead of uploading it to the web page by myself

**Comment by 544531645** [comment]
@nicolocarpignoli

**Comment by nicolocarpignoli** [comment]
Hi, 
never digged on this honestly, but with a quick search I found the source code for the pattern marker generator:

https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/marker-training/examples/generator.html

Take inspiration on that :)
