### ISSUE TITLE
Update AR.js and aframe versions at README

### ISSUE THREAD

**Issue by cernadasjuan** [jeromeetienne/AR.js#454]
Hi,

At the README.md, the code snippet of the basic example has outdated versions of AR.js and aframe. The latest versions are 

<script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.2/aframe/build/aframe-ar.js"></script>

Thanks!

**Comment by chimbs86** [comment]
+1 A lot of the bugs I was facing were miraculously solved once I updated my Aframe and arjs.

**Comment by subgero** [comment]
Could you please share you code, we are trying to load gltf files but it doesn't work what any version of iframe, even with the extra loaders. Thanks in advance.

**Comment by chimbs86** [comment]
@subgero 
https://github.com/chimbs86/pwa/blob/master/src/components/app-home/app-home.tsx

**Comment by subgero** [comment]
@chimbs86 Thank you.

**Comment by nicolocarpignoli** [comment]
absolutely. changed on master Readme. thanks!
