### ISSUE TITLE
model show bug 

### ISSUE THREAD

**Issue by 544531645** [jeromeetienne/AR.js#455]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The first loading of the material in android chrome is fine, and the second time the material flashes, it will only show up when the cache is cleared and reloaded, and it work well in safari.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
google pixel 

you can go to https://webar.dyver.se/103  test

**Comment by cann1132** [comment]
same here, i need to clear all data before access again

**Comment by 544531645** [comment]
@cann1132 yes , did you fixed it ?

**Comment by cann1132** [comment]
@544531645 no, just the same, cleaning cache and drowsing data everytime..

**Comment by commentatorboy** [comment]
Not me. I reloaded the url 3 times and it still shows the model fine. I am using android 8 + chrome on a moto e5.
What do you mean by "flashes" like it shows and then disappears?

Try firefox or on a laptop... see if the problem also happens there.

**Comment by cSparkle** [comment]
@544531645 The link you shared works perfectly for me. Were you able to find a solution?

I'm experiencing a similar issue, but I don't even see the flash. Everything appears fine on a fresh load, but no models show up for any of my markers (custom or preset) on page reload. Clearing the cache does not fix the issue for me. I'm experiencing this on Safari, Firefox, and Chrome on both my macbook and my android from my staging and dev environments.

**Comment by cann1132** [comment]
@cSparkle I don't know how your produced the marker, but i was having the same issue while ago. Currently,I can say that "hiro" or custom marker recognition is not stable.

And I think that unfortunately @jeromeetienne left ar.js development.

**Comment by commentatorboy** [comment]
Yeah I have noticed this problem on a Iphone X.
Have @544531645 tried to push the "VR" button? To see if it works in that?

**Comment by 544531645** [comment]
I already fixed it .

**Comment by 544531645** [comment]
var newCamera = new THREE.PerspectiveCamera();
        newCamera.near = 1;
        newCamera.far = 100;
        sceneEl.camera = newCamera;
      sceneEl.addEventListener('loaded', () => {
        var newCamera = new THREE.PerspectiveCamera();
        newCamera.near = 1;
        newCamera.far = 100;
        sceneEl.camera = newCamera;
      });

**Comment by 544531645** [comment]
I don't know why need twice , but when one time . it not work . now I work it well @cann1132

**Comment by commentatorboy** [comment]
@544531645 nice!
Just wanted to add that the "sceneEl" variable is from:
`const sceneEl = document.querySelector('a-scene');`

I want to test it myself, although, I guess we can close this issue of the time being.
