### ISSUE TITLE
ios chrome don't work 

### ISSUE THREAD

**Issue by 544531645** [jeromeetienne/AR.js#456]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Android chrome is work, ios chrome say don't support webtrc

**Comment by MartijnEisses** [comment]
https://github.com/aframevr/aframe/issues/3892#issuecomment-445778511

**Comment by nicolocarpignoli** [comment]
Hi,
as they have already answered you in that thread, we just have to wait for the API to be available. So, this is not a AR.js issue, sorry.
