### ISSUE TITLE
Unable to load the file ply and gltf2

### ISSUE THREAD

**Issue by ophuicus** [jeromeetienne/AR.js#459]
Unable to load the file ply and gltf2. but the format obj is ok? else have the problem?

**Comment by ophuicus** [comment]
stadium.ply file and aframe-extras-loaders add

**Comment by kalwalt** [comment]
@ophuicus I tryed time ago to load a gltf model and was impossible for me, I don't know why, maybe i will try again...

**Comment by subgero** [comment]
Same problem here, obj file load perfectly but not gltf, I tried version 1.0 and 2.0. According to a few tutorials it must be works, but the file it is not loaded.  https://medium.com/@akashkuttappa/using-3d-models-with-ar-js-and-a-frame-84d462efe498

**Comment by ophuicus** [comment]
no choice ! test to do !

**Comment by commentatorboy** [comment]
I managed to load gltf (or rather glb files) using the example here: https://aframe.io/docs/0.9.0/components/gltf-model.html#example

**Comment by kalwalt** [comment]
For anyone interested i have an example with ar-aframe.js here: https://github.com/kalwalt/kalwalt-interactivity-AR/blob/master/aframe-ar-simple-gltf.html

**Comment by subgero** [comment]
> For anyone interested i have an example with ar-aframe.js here: https://github.com/kalwalt/kalwalt-interactivity-AR/blob/master/aframe-ar-simple-gltf.html

It doesn't work for me.
