### ISSUE TITLE
Cross origin request / 404

### ISSUE THREAD

**Issue by pcvonz** [jeromeetienne/AR.js#46]
I pulled this repos and tried linking aframe-ar.js into my project, but I'm getting some weird problems. Here is something peculiar: `THREEx.ArToolkitContext.baseurl` is set to `https://jeromeetienne.github.io/AR.js/`, which throws a cross origin request error in the console. 

Also, when I run basic.html in the aframe examples, the console says it can't find:
`https://jeromeetienne.github.io/data/data/camera_para.dat`, which doesn't exist. 

Any ideas on how to fix this? This is pretty cool project, but seems like it's hard to get up and running.

**Comment by jeromeetienne** [comment]
the proper value is

THREEx.ArToolkitContext.baseURL = 'https://jeromeetienne.github.io/AR.js/three.js/'

not the three.js at the end

i hope this helps
