### ISSUE TITLE
i want to load a gltf model in the multiple marker concept 

### ISSUE THREAD

**Issue by ashwinkapure** [jeromeetienne/AR.js#462]
i was able to load a gltf model through a-frame for AR, here i faced an issue that when the camera is away from the marker the model disappears , here i studied the multimarker concept but i an new to javascript, the code on github shows how to load a box and torus which is code generated, it would be helpful if anyone can help me loading a gltf model instead.

**Comment by droid001** [comment]
It's the same concept as with geometric objects. Just swap out the box or torus with an entity which contains a gltf model. Check out the a-frame documentation: https://aframe.io/docs/0.8.0/components/gltf-model.html

**Comment by ashwinkapure** [comment]
> It's the same concept as with geometric objects. Just swap out the box or torus with an entity which contains a gltf model. Check out the a-frame documentation: https://aframe.io/docs/0.8.0/components/gltf-model.html

thankyou very much for quick reply, i have done the above suggestion at the beginning and its working smoothly, please find the below code 

        AR.js/three.js/examples/multi-markers/examples/player.html
      
i  found the above code in the AR.js multimarker examples, here this code is in javascript and has the multimarker concept working. here as i am new to javascript i dont know how to add a gltf model instead of the box and torus

**Comment by commentatorboy** [comment]
This is the code used for multimarker:
https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/multi-markers/examples/player.html
It does not look like that it uses a-frame rather just threex and other.
I suspect that none of them would work with gltf.
But you can experiment with it.
Firstly include a-frame.
secondly use the example here: https://aframe.io/docs/0.9.0/components/gltf-model.html#example
thirdly replace the object created around here: 
[link](https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/multi-markers/examples/player.html#L245) with gltf.

**Comment by Poojahm3** [comment]
hi,
when i replace the src link to my new gltf model it stops working. i dont know whats wrong.

<html>
  <head>
<script src="https://aframe.io/releases/1.0.0/aframe.min.js"></script>
 
<script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
</head>

<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs='sourceType: webcam;'>
   <a-assets>
  <a-asset id="cesium-manw" src="CesiumMan.glb"></a-asset>
</a-assets>
<a-entity id="walker" gltf-model="#cesium-manw" position="0 0 -5" scale="0.5 0.5 0.5" animation-mixer>
</a-entity>
    <a-marker  preset='hiro'>
      
   <a-entity
                animation-mixer
                gltf-model="#cesium-manw"
                scale="1 1 1">
            </a-entity>
      
    </a-marker>

    <a-entity camera></a-entity>
  </a-scene>
</body>

</html>

this is working exmple. how can i put my own gltf model on scanning hiro marker

**Comment by Poojahm3** [comment]
![Screenshot from 2019-12-20 15-18-37](https://user-images.githubusercontent.com/59049686/71246087-0ceba080-233c-11ea-97f5-4725b7a3a23a.png)
this is my example code. how i can put new gltf file in that.. if i edit src link it doesn't work

**Comment by commentatorboy** [comment]
Can you open your browsers developer console, when running the code? (Usually through f12). And post/screenshot the errors. I suspect that it is because it can not find the gltf.
