### ISSUE TITLE
WebRTC Issue - Navigator.MediaDevice is not presented in your device.

### ISSUE THREAD

**Issue by lasharela** [jeromeetienne/AR.js#463]
When I'm trying to load the example I see the error:
 WebRTC Issue-!
navigator.mediaDevice not present in your browser.

I had no this error 2 weeks ago.

![img_4990](https://user-images.githubusercontent.com/2189316/52237810-813e6200-2898-11e9-82ae-92556da86b15.PNG)

- OS: iOS 12.0.1 (16A404)
- Brower: Safari

**Comment by nicolocarpignoli** [comment]
maybe you have denied the app the access to your camera when it prompted you ?

**Comment by janpio** [comment]
Would there be a way to undo that @nicolocarpignoli, in the Settings app for example?

I have an older iPad here where I get the same error message. It is running iOS 9.3.5 - can this also be caused by older iOS and Safari versions?

**Comment by nicolocarpignoli** [comment]
Hi @janpio , searching a little bit on the web, I found that mediaDevices is fully supported on iOS from 11+.

So, if iOS is 11+, Safari (instead of Chrome that not asks every time for camera permissions) will ask the user for camera usage at EVERY refresh of the app. If not, try to clear Safari cache.
That error, anyway, could mean two things: mediadevices is not supported or you have previously denied accesso to that website for your camera. :)

**Comment by raywu** [comment]
+1 thanks @nicolocarpignoli good call. Safari prompts for authorization whereas Chrome does not.

**Comment by commentatorboy** [comment]
Weird I am pretty sure that Safari did promt for camera...
But it is different from Safari and IOS versions I guess.

**Comment by andreyrd** [comment]
This is the same issue as #476.

From your screenshot, I see the back button in the top left corner, which means that the page is open in an embedded WKWebView inside of another app, and is not actually full Safari. You'll need to open the page with the regular Safari app.

For a full explanation see [this comment](https://github.com/jeromeetienne/AR.js/issues/476#issuecomment-466099176).

**Comment by keyserfaty** [comment]
Just in case it's helpful to anyone I was getting this same error when trying to run an example from my phone (Chrome) from my IP. I was getting this error and there was no prompt to give camera permissions. 
Apparently, Chrome won't ask for permissions when running a site from `http` so I solved this problem by running my example from ngrok using `https`. Works now.

**Comment by fmagno** [comment]
@keyserfaty that was exactly my problem. Thanks!

**Comment by jazzyjube** [comment]
> Just in case it's helpful to anyone I was getting this same error when trying to run an example from my phone (Chrome) from my IP. I was getting this error and there was no prompt to give camera permissions.
> Apparently, Chrome won't ask for permissions when running a site from `http` so I solved this problem by running my example from ngrok using `https`. Works now.

That solved my problem, thanks @keyserfaty  !

**Comment by Ymcmbennie** [comment]
Change the file protocol to https:// or something secure. This is because of the new updates from google chrome. I found this to work for me. Just basically adding https:// to the beginning of my link

**Comment by ImranBug** [comment]
same here, adding `https` solved the issue.

**Comment by urajcic** [comment]
After new update, Safari again shows same error. Https does not help. Any solution?

**Comment by roons** [comment]
I'm having the same issue on Chrome on the latest generation of iPhones.

Works on Pixel 3 (Android 10) and older iPhones and iPads on both pre and post iOS13 versions.

Running the demo over https but get WebRTC issue-! on new iPhones. Could this be hardware related?

**Comment by benallfree** [comment]
Would it be worth a PR to check for `https` before displaying the `navigator.mediaDevices not present` message?

**Comment by the-lost-explorer** [comment]
> Change the file protocol to https:// or something secure. This is because of the new updates from google chrome. I found this to work for me. Just basically adding https:// to the beginning of my link

Worked for me too.

**Comment by arielweinberger** [comment]
Can we please leave this ticket open? Running on iOS 13, using Chrome, via https (ngrok). Getting the same error.
Safari works fine via https.

**Comment by nicolocarpignoli** [comment]
Chrome on ios does not support camera access. Chrome problem. PLease use safari on  iphones and ipads

**Comment by jrDev1** [comment]
Firefox on iOS is having this problem too!

**Comment by andreyrd** [comment]
Any browser on iOS that is not Safari will NOT work.

**Comment by dzoech** [comment]
In addition to @andreyrd's answer, the reason why all browsers other than Safari have this problem is because all of them (have to) use WebKit. Now [WebKit has a bug where gutUserMedia fails](https://bugs.webkit.org/show_bug.cgi?id=208667). So this AR.js issue cannot be fixed until the WebKit problem is solved.

**Comment by iyasilias** [comment]
If anyone having problem running on iOS (through app, in my case - ionic app), please add below description in your Info.plist.

```
NSCameraUsageDescription (Privacy - Camera Usage Description)
NSPhotoLibraryAddUsageDescription (Privacy - Photo Library Additions Usage Description)
NSPhotoLibraryUsageDescription (Privacy - Photo Library Usage Description)
```

**Comment by muhammedbasilsk** [comment]
I was using python http.server to serve the local website. 
Thanks to the pointers in the above comments about https, I served the same local website using [ngrok](https://ngrok.com/) and it all worked.

Thanks folks !
