### ISSUE TITLE
https://jeromeetienne.github.io/AR.js/data/data/camera_para.dat

### ISSUE THREAD

**Issue by janpio** [jeromeetienne/AR.js#465]
Hey,

I just implemented my first project with AR.js and aframe - very nice experience!

During the last testing I noticed that 1 file is downloaded from a remote URL: https://jeromeetienne.github.io/AR.js/data/data/camera_para.dat 

Is there a specific reason why the information in this file is not inlined in the build? 
What is this data needed for?

Thanks.

**Comment by kalwalt** [comment]
Hi @janpio, normally it shouldn't download it, It should be in the `path/to/Ar.js/data/data` folder of AR.js. Where this happening? Does it come from you custom code or an example from AR.js? You should also provide more infos: Are you using` <a-frame>` or what else? :smile:

**Comment by janpio** [comment]
(Sorry I was a bit light on information, posted this after an all-nighter to get the project out. Just wanted to make sure I don't forget it.)

I am using AR.js with Aframe, so I downloaded `aframe.min.js` and `aframe-ar.min.js` and put it into my local `assets` folder where I embed it from, which is similar to the famous 10 line example: https://github.com/jeromeetienne/AR.js#augmented-reality-for-the-web-in-less-than-10-lines-of-html

You can actually reproduce the behaviour when you deploy exactly that example to a server and run it - it will make xhr requests for https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/pattern-files/pattern-hiro.patt (expected as the example does not specify a local pattern to use for matching) and https://jeromeetienne.github.io/AR.js/data/data/camera_para.dat - which is what I am trying to understand.

I was thinking on how to make the project run fully offline, wrapped in a native Cordova app - and that request to that file might be a problem.

(Let me know if you need even more information, I am very happy to provide it)

**Comment by nicolocarpignoli** [comment]
hi @janpio, as far as I know, there is no reason to pull that from remote, 'every time'. it is a static file that doesn't change. You can simply include it on the project you import on your app. To do so, fork AR.js, move this file on the project somewhere and import it locally.
In fact, if you have time for that, would be nice a PR, I will be glad to review it and eventually merge it :)

**Comment by janpio** [comment]
Ok, quick investigation into the code: Appears twice in `arframe.js`. Source are:

https://github.com/jeromeetienne/AR.js/blob/048eebc113e1cd136c4fdbbaa491868d5a208887/three.js/src/threex/threex-artoolkitprofile.js#L46-L54
https://github.com/jeromeetienne/AR.js/blob/b0fec0c2eafbf9e51b8b3fc6ee1b0e1f7f5fb1cd/three.js/src/threex/threex-artoolkitcontext.js#L21

As the request contains `data/data`, I think the source is the first one.

Now how to solve this?

We could change `THREEx.ArToolkitContext.baseURL` to default to a local path, then the uses will also have to download `[camera_para.dat](https://jeromeetienne.github.io/AR.js/data/data/camera_para.dat)` together with `aframe.(min.).js`.

We might also inline the file - it is only 176 bytes. But as it is binary data, no idea how to do that to be honest.

---

Before we go ahead here, can someone explain what this actually does? Can it be supplied manually and overwritten when using AR.js?

**Comment by janpio** [comment]
> cameraParametersUrl: to load the camera parameters for calibration
> http://jeromeetienne.github.io/slides/artoolkit-aframe/#14

**Comment by commentatorboy** [comment]
https://learningactors.com/how-to-code-an-augmented-reality-marker/

> 
> 14. AR renderer
> 
> The AR.js needs a context set up, calling the Three.JS extension to do so. Here it takes the camera data file, which is included in the data folder, and detects at 30 frames per second with the canvas width and height set up for it.

**Comment by LostInBrittany** [comment]
Hi all! I am getting the same issue. As far as I see in the code, the problem is in line 5310 on `aframe-arjs.js`:

```js
ARjs.Context.baseURL = 'https://jeromeetienne.github.io/AR.js/three.js/'
```

It defines the base URL directly to the site instead to the local install.

And then in line 5707 we get the camera data from this base URL:

```js
cameraParametersUrl: THREEx.ArToolkitContext.baseURL + '../data/data/camera_para.dat
```

**Comment by nicolocarpignoli** [comment]
@LostInBrittany problem is this line, this is the source code: https://github.com/jeromeetienne/AR.js/blob/6350b439077bd67b11999114fb79050e532bc969/three.js/src/threex/threex-artoolkitcontext.js#L78

I may do a PR for that using what's at line 76 (so '../').
Are you will to test such PR in case?

**Comment by LostInBrittany** [comment]
I have found an alternate way, using the `cameraParametersUrl` arjs
attribute:

```html
<a-scene embedded  arjs="cameraParametersUrl:
./node_modules/ar.js/data/data/camera_para.dat;" >
   ...
</a-scene>
```

But I think that the PR idea is a good one, for a saner by default value :)

**Comment by nicolocarpignoli** [comment]
Closed for now, BTW there is a PR for this, already opened and to be closed shortly

**Comment by nicolocarpignoli** [comment]
@LostInBrittany 's solution works

**Comment by frederic-bonjour** [comment]
Thanks, @LostInBrittany! :)
