### ISSUE TITLE
[aframe-ar(.min).js] Smaller builds?

### ISSUE THREAD

**Issue by janpio** [jeromeetienne/AR.js#466]
`aframe-ar.min.js` currently is 940KB. Has anyone tried to produce a smaller build? 

Looking at the `Makefile`, it seems to combine quite a lot of files. Are all those necessary for all projects? Or would it be possible to look at the local feature usage and then produce and optimized, smaller build?

**Comment by nicolocarpignoli** [comment]
I'm thinking of that, trying to create a smaller builder. Have to find the time to do this actively tho :)

**Comment by nicolocarpignoli** [comment]
On latest releases I have removed a lot of files, so build are now smaller. In next major release (3) we will remove even more.
