### ISSUE TITLE
Benchmarking markers quality?

### ISSUE THREAD

**Issue by janpio** [jeromeetienne/AR.js#468]
Is there a way to evaluate a generated marker or pattern? An automated way to test a marker in different scenarios could also help.

**Comment by nicolocarpignoli** [comment]
As i wrote here https://medium.com/chialab-open-source/ar-js-the-simpliest-way-to-get-cross-browser-ar-on-the-web-8f670dd45462, we have the 'hamming distance' meter for barcode markers, but nothing 'automated' at the moment, and not for the other markers types.
I do not know if such things is possible with good results.
We can wait to see if others know something more. 

One thing I can tell you, this question is not regarding AR.js but rather artoolkit (https://github.com/artoolkit/jsartoolkit5). AR.js simply uses it for marker recognization.
You could open a issue there, they surely can answer you. And then you can link the issue you open here as a reference. We can add it to the Readme if answer is useful
