### ISSUE TITLE
running demo in local server

### ISSUE THREAD

**Issue by tcwyjno1** [jeromeetienne/AR.js#47]
Sorry to disturb.
I visit this url: https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html in my chrome with an android phone. It worked excellent.
I download the demo and run in local server.
I visit http://localhost/AR.js/three.js/examples/mobile-performance.html. It shows nothing,no error either.
Can you help and analyse this issue?

**Comment by yjfeng** [comment]
only run in https!

**Comment by jeromeetienne** [comment]
Exactly that!

I should do a section on that in the readme

**Comment by karanganesan** [comment]
Actually what is the reason first I would like to understand it first about HTTPS ... ?

**Comment by jeromeetienne** [comment]
This is a security requirement from chrome. I will find links and post that
in the readme

**Comment by tcwyjno1** [comment]
great. I haven't found that different! 
Keeping focus on this project!

**Comment by tcwyjno1** [comment]
according from part:browser support.
I have another doubt:
It can't work on Android 4.4.2 above or Android 5?  No browser support yet? even chrome?

**Comment by blq** [comment]
Runs on my S3 with Android 4, using Chrome. (Old native Android browser probably not/never)

**Comment by tcwyjno1** [comment]
I still faced a problem when i running the aframe demo.
eg:https://jeromeetienne.github.io/AR.js/aframe/examples/basic.html
I found a loop error in my browser console:

aframe.js:64445 Uncaught TypeError: Cannot read property 'setSize' of undefined
    at HTMLElement.value (aframe.js:64445)
    at bound (aframe.js:67157)
    at tick (aframe-ar.js:1174)


then it did not work either.
anyone knows about the issue?

**Comment by jeromeetienne** [comment]
Here is more info on the https requirement for WebRTC

https://tokbox.com/blog/the-impact-of-googles-new-chrome-security-policy-on-webrtc/

**Comment by jeromeetienne** [comment]
I will look when I reach home

**Comment by tcwyjno1** [comment]
great...  I need get a VPN to visit the link....
We China can not visit lots of  technique website. It's frustrating ..
I have another problem and I have no idea to do.
I made a simple html with only code below:


` <a-scene embedded artoolkit="sourceType: webcam">
      <a-video  id="inputVideo" src="roger.mp4" width="0" height="0" position="0 0 -20"></a-video>    </a-scene>`

It can open my camera and load the video to play.

I want to do below things:
1.open the camara and scene a picture. eg: https://jeromeetienne.github.io/AR.js/data/images/HIRO.jpg
2.distinguish the jpg.
3.play the video.

I do not konw how to distinguish the picture.
just like demo
https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html
why i move the jpg .the cube move with the pic. How can the camera distinguish the picture
and draw the cube on it.

**Comment by yjfeng** [comment]
@tcwyjno1 ,I think my be "ar-code"  is your need:
https://jeromeetienne.github.io/AR.js/three.js/examples/arcode.html

**Comment by tcwyjno1** [comment]
@yjfeng I want to understand why the cube always stays on the hiro picture in https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html 
Is there any possible that I can change hiro picture to another picture?

**Comment by yjfeng** [comment]
@tcwyjno1, I think the maker just as the Base position for element that you want to show, and I don't know how to change the maker to any marker you want,I think Just two marker you can choose.
(如果没有一个基本的面来作为参考，加载进来的3d元素将无法知道以何种方向放在何处，所有基于maker的ar相关的app也都是这样吧。目前我只知道基于web的2个marker图案好像是硬写到js里的，无法改变。以上只是个人理解，不一定正确，我也是刚尝试。)

**Comment by tcwyjno1** [comment]
@yjfeng Thanks,I do think so too. Maybe I can find the base position and change it.(原来同为国人..幸会幸会,我想做的是通过HTML5把手机摄像头打开以后,对准中国电信的标志,然后假设可以识别出这是中国电信的标志(也许不能识别,对吧?),那么就播放一段视频. APP是可以实现,现在就是要用HTML5实现,真让人头大...)
@jeromeetienne ,Is the understanding of @yjfeng  right?

**Comment by yjfeng** [comment]
@tcwyjno1 ,不支持苹果，不支持微信，你确认要用吗？

**Comment by tcwyjno1** [comment]
@yjfeng 确认啊..上级命令压死人. 都说了不支持了,还是想实现一下..  我看这个ar.js好像也不支持扫描哦.

**Comment by tcwyjno1** [comment]
@yjfeng 方便加个QQ之类的,问你点问题么

**Comment by yjfeng** [comment]
@tcwyjno1 ,qq:790543010

**Comment by patricknelson** [comment]
@jeromeetienne, I think the issue @tcwyjno1 is having is not relating to HTTPS in Chrome since the literal hostname `localhost` (along with the loop back IP of `127.0.0.1`) will work fine without a secure connection. I've tested this myself in Chrome 57. I think this is caused by something unrelated.

**Comment by MasonGhost** [comment]
> @yjfeng 确认啊..上级命令压死人. 都说了不支持了,还是想实现一下.. 我看这个ar.js好像也不支持扫描哦.

你好，方便留个联系方式吗？微信或者QQ都可以，我现在使用AR.js也遇到需要翻墙了才能识别出来的问题，能帮我一下吗

**Comment by patricknelson** [comment]
@MasonGhost this repository is old. Go to: https://github.com/AR-js-org/AR.js
