### ISSUE TITLE
Video stuck on IOS

### ISSUE THREAD

**Issue by SerkaFox** [jeromeetienne/AR.js#472]
Hello. Problem with support IOS phones. My project scan custom marker and autoplay video, then camera saw marker. On android and desctop system works fine, but on IOS phones only first FRAME and stop, nothing happen.

1. Go to 'https://taswitta.ru/wow.php'
2. Check on 'https://taswitta.ru/wow/vr.jpg'
3. Wait then play
4. See error - NOTHING, only black screen

This is if i use Iphone, but allright if i use Android phones.

**Comment by navanchauhan** [comment]
Could you show the code

**Comment by SerkaFox** [comment]
> Could you show the code
```
<!doctype HTML>
<html>
    <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
    <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.2/aframe/build/aframe-ar.js"></script>
    <script src="https://cdn.rawgit.com/donmccurdy/aframe-extras/v4.1.2/dist/aframe-extras.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>
        AFRAME.registerComponent('vidhandler', {
            init: function() {
                this.toggle = false;
                this.vid = document.querySelector("#vid");
                this.vid.pause();
            },
            tick: function() {
                if (this.el.object3D.visible == true) {
                    if (!this.toggle) {
                        this.toggle = true;
                        this.vid.play();
                    }
                } else {
                    this.toggle = false;
                    this.vid.pause();
                }
            }
        });

        function refrespage() {
            location.reload();
        }

        function playvid() {
            vid.play();
        }
    </script>

<body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs='sourceType: webcam; detectionMode: mono; trackingMethod: best; debugUIEnabled: false;' vr-mode-ui="enabled: false">
    <a-assets>
            <video preload="auto" id="vid" poster="ANY IMAGE PATH (THUMBNAIL)" response-type="arraybuffer" loop="true" autoplay type="video/mp4" crossorigin webkit-playsinline playsinline controls>
                <source  src="./wow/1.mp4">
                <img src="ANY IMAGE PATH (THUMBNAIL)"> Your browser does not support Or Else Please Click Reset Button.
            </video>
        </a-assets>  
         <a-marker id="memarker" type="pattern" url="./wow/1.patt" vidhandler>
            <a-video position='2 0 0' rotation="-90 0 0" scale="3.54 2 3.54" material='transparent:true;src:#vid' play="true" controls></a-video>
        </a-marker>
      
    <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>

```

**Comment by janpio** [comment]
Interesting, the video itself works just fine in Safari.

You might want to try this to get a look at the Safari console: https://ionic.zone/debug/remote-debug-your-app#ios-remote-debugging-with-safari-macos-only

**Comment by SerkaFox** [comment]
> Interesting, the video itself works just fine in Safari.
> 
> You might want to try this to get a look at the Safari console: https://ionic.zone/debug/remote-debug-your-app#ios-remote-debugging-with-safari-macos-only

You propose me check by iphone web inspector? But on mac all works fine???

**Comment by janpio** [comment]
Read the link I posted. It explains how to debug the webview of your app via Safari on macOS.

**Comment by SerkaFox** [comment]
> Read the link I posted. It explains how to debug the webview of your app via Safari on macOS.

Understand, i check the, problem only with devices, i havent iphones or else, this problem then i come to people, who get iphone or mac. Need some emulator of ios system. Thank you, when i got iphone and find debug - i write here. Thx again ;)

**Comment by SerkaFox** [comment]
People, i meet with friend with Iphone, he show me site page, there load VideoPlayer with my record. He press play and video plays. No one camera or marker. Just player with video.

**Comment by jamess922** [comment]
@SerkaFox  I also got something like you with Iphone , but only audio  no image

**Comment by SerkaFox** [comment]
> @SerkaFox I also got something like you with Iphone , but only audio no image

Many trouble, low fixes

**Comment by SerkaFox** [comment]
Still notfing happened. Maybe i use bug or error in my html code?

**Comment by antnicole** [comment]
I cannot get my video to play on iOS either (tried chrome, safari, firefox). It plays on my macbook pro (chrome, firefox) without a problem. I use this code:

<script src="https://aframe.io/releases/0.9.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.2/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>	
	
	<a-scene embedded arjs='debugUIEnabled: false; sourceType: webcam;'>
        	<a-assets>
             		<a-asset-item id="Tree-obj" src="Assets/Lowpoly_tree_sample.obj"></a-asset-item>
			<a-asset-item id="Tree-mtl" src="Assets/Lowpoly_tree_sample.mtl"></a-asset-item>
        	</a-assets>
        
        	<a-marker type='pattern' url='Markers/j-pattern-marker.patt'>
            		<a-entity obj-model="obj: #Tree-obj; mtl: #Tree-mtl" scale='0.08 0.08 0.08'></a-entity>
        	</a-marker>
		
		<a-entity camera></a-entity>
	</a-scene>
</body>

**Comment by nicolocarpignoli** [comment]
Maybe, this comment by @andreyrd has something to do wit this topic
https://github.com/jeromeetienne/AR.js/pull/482#issuecomment-468931919
Hope this helps

**Comment by antnicole** [comment]
Wow thank you so much! That answers my question!!

*Vanisara Nicole Anthony*
Designer & Artist
<https://mailtrack.io/trace/link/7b89be4234cec9c73578ee0069d96ae919731670?url=https%3A%2F%2Fwww.facebook.com%2FvanisaraDesign%2F&userId=1333575&signature=a6f7ec9fd363e26e>

<https://mailtrack.io/trace/link/e58330d34be8a825177a3df7d151c83f6cd5e6c6?url=https%3A%2F%2Fwww.instagram.com%2Fvanisara.n&userId=1333575&signature=429ae53db2daf375>
|  vanisara.com
<https://mailtrack.io/trace/link/801714e7bcc22413a85cf7694f6c52cde672796e?url=http%3A%2F%2Fvanisara.com&userId=1333575&signature=64b4d32f0b345579>

**Comment by h33ler** [comment]
I also was in big trouble getting any kind of video work on iOS 'couse i'm not a native programmer. Maybe my solution helps anyone out there:

`
<script src="scripts/play-on-window-click.js"></script>

<a-assets>

    <video id="video"  autoplay loop crossorigin="anonymous" playsinline webkit-playsinline src="https://cdn.glitch.com/e614a6f8-f4ba-4733-8a7c-e61e5d59427e%2Fd55bddf8d62910879ed9f605522149a8.mp4?1551541382508"></video></a-assets>

    <a-marker type="pattern" preset="hiro" material="" arjs-anchor="" arjs-hit-testing="" smooth="true">
      <a-video play-on-window-click src="#video" width="1.6" height="0.9" rotation="90 180 0" position="0 2 0" material="" geometry=""></a-video>
    </a-marker>
`

I used the play-on-window-click.js script from the a-frame example [https://glitch.com/edit/#!/aframe-360-video-example](url) 

Of course it's nothing close to autoplay but still gets a video play on click with audio in ARjs on iOS.. Tested it with an iPhone 6S and iOS 11.. 

Thanks alot to @nicolocarpignoli and aframe for giving the right hints!

**Comment by nicolocarpignoli** [comment]
Glad to hear this is solved. I'm closing this :)

**Comment by debayanj** [comment]
video not detecting on first attempt

the issues is on mobile its not detecting the marker on first time, it detects on third fourth time and then plays video . help me on this.
by collecting all related implementation of ar js on desktop and mobile using camera this code is working..

<!doctype HTML>

<script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js"></script>
<script src="https://cdn.rawgit.com/donmccurdy/aframe-extras/v4.1.2/dist/aframe-extras.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://rawgit.com/mayognaise/aframe-gif-shader/master/dist/aframe-gif-shader.min.js"></script>
<script>
    AFRAME.registerComponent('vidhandler', {
        init: function() {
            this.toggle = false;
            this.vid = document.querySelector("#vid");
            this.vid.pause();
        },
        tick: function() {
            if (this.el.object3D.visible == true) {
                if (!this.toggle) {
                    this.toggle = true;
                    this.vid.play();
                }
            } else {
                this.toggle = false;
                this.vid.pause();
            }
        }
    });

    function refrespage() {
        location.reload();
    }

    function playvid() {
        vid.play();
    }
</script>



Your browser does not support Or Else Please Click Reset Button.
Play (CHROME)
Refresh
