### ISSUE TITLE
Cannot full screen? [Solved - False Alarm]

### ISSUE THREAD

**Issue by farhanRIT** [jeromeetienne/AR.js#477]
I'm testing this example.

https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/basic.html

How do we make it the camera display fullscreen? So it is fullscreen across different devices with different screen size? Some of them looks small some looks large and none of them are centered.

Is there a documentation on how to render the camera center?

Sorry if I am posting at the wrong place. Pretty limited place to find info on this AR.js

Thanks.

**Comment by janpio** [comment]
Can you provide screenshots for illustration what you mean?

(But yes, you are in the right place. You could also have posted on StackOverflow with tag `AR.js` - but the same people would probably look at it.)

**Comment by farhanRIT** [comment]
Sorry, can close this thread. Wasn't an issue. Was just implemented it incorrectly.

**Comment by janpio** [comment]
(You should be able to close yourself)

**Comment by farhanRIT** [comment]
Oh, thread close!
