### ISSUE TITLE
Get Camera Position

### ISSUE THREAD

**Issue by mwmwmw** [jeromeetienne/AR.js#479]
**Is your feature request related to a problem? Please describe.**
Feature for THREEx version (not Aframe)

**Describe the solution you'd like**
I'd like the position of the camera to be where the viewer is, and have the marker be at 0,0,0; This could be behind a flag/config option.

**Describe alternatives you've considered**
I have tried a few different ways of calculating the position of the camera without much success. Point blank, I don't know enough about 3D to invert the relationship of the camera and marker. I have seen a few other posters who have had issues with this, but I find their answers to be incomplete.

**Additional context**
I want to be able to shoot things from the camera and raycast from the camera.

**Comment by nicolocarpignoli** [comment]
duplicate https://github.com/jeromeetienne/AR.js/issues/249
