### ISSUE TITLE
Stereoscopic Screen in Aframe-AR is Blank

### ISSUE THREAD

**Issue by vijayrajasekaran** [jeromeetienne/AR.js#48]
Hello,

Thank you for your contribution toward AR. This is an awesome extension for A-Frame.

It works fine in normal mode, but when the stereoscopic icon is tapped. It enters stereoscopic mode, but it only display the 3D object attached to the marker but the background is blank instead of showing the live camera footage.

**Comment by karanganesan** [comment]
It's not yet been supported as of now I guess but the method is to do is by adding 2 stereoscopic iframe of camera view

**Comment by jeromeetienne** [comment]
the work is in progress but not yet completed. 

see the current code at https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/ar-in-webvr.html

**Comment by vijayrajasekaran** [comment]
I will check it out. Thank you. :)

**Comment by vijayrajasekaran** [comment]
Any Update on this?

Thank you.
