### ISSUE TITLE
Augment A Transpirant(Alpha) Video on HIRO

### ISSUE THREAD

**Issue by jamess922** [jeromeetienne/AR.js#480]
Hi there:
        I have been searching for how to augment a Transparent (Alpha) Video on HIRO with AR.js for a while,but still don't know how to make that happen, is that even possible to augment a Transparent (Alpha) Video on HIRO with AR.js ,any demo ?

**Comment by kalwalt** [comment]
@jamess922 you can do with Three.js, you can found many resources googling, for example: https://github.com/SunriseFox/Three-Transparent-Video 
basically you should use a glsl shader and a texture with an alpha channel. I have not tested that code, it' is just an idea.
Instead If you want to use <a-frame> i think you can do the same passing the video texture to a shader. 
Hope that this can be useful...

**Comment by agusalex** [comment]
In a-frame, there is a property for your object material called alphaTest if you set that to less than 1 eg. 0.9 you can play an alpha channel enabled transparent video on ar.js too. I used it to make a futuristic HUD, the problem is AR.js is too flickery for that (at least when I tried). Something like this if I remember correctly (sintax may be wrong im on my phone atm) `<a-video material="alphaTest:'0.9'"></a-video>`

**Comment by jamess922** [comment]
Thank you I will give a try

**Comment by jamess922** [comment]
@agusalex  which video format you were using?  I just try with webm`material='transparent:true;alphaTest:0;src:#video'`video just playing with black background

**Comment by agusalex** [comment]
Got it working, there is an issue on a-frame 0.9. On 0.8 works just fine you don't even need to set transparency. I used webm for the video, try this one [https://drive.google.com/file/d/1DDQClKEoLwiSYkuxvKa-LsMIYxmxhvP9/view?usp=sharing](known working video).

**Comment by agusalex** [comment]
Sorry forgot to set it up for ar.js, its quite the pain dont ask how I found out a while back. 
https://glitch.com/edit/#!/ar-js-alphachannel

**Comment by agusalex** [comment]
I made an issue on a-frame, hope it gets solved! https://github.com/aframevr/aframe/issues/4079

**Comment by jamess922** [comment]
I find another problem,the Transparent video(.webm) I used has different background from your video,my video has black background,So could you show me how to make a Transparent video for A-frame,

**Comment by jamess922** [comment]
I find another problem,the transparent video(.webm) i used has different background from the video in your example,my video has a black background ,looks not right for A-frame,so could you show me how to make a right transparent video for A-frame.

**Comment by agusalex** [comment]
I'm sorry, I don't make them myself they were designed for a project but I only did the coding.

**Comment by jamess922** [comment]
OK I will try to find out how 
and you were using with an Android cellphone right ? because i tried with my iphone 7 ,not working

**Comment by jamess922** [comment]
Looks at present Safari doesn't support WebM video format.

**Comment by droid001** [comment]
There's a lot of video related things which desktop/mobil Safari doesn't handle. Take for instance just serving .mp4 video you have to have the server [configured to handle byte ranges](https://stackoverflow.com/a/51901198/7197027). In the development environment it's also tricky as your default express or php server doesn't output video which is Safari compatible.

**Comment by nicolocarpignoli** [comment]
close as no discussion is going over here, or at least no more
