### ISSUE TITLE
Some testing with smoothing code    e59568b

### ISSUE THREAD

**Issue by jamess922** [jeromeetienne/AR.js#481]
I did some test this `smooth:true`  working with a 3d model (OBJ) ,but when i try it with a video ,I only get sound ,nothing i could see,and if I set `smooth: false` the video works as normal.
here is the code I use:
`let markerControls1 = new THREEx.ArMarkerControls(arToolkitContext, markerRoot1, {
		type: 'pattern', patternUrl: "data/hiro.patt", smooth: true,smoothCount: 5,smoothTolerance: 0.01,smoothThreshold: 2,
	})`

**Comment by janpio** [comment]
Interesting problem, maybe @andreyrd can give some insight if he tested with video or if he is aware of any possible problems with the smoothing and videos.

**Comment by andreyrd** [comment]
Think I found the problem, opened PR #482
Thanks!

**Comment by ramonortigosa** [comment]
Hi:

Where are the smooth, smoothCount and SmoothTolerance parameters?? I can find them...

I see these parameters on threex-armarkercontrols.js:

this.parameters = {
		// size of the marker in meter
		size : 1,
		// type of marker - ['pattern', 'barcode', 'unknown' ]
		type : 'unknown',
		// url of the pattern - IIF type='pattern'
		patternUrl : null,
		// value of the barcode - IIF type='barcode'
		barcodeValue : null,
		// change matrix mode - [modelViewMatrix, cameraTransformMatrix]
		changeMatrixMode : 'modelViewMatrix',
		// minimal confidence in the marke recognition - between [0, 1] - default to 1
		minConfidence: 0.6,
	}
