### ISSUE TITLE
Lights sometimes don't work on Android when deployed.

### ISSUE THREAD

**Issue by Sylfschiffer** [jeromeetienne/AR.js#486]
**Describe the bug**
This bug is a very mythical bug. It only triggers under specific circonstances ( See To Reproduce ). The effects are that lights don't seem to work and my 3D model is darker. You can still see the texture, but it's very dark. It is an intermittent problem, it happens roughly half the time, and only happens on Android when hosted on Web Server, it works perfectly when hosted locally with node.js.

**To Reproduce**
1. Create AR.js project with .gltf model, .png texture and lights on a-scene.
2. Host on web server, Google Cloud Platform in my case
3. Visit the website on Android Phone with Google Chrome
4. Scan the AR Marker.

**Expected behavior**
I expected to see a lit model. It happens sometimes but not every time under these specific conditions (web hosted, android phone only).

**Screenshots**

https://i.imgur.com/sOU3nHL.jpg
https://i.imgur.com/tHH3E0X.jpg`

**Smartphone**
 - Device: Samsung Galaxy S9 and Google Pixel 2
 - OS: Android 9
 - Browser : Google Chrome
 - Version : 72.0.3626.121

**Comment by commentatorboy** [comment]
Try and look at the dev console when the error occurs. Does it indicate any errors?

**Comment by Sylfschiffer** [comment]
No, I don't notice anything different when it works and when it doesn't. No errors, network data seems fine texture-wise, etc. I tried it on many different phones and the issue still happens.

I'm aware of how weird this all sounds and I really dug in deep to try and fix it, to no avail for the moment.

**Comment by commentatorboy** [comment]
@Sylfschiffer 
Try and see if this works.
https://github.com/jeromeetienne/AR.js/issues/494
Basically:
Set a `renderer='precision: medium'` on the a-scene tag.
Not sure if it works. But try anyways.

**Comment by nicolocarpignoli** [comment]
@Sylfschiffer news? it worked?

**Comment by Sylfschiffer** [comment]
Unfortunately no. I tried this a while ago but to be honest, I kinda dropped the issue. The producer wasn't interested in spending more to fix the issue and personally I was getting frustrated with this.

**Comment by nicolocarpignoli** [comment]
ok thanks
