### ISSUE TITLE
Flat surface detection

### ISSUE THREAD

**Issue by bitbythecron** [jeromeetienne/AR.js#487]
**Is your feature request related to a problem? Please describe.**
It would be nice if AR.js could be used to detect flat surfaces (horizontal or vertical) and provide some form of bounding box or geometry w/ coordinates for where these surfaces exist.

**Describe the solution you'd like**
Provided above

**Describe alternatives you've considered**
Trying to roll my own based on some 3d recon libraries

**Additional context**
N/A

**Comment by janpio** [comment]
AR.js is pretty much a marker recognition thing, so this is most probably out of scope.

But yes, it would be nice if there was a nice way to do this on the web platform.

**Comment by bitbythecron** [comment]
Thanks @janpio any libraries (JS or otherwise) you can recommend for flat surface detection? Maybe the `artoolkit` that AR.js is based on?

**Comment by janpio** [comment]
The reason AR.js only support markers and these barcodes it because [artoolkitx](https://github.com/artoolkitx/artoolkitx) only supports these as far as I know.

There is some "NFT - Natural Feature Tracking" - but I don't know exactly how this works and if it can be used together with AR.js: https://github.com/artoolkitx/artoolkitx/wiki/Creating-and-using-NFT-markers

**Comment by droid001** [comment]
Your best bet so far is to get an [ARCore compatible Android](https://developers.google.com/ar/discover/supported-devices) device, turn on smoe flags in Chrome and check [out this page](https://developers.google.com/web/updates/2018/06/ar-for-the-web).

**Comment by commentatorboy** [comment]
Perhaps take a look at:
https://youaugment.com/ or https://github.com/KhronosGroup/OpenXR-SDK

**Comment by thor-brickman** [comment]
There is some hope in this, perhaps:
https://trackingjs.com/

**Comment by commentatorboy** [comment]
Since this is outside of the scope of this project should someone not close this? 
A related issue is this:
https://github.com/jeromeetienne/AR.js/issues/544

**Comment by Joshua-Madrid** [comment]
What would need to be done to get this added? what is the code use to take a video and detect the lines and then assume the surface? I looked at trackingjs but it seems to no longer be working. Although did get me thinking can you detect something and then have the 3D object simple show on that thing?

**Comment by fuleinist** [comment]
https://www.8thwall.com/8thwall/placeground-aframe found this
