### ISSUE TITLE
NFT ?

### ISSUE THREAD

**Issue by Samsy** [jeromeetienne/AR.js#49]
Hello Jerome, 
Thank you for putting this in place, thats awesome.

Is there possibly any NFRMarker implementation coming in ?

**Comment by jeromeetienne** [comment]
it isnt a priority at the moment because they require a lot more CPU as pattern marker

**Comment by Samsy** [comment]
Oh ok right :)
Thank you very much again for putting all of this

**Comment by AndreaMonzini** [comment]
Hello,

 what about custom marker? ( not a NFT)

https://github.com/kig/JSARToolKit/issues/9

http://www.artoolworks.com/support/library/Creating_and_training_new_ARToolKit_markers

**Comment by jeromeetienne** [comment]
Thos are supported

**Comment by jeromeetienne** [comment]
@AndreaMonzini pattern markers and barcode markers are supported. and fully compatible with artoolkit c++
