### ISSUE TITLE
Problem using ARJS with OpencvJS

### ISSUE THREAD

**Issue by YasserManss** [jeromeetienne/AR.js#490]
I think that using two Emscripten dependent libraries in the same html page is causing problems. I think that the solution is to build ARjs with Emscripten option "-s MODULARIZE=1". If there is any instructions about how to rebuild the library (ARjs with threejs), please post it. Also, if anyone managed to use both Opencv js and ARjs, please share how you did it. 
Thank you in advance.

**Comment by JamesMilnerUK** [comment]
@YasserManss can you try with https://github.com/JamesMilnerUK/THREEAR and see if you have the same issue? I bundled in artoolkitjs so that might help if you're having namespacing issues.

**Comment by YasserManss** [comment]
@JamesMilnerUK Thank you very much sir! Your bundle works perfectly with opencvJS.

**Comment by nicolocarpignoli** [comment]
@YasserManss hey, so you managed to user OpenCV.js with AR.js with success? 
This could be very interesting for the AR.js future!
Can you tell us more, or give us a repository to look at?
Thank you in advance from the community!

**Comment by kalwalt** [comment]
> I think that using two Emscripten dependent libraries in the same html page is causing problems. I think that the solution is to build ARjs with Emscripten option "-s MODULARIZE=1". If there is any instructions about how to rebuild the library (ARjs with threejs), please post it. Also, if anyone managed to use both Opencv js and ARjs, please share how you did it.
> Thank you in advance.

@YasserManss Ar.js is based on [jsartoolkit5](https://github.com/artoolkit/jsartoolkit5) i can try to build with that option. It is not a proirity but i will try to do when i have a bit of time.

**Comment by evaristoc** [comment]
@JamesMilnerUK excellent, nice to know about your option!

@kalwalt adding the possibility to bundle opencvjs together arjs will be an interesting add on. I suspect there will be a bit of a conflict to solve.

**Comment by kalwalt** [comment]
@evaristoc yes i agree with you. But i have the suspect that It Is not so simple, It Is not sufficient to build jsartoolkit5 with the Modularize option...

**Comment by nicolocarpignoli** [comment]
Closing this issue due to dismission of this repository. New repository of AR.js will be up at https://github.com/AR-js-org/AR.js/

Feel free to re-open the issue there if still valid.
