### ISSUE TITLE
a-marker-camera barcode doesn't work on threejs version example

### ISSUE THREAD

**Issue by breezeLoganGithub** [jeromeetienne/AR.js#491]
The example link:
https://github.com/stemkoski/AR-Examples/blob/master/barcode.html
It's doesn't work,and I have try it on pc and andorid phone.

**Comment by janpio** [comment]
Any you are reporting this in the AR.js repository why exactly? The example does not use AR.js.

**Comment by breezeLoganGithub** [comment]
sure,the example is link is come from the ar.js readme file:
![error](https://user-images.githubusercontent.com/19275567/55206232-b4ee9600-5210-11e9-98cf-fd3cd5d0d62b.jpg)

**Comment by janpio** [comment]
Ok, then that links is definitely wrong @nicolocarpignoli 

Still, if you have a problem in another repository, you should report the error there and not here.

**Comment by nicolocarpignoli** [comment]
Yea, I will remove the link and add it on a 'Related Projects' section. Closing this issue, it is not related with AR.js but is a work from @stemkoski
