### ISSUE TITLE
is 'Get Started' script still working?

### ISSUE THREAD

**Issue by mercem** [jeromeetienne/AR.js#492]
**Describe the bug**
I'm just trying to run with most basic setup which is 10 lines of html. Camera opens but no object is shown on the marker. There is a 'markersAreaEnabled :false' text at the bottom. On the comment section of youtube video lots of people encountered same problem. What am I missing here? 

**To Reproduce**
Just wrote the sample 10 line code and opened my browser. 

**Expected behavior**
Same behavior as in youtube video

**Screenshots**
https://ibb.co/Qfb4gw3

**Smartphone (please complete the following information):**
 - Device: [iPhone6s+]
 - OS: [iOS11.3]
 - Browser [safari]

Adding console logs here:

**Comment by nicolocarpignoli** [comment]
Hi, you are right, thanks for that!
I see that is not working for me too. I think it uses an old version of aframe and also ar.js. Also, it uses <a-marker camera> entity that last time I saw it, it was not working (better use a static camera and a marker as a separate entity).

Tomorrow I will update this :)

**Comment by commentatorboy** [comment]
It works for me, if I update the versions. 
But it does not show the entire animation claimed. (Refer to the image)
![55518358_837395186615711_5343035261498425344_n](https://user-images.githubusercontent.com/1793964/55217154-160d6e00-51ff-11e9-8eb5-6d37711c36a0.png)

Source code here:
https://codepen.io/commentatorboy/pen/BbXvPW

**Comment by mercem** [comment]
@commentatorboy I am using exactly the same code that you have shared and still cant see anything on the marker. Can it be related to IOS?

@nicolocarpignoli  Can you tell me when you guys update the code?

**Comment by nicolocarpignoli** [comment]
If you are using Chrome on iOS, it won't work, it is a known issue. Try with Safari instead. This afternoon I will probably update that code on Readme, anyway

**Comment by nicolocarpignoli** [comment]
For now, if you need a quick working version (again, in ios only on safari), try with this:

```
<script src="https://aframe.io/releases/0.9.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.2/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
	<a-scene embedded arjs='sourceType: webcam;'>
                <a-marker preset='hiro'>
                    <a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
                 </a-marker>
                 <a-entity camera> </a-entity>
	</a-scene>
</body>
```

In here, I used a-entity static camera and a-marker instead of a-marker camera. Although I don't believe this is the problem in your case, try with this. Let us know if it works so we can understand better

**Comment by mercem** [comment]
Last example works like charm thank you!

Off topic: When I wrap a-scene with html elements in body it is not working properly. Is there a way to eliminate this because I'm trying to integrate it to my React project.

**Comment by nicolocarpignoli** [comment]
It is impossible to answer to this in general. If you have a specific issue, please provide an example. On a separate issue, this one only for the 'get started' bug :)
