### ISSUE TITLE
Using with React

### ISSUE THREAD

**Issue by mercem** [jeromeetienne/AR.js#493]
I am not sure if this is really feature request but it suits better than bug report.

**What is the current behavior?**
When I use get started code into react project, object does not appear on marker. When I change enclosing div element inside index.html to span, object appears but shifted like 20-30 cm away. I have tried this behavior with get started script and same problem occurs there as well.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
<body style='margin : 0px; overflow: hidden;'>
    <div>
      <a-scene embedded arjs='sourceType: webcam;'>
        <a-marker preset='hiro'>
          <a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
        </a-marker>
        <a-entity camera> </a-entity>
    </div>
 </body>
```

**What is the expected behavior?**
Works same as html element is not added.

**Comment by kalwalt** [comment]
HI @mercem that is a strange issue... have you tried not with a-frame but "regular" `AR.js` and could be interesting to know something more about your react setup/project. Maybe starting from the simplest situation to debug and isolate the problem. Could be that some React Component causing the issue? I am learning Gatsby  that is based on React, so i could give to you some little advice....

**Comment by mercem** [comment]
Hi @kalwalt, I used this piece of code because one of the contributors told me that the this is the most recent get started code. I use basic create-react-app project and I added this inside of a default App.js file. So it is just this code wrapped with div element.

As I said even without react when I just wrap this code with div element inside of a body it does not work.

**Comment by elailai94** [comment]
Hi @mercem, I am currently experimenting with AR.js and React as well. However, I can't get AR.js to load properly. Did you include the AR.js library in the index.html file in public folder or did you import the module after installing it through NPM? Thanks for your help.

**Comment by mercem** [comment]
I added to index.html but as I said, it does not work properly since index.html wraps app.js with html element :(

**Comment by andreyrd** [comment]
I've run into similar issues with Vue.js in the past, and ended up giving up.

I think the problem here is that AR.js is expecting to be the root element right inside of `<body>`. In general, AR.js makes a LOT of assumptions about the HTML structure.

As for loading the library, I've been able to load aframe with webpack, but AR.js is unfortunately not packaged in that way. I used [webpack-script-loader](https://github.com/webpack-contrib/script-loader) for AR.js.

**Comment by kalwalt** [comment]
@mercem @andreyrd i was able to make working the simplest example with aframe, if you want, try this code:

file `index.html`
```html
<!-- file index.html -->
<script src="./aframe.js"></script>
<script src="./aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
		<div id=marker></div>
	<script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
	<script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
	<script type="text/babel" src="af.js"></script>
</body>
```
and file `ar.js`
```javascript
'use strict';

const e = React.createElement;

class AF extends React.Component {

  render() {

    return (
      <div>
        <a-scene embedded arjs='sourceType: webcam;'>
       		<a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
       		<a-marker-camera preset='hiro'></a-marker-camera>
     	  </a-scene>
      </div>
    );
  }
}

const domContainer = document.querySelector('#marker');
ReactDOM.render(e(AF), domContainer);
```
`aframe.js` and `aframe-ar.js` must be in the same folder, i taken from the master branch 

In this test i didn't notice a shifting in the model, it was instead perfectly centered on the marker. 
I tryed also with npx, that is creating an app with create-react-app command, but i hadn't luck at this moment. Maybe i will post the result tomorrow with more time and with an explanation and some piece of code. I hope that this can be helpful... and i would see your results.

**Comment by mercem** [comment]
hi @kalwalt,

This is interesting workaround. Thank you for your effort. As you said I countered this problem when tried with create-react-app. I couldn't understand what is the difference between yours and create-react-app's except the minor differences.

**Comment by kalwalt** [comment]
@mercem as i said i tried with the `create-react-app` cli and but i received some errors while yarn was compiling. Though i don't remember now  exactly the error, maybe it's a question of Component location in the app. 
I agree with you that there are not such big differences... Only one note to your code: your <a-scene> tag miss an enclosing tag </a-scene> but i'm not sure that this was the source of the issue.
I also discovered from the [threejs page](https://threejs.org/) that there is a [react-vr](https://facebook.github.io/react-360/) plugin  i discovered that is based a lot on threejs maybe it can be proficient to investigate in.
I want to do other tests, maybe i will open a little repo to share these experiments....

**Comment by fega** [comment]
@kalwalt @mercem @andreyrd 

I got a solution for create react app :D!!!

1) set the a-scene in the root of the body tag, keep also the <div id="root"></div> where is the point where create react app mounts the react app

2) wrap the the ReactDOM.render function located on index.js inside a setTimeout, and give it a delay of one second or so.

let me know if that works for you :D

**Comment by kalwalt** [comment]
@fega Wow! Great news !  I will try to reproduce your steps and i will inform you of my result.... :smile:

**Comment by mercem** [comment]
@fega That's really really interesting solution mate grats!

@kalwalt Can you tag me to your result? I am really wondering if it works for you as well

**Comment by kalwalt** [comment]
Unfortunately i have no luck :sob: maybe i had something wrong. My code compile but nothing happens...
Not sure what you did @fega but my code is available in this repo: https://github.com/kalwalt/react-aframe-ar-test 
@mercem if you want to take a look, i will appreciate it.

> set the a-scene in the root of the body tag, keep also the` <div id="root"></div>` where is the point where create react app mounts the react app

i did but react already assign a `<div id="root"></div>` so not sure to understand, and it is not possible to assign another body tag ( you will recive an error!)

> wrap the the ReactDOM.render function located on index.js inside a setTimeout, and give it a delay of one second or so.

This is really necessary?

**Comment by fega** [comment]
@kalwalt Please check the changes in my pull request.

**Comment by kalwalt** [comment]
@fega i'm looking into your [PR](https://github.com/kalwalt/react-aframe-ar-test/pull/1) , but it seems that still something is not working, maybe some missed dependencies?

**Comment by kalwalt** [comment]
@fega @mercem i solved! For anyone else interested  this is the repo: https://github.com/kalwalt/react-aframe-ar-test

**Comment by fega** [comment]
@kalwalt hehe yes I forgot to add the deps to the index.html file, sorry! 

good to hear that you solved it :D

**Comment by kalwalt** [comment]
@fega no problem! It will be nice to use AR.j also as a package, i mean a node_module, i hope that in a future this will be possible.

**Comment by mercem** [comment]
@kalwalt node module package is mandatory for AR.js. I hope they make asap.

@fega @kalwalt Thank you both for your effort!

**Comment by kalwalt** [comment]
> @kalwalt node module package is mandatory for AR.js. I hope they make asap.
> 
> @fega @kalwalt Thank you both for your effort!

Agree with you! You are welcome :smile:

**Comment by nicolocarpignoli** [comment]
So I was thinking it is a common use case to have AR.js embedded on a framework App, like React.
I see you guys have achieved that! Can some of you have a repo for that? We can link it on the Readme under 'integrations with framework' section. it could be very useful for many devs.

**Comment by kalwalt** [comment]
@nicolocarpignoli yes absolutely! all my examples are here: [react aframe example](https://github.com/kalwalt/react-aframe-ar-test) and the other the first example i have to put online, bt all the code is written above.

**Comment by kalwalt** [comment]
You can find also the first example [here](https://github.com/kalwalt/react-AR-experiments/tree/master/react-aframe-ar)

**Comment by JustinStoddard** [comment]
One of the big benefits of using React is the ability to create Component Architectures. So, what if I want to use AR.js in one view/page/route in an application and not use it in another? Right now using Ar.js turns my entire application into an Web AR application. Thats because in React, the whole application is loaded between one div with an id of 'root' inside the index.html. You can see this taking place within the index.js if you use create-react-app. So, I think it would be beneficial to let users decide what parts of their apps contain WebAR elements and what parts dont, rather than having to deal with the entire app being an AR environment. Thoughts?

**Comment by nicolocarpignoli** [comment]
@JustinStoddard absolutely. I will wait for someone who has already tried integration with React.
 Please answer on this new thread about integrations with framework, also with react https://github.com/jeromeetienne/AR.js/issues/537

@kalwalt you have a solution for @JustinStoddard problem?

**Comment by nicolocarpignoli** [comment]
@JustinStoddard I see in this very thread that this issue has been already found and solved by https://github.com/jeromeetienne/AR.js/issues/493#issuecomment-490303718
and https://github.com/jeromeetienne/AR.js/issues/493#issuecomment-490685501
just try and let us know if it works also for you

**Comment by JustinStoddard** [comment]
@nicolocarpignoli Thank you!!

**Comment by JustinStoddard** [comment]
@nicolocarpignoli @kalwalt I've been messing around with different ways to render the AR.js stuff. I got it to work with react but then I wanted it to only show up on a particular route. Below was my fix for that.
```const renderApp = () => {
  if (window.location.pathname === "/webar") {
    return <div dangerouslySetInnerHTML={createMarkUp()}></div>
  } else {
    if (isMobile) {
      return <MobileLoader/>
    } else {
    return <WebLoader/>
    }
  }
}

const createMarkUp = () => {
  return {__html: '<a-scene embedded arjs><a-marker preset="hiro"><a-box position="0 0.5 0" material="color: yellow;"></a-box></a-marker><a-entity camera></a-entity></a-scene>'}
}

ReactDOM.render(
  <BrowserRouter>
    {renderApp()}
  </BrowserRouter>,
  document.getElementById('root')
);
registerServiceWorker();```

**Comment by JustinStoddard** [comment]
This allows me to use AR.js on different routes without it taking over the application.

**Comment by kalwalt** [comment]
@JustinStoddard my approach was very basic, just to test the simpler approach  to implement. I heaven't tried in a Component, and i think,as you point out, it's a reasonable idea. It is one of my next goal. Gald that you manage to make it works.

**Comment by JustinStoddard** [comment]
@kalwalt So, I've got it working but only in fullscreen mode. Have you run into this issue?

**Comment by JustinStoddard** [comment]
But if you inspect the page and take the "position: absolute" styles off the canvas element the object shows up.

**Comment by JustinStoddard** [comment]
@nicolocarpignoli Sorry for the spam. I'm just close to getting this working. When I'm not in full screen mode the default yellow box in the starter code isnt showing up as expected. I think this is the reason.
```<canvas class="a-canvas" data-aframe-canvas="true" width="2102" height="0"></canvas>```
For some reason the height of the canvas has defaulted to 0.

**Comment by JustinStoddard** [comment]
But when I enter full screen mode through the VR goggles button it changes to:
```<canvas class="a-canvas" data-aframe-canvas="true" width="2399" height="1799"></canvas>```

**Comment by nicolocarpignoli** [comment]
Great job @JustinStoddard !
Two things:
- can you share the code of the working example, hopefully with a repo?
- you are not supposed to user the VR toggle button ever. It is not useful, if not causing bugs, on AR.js, cause it is thinked for VR, not AR.

**Comment by nicolocarpignoli** [comment]
gusy please use https://github.com/jeromeetienne/AR.js/issues/537 that is an open issue about integrations

**Comment by joseocasioserra** [comment]
> @nicolocarpignoli Sorry for the spam. I'm just close to getting this working. When I'm not in full screen mode the default yellow box in the starter code isnt showing up as expected. I think this is the reason.
> `<canvas class="a-canvas" data-aframe-canvas="true" width="2102" height="0"></canvas>`
> For some reason the height of the canvas has defaulted to 0.

Same thing happening to me.  Did you find a fix?

**Comment by fega** [comment]
@joseocasioserra @nicolocarpignoli  I think you guys will need to edit and css and attributes manually until you get it working, probably every use case is different and will not a valid solution for all.

**Comment by joseocasioserra** [comment]
@fega I have tried to play around with the attributes which results in offsets in the 3d object. I think  it might have something to do with the rendering on react and calculating the height of the canvas since it is forced to 0 even if you try change it. 

One approach I tried was change the position from 'absolute' to something else and that results in offsets which is also problematic. I will leave it for now since it seems it's a bigger issue that just simple CSS management. 

Thanks for the prompt reply!

**Comment by nicolocarpignoli** [comment]
> But when I enter full screen mode through the VR goggles button it changes to:
> `<canvas class="a-canvas" data-aframe-canvas="true" width="2399" height="1799"></canvas>`

this is true, I had same problem. Have to investigate what caused it

**Comment by JustinStoddard** [comment]
@joseocasioserra I have not found a fix. I've ben trying to edit the CSS manually but regardless of what I do it doesn't want to budge.

**Comment by joseocasioserra** [comment]
@JustinStoddard Same issue here. I tried a couple of things, but there seems to be some code on the library that resizes elements. I guess we need to wait for a fix

**Comment by denisstasyev** [comment]
Hello, everyone! It looks like I have found one more way how to implement AR.js into React to use it as React Component. [Here](https://github.com/denisstasyev/AR-Test) you can check my attempt.

**Comment by denisstasyev** [comment]
I made a separate repository with the results of my work and tips for embedding AR.js in React. You can find it [here](https://github.com/denisstasyev/AR-Test-2). Hope it will help a lot of people.

It contains an implementation of AR.js as a React Component for any projects. You can see this component [here](https://github.com/denisstasyev/AR-Test-2/blob/master/src/components/ViewerVR/ViewerVR.js).
