### ISSUE TITLE
[Solved issue] Black objects and/or material when using aframe box or 3D files

### ISSUE THREAD

**Issue by commentatorboy** [jeromeetienne/AR.js#494]
A related issue is here:
https://github.com/jeromeetienne/AR.js/issues/325

**_The problem_**
Multiple problems. When adding an a-frame object (like a-box) or using gltf, obj, or similar 3D filetypes the objects become black.

This occurs only on some smartphones like my moto e5. 

**_In depth about the problem_**
Kind of hard to reproduce the problem since it only occurs on some smartphones.
The problem is related to rendering and how three.js handles it.
More about the issue here: https://github.com/mrdoob/three.js/issues/14137
A demonstration for the problem:
https://github.com/mrdoob/three.js/issues/14137#issuecomment-397856954

People have also this issue with it in aframe.
Here is a related issue: https://github.com/aframevr/aframe/issues/3523

**_The solution_**
The solution is using another precision renderer as described below:
https://aframe.io/docs/0.9.0/components/renderer.html#precision
Go to this website to see it working:
https://www.internet-guiden.dk/nomarker
Here is the source code:
https://jsfiddle.net/gwo2y4dn/

**_Notice_**
Make sure that when using a-box set the following property: `material='color: green';`. (green is just an example).
Make sure that you color 3D object in blender or similar software. If you just created a 3d cube object in blender and then export it, the 3D object will not show colors.

**_Results/Examples_**
These are some examples of when it does not work and when you apply the precision to lowp or mediump. Please refer to the images below.

Any feedback and/or question is appreciated.

![55478644_1095317373987784_7322158777065537536_n(1)](https://user-images.githubusercontent.com/1793964/55250689-103f7900-524f-11e9-9ecb-b06c76e0c3ad.jpg)
![55517404_2234166103502458_881576354292695040_n(1)](https://user-images.githubusercontent.com/1793964/55250690-103f7900-524f-11e9-95ac-363db3fb50a7.jpg)

**Comment by andreyrd** [comment]
If this is solved, we should probably close the issue.

But perhaps let's first add to FAQ/README about this issue?

**Comment by commentatorboy** [comment]
@andreyrd Yeah. I can create a FAQ about this issue.
I think it would be more appropiate to have it in the WIKI.

**Comment by kalwalt** [comment]
@commentatorboy @andreyrd I also encountered this issue with a Wiko View device, can't see the colours of simple meshes, adding  `renderer='precision: medium'` in te a-scene tag solved it. I think this should be added in a FAQ list. Note also that is not related to AR.js but exclusively to aframe.

**Comment by commentatorboy** [comment]
@kalwalt Yeah. Unfortunately I do not have time right now to do it. I am trying to find a job. 
But will update it here when I do.

**Comment by kalwalt** [comment]
@commentatorboy Good luck for the job research! i will look if i have time for this FAQ....
