### ISSUE TITLE
gltf code for model not compatible with custom marker

### ISSUE THREAD

**Issue by TumblinDwnAgain** [jeromeetienne/AR.js#496]
**Describe the bug**
[UPDATED: I have been grappling with getting my custom 3D models and custom markers to work together, and having the models appear and appearl undistorted seems to be a recurring issue with my code] **My gltf files are being referenced correctly on the markers, but they are glimpsing in and out of the camera view**

**To Reproduce**
1. Download model from Sketchfab as gtlf
2. upload the gtlf and bin file onto Github site (they are in the same folder)
3. Use Raw url from gtlf file and paste it into code (below)
4. Test with custom marker
5. Distorted content 

This is the code I am utilizing:
```
<<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
    <<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
      <a-gltf-model src="https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/spore_2_attempt_1/scene.gltf"></a-gltf-model>
      <a-marker preset='custom' type='pattern'  url='https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/Markers/MarkerS1240.patt' ></a-marker-camera>
      <a-entity scale="0.01 0.01 0.01">
      <a-camera-static/>
    </a-scene>
</body>
```

This is the [marker](https://github.com/pr0bes/pr0bes.github.io/blob/master/MarkerS1240.png) I am using

**Expected behavior**
I expect to see a 3D model appear above the custom marker without any distortion.

**Screenshots**
![IMG_592400DAF6D2-1](https://user-images.githubusercontent.com/47367954/55498728-53fcfe80-5612-11e9-9364-3b5599b1804f.jpeg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone7

**Additional context**
I hope that I am simply incorrectly writing the scaling aspect of the code and I have looked for other solutions to these glitches, but have yet to find a solution for my code.

Where is the error coming from?

Please let me know if there is additional information I need to provide to help find a solution. Any guidance/direction on what I should look into and change is greatly appreciated.

**Comment by commentatorboy** [comment]
2 things:
1. Try and use this method instead. https://aframe.io/docs/0.9.0/components/gltf-model.html#sidebar
By that I mean try and use the following code: 
`<a-scene>
  <a-assets>
    <a-asset-item id="tree" src="/path/to/tree.gltf"></a-asset-item>
  </a-assets>

  <a-entity gltf-model="#tree"></a-entity>
</a-scene>`

2. Try and upgrade aframe from 0.8.0 -> 0.9.0

**Comment by andreyrd** [comment]
I can't get the URL in the screenshot to show any model, not even a flickering model.

I'm not sure if this is just how you typed your snippet, but there are several general HTML errors:
```html
<<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
    <<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
      <a-gltf-model src="https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/spore_2_attempt_1/scene.gltf"></a-gltf-model>
      <a-marker preset='custom' type='pattern'  url='https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/Markers/MarkerS1240.patt' ></a-marker-camera>
      <a-entity scale="0.01 0.01 0.01">
      <a-camera-static/>
    </a-scene>
</body>
```

First of all there's the `<<`. That fixed, plus cleaned up a bit:
```html
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
      <a-gltf-model src="https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/spore_2_attempt_1/scene.gltf">
      </a-gltf-model>
      <a-marker preset='custom' type='pattern' url='https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/Markers/MarkerS1240.patt'>
      </a-marker-camera>
      <a-entity scale="0.01 0.01 0.01">
      <a-camera-static/>
    </a-scene>
</body>
```

The gltf model that you are attaching to the marker needs to be *inside* of the `<a-marker>` element:
```html
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
      <a-marker preset='custom' type='pattern' url='https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/Markers/MarkerS1240.patt'>
        <a-gltf-model src="https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/spore_2_attempt_1/scene.gltf">
        </a-gltf-model>
      </a-marker-camera>
      <a-entity scale="0.01 0.01 0.01">
      <a-camera-static/>
    </a-scene>
</body>
```

You open with `<a-marker>` and close with `</a-marker-camera>`. I'm sure most browsers are correcting this specific one, but could cause other problems.

```html
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
      <a-marker preset='custom' type='pattern' url='https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/Markers/MarkerS1240.patt'>
        <a-gltf-model src="https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/spore_2_attempt_1/scene.gltf">
        </a-gltf-model>
      </a-marker>
      <a-entity scale="0.01 0.01 0.01">
      <a-camera-static/>
    </a-scene>
</body>
```

It then looks like you tried to scale things, and opened a new `<a-entity>` with a `scale` component. But that shouldn't just go anywhere, and where it is right now, it ends up applying to the camera and breaking it, which is why I wasn't seeing anything at all!

The correct way is to actually use the `scale` component directly on the `<a-gltf-model>` element:
```html
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
      <a-marker preset='custom' type='pattern' url='https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/Markers/MarkerS1240.patt'>
        <a-gltf-model src="https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/spore_2_attempt_1/scene.gltf">
        </a-gltf-model>
      </a-marker>
      <a-camera-static/>
    </a-scene>
</body>
```

And finally, updated to use the latest versions of aframe (0.9.0) and AR.js (1.6.2). Note that with the latest versions the camera should be defined with `<a-entity camera></a-entity>` and not `<a-camera-static/>` or else the position of the object will be wrong.
```html
<script src="https://aframe.io/releases/0.9.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.2/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
      <a-marker preset='custom' type='pattern' url='https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/Markers/MarkerS1240.patt'>
        <a-gltf-model src="https://raw.githubusercontent.com/TumblinDwnAgain/TumblinDwnAgain.github.io/master/spore_2_attempt_1/scene.gltf">
        </a-gltf-model>
      </a-marker>
      <a-entity camera></a-entity>
    </a-scene>
</body>
```

Here's a glitch of the above that you can try out with your marker:
Page: https://protective-gull.glitch.me
Code: https://glitch.com/edit/#!/protective-gull

Hope this is helpful :)

**Comment by nicolocarpignoli** [comment]
great @andreyrd !
