### ISSUE TITLE
How to know that an image matches the marker?

### ISSUE THREAD

**Issue by hall-effect** [jeromeetienne/AR.js#497]
**Is your feature request related to a problem? Please describe.**

I want to do something when I match the marker. 
But, I read all example and issues, can't find a solution.

**Describe the solution you'd like**

I hope open some APIs, for example

```js
ar.matchMarker(function() {})
```

**Comment by nicolocarpignoli** [comment]
Hi, 
take a look at this PR that was merged some time ago, it permit to emits and listen to events when a marker is found and lost. I think it can suit with your needs.

https://github.com/jeromeetienne/AR.js/pull/303

**Comment by hall-effect** [comment]
I found the solution at:  
https://stackoverflow.com/questions/44799413/how-to-detect-when-a-marker-is-found-in-ar-js

the solution also from nicolocarpignoli comment PR.  

thanks,   
(oﾟvﾟ)ノ
