### ISSUE TITLE
A-frame 0.9.0 incompatibility

### ISSUE THREAD

**Issue by gavan1** [jeromeetienne/AR.js#498]
3D object position not positioned correctly over hero Marker with a-frame 0.90

```
<html>
    <head>
     <script src="https://aframe.io/releases/0.9.0/aframe.min.js"></script>
   <script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script> 
</head>

<body style='margin : 0px; overflow: hidden;'>
        <a-scene embedded arjs='sourceType: webcam;'>
                <a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
                <a-marker-camera preset='hiro'></a-marker-camera>
            </a-scene>
	</a-scene>
</body>

  </html>
```

![UNADJUSTEDNONRAW_thumb_3139](https://user-images.githubusercontent.com/40079787/55526110-b3b8df80-56ce-11e9-960b-64e76e7b0988.jpg)

Works fine with a-frame 0.8.2

```
 <head>
     <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
   <script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script> 
</head>
```

![UNADJUSTEDNONRAW_thumb_3138](https://user-images.githubusercontent.com/40079787/55526344-b405aa80-56cf-11e9-9496-c5de2dde671f.jpg)

 - Device: iPhone XS max
 - OS: iOS 12.1.4 (latest as of April /2019)
 - Browser: ios safari + chrome

Hoping to get AR.js working with a-frame 0.9.0!

Thanks.

**Comment by nicolocarpignoli** [comment]
Hi, first of all try again using a printed marker (and possibly put the HIRO marker on a white or light color surface, to make the marker stand out better). Let us know if the bug shows again.

I can tell that I updated on README and on my experiments to 0.90 of a-frame and found NO differences at all. So this might be a bug of latest Safari with a-frame 0.9.0.

**Comment by andreyrd** [comment]
Your pasted example URL has `<a-box>` outside of the `<a-marker-camera>`, and has the `</a-scene>` closing tag twice. Here is an updated example on glitch.me: https://glitch.com/~actually-macaroon

Putting the `<a-box>` inside of the `<a-marker-camera>` fixes it.

It does look like aframe 0.8.2 works with the unfixed version, but I believe that having the object outside of the marker is territory for undefined behavior, and should not be relied upon. Is there a specific reason that the object is not inside of the marker?

**Comment by EdieJoMurray** [comment]
andreyrd your glitch.me example doesn't seem to work for me - can you confirm it's still working for you? (so I know it's something on my end!)

**Comment by andreyrd** [comment]
Hey, it works for me on an iPhone 8 using Safari.
You have to visit the non-embedded version of the glitch on the device:
https://actually-macaroon.glitch.me/

![IMG_AE845D95AAD3-1](https://user-images.githubusercontent.com/2107076/57945017-978f8d00-788d-11e9-9783-0328fce5207d.jpeg)
