### ISSUE TITLE
How does this differ from other JS AR libs?

### ISSUE THREAD

**Issue by marklundin** [jeromeetienne/AR.js#5]
Hey! Would be great to know how this library differs from  some of the other CV/AR libs out there. Also is this just a wrapper/abstraction around ARToolkit/Three or is there something other magic going on underneath the hood ?

Keep up the good work!

**Comment by jeromeetienne** [comment]
it is mainly the performance i think. 

But please dont trust me, do you own comparison, and use the AR solution that fit your need.
