### ISSUE TITLE
link THREEx.ArToolkitContext.baseURL to local three.js folder

### ISSUE THREAD

**Issue by kurai021** [jeromeetienne/AR.js#50]
why not to change

THREEx.ArToolkitContext.baseURL = 'https://jeromeetienne.github.io/AR.js/three.js/

for local three.js folder in aframe-ar.js? could be better for offline demos.

**Comment by jeromeetienne** [comment]
it was a relative url until very recently. It is ok for the user to set it to whatever value you like. I changed the default recently to the official homepage. as it is more generic and make teaching easier.

i hope it answer your question

Personnally i set it to a local relative url. e.g. in three.js/examples i add

```
<script>THREEx.ArToolkitContext.baseURL = '../'</script>
```

**Comment by tcwyjno1** [comment]
@jeromeetienne can u explain how the carema can read the pic with a word hiro in the demos.
How it works?

**Comment by jeromeetienne** [comment]
I use webrtc to read the webcam

**Comment by BetoRincon** [comment]
@jeromeetienne  could you please explain me a little bit more how to  link `<script>THREEx.ArToolkitContext.baseURL = '../'</script>` with local files... Something like @kurai021 said. I dont't undestand :(. 

Your work is amazing! :1st_place_medal:

**Comment by sjraziva** [comment]
<script>THREEx.ArToolkitContext.baseURL = '../'</script> 
please explain this code a little deeper

**Comment by ahfathi** [comment]
Would you please explain how did you resolve thee issue?

We're using [this repository](https://github.com/lbelfield/augmented-reality), whenever we import the `import { AFrameRenderer, Marker } from 'react-web-ar';` and run the following piece of code, we face with the same error:

```
import React, { Component } from 'react'

import { AFrameRenderer, Marker } from 'react-web-ar';


export default class Camera extends Component {
    render() {
        return (
            <AFrameRenderer arToolKit={{ sourceType: 'webcam' }}>

            <Marker parameters={{ preset: 'hiro' }}>
              <a-box position="0 0.5 0" material="opacity: 0.5; side:double; color:red;">
                <a-torus-knot radius="0.26" radius-tubular="0.05">
                  <a-animation attribute="rotation" to="360 0 0" dur="5000" easing="linear" repeat="indefinite" />
                </a-torus-knot>
              </a-box>
            </Marker>
    
            <Marker parameters={{ preset: 'kanji' }}>
              <a-box position="0 0.5 0" material="opacity: 0.2; side:double; color:blue;">
                <a-octahedron opacity="0.5" radius="0.6" radius-tubular="0.05" color="yellow">
                  <a-animation attribute="rotation" to="0 360 0" dur="5000" easing="linear" repeat="indefinite" />
                </a-octahedron>
                <a-octahedron radius="0.26" radius-tubular="0.05" color="white">
                  <a-animation attribute="rotation" to="360 0 0" dur="5000" easing="linear" repeat="indefinite" />
                </a-octahedron>
              </a-box>
            </Marker>
    
          </AFrameRenderer>        )
    }
}
```
