### ISSUE TITLE
Do you have any demo example of markerless Arjs? 

### ISSUE THREAD

**Issue by soultrue** [jeromeetienne/AR.js#500]
I have checked several articles of ARjs but all using AR frame and marker to display the object. Is there a way to implement markerless AR using Arjs and ARframe only without using any other pakaze or library.

Sample code:

<script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>

<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs>
    
    <a-box position='0 0.5 0' material='opacity: 0.5;'></a-box>
    
    <a-marker-camera preset='hiro'></a-marker-camera>
  </a-scene>
</body>

**Comment by janpio** [comment]
Simple answer: No, AR.js is a thing for marker based AR.
More complicated answer: There might have been working experiments with image based AR in the past, but their state etc. are unknown and not documented.

**Comment by soultrue** [comment]
Thanks

**Comment by nicolocarpignoli** [comment]
https://github.com/jeromeetienne/AR.js/issues/171
https://github.com/jeromeetienne/AR.js/issues/190
