### ISSUE TITLE
Using a button inside a-scene to start a video

### ISSUE THREAD

**Issue by h33ler** [jeromeetienne/AR.js#504]
Hey there!

I'm working on a project where i've to start a video which is placed inside a-scene with a button also placed inside a-scene.

I tried alot but nothing worked so far. 

For the buttons inside a-scene i'm using the [https://www.npmjs.com/package/aframe-event-set-component](url) which allows me to set up custom events for an entity itselfs or another entity as a target. I can set parameters like visible="" autoplay (i.e. for an animation on the target object) ="" etc.. 

I knew that my video needs a workaround to start on mobile devices (in my case iOS) like an event trigger or something like that. But everything i tried so far doesnt give me the desired behavior.

The last thing i tried was using the play-on-window-click.js script from the a-frame example [https://glitch.com/edit/#!/aframe-360-video-example](url) on my a-video. That worked well on iOS until i tried to combine it with the aframe-event-set-component which requires adding cursor="rayOrigin: mouse" to my scene.

I guess that cursor="" blocks the screen space click detection which is needed by play-on-window-click. 

Thats my code:

```
<html>
	<head>
		<meta charset="utf-8">
		<title>A-Frame Effects</title>
		<meta name="description" content="A-Frame Effects - Spheres">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta aframe-injected="" name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,shrink-to-fit=no,user-scalable=no,minimal-ui"><meta aframe-injected="" name="mobile-web-app-capable" content="yes"><meta aframe-injected="" name="theme-color" content="black">

		<script src="scripts/a-frame/lib/aframe.js"></script>
		<script src="scripts/aframe/build/aframe-ar.js"></script>
		<script src="https://unpkg.com/aframe-event-set-component@4.2.1/dist/aframe-event-set-component.min.js"></script>
		<script src="https://unpkg.com/aframe-animation-component@4.1.2/dist/aframe-animation-component.min.js"></script>
		<script src="https://rawgit.com/mayognaise/aframe-mouse-cursor-component/master/dist/aframe-mouse-cursor-component.min.js"></script>
		<script src="scripts/play-on-window-click.js"></script>

	</head>

 <body style='margin : 0px; overflow: hidden; width: 100%; height: 100%'>

	<a-scene embedded arjs="debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 3x3;" renderer="antialias: true; colorManagement: true; sortObjects: true; logarithmicDepthBuffer: true;" vr-mode-ui="enabled: false" >

		<a-camera look-controls-enabled="false" near="0.1" far="20" camera="" cursor="rayOrigin: mouse"  position="" rotation="" look-controls="" wasd-controls="">

		</a-camera>

		<a-assets>
		<video id="video" autoplay loop crossorigin="anonymous" playsinline webkit-playsinline src="https://cdn.glitch.com/e614a6f8-f4ba-4733-8a7c-e61e5d59427e%2Fd55bddf8d62910879ed9f605522149a8.mp4?1551541382508"></video>
		<a-asset-item id="profilbild" src="assets/profilbild.jpg"></a-asset-item>

		</a-assets>

		<!-- Ancherpoint smooth="true" -->
		<a-marker id="barmarker" type="barcode" value="6">

			<!-- AR Inhalte -->

			<a-video id="myvideo" play-on-window-click  src="#video" scale="5.5 3.1 1" rotation="-100 0 0" position="-0.573 0.186 2.786" material="" geometry=""

				animation__video_scale="property: scale; from: 0 0 0; to: 5.5 3.1 1; dur: 1000; easing: easeInOutElastic; autoplay: false"
				animation__video_descale="property: scale; from: 5.5 3.1 1; to: 0 0 0; dur: 1000; easing: easeInOutElastic; autoplay: false"

			></a-video>

			<a-plane id="videobutton"  position="-0.358 0 0.186" rotation="-90 0 0" scale="1.5 1.5 1.5" color="#7BC8A4" material="color:#fefcff;src:assets/abutton.png;transparent:true;shader:flat" visible="true" geometry="" material.color="#5e5e5e"

					animation__vidbtn_rotate="property: scale; from: 1.2 1.2 1.2; to: 1.3 1.3 1.3; dur: 1000; easing: easeInOutQuad; dir: alternate; loop:true; autoplay: true"

          event-set__videoraise="_event: mousedown; _target: #myvideo;  visible: true; animation__video_scale: autoplay: true"

			></a-plane>

		</a-marker>

	</a-scene>
 </body>
</html>
```

Thats my problem.. I'm also not a native programmer so i collected all my knowledge from here. Maybe one of you guys have the right hints for me :-)

**Comment by thor-brickman** [comment]
I was playing with this a bit ago and got something to work.  Don't know if it will be useful, but you can look at it, here.

https://github.com/thor-brickman/thor-brickman.github.io/tree/master/LayerOne2019

**Comment by h33ler** [comment]
> I was playing with this a bit ago and got something to work. Don't know if it will be useful, but you can look at it, here.
> 
> https://github.com/thor-brickman/thor-brickman.github.io/tree/master/LayerOne2019

Thanks for your reply! Did it worked also with iOS for you ? I tried to implement your way into my project. The material change from png to the mp4 worked well but the video doesnt start either.

**Comment by thor-brickman** [comment]
I only just tried testing things out on iOS.  I'll be doing that this weekend, so maybe I will have news. :-)

**Comment by h33ler** [comment]
I tested it today with my Macbook and Safari.. Of course it works fine .. arrgh. But still no luck on iOS.

**I modified your event.js a bit:**


AFRAME.registerComponent('screenhandler', {
    init: function() {
        console.log("In Init for Screen Handler");
        var el = this.el;
        el.addEventListener('click', function(){
            // console.log("Click event heard.");
            el.setAttribute("material","src", "#video");
            var videoEl = document.querySelector('#video');
            el.setAttribute("visible", true);
            console.log("Playing Video");
            videoEl.play();
        });
}});

**And thats the code from play-on-window-click.js**


AFRAME.registerComponent('play-on-window-click', {

  init: function () {
    this.onClick = this.onClick.bind(this);
  },
  play: function () {
    window.addEventListener('click', this.onClick);
  },
  pause: function () {
    window.removeEventListener('click', this.onClick);
  },
  onClick: function (evt) {
    var video = this.el.components.material.material.map.image;
    if (!video) { return; }
    video.play();
  }
});

Using this, the video starts on click with iOS but the event-set-component doesnt work.. I really have no clue how to solve this.

**Comment by thor-brickman** [comment]
So did you make these mods against the html from my project, or yours.  Without knowing the html you are running this javascript against, it's hard to say anything useful. :-)

**Comment by h33ler** [comment]
I looked at your html and changed mine. As i wrote earlier, the material change works so the click is detected i think. On Mac OS the Video Starts on click. 

The only problem i got is to play the Video on iOS. 

I‘m posting the html in a couple of hours. Currently trying to get some sleep. In Germany its in the middle of the Night :-)

**Comment by thor-brickman** [comment]
Hee...no worries.  I will take a look when you post.

**Comment by h33ler** [comment]
I uploaded my html and booth .js files in my repo: https://github.com/h33ler/video_AR

Thanks for your help! Really appreciate it!

**Comment by h33ler** [comment]
Tried some variations in the meantime.. Maybe iOS doesnt allow to start a video with an event triggered inside a-scene ? So that only events which are triggered outside a-scene can play a video. And play-on-window-click is working becouse it listens to clicks triggered directly on the screenspace ? 

Just an idea to explain the case..

**Comment by thor-brickman** [comment]
So I will admit a little black box syndrome in how I have been using this, but after looking at your code, there are a few things I can point you at that might work.

To get mine to work, I had to explicitly create the cursor entity in the camera entity.  I know that what you have should be the same, but I didn't manage to get that to work and never figured out why.

I have since found that putting ' autoplay="false" loop="false"' has the opposite effect since they are not booleans and having any value is interpreted as an 'on' switch.  Again, this is just my experimentation.

My most recent project in AR is here: https://github.com/thor-brickman/thor-brickman.github.io/tree/master/WalkAbout2019.  It's in progress but it has been tested on an iPhone and seems to work.  There is other madness in there around chroma-key, but there may also be something that would get you up and running.

Sorry that I can't offer a more technical answer, but I am very much an end user of this and have not delved into the innards of AR.js, ARtoolkit, or A-Frame any further than I've needed to for any particular effort.

Hope something in there helps. :-)

**Comment by thor-brickman** [comment]
Oh...and I tried set-component and gave up on it on the way to a solution.  It may work perfectly, but I never managed to make that happen with AR.js.

**Comment by nicolocarpignoli** [comment]
confirming some things showed up here: from a-frame doc

https://aframe.io/docs/0.9.0/primitives/a-video.html

```
iOS has a lot of restrictions on playing videos in the browser. To play an inline video texture, we must:

Set the <meta name="apple-mobile-web-app-capable" content="yes"> meta tag. A-Frame will inject this if missing.
Set the webkit-playsinline and playsinline attribute to the video element. A-Frame will add this to all videos if missing).
Since iOS 11, iOS has required user interaction to trigger video playback. This is also true on a number of Android device and browser combinations.



```
