### ISSUE TITLE
remain object coordinates in scene when marker is off camera?

### ISSUE THREAD

**Issue by aerchit** [jeromeetienne/AR.js#505]
Is there a way to remain the object in the last seen coordinates when marker is off camera?

so if I turn my camera away from marker, the object still response to camera rotation like in a-frame?

an alternative way I tried is to use a-maker-camera, but the object was fixed to screen position, not world coordination, not the behavior I want.

any ideas please? :)

**Comment by droid001** [comment]
You could in fact do this with placing a hidden object in the marker and feed the global coorss to your model which recides outside the marker. You would need to somehow get accellerameter values for zooming when the marker is not detected. This isn't trivial though as you'dd need to gather stats on the sensors data compared to the marker position when detection is lost and found again or else the model will jump around.

**Comment by aerchit** [comment]
Sorry, I am new, and this sounds a lot complex than I expect... 
basically I was looking for a way to keep displaying object when marker is off camera,
After some search I found it is not possible, unless using SLAM.
but I wonder if it is possible to fake it, e.g. when the marker is visible, put object on it, when marker is off camera, record its last position and let gyro take over, so objects still response to phone rotation like a-frame does. When a marker is visible again, the marker position will overwrite object position.
Again, I am a layman to coding.....

**Comment by janpio** [comment]
Of course that is possible, you described the logic behind it - but nobody has written that code. Problem is that this wouldn't look and "feel" good or natural in any way to the user.

**Comment by aerchit** [comment]
thanks for your opinion, I was quiet surprised no one tried it before,
this may solve occasional lost-tracking issue, keep object say in the scene.  I think it worth a try?

**Comment by sjraziva** [comment]
I have this problem too ... please write your solution code

**Comment by droid001** [comment]
@janpio The experience would probably feel a bit weird if the solution was just to use the giro sensors and the effect would be like in VR, but if you could also get in depth perception with the accelerometer sensor then I think the transition would work. There's just quite a bit of work to get this to really function and that involves gathering statistical data from the sensor and and using that to auto correct positioning in relation to the marker when it's found again.
