### ISSUE TITLE
Add links to glitter AR.js/lobby and the AR.js Trello to the Readme.

### ISSUE THREAD

**Issue by thor-brickman** [jeromeetienne/AR.js#506]
**Is your feature request related to a problem? Please describe.**
It would be nice to steer people to a place for more interaction with questions as well as something that shows things aren't dead, yet. :-)

**Describe the solution you'd like**
Perhaps the following links in the Status section of the Readme:
https://trello.com/b/63F7JlvD/arjs
https://gitter.im/AR-js/Lobby

**Describe alternatives you've considered**
Don't really have any, though I guess it could also go under 'What's Next' or 'Last but not least'

**Additional context**
There's a good start on picking this back up, but the pieces still seem disconnected...this might help.

**Comment by nicolocarpignoli** [comment]
Sounds good! Can someone make a simple 2 PR for this, on both dev branch and master?

**Comment by thor-brickman** [comment]
I will make an attempt at that.  Sounds like a good way to get started with pull requests. :-)
