### ISSUE TITLE
How to enable 6x6 barcode marker.

### ISSUE THREAD

**Issue by ksankark** [jeromeetienne/AR.js#509]
**Is your feature request related to a problem? Please describe.**
I am planning to use a 6x6 barcode marker similar to ARToolkit. Since here, the options are only available till 4x4 marker. Looking for help to enable the 6x6 barcode marker

**Describe the solution you'd like**
Should able to recognize 6x6 barcode marker.

**Describe alternatives you've considered**
It is available in ARToolkit so there might be a way to enable here too.

**Additional context**
![marker](https://user-images.githubusercontent.com/4627431/56483864-18a37080-64ea-11e9-984b-9fab83ed4195.gif)

**Comment by nicolocarpignoli** [comment]
On 'arjs' attribute on a-scene element, you can specify matrixCodeType:
on the following example i'm using 3x3 standard

```
<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 3x3;'>
```

See here for valid values:

https://github.com/jeromeetienne/AR.js/blob/master/three.js/README.md

**Comment by thor-brickman** [comment]
So I could be wrong, but I believe the 6x6 markers are actually from ARtoolkitPlus, not the vanilla ARtoolkit.

https://github.com/paroj/artoolkitplus

**Comment by ksankark** [comment]
> On 'arjs' attribute on a-scene element, you can specify matrixCodeType:
> on the following example i'm using 3x3 standard
> 
> ```
> <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 3x3;'>
> ```
> Never tried other values than 3x3, you can try :)
> 
> Do you have already tried this? what you mean with 4x4 is this?

I tried the below type of matrix code (2D barcode) in use. Options include:
                AR_MATRIX_CODE_3x3
                AR_MATRIX_CODE_3x3_HAMMING63
                AR_MATRIX_CODE_3x3_PARITY65
                AR_MATRIX_CODE_4x4
                AR_MATRIX_CODE_4x4_BCH_13_9_3
                AR_MATRIX_CODE_4x4_BCH_13_5_5
                The default mode is AR_MATRIX_CODE_3x3.
All are working.

But I want to use 6x6 one.
4x4 I mean is the barcode matrics of four columns and four rows.

**Comment by ksankark** [comment]
> So I could be wrong, but I believe the 6x6 markers are actually from ARtoolkitPlus, not the vanilla ARtoolkit.
> 
> https://github.com/paroj/artoolkitplus

Hi, It is available in vanilla ARtoolkit itself but in a commented form, just need to uncomment there to use it.

**Comment by willxvi** [comment]
Is there any update on how can we use a 5x5 or a 6x6 barcode ?

**Comment by nicolocarpignoli** [comment]
nope, there will not be realistically speaking. It's in the artoolkit core that is not in development anymore, apart from NFT feature (image target tracking )

**Comment by kalwalt** [comment]
You cann't use them because they are  not included in the jsartoolkit5 base:
https://github.com/artoolkitx/jsartoolkit5/blob/244b2b23286403e78fa24805b34509dc5a88052f/emscripten/ARBindEM.cpp#L101-L106
but are availble in the artoolkit lib:
https://kalwalt.github.io/artoolkit-docs/3_Marker_Training/marker_barcode.html
of course it's possible to add them, i think that is not a difficult task. But we can do with the new jsartoolkit5 lib.
