### ISSUE TITLE
threejs examples parameters-tuning.html

### ISSUE THREAD

**Issue by sorianog** [jeromeetienne/AR.js#51]
@jeromeetienne Here is the issue

**Comment by jeromeetienne** [comment]
The goal is to expose a html UI with all the parameters for source/context/markers. It aims to help people understand and tune AR.js parameters.

- context parameters - https://github.com/jeromeetienne/AR.js/blob/master/three.js/threex-artoolkitcontext.js#L9
- source parameters - https://github.com/jeromeetienne/AR.js/blob/master/three.js/threex-artoolkitsource.js
- controls parameters - https://github.com/jeromeetienne/AR.js/blob/master/three.js/threex-armarkercontrols.js

**Comment by jeromeetienne** [comment]
### About parameters formats
- some parameters are number, or string, or part of a set of value
- the html <input> should reflect those and prevent invalid combinasion. Thus it helps people learns relation between parameters
- about which value are ok or not, there is some short help in the source. 

i will obvious help as we go :)

**Comment by jeromeetienne** [comment]
and thanks for your contribution :)

**Comment by jeromeetienne** [comment]
here is a old-no-more-working version of that

https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/demo.html

This one is in a-frame. but it may help on how to build the html <input>

**Comment by sorianog** [comment]
@jeromeetienne Thanks for the info. I'll get to work on this when I can!

**Comment by sorianog** [comment]
If I understand correctly, you would like a separate HTML page to be created that will allow users to specify ARToolKit parameters through UI Inputs? If inputs are invalid, I can implement error messages that will pop up on the page for users to see. Now if that's the case, I'll have to see where the best place is to create this new page ;)

**Comment by jeromeetienne** [comment]
here is an old incomplete example i found https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/parameters-tunning.html

the ui is simple HTML5, then based on all those <input> we build the paramteres for source/context/markers

**Comment by sorianog** [comment]
@jeromeetienne What I have so far from modifying the html you linked previously:
![image](https://cloud.githubusercontent.com/assets/13261711/26135512/9aca872e-3a7b-11e7-9b06-422ca09f9a92.png)

How does it look so far?

**Comment by jeromeetienne** [comment]
seems very good! can you put that in a repo and do a pull request ? thus we
can easily run it

**Comment by RonHouben** [comment]
@nicolocarpignoli, can you please close this issue?

There already has been a merged PR for it:
https://github.com/jeromeetienne/AR.js/pull/66
