### ISSUE TITLE
Disabling the google vr app dowload

### ISSUE THREAD

**Issue by Abelia** [jeromeetienne/AR.js#510]
**Is your feature request related to a problem? Please describe.**
When an Android user tries to use an AR code, it always force them to download the google VR app. This problem does not exist on iPhone. This ruins the experience on android.

**Describe the solution you'd like**
A way to disable this behavior.

**Describe alternatives you've considered**
I did try to find a way to disable the popup that appears. Maybe I lack technical skills but I didn't find any way. So maybe it has something to do with AR.js?

**Comment by nicolocarpignoli** [comment]
interesting, this seems a new thing. Which marker were you using when you found that issue?

**Comment by thor-brickman** [comment]
Abelia, can you give a little more detail on this?  I am using AR.js literally every day on Android and I have never been prompted for the VR app download, so I am interested in what is causing this.

Thanks!

**Comment by MartinParrish** [comment]
I have encountered the same problem on android, but managed to solve it by making sure the site was behind `https`

**Comment by edpaez** [comment]
I have my demo on HTTPS and it's asking to install Google VR. Anyway to bypass this installation?
