### ISSUE TITLE
Upgrade to the latest Three.js version

### ISSUE THREAD

**Issue by kalwalt** [jeromeetienne/AR.js#513]
**Is your feature request related to a problem? Please describe.**
I would upgrade the Three.js version included in the examples, I think many features and improvements were added that we can profit of.

**Describe the solution you'd like**
It simple: upgrade to the version `r103` or `r100`

**Describe alternatives you've considered**
none.

**Additional context**
We should know if yes or not and when. I'm preparing a PR but i would know what do you think and what are the possibles issues that can raise with this operation.
Also a part of the build process for the final ar.js build depend on the Three.js version used?
Maybe willl be fine to add one or some other example with some new Three.js feature?

We let this issue open until the upgrade process will be terminated.

**Comment by nicolocarpignoli** [comment]
Don't open an issue that explain that you will open a PR, but rather open a PR with the WIP (work in progress) prefix. Thanks :)

**Comment by kalwalt** [comment]
@nicolocarpignoli ok as you prefer, i'm working on it, I will do this in a short time.

**Comment by nicolocarpignoli** [comment]
Thank you, I'm only trying to keep issues section as  'clean' as possible, and I'm on my own, thanks for your support :)

**Comment by kalwalt** [comment]
Yes, I think you @nicolocarpignoli are alone now, we haven't heard  some news from the site owner @jeromeetienne for a long time ...
