### ISSUE TITLE
Change Font family

### ISSUE THREAD

**Issue by michaelomdesign** [jeromeetienne/AR.js#517]
**Describe the bug**
hello, I have a target with a 3D model of an elephant, and over it his a text, everything is working ok, but I can not change the font family of the text. I can change the size, position, color... but not the type. 

**To Reproduce**
  <a-text  value="AFRICAN ELEPHANT"  position="-0.5 0.5 0" height="3" width="3" color="red"  font-family="Lora, serif"</a-text>

This is the code in line.

**Expected behavior**
Everything changes but not the font family 

**Screenshots**

**Desktop (please complete the following information):**
windows 10

**Smartphone (please complete the following information):**
 android 9

**Additional context**
I tried to change in the ,js libraries or add different css but nothing is working.

**Comment by kalwalt** [comment]
Hi @michaelomdesign which aframe version are you using? How do you import the font? please share more informations,  very difficult to help you in this way. Do you also read the aframe docs [here](https://aframe.io/docs/0.9.0/components/text.html)?

**Comment by nicolocarpignoli** [comment]
closed as no answer from author
