### ISSUE TITLE
keep object not only on screen but in the same position (old position of marker) like vuforia option? 

### ISSUE THREAD

**Issue by sjraziva** [jeromeetienne/AR.js#518]
hello everybody
I have a question, I want to keep object not only on screen but in the same position (old position of marker) thing like vuforia option? I didn't find any solution until now? does somebody know? please say

**Comment by RonHouben** [comment]
Hi @sjraziva,
Can you please elaborate. Do I understand you correctly that you want to keep the object on the place where the camera sees the marker for the first time and when you move the marker the object will stay in it's original spot?
You're pointing towards Vuforia. Maybe you can share a specific (video) example?

Thanks :)!

**Comment by sjraziva** [comment]
I need sth like this .... when I used a-marker .... the 3d model(marker root) is moving with camera two .... this example is markless AR but for positioning the model is what I needed https://www.youtube.com/watch?v=-o7qr1NpeNI

**Comment by nicolocarpignoli** [comment]
try to use the a-marker-camera component instead of a-marker one.
It's kinda of deprecated, but maybe for your purposes it's better and also the only option with ar.js. Let me know if it works, have not used it for a while.

**Comment by meizano** [comment]
I'v created something basic like this, you can see it in: https://github.com/meizano/AR/blob/master/aframe/AR-event-marker-lost-object-stay.html
It seems you need to scan marker to pin position and put object on display, and then change the camera position based on marker position (or the last known position).

**Comment by vadermemo** [comment]
> I've created something basic like this, you can see it in: https://github.com/meizano/AR/blob/master/aframe/AR-event-marker-lost-object-stay.html
> It seems you need to scan marker to pin position and put object on display, and then change the camera position based on marker position (or the last known position).
> Maybe you could look into issue #313

the link is broked => 404 error
