### ISSUE TITLE
Running live on server

### ISSUE THREAD

**Issue by jodyataylor** [jeromeetienne/AR.js#519]
Hi There!

This is my first time asking a question, so I hope I'm doing it in the correct way!

It's probably a rather simple one, but I'm actually having trouble getting my AR files to work live? They all work fine (In Firefox) locally, and I've checked and re-checked all my file paths over and over. 

I got ONE file that uses A-FRAME to work and show up correctly after getting the security certificate on my domain, but weirdly it seems to work by calling the java from the web, not my folders on the server. 

So now I have the "https" sercure server, but the others (using three.js, AR.js, and a-frame) do not show up for me. Is there anything you can think of that I'm missing?

Thanks so much for your help!
Jody

**Comment by janpio** [comment]
>  but weirdly it seems to work by calling the java from the web, not my folders on the server.

Can you elaborate on what you mean here?

What does your `index.html` file, the `<script>` tags that include those libraries look like?

**Comment by jodyataylor** [comment]
Hi! Thank you!
Like this:
<script src='js/three.js'></script>
	
	<script src="jsartoolkit5/artoolkit.min.js"></script>
	<script src="jsartoolkit5/artoolkit.api.js"></script>
	
	<script src="threex/threex-artoolkitsource.js"></script>

the one file that does work, is the a-frame file, which looks like this:

<script src="/js/three.js"></script>	
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js">
</script>

So I'm a bit confused because they all work beautifully locally, and the a-frame file started working when I activated my SSL cert.

Thanks so much for your help!

**Comment by kalwalt** [comment]
@jodyataylor what server are you using? maybe it could be some wrong permits?

**Comment by jodyataylor** [comment]
Hi!

Yes I had a similar thought - since some of the original files from within
didn't work either.

I'm using go daddy and have the hosting reseller acct to have unlimited
hosting.

And the one file worked when I got my ssl (https)

Thanks so much!

**Comment by kalwalt** [comment]
Hi @jodyataylor  have you solved your problem?

**Comment by commentatorboy** [comment]
I think he got it to work.
The solution is to always run AR.js as a https site.

**Comment by iggykov** [comment]
Actually it is not really solved...

I have different behavior when running **locally** from 
```
<script src="https://aframe.io/releases/0.9.1/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.7.2/aframe/build/aframe-ar.js"></script>
```
and different when running from this
```
<script src="js/aframe.min.js"></script>
<script src="js/aframe-ar.js"></script>
```
the difference is 
when I run from the **https** the picture slides weirdly over the marker, for Ex: down when the marker looks up ect.
on the second option from file there is good tracking.... but its much slower and brakes

**Comment by commentatorboy** [comment]
Hm... I do not think that just downloading the files locally would solve the problem.
The thing with aframe and aframe-ar is that they depend on other libraries (I think).

Have you tried to see what the different options show of errors in console?

**Comment by kalwalt** [comment]
since i made the upgrade to the  aframe v0.9.2 in this PR #515 see https://github.com/jeromeetienne/AR.js/pull/515/commits/dc6eaefd054066aa9d54d219608817feb764181a
try:
```html
<script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.7.2/aframe/build/aframe-ar.js"></script>
```
tell us if it makes any difference.

**Comment by iggykov** [comment]
@kalwalt thank you for the input, this will not change the "sliding" problem, though. Any idea what is the reason for this?

here an example: https://github.com/iggykov/AR/blob/master/IK_AR_test.mov

**Comment by commentatorboy** [comment]
@iggykov I think it is because the starting point (anchorpoint) for the model is not 0,0,0.
Is it a 3d model? 
I assume it is just an image, so I might actually recommend using: https://github.com/rodrigocam/ar-gif

**Comment by commentatorboy** [comment]
@iggykov did you solve the problem?
