### ISSUE TITLE
How to change the default directory?

### ISSUE THREAD

**Issue by henriquemota99** [jeromeetienne/AR.js#52]
Hey guys,
I can use my own Hiro because the script is tracking the: https://github.com/jeromeetienne/AR.js/ and I changed for my own but it dont work..

How to fix this?

**Comment by jeromeetienne** [comment]
Sorry I don't understand

**Comment by henriquemota99** [comment]
I cant use my own tracker image, like a dog or something because the script its always getting the patt.hiro from the github..

**Comment by jeromeetienne** [comment]
You should replace the pattern url to point to your own marker

**Comment by henriquemota99** [comment]
When I do that I dont get any logs in my console but If I use default it show me logs and work well.. I dont know what Im doing wrong..

**Comment by jeromeetienne** [comment]
My guess is that your pattern file isn't working properly

**Comment by henriquemota99** [comment]
I need to use the big black border? Or I can use just a simple image without it?

**Comment by jeromeetienne** [comment]
You need to use a artoolkit pattern markers. there is a complete page explaining the details to achieve this. i hope this help

https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training

**Comment by jeromeetienne** [comment]
Btw meanwhile i wrote a webpage to easily create patttern markers

https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html
