### ISSUE TITLE
Possibility to zoom on the camera

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#521]
**Is your feature request related to a problem? Please describe.**
A request 

**Describe the solution you'd like**
Possibility to zoom the user camera. I initially was thinking that using
`<a-entity camera="zoom: <ZOOM-VALUE>;"></a-entity>`
would do the trick, but it does not change anything - maybe the camera entity refers to aframe camera, not the user one.

Guess if there is the possibility to do this, maybe accessing the camera stream opened by AR.js

**Comment by nicolocarpignoli** [comment]
In fact, the camera I'd like to zoom is the principal of the arjs a-scene, so not the a-entity camera

**Comment by janpio** [comment]
So you want to zoom the actual image / video, which should change the marker size and thus also resize the rendered scene?

**Comment by nicolocarpignoli** [comment]
Yes. I found that maybe this can be possible with 
```
camera.zoom = <zoomFactor>;
camera.updateProjectionMatrix();
```

But first we have to retrieve the camera instance

**Comment by nicolocarpignoli** [comment]
I confirm is not possible (as far as I checked) to change 'zoom' value of the Threejs PerspectiveCamera istantiated by arjs: I changed it with the code above but it does not change anything.

Anyway, I went deeper and managed to make working the zoom using directly the 'getUserMedia' stream istantiated by arjs

```
   document.querySelector('body').addEventListener('click', (event) => {
            let mediaStream = document.querySelector('video');
            // this is the runnning camera stream 
            mediaStream = mediaStream.srcObject;

            const track = mediaStream.getVideoTracks()[0];
            const capabilities = track.getCapabilities();

            // Check whether zoom is supported or not.
            if (!('zoom' in capabilities)) {
                return Promise.reject('Zoom is not supported by ' + track.label);
            }

            // 5 as example value
            track.applyConstraints({ advanced: [{ zoom: 5 }] });
        });

```

this way we can zoom the user camera, at least.
hope it helps

**Comment by nicolocarpignoli** [comment]
code for zooming, once got the stream, at: https://googlechrome.github.io/samples/image-capture/update-camera-zoom.html

**Comment by ziv1011169** [comment]
How to achieve open camera and zoom in/out facility for ios safari browser using javascript
