### ISSUE TITLE
Camera not active in Ionic-iOS

### ISSUE THREAD

**Issue by abroekhuis** [jeromeetienne/AR.js#522]
**Describe the bug**
When using aframe in an Ionic based application, the camera is not started. Also the following error is given in the console log:

[Error] Not allowed to load local resource: blob:blobinternal:///480951e5-1001-423b-837f-2f6d1572d469

Some more details about the project, by default on iOS there is no webrtc when using Ionic. We use the iosrtc plugin to solve this. I can open the camera when using the rtc api (getUserMedia etc).

Ionic/iOS uses wkwebview, this view does have issues with getting local files. (see https://ionicframework.com/docs/v3/wkwebview/). I suspect this is related to the problem, but am not sure..

When plotting a simple box, I can see the box, but not the camera view.

**To Reproduce**
Build the cordova/ionic app at https://github.com/abroekhuis/ionic-aframe. Run on a recent iOS device and view console log using Safari Development options.

**Expected behavior**
Working camera

**Desktop (please complete the following information):**
 - OS: Cordova/Ionic on iOS
 - Browser: WkWebview plugin from Ionic (https://ionicframework.com/docs/v3/wkwebview/)

**Smartphone (please complete the following information):**
 - OS: Cordova/Ionic on iOS 12.2
 - Browser: WkWebview plugin from Ionic (https://ionicframework.com/docs/v3/wkwebview/)

**Comment by janpio** [comment]
WebViews are not supported in AR.js.

**Comment by janpio** [comment]
> It works great on Android though.

Oh really? Which Android version?

**Comment by abroekhuis** [comment]
@janpio yeah, it works, I am using the latest SDK with my S8+ (up to date with Android 9).
On Android we did have to use an iframe for viewing the camera image, without it, only a narrow band is shown on a small part of the screen. Perhaps this can be solved with aframe/ar, but haven't yet found out how. 
I've updated the example at https://github.com/abroekhuis/ionic-aframe.

**Comment by kalwalt** [comment]
AR.js with webView ? That's great @abroekhuis ! but no idea how to solve this issue, sorry... :smile:

**Comment by abroekhuis** [comment]
@janpio Any pointers on where I should look for the enabling of the camera?

**Comment by janpio** [comment]
No idea, sorry.

**Comment by benallfree** [comment]
@abroekhuis I'm working on iosrtc+as.js as well, are you still?

**Comment by abroekhuis** [comment]
@benallfree No, we opted to move to a native solution, in which we can properly use arkit and 3d models. We tried with AR.ja/AFrame, but, sadly enough, kept running into issues. :(

**Comment by nicolocarpignoli** [comment]
please continue discussing this, along with other JS framework-related stuff, at: https://github.com/AR-js-org/AR.js/issues/17
