### ISSUE TITLE
Scale the object and move it rotate it after loading into the scene

### ISSUE THREAD

**Issue by jamess922** [jeromeetienne/AR.js#527]
How can i  scale the 3d model and move it rotate it after loading into the scene ？

**Comment by RonHouben** [comment]
Hi @jamess922,

Before asking these kind of questions on this repository please search in the various documentation resources.
This so we can keep the issues clean :).

Depending if you're using a-frame or Three.js, here 're the answers:
**a-frame solution:**
`<a-entity id="entityID"  scale="x y z" position="x y z" rotation="x y z"></a-entity>`

Replace the letters x y z by the actual numeric values

https://aframe.io/docs/0.9.0/components/scale.html
https://aframe.io/docs/0.9.0/components/position.html
https://aframe.io/docs/0.9.0/components/rotation.html

**Three.js solution:**
```
const geometry = new THREE.BoxGeometry( 1, 1, 1 )
const material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } )
const cube = new THREE.Mesh( geometry, material )

cube.scale.set(x, y, z)
cube.rotation.x = newValue
cube.position.set(x, y, z)

scene.add( cube )
```
https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene

**Comment by RonHouben** [comment]
@nicolocarpignoli , can you please close this issue?
