### ISSUE TITLE
My demo Stopped working suddenly

### ISSUE THREAD

**Issue by IndianTinker** [jeromeetienne/AR.js#53]
Hi, I loved the library. I built a small demo of it - https://rohit7gupta.github.io/explore/objects.html 
Showed it in the class. I wanted to experiment more but all of a sudden nothing seems to work at all on the same setup. I am going all bonkers. I am not a java head. 

My current setup is Windows64bit chrome Version 57.0.2987.133 (64-bit).
I am using barcode markers.

Thanks!

**Comment by jeromeetienne** [comment]
if it stopped working, something changed in what you are running.

i think it would be good to find out what

**Comment by sorianog** [comment]
@IndianTinker Would you be able to share the code of your demo with us?

**Comment by IndianTinker** [comment]
Hi, Thanks for taking this up! The code is in this repo https://github.com/rohit7gupta/rohit7gupta.github.io/tree/master/explore

**Comment by jeromeetienne** [comment]
@IndianTinker sorry if i cant bring better news :(

**Comment by ZoltanVeres** [comment]
Referenced issue #54 was closed PR got merged
