### ISSUE TITLE
How to know if the model is being rendered if it is not visible on screen due to scaling issue

### ISSUE THREAD

**Issue by shubhamraghav1** [jeromeetienne/AR.js#531]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by commentatorboy** [comment]
I would recommend starting to change the size of the object to be 1x1x1.

If the object is not rendered usually there would be an error/warning in the console log

**Comment by kalwalt** [comment]
@shubhamraghav1 if you are using afram-ar.js you can use the [aframe inspector](https://github.com/aframevr/aframe-inspector) just type `ctrl-alt-i` and you can see where is located your model and understand if is under- or over-sized or wrong placed in the coord. system. 
If you are using ar.js instead, follow the @commentatorboy advice,  start with 1x1x1 dimension, and maybe check if the model is rendered with [the three.js editor.](https://threejs.org/editor/).

**Comment by kalwalt** [comment]
Also read this: https://aframe.io/docs/0.9.0/introduction/models.html#i-don%E2%80%99t-see-my-model

**Comment by nicolocarpignoli** [comment]
this is an aframe specific issue. also, suggestions has been given. i'm closing
