### ISSUE TITLE
Can I use a video as webcam source?

### ISSUE THREAD

**Issue by Aqours** [jeromeetienne/AR.js#533]
**Is your feature request related to a problem? Please describe.**
I just want to use a video as webcam source.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Take video frame as reality. (I think it's a practical proposal)

**Additional context**
N/A

**Comment by nicolocarpignoli** [comment]
Hi, I don't understand. Explain better what you want to achieve

**Comment by Aqours** [comment]
![40343608-f51a-11e6-8cb3-900e37a7f658](https://user-images.githubusercontent.com/8586286/58155725-0d895f00-7ca7-11e9-8341-59fc18a5f915.jpg)

Sorry for my unclear description.

for example, ① frame is from real world captured by webcam, ② frame is from virtual world created by 3d model, we obtain AR frame by concating ① frame with ② frame.

So could we use AR tech to HTML5 video domain without webcam devices?  Replacing ① frame with video frame,  then we draw the AR frame(concat video frame and ② frame) onto WebGL canvas.

**Comment by kalwalt** [comment]
@Aqours  Do you want use a video as source instead of webcam source video?
in a-frame-ar:

```jsx
<a-scene embedded arjs='patternRatio: 0.5; sourceType: video; sourceUrl: path/to/video.mp4;'>
 // your code
</a-scene>
```
in ar.js:

```js
var arToolkitSource = new THREEx.ArToolkitSource({
		// to read from the webcam 
		//sourceType : 'webcam',
		
		// // to read from an image
		// sourceType : 'image',
		// sourceUrl : THREEx.ArToolkitContext.baseURL + '../data/images/img.jpg',		
		// to read from a video
		 sourceType : 'video',
		 sourceUrl : THREEx.ArToolkitContext.baseURL + '../data/videos/headtracking.mp4',		
	})

```

**Comment by nicolocarpignoli** [comment]
Yes, but basically it is not augmented reality anymore, it is just an a-frame app

**Comment by Aqours** [comment]
@kalwalt Thanks. Where could I find some docs? I use these code, and log error: `Uncaught TypeError: systems[name] is not a constructor`.

```html
        <div id="aframe">
            <a-scene embedded arjs='patternRatio: 0.5; sourceType: video; sourceUrl: headtracking.mp4;'>

            </a-scene>
        </div>
        <script src="../node_modules/three/build/three.min.js"></script>
        <script src="../node_modules/aframe/dist/aframe-v0.9.2.js"></script>
        <script src="../node_modules/ar.js/three.js/build/ar.min.js"></script>
        <script src="../node_modules/ar.js/aframe/build/aframe-ar.min.js"></script>
        <script>
            var arToolkitSource = new THREEx.ArToolkitSource({
                // to read from the webcam
                //sourceType : 'webcam',

                // // to read from an image
                // sourceType : 'image',
                // sourceUrl : THREEx.ArToolkitContext.baseURL + '../data/images/img.jpg',
                // to read from a video
                sourceType : 'video',
                sourceUrl : 'headtracking.mp4',
            });
        </script>
```

**Comment by kalwalt** [comment]
If you want to use `aframe-ar` you don't need to include THREEx at all. 

```jsx
<script src="../node_modules/aframe/dist/aframe-v0.9.2.js"></script>
<script src="../node_modules/ar.js/aframe/build/aframe-ar.min.js"></script>
        <div id="aframe">
            <a-scene embedded arjs='patternRatio: 0.5; sourceType: video; sourceUrl: headtracking.mp4;'>
             // your code here
            </a-scene>
        </div>
```

please go to the [examples](https://github.com/jeromeetienne/AR.js/tree/master/aframe/examples) and read the [Readme,md](https://github.com/jeromeetienne/AR.js/blob/master/aframe/README.md)

**Comment by Aqours** [comment]
Thanks. I will retry it.

**Comment by kalwalt** [comment]
@Aqours as a final not if you don't want use tha aframe approach take a look at the  [markerrroot example](https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/markerroot.html).

**Comment by sehadnassim** [comment]
Can we have a source as a video stream, for instance a video id ?
