### ISSUE TITLE
rawgit is ending!

### ISSUE THREAD

**Issue by Ouyang-Zhaoxing** [jeromeetienne/AR.js#535]
[Trello](https://trello.com/c/agF1dxs5)
rawgit is ending! read at the home page: https://rawgit.com/ we need to change all the rawgit path to an alternative.

**Comment by kalwalt** [comment]
Thank you @Ouyang-Zhaoxing to repost it!

**Comment by elimerl** [comment]
Try using githack:
https://raw.githack.com/jeromeetienne/AR.js/1.7.0/aframe/build/aframe-ar.js

**Comment by nicolocarpignoli** [comment]
Someone is will to make a PR for that? Using githack seems good
it should not be a big thing, just a find-and-replace and a quick test

**Comment by nicolocarpignoli** [comment]
https://github.com/jeromeetienne/AR.js/pull/538

**Comment by kalwalt** [comment]
Well done guys!
