### ISSUE TITLE
How to set height and width of a-image dynamically

### ISSUE THREAD

**Issue by soultrue** [jeromeetienne/AR.js#536]
**Is your feature request related to a problem? Please describe.**
I would like to set height and width of a-image dynamically. Could you please help me on that?

**Describe the solution you'd like**
I would like to set height and width of a-image dynamically. Could you please help me on that?

I am uploading  image and wants to display as it is in <a-image>  but it is always resizing.  I want to display original image without resize.

<a-image src="#logo" **width="3" height="1.5"**></a-image>

**Describe alternatives you've considered**

**Additional context**

**Comment by nicolocarpignoli** [comment]
`document.querySelector('a-image').setAttribute('width', <another value>)`
`document.querySelector('a-image').setAttribute('height', <another value>)`

**Comment by soultrue** [comment]
Thanks you so much!!

But I have another problem, my image width is 350px and height is 150px, now I would like to set same height and width in <a-image > but it only accept height and width in "M"(Meter). Could you please guide me how can I convert equivalent  height and width of my a-image in "Meter" so that it will look exactly same and display in the center of screen?

If you could share me the formula which I can use to convert pixel ( width and height) into  Meter( width and height)  so that it would be so helpful for me. Thank you.

**Comment by nicolocarpignoli** [comment]
> But I have another problem, my image width is 350px and height is 150px, now I would like to set same height and width in but it only accept height and width in "M"(Meter).

Well, width and height attribute of image on HTML accepts pixels, not Meters. I can't understand why you are saying you need to insert values as Meters. Are you using a specific form data, or you have values in Meters?

Btw, I found this: https://www.unitconverters.net/typography/meter-to-pixel-x.htm

hope it helps :)

**Comment by soultrue** [comment]
> > But I have another problem, my image width is 350px and height is 150px, now I would like to set same height and width in but it only accept height and width in "M"(Meter).
> 
> Well, width and height attribute of image on HTML accepts pixels, not Meters. I can't understand why you are saying you need to insert values as Meters. Are you using a specific form data, or you have values in Meters?
> 
> Btw, I found this: https://www.unitconverters.net/typography/meter-to-pixel-x.htm
> 
> hope it helps :)

I am using <a-image> tag of a-frame and in <a-image> you can only set "height" and "width" only in Meter(as per my understanding). For example:
<a-image src="#logo" **width="3" height="1.5"**>

My problem is, I want to display a 350x150 pixel image exactly same in  <a-image> tag but it is not coming correctly because <a-image> needs height and width in meters. I hope this time I am able to explain my problem :)

**Comment by nicolocarpignoli** [comment]
ok, understood.

I found this

```
<!-- image width = 987, height = 739
     aspect ratio = w/h = 987/739 = 1.33
     assuming 987 px = 1 m
     expected width of image in VR = 2.5 m
     height of image in VR = 2.5/1.33 = 1.87 -->
<a-image src="assets/controllers.jpg" position="0 0 -2" width="2.5" height="1.87"></a-image>
```

https://medium.com/@kumar.ahir/how-to-correctly-set-dimensions-of-an-image-in-a-frame-8c1e598416e1

I think it is exactly what you need

**Comment by soultrue** [comment]
Thank you
