### ISSUE TITLE
Barcode Markers (May Be) Broken

### ISSUE THREAD

**Issue by Miserlou** [jeromeetienne/AR.js#54]
Awesome project!

Hiro markers in my AR.js app (based on the a-frame example) are working fine. 

However, I want to use 3x3 barcode markers!

I am following this example: http://jeromeetienne.github.io/slides/artoolkit-aframe/#20

The slideshow has this section:

```
<a-scene artoolkit='detectionMode: mono_matrix; sourceType: webcam;'>  
        <!-- here, put the content of your scene -->
</a-scene>
```

But changed `mono_matrix` to `mono_and_matrix` since `mono_matrix` does not exist. 

Even after that, however, this does not appear to work:

```
<a-marker type='barcode' value='20' >
        <!-- here put your content -->
</a-marker>
```

Though the code runs in the browser without error, it is never able to identify the marker. This seems to be the case even when matrixCodeType is in `3x3, 4x4, 3x3_HAMMING63`, etc..

Any ideas? It's possible this is related to an underlying bug: https://github.com/artoolkit/jsartoolkit5/issues/34

Can somebody sanity check this for me, please?

**Comment by Miserlou** [comment]
Similarly, there are no examples which use the 'barcode' format, which makes this more difficult to learn by example.

**Comment by IndianTinker** [comment]
Hi, I tried barcode markers. But i guess they are not working now. I used them in a class demonstrations to put a point forward regarding the amazing work and world of Web Reality.
https://github.com/rohit7gupta/rohit7gupta.github.io/tree/master/explore

**Comment by freinbichler** [comment]
Currently having the same issue, can't get the barcode markers to work.

**Comment by jeromeetienne** [comment]
ok i will look

**Comment by jeromeetienne** [comment]
everybody who experienced issue with barcode marker is using a-frame, correct ?

**Comment by IndianTinker** [comment]
yes ! a-frame. Thanks :)

**Comment by chisaipete** [comment]
I believe I'm facing a similar issue. Adding the matrixCodeType and detectionMode, but barcode markers aren't being detected at all.

**Comment by KollegeBratwurst** [comment]
I also face the problem with the barcodes. Something new on this one?

**Comment by jeromeetienne** [comment]
Sorry for the delay, i spent time on this today. And fixed an issue. I wrote an aframe example which handle multiple independant markers, and there is barcode is working there. 

See the example [here](https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/multiple-independant-markers.html#L27-L33)

You change the scene configuration to specific you are looking for matrix marker too and their type e.g.
```
<a-scene embedded artoolkit='sourceType: webcam; detectionMode: mono_and_matrix; matrixCodeType: 3x3;'>
</a-scene>
```

You define the marker like this
```
<a-marker type='barcode' value='5'>
     <a-box></a-box>
</a-marker>
```


![screen shot 2017-06-06 at 15 25 17](https://cloud.githubusercontent.com/assets/252962/26834525/7e61e1ec-4acd-11e7-80cf-b369a7767a0e.png)

**Comment by jeromeetienne** [comment]
Here is the image of the barcode marker 5 in 3x3 https://github.com/artoolkit/artoolkit5/blob/master/doc/patterns/Matrix%20code%203x3%20(72dpi)/5.png

**Comment by freinbichler** [comment]
I can confirm that this works! Thank you very much Jerome!

**Comment by KollegeBratwurst** [comment]
Thanks :)

**Comment by IndianTinker** [comment]
Super Dooper Thanks !! 💃

**Comment by vingkan** [comment]
Still not working for me, even when using the exact code from the example linked by @jeromeetienne .

There is also a strange effect where even when the hiro marker is not being used, the hiro marker shows the objects that were meant to be shown from the barcode.

Is it possible that the cause of this is that tracking backend is not being set to aruco?

**Comment by ZoltanVeres** [comment]
@vingkan Pleased create a new issue, if the issue is still persists.

**Comment by teasacura** [comment]
@reza21 Hey, I'm also a newbie, but in case you're still looking for barcode (3x3), artoolkit has some pre-generated numbers (0 to 63) here: https://github.com/artoolkit/artoolkit5/tree/master/doc/patterns/Matrix%20code%203x3%20(72dpi). I hope that helps!

**Comment by ppscvalentin** [comment]
I am using artoolkit to look for barcode 37 and I seem to find it (i'm inspecting `arToolkitContext.arController.barcodeMarkers[37].inCurrent`/`.inPrevious` and they're true), but the model doesn't show. The model does show when usign hiro.patt, however.

```
    arToolkitContext = new THREEx.ArToolkitContext({
      cameraParametersUrl: '/assets/cameras/camera_para.dat',
      detectionMode: 'mono_and_matrix',
      matrixCodeType: '3x3',
      debug: true
    });
    ...
    let markerControls1 = new THREEx.ArMarkerControls(arToolkitContext, markerRoot1, {
      type: 'barcode', 
      barcodeValue: "37",
    });
```

Could someone please help?
