### ISSUE TITLE
Is there any way to turn off tracking?

### ISSUE THREAD

**Issue by yydtcy** [jeromeetienne/AR.js#540]
Hey,

I want to turn off tracking after a successful recognition, and still retain the object on the screen, is there any way to do this? Thank you!

**Comment by ArcaneDiver** [comment]
I'm not sure but if you obtain the right 3d coordinates of the marker in the scene and you move the object out of the market root to the scene it should work. Obviously i'm talking about THREEJS for A-FRAME it should be probably easier. 
Then 1- Get the coordinates of the marker in the scene, 2- move group or the object into the scene at the coordinates;

**Comment by yydtcy** [comment]
I want to get a function that can freely  turn off the tracking , even the marker is visible. Do you know if there is such a function? Thank you !

**Comment by yydtcy** [comment]
> I'm not sure but if you obtain the right 3d coordinates of the marker in the scene and you move the object out of the market root to the scene it should work. Obviously i'm talking about THREEJS for A-FRAME it should be probably easier.
> Then 1- Get the coordinates of the marker in the scene, 2- move group or the object into the scene at the coordinates;

I want to get a function that can freely  turn off the tracking , even the marker is visible. Do you know if there is such a function? Thank you !

**Comment by nicolocarpignoli** [comment]
No, there is not a simple way of do that. @ArcaneDiver way can be suitable but surely not so easy.

**Comment by nicolocarpignoli** [comment]
https://github.com/jeromeetienne/AR.js/issues/313
