### ISSUE TITLE
NFT (Natural Feature Tracking) on AR.js

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#544]
AR.js is currently able to recognize markers based on artoolkit marker, so the ones with the dark (black) border around shapes.

NFT (Natural Feature Tracking) can bring new life to AR.js, we eventually will be able to scan and recognize also 2D images, for example.

There is a branch for NFT on artoolkit, the library that AR.js is using for recognization.
@kalwalt is working on his fork of jsartoolkit (https://github.com/kalwalt/jsartoolkit5/pull/1) in order to bring the NFT branch alive again, including examples. They are outdated, but some times ago they where working.

So: if we can help him/support him bringing the NFT branch alive and working again, we can then think of use that jsartoolkit version in order to bring NFT feature to AR.js.

Just wanted to make this more visible.
If someone is willing to help and has experience about that, please let us know :)

**Comment by kalwalt** [comment]
Thank you @nicolocarpignoli we need to take this beast by the horns!

**Comment by nicolocarpignoli** [comment]
Update: @kalwalt has been able to make NFT branch working again on jsartoolkit! 

Now we need to find a way to:

* create NFT markers starting from a 2D image
* possibly load such markers dynamically on jsartoolkit example
* replace/port the NFT jsartoolkit version into AR.js

**Comment by kalwalt** [comment]
Thanks for the enthusiasm @nicolocarpignoli  !! :1st_place_medal: 
> create NFT markers starting from a 2D image
i want to look to this! i want to try with my own image....

**Comment by kalwalt** [comment]
@nicolocarpignoli Idea: i am working on adding NFT to jsartoolkit5 https://github.com/kalwalt/jsartoolkit5/pull/1 , that is all is together (marker, multimarker, barcode, and NFT) but maybe one person could be interested to only the markerless NFT tech, so i was wondering that it will be cool to develop a lighter version of jsartoolkit with only NFT, what do you think?

**Comment by nicolocarpignoli** [comment]
In my opinion it could be interesting, but I will see that as a 'nice-to-have'. Priority should to **simply**  (lol) bring NFT to AR.js.

**Comment by kalwalt** [comment]
Yes of course! 😀

**Comment by Carnaux** [comment]
Omg! How can I help?

**Comment by nicolocarpignoli** [comment]
Things are moving! @Carnaux has started a repo to bring to the web a tool to create NFT marker!
https://github.com/kalwalt/jsartoolkit5/pull/1#issuecomment-514449013

**Comment by kalwalt** [comment]
For anyone interested in this topic: i uploaded some examples in my github webpage [kalwalt.github.io/kalwalt-interactivity-AR/](https://kalwalt.github.io/kalwalt-interactivity-AR/) to help testing on mobile devices. For now i uploaded only the threaded version of jsartoolkit5 with NFT, before using it read carefully the infos especially the Spectre issue!! I will upload the other examples ( the non threaded version) when i will have a bit of time, sadly i have not so much in this last period...

**Comment by MiguelNunes71** [comment]
Congratulations kalwalt, i successfully tested your NTF  examples kalwalt.github.io/kalwalt-interactivity-AR/  on both  Android and IOS devices !

A question,  how can we detect when the marker is visible and when it is hidden, so we tell to start or to stop other actions like animation and sound?

**Comment by kalwalt** [comment]
> Congratulations kalwalt, i successfully tested your NTF examples kalwalt.github.io/kalwalt-interactivity-AR/ on both Android and IOS devices !
> 
> A question, how can we detect when the marker is visible and when it is hidden, so we tell to start or to stop other actions like animation and sound?

You should look in the console you should receive some notifications. Not sure if at the moment it is implemented a event listeners for this, Sorry! but i will look into it... BTW could you be more specifc with performances and devices? Thank you! :smile:

**Comment by kalwalt** [comment]
We @kalwalt @nicolocarpignoli @ThorstenBux are on the road to merge the jsartoolkit5 **NFT** feature into the master branch of **artoolkitx/jsartoolkit5** in this [PR](https://github.com/artoolkitx/jsartoolkit5/pull/86). :smile: :+1: 

This means that in another step will be integrated into AR.js !! If you want to test the examples go to this page [kalwalt.github.io/jsartoolkit5/examples/](https://kalwalt.github.io/jsartoolkit5/examples/) and report your tests and issues in the 
**artoolkitx/jsartoolkit5** [PR](https://github.com/artoolkitx/jsartoolkit5/pull/86) or in the [PR](https://github.com/kalwalt/jsartoolkit5/pull/1) where i started this hard/crazy work.

See you soon for nice updates !! :100: :bomb: :fire:

**Comment by TheBricktop** [comment]
holy moses,
this is the most profound work on AR,js and AR in general ive seen in years,
if this would be implemented the pain of cross compiling android and ios apps would be gone forever

**Comment by kalwalt** [comment]
> holy moses,
> this is the most profound work on AR,js and AR in general ive seen in years,
> if this would be implemented the pain of cross compiling android and ios apps would be gone forever

Yes @TheBricktop this is real! We hope to merge into the **artoolkitx/jsartoolkit5** master branch in january and after include it in AR.js If you find some issues please open it at https://github.com/kalwalt/jsartoolkit5/issues or leave a comment in the [PR](https://github.com/kalwalt/jsartoolkit5/pull/1)

**Comment by TheBricktop** [comment]
Will definitely try it out

**Comment by cvasquez-github** [comment]
Thank you @nicolocarpignoli  and @kalwalt for this huge effort! Please let me know if can contribute in any way. Thanks!

**Comment by kalwalt** [comment]
The NFT feature finally has been merged in the **artoolkitx/jsartoolkit5** master branch !!! It's An **EPIC MOMENT** :smile: :tada: :bangbang: :bomb: We are working on the Ar.js side to integrate the new jsartoolkit5 libs with NFT support into the core. You can follow our progresses in this PR https://github.com/jeromeetienne/AR.js/pull/705 many thanks to all the people involved in this wonderful process, not to help for coding but also for testing and for the support. I am very happy of this community and of opensourcing. I have also written this article on my blog for the historic event: https://www.kalwaltart.com/blog/2020/01/21/nft-natural-feature-tracking-with-jsartoolkit5/ and please spread the word! Thank you all!

**Comment by cvasquez-github** [comment]
OMG!!! Congratulations!!! A huge contribution to the AR Development ecosystem!!! Thank you so much for reaching this milestone! Which example should we consider as a base for testing it main_threejs_wasm_worker.html? Regarding NFT Marker creation, would it work properly with fset files generated with https://carnaux.github.io/NFT-Marker-Creator/ ? Thanks!

**Comment by kalwalt** [comment]
HI @cvasquez-github! Thank you! Yes consider to test that example and if you want create yours NFT markers you can use the https://carnaux.github.io/NFT-Marker-Creator/ web version or the command line app https://github.com/Carnaux/NFT-Marker-Creator enjoy!

**Comment by cvasquez-github** [comment]
Awesome, thanks @kalwalt !
BTW which camera calibration parameters dat files should we use? I see the example threejs_wasm_worker uses _camera_para-iPhone 5 rear 640x480 1.0m.dat_ file.

**Comment by linkadjausal** [comment]
Marvelous. Thank you very much for contributing a very important feature of augmented reality, in JavaScript !!

**Comment by pepperface** [comment]
Simply... THE... BEST... NEWS... 😎👏👏👏👏👏❤️ Huge thanks for all the amazing work that's been done!

**Comment by markerio** [comment]
That’s perfect guys, thanks a million!

**Comment by nicolocarpignoli** [comment]
closed, see related PRs.

**Comment by abhishekQ** [comment]
can we play an mp3 file with nft marker

**Comment by subjectdenied** [comment]
@abhishekQ : the markers are only used for AR features, audio is done at the "3d-engine" level (three-js), so it should work. i did this successfully using arNFT (what ar.js is based on afaik) and three-js

**Comment by abhishekQ** [comment]
> @abhishekQ : the markers are only used for AR features, audio is done at the "3d-engine" level (three-js), so it should work. i did this successfully using arNFT (what ar.js is based on afaik) and three-js

I want to play sound with 3d model when nft marker is detected. if you have code can you please share it with me

**Comment by subjectdenied** [comment]
https://www.trickymind.at/ar
get the tracking-image by clicking the button on the bottom-right at the screen
