### ISSUE TITLE
ThreeJS like raytracing

### ISSUE THREAD

**Issue by timgrossmann** [jeromeetienne/AR.js#55]
Hey there, awesome project!

Is its possible to do raytracing to find out where the click on the screen would hit the 3D model?
It's possible in threeJS, so this should be possible here as well, right?

If yes, I'd love to get an example.

**Comment by jeromeetienne** [comment]
Good news, there is nothing special about this in AR.js :) AR.js is only controlling the position of the camera. all the rest is normal three.js

You can get the examples interactives from three.js. and use AR.js to controls the camera

**Comment by timgrossmann** [comment]
@jeromeetienne Yes, thank you we already got it working 😉
