### ISSUE TITLE
Sorry to open a new Issue coming  from  #550

### ISSUE THREAD

**Issue by jamess922** [jeromeetienne/AR.js#551]
Sorry to open a new issue i don't know if  you  @nicolocarpignoli  could see the comments in a closed issue ,but the #550 dosen't solved 
with my testing Border color only  working with Android ，not IOS
Android ：huawei mate 20 pro                                    （working）
IOS ：iphone 7   IOS12.1    and iphone 6 plus IOS12  （not working）

**Comment by nicolocarpignoli** [comment]
Yes, I can see comments, don't worry. Anyway, we can continue here.

Can you please send screenshot, and also send console.logs if there is some log. from iphone. it is very strange. the behaviour has to be the same

**Comment by jamess922** [comment]
Here is the screenshot,i don't know how to get console.logs,maybe you could tell me how then  i will send to you
![QQ图片20190702163249](https://user-images.githubusercontent.com/28625879/60497249-0e220600-9ce7-11e9-9911-408decfae6d2.jpg)
and in fact the model show up for maybe 1 second before it disappear after i reload the page

**Comment by commentatorboy** [comment]
@jamess922 Can you link it to us?
You can get the developer console by going to your laptop webbrowser (like google chrome) and press f12.

Can you do this in safari mobile?
https://www.dummies.com/web-design-development/how-to-use-developer-tools-in-safari-on-ios/
Or safari apple computer:
https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac

**Comment by jamess922** [comment]
It's not available right ,but I will try to make it happen!!!
 I did some google iphone looks need an apple computer to get developer tool

**Comment by jamess922** [comment]
Is that any good news？

**Comment by commentatorboy** [comment]
Huh? Have you tried to open the site on a windows computer and opened the developer console on chrome?
You just open chrome, go to the website, and press f12 (a menu will pop up, and go to "console").

**Comment by jamess922** [comment]
I did  as you say with chrome on a windows computer
No matter which markerI use(red border or black border  ), it all shows like this
![360截图18500826374037](https://user-images.githubusercontent.com/28625879/60758125-2a56d780-a046-11e9-8915-3e53852d7a3b.jpg)

**Comment by commentatorboy** [comment]
Nice. I can see that switch02Btn is not defined. 
That would mean that something is wrong with the code.
It is hard to determine what to do when we do not have the code.

Can you somehow provide us with the source code?
Either by linking to the website, or post the source code on https://glitch.com/ ?

**Comment by jamess922** [comment]
It's because i didn't clean up my code，just ignore this error whe it's  working  
As i said when i use a marker with black border （it's working,the model shows up）I also get this switch02Btn error.so i don't think it's because this one

**Comment by jamess922** [comment]
So @commentatorboy you could working with iphone when using this Border color function ？

**Comment by commentatorboy** [comment]
Unfortunately I do not have time to create an example to test.
Although you could just use the example here:
https://github.com/jeromeetienne/AR.js#augmented-reality-for-the-web-in-less-than-10-lines-of-html
Instead of having your 3D figure, try and add an a-box. Does the above code work on Iphone and android?

The reason why Iphone might not work is because apple are very strict on javascript and html. If there are any mistakes/errors it might break everything.
