### ISSUE TITLE
one simple question about 404

### ISSUE THREAD

**Issue by Crui3in** [jeromeetienne/AR.js#560]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Hi ,i am a new hand in AR，yesterday i downloaded your code and took a try, it turned out that there were several bugs in js code,I pressed F12 and it showed"Failed to load resource: the server responded with a status of 404 (Not Found)". as follows:
![image](https://user-images.githubusercontent.com/52872841/61216088-23fbe600-a73f-11e9-9831-cd128232c1bd.png)
![image](https://user-images.githubusercontent.com/52872841/61215970-d7b0a600-a73e-11e9-81d2-73766cf0990d.png)
![image](https://user-images.githubusercontent.com/52872841/61215999-e7c88580-a73e-11e9-9245-4650c0302791.png)
PS:my url is totally right,and i also have deployed to web server to take a try,but it shows the same question,this HTTP Error 404.3 says"The page you requested could not be provided due to the extended configuration problem. If the page is a script, add a handler. If you should download the file, add the MIME mapping." I would appreciate it if you could solve my problem.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by kalwalt** [comment]
HI @Crui3in welcome to AR.js! i'm sorry for your problems, but within example you get this error?

**Comment by Crui3in** [comment]
@kalwalt yep,i downloaded this example and ran it both in my localhost and web server.both of them showed this problem.

**Comment by nicolocarpignoli** [comment]
Hi
this is your answer I guess, try and let me know: https://github.com/jeromeetienne/AR.js/issues/363 

anyway, we are working to get this fixed

**Comment by nicolocarpignoli** [comment]
there is already this PR that's still to be merged that potentially fix that problem (https://github.com/jeromeetienne/AR.js/pull/549) - it's an issue of external references

**Comment by Crui3in** [comment]
@nicolocarpignoli Thank you very much.I have tried the first way and it runs perfectly.

**Comment by nicolocarpignoli** [comment]
great!

**Comment by nicolocarpignoli** [comment]
solved with: https://github.com/jeromeetienne/AR.js/issues/363#issuecomment-396185758
