### ISSUE TITLE
failed to start video feed/showing a write screen on ios 13

### ISSUE THREAD

**Issue by kylelamx** [jeromeetienne/AR.js#561]
**Describe the bug**
With iPhone X, running iOS 13(17A5522g), AR js seems to fail to render on screen.

**To Reproduce**
1. this demo: https://github.com/jeromeetienne/AR.js/blob/master/README.md#try-it-on-mobile
2. Scan the QR code with iPhone X (iOS 13: build 17A5522g)
3. Click Allow for camera access
4. Video feed does not start

**Expected behavior**
video from camera should be shown on screen, with AR overlay

**Screenshots**
https://ibb.co/m8WRzS0
https://ibb.co/PGsdBM4

**Smartphone (please complete the following information):**
 - iPhone X
 - OS: iOS 13(17A5522g)
 - Browser: safari

**Additional context**
The same device, with iOS 12, was able to launch the demo. So this would not be a hardware
issue.

**Comment by Pomettini** [comment]
I'm having this problem as well with the same configuration

**Comment by nicolocarpignoli** [comment]
very interesting. can you please share with us console errors, if any?

**Comment by commentatorboy** [comment]
And adding to @nicolocarpignoli you can show your console by properly doing it be following one of these examples:
http://www.imagezap.org/developer-console-safari-iphone/
https://www.lifewire.com/activate-the-debug-console-in-safari-445798

**Comment by kylelamx** [comment]
I don't think there's any error.

https://ibb.co/6NK2t6G
https://ibb.co/0BDZCdN
https://ibb.co/Yj3xXCG
https://ibb.co/J59S1Xy
https://ibb.co/JnjgVrh
https://ibb.co/jJgfcQJ
https://ibb.co/nCNfJWs
https://ibb.co/yyZFjs1

**Comment by commentatorboy** [comment]
So weird... Have you tried it on google chrome? (I know it should still work on safari, but wanted to see if it is a safari only problem or if it a iOS 13 problem).

**Comment by kylelamx** [comment]
Chrome gives me this 
https://ibb.co/SRgBj6J

but I think it's just chrome on ios. with iphone 5s (ios 12.3) I get the same error.
https://ibb.co/9cwHfPz

**Comment by commentatorboy** [comment]
Have you tried to enable the microphone access?
Settings > Safari > Camera & Microphone Access.

I have seen some people have this problem mostly with newer iPhones.
So I am just grasping at straws here.

**Comment by kylelamx** [comment]
Sadly, no. I had it set to Ask, and I did allow access.
I also set them to Allow (for all website) too, that didn't fix it.

**Comment by nicolocarpignoli** [comment]
Don't even try on Chrome on iOS, it won't prompt for camera access. Still in 2019😒

**Comment by nicolocarpignoli** [comment]
Can someone tell if this is preproduceable with Simulator of iOS on Mac? In that case I may give it a look

**Comment by kylelamx** [comment]
no.. I think iOS Simulator just don't have web cam access

**Comment by kylelamx** [comment]
Sad to confirm that this happens on the latest ios13 beta 13.0 (17A5534f)

**Comment by nicolocarpignoli** [comment]
I'd like to know if it is an AR.js problem with  new iOS beta or a generic camera-stream problem.

Can someone please tell me if this example works ==> https://mdn-samples.mozilla.org/s/webrtc-capturestill/ ?

**Comment by nicolocarpignoli** [comment]
Also, keep in mind iOS 13 is in beta. It is interesting to dig on it, tho

**Comment by nicolocarpignoli** [comment]
Just tested on iOS 13 beta 4 (https://developer.apple.com/news/releases/?id=07172019d), and it is NOT working, even with a basic camera-using example like the one I posted above.

So it is a serious bug from Apple, for now. Keep in mind that this is still in beta, maybe they changed the APIs, maybe something worse. But I feel like this will be raised in the future from a lot of developers if not get fixed.

For now I close, as it is not an AR.js related bug. If this will come out also on official iOS 13, we will think about it and dig on it more, and eventually open an issue to Apple

**Comment by kylelamx** [comment]
@nicolocarpignoli 
Just some update
The basic camera-using example (https://mdn-samples.mozilla.org/s/webrtc-capturestill/) does not have the autoplay, mute, and playsinline
https://codepen.io/kylelam/pen/oKLxMy

**Comment by nicolocarpignoli** [comment]
@kylelamx I don't know what is changed, but now it works even without those attributes: if you check the URL you have posted on the first post of this thread, it works now with iOS 13. Also, your last example works without autoplay, mute and playsinline (try to remove them on codepen).

Honestly, I don't know how this is possible, I don't think Apple has released a fix silently, but I guess it may happen in iOS beta program.

**Comment by robertpriewe** [comment]
Its fixed in Beta 5 which released today
