### ISSUE TITLE
Add events documentation

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#567]
Last features of AR.js are basically for making development more flexible and open new possibility to developers: we have added several events, from marker-found/marker-lost, camera init and so on. 
It makes sense to document them, and fine a place for that in the Readme or other .md files on the repo.

**Comment by nicolocarpignoli** [comment]
make also aframe/threejs readme (on subfolders) more visible on principal Readme

**Comment by commentatorboy** [comment]
Is there a list of these events right now? Is there a place to find them?

**Comment by nicolocarpignoli** [comment]
You could search on the entire project. Only. Js files under aframe directory or three.js directory. Search for events create with new CustomEvent.

Will be great if you can create a place for them on the Readme. Then I will add the new ones when I will add more.

**Comment by commentatorboy** [comment]
This lists all the "new CustomEvent"'s I could find in the master branch:

- three.js/src/threex/threex-artoolkitsource.js and three.js/build/ar.js: arjs-video-loaded
- three.js/src/threex/threex-artoolkitsource.js and three.js/build/ar.js: camera-error
- three.js/src/threex/threex-artoolkitsource.js and three.js/build/ar.js: camera-init
- three.js/examples/vendor/webvr-polyfill.js: vrdisplaypresentchange
- three.js/examples/vendor/webvr-polyfill.js: vrdisplaydeviceparamschange
- aframe/src/location-based/gps-entity-place.js: gps-entity-place-update-positon
- aframe/src/location-based/gps-entity-place.js: gps-entity-place-added
- aframe/src/location-based/gps-camera.js: gps-camera-origin-coord-set
- aframe/src/location-based/gps-camera.js: gps-camera-update-position
- aframe/src/location-based/gps-camera-debug.js: debug-ui-added
- aframe/examples/places-name/places.js: gps-entity-place-loaded

I found events for "markerFound" and "markerLost" inside aframe/examples/marker-events.html

When I know how and what they are used, I will update the documentation.

**Comment by nicolocarpignoli** [comment]
Yes, they're all.

I have fixed the list, here's the ones to be detailed and added to the docs:

```
three.js/src/threex/threex-artoolkitsource.js and three.js/build/ar.js: arjs-video-loaded
three.js/src/threex/threex-artoolkitsource.js and three.js/build/ar.js: camera-error
three.js/src/threex/threex-artoolkitsource.js and three.js/build/ar.js: camera-init
aframe/src/location-based/gps-entity-place.js: gps-entity-place-update-positon
aframe/src/location-based/gps-entity-place.js: gps-entity-place-added
aframe/src/location-based/gps-camera.js: gps-camera-origin-coord-set
aframe/src/location-based/gps-camera.js: gps-camera-update-position
aframe/examples/places-name/places.js: gps-entity-place-loaded
 aframe/examples/marker-events.html: markerFound
 aframe/examples/marker-events.html: markerLost
```

**Comment by nicolocarpignoli** [comment]
closed, will be added on new repo doc https://github.com/AR-js-org/AR.js/issues/8
