### ISSUE TITLE
AR file offline

### ISSUE THREAD

**Issue by willxvi** [jeromeetienne/AR.js#569]
**Do you want to request a *feature* or report a *bug*?**
Just a doubt

**What is the current behavior?**
I have an AR solution, but all the files on <script> are storage in the AR.js github repository, and there is other resources that are in the folders of the AR.js project. I wanted to know if there is a way to run the solution totally offline.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
I want to teach a few AR examples in distant place without the internet connection.

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment]
Hi @willxvi , yes it is possible. You do not have to use script that are referring to remote AR.js repository, instead you have to take that file (aframe-ar.min.js for example, the one that is referred from the remote script), and place it in your local folder on the pc. Then you have still to refer with the script but using a local path.

For example, if you have a directory where your index.html is in a folder called 'project', you can place the aframe-ar.min.js (or aframe-ar.js, it is the same but bigger size) in the folder project and then use the script like this: 
`<script src="./aframe-ar.js"></script>`

The same you have to do for all the other script (like aframe).

EDIT: I have already answered same question [here](https://github.com/jeromeetienne/AR.js/issues/432)

Also, if you find problem with camera_para.dat file using AR.js offline, check this out https://github.com/jeromeetienne/AR.js/issues/50: you may have to add this script `<script>THREEx.ArToolkitContext.baseURL = './'</script>` to tell AR.js to search for external files referring to your local folder.

**Comment by Nehemek** [comment]
If you'd like your users to be able to run it offline, you could make a progressive web app out of your site https://blog.heroku.com/how-to-make-progressive-web-app#create-code-offline-html-code-as-an-alias-to-code-index-html-code which is what I'm currently doing.

**Comment by droid001** [comment]
I successfully used this boilerplate in a project: https://github.com/digaverse/webxr-webpack-boilerplate
