### ISSUE TITLE
add NoSleep.js in to force phone browser to stay awake

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#57]
https://github.com/richtr/NoSleep.js

This is the one i found after 10 second search. maybe another one would be better. 

- the api is ultra simple which is great
- first test if it works [demo here](https://richtr.github.io/NoSleep.js/example.html)
- need to work in a-frame too

**Comment by ZoltanVeres** [comment]
FYI in [Safari 46](https://webkit.org/blog/8042/release-notes-for-safari-technology-preview-46/) this will be fixed. 
Prevented the display from going to sleep when playing WebRTC video tracks ([r225822](https://trac.webkit.org/changeset/225822/webkit/))

**Comment by nicolocarpignoli** [comment]
obsolete?

**Comment by jeromeetienne** [comment]
nope, it is needed or the phone will go onsleep after a timeout. 

so during the ar experience goes to sleep..

**Comment by nicolocarpignoli** [comment]
not relevant anymore in my opinion.
