### ISSUE TITLE
A Frame light not working if CanvasWidth and CanvasHeight specified

### ISSUE THREAD

**Issue by Nehemek** [jeromeetienne/AR.js#570]
**Describe the bug**
I had issue setting up lights in my project until I randomly experimented with the CanvasWidth and CanvasHeight parameters. If they are not defined, ambient or hemispherical lights do not work.

**To Reproduce**
1. Create a simple setup that loads a model 3d model (important, a frame's primitives do not get shaded).
2. Add an hemispherical/ambient light and a point light to the scene inside the a-marker
3. Run the project on Chrome-Android, you'll see the model is dark.
4. Go back to your project and in the arjs parameters set canvasWidth: 1920; canvasHeight: 1080; (assumming you are runnning landscape).
5. Voila, now the scene is properly lit.

**Expected behavior**
Lights should work regardless of canvasWidth and CanvasHeight definition. They work in a-frame without arjs or in a-frame Inspector Mode (desktop),

**Comment by nicolocarpignoli** [comment]
Closing this issue due to dismission of this repository. New repository of AR.js will be up at https://github.com/AR-js-org/AR.js/

Feel free to re-open the issue there if still valid.
