### ISSUE TITLE
could ar.js use a spritesheet as texture to get a animated texture

### ISSUE THREAD

**Issue by jamess922** [jeromeetienne/AR.js#572]
Could ar.js use a spritesheet as texture to get a animated texture ? something like gif ,but i need to use a spritesheet

**Comment by kalwalt** [comment]
@jamess922 As AR.js and Aframe-ar.js use Three.js in his core, then i think, you can do this, and someone also make this project with **jsartoolkit5**, **three.js** and  **gifler.js** https://github.com/rodrigocam/ar-gif/ maybe could help you!

**Comment by jamess922** [comment]
Thank you
