### ISSUE TITLE
lots of resize events getting fired

### ISSUE THREAD

**Issue by FelixStumvoll** [jeromeetienne/AR.js#574]
**Describe the bug**
Im not quite sure if this is intended behaviour or a bug, but a lot of resize events are getting fired once ar.js has loaded (ca. 20 per second)

**To Reproduce**
Add this to the html page
`<script>
        window.addEventListener("resize", () => console.log("yeet"));
    </script>`

**Expected behavior**
No Events beeing fired since the window isn't resizing

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome, Firefox Dev Edition
 - Version Chrome: 75 , Firefox:69

**Comment by FelixStumvoll** [comment]
I just discovered #91, don't get why its closed though.

**Comment by nicolocarpignoli** [comment]
Hi, you're right the bug is still there!
It's a bug that has not been fixed from a long time. 
I will take care of that. thanks!

**Comment by nicolocarpignoli** [comment]
fixed with https://github.com/jeromeetienne/AR.js/releases/tag/1.7.8
