### ISSUE TITLE
what's the type of this code?Can track this?

### ISSUE THREAD

**Issue by paulwang2012** [jeromeetienne/AR.js#576]
what's the type of this code?like HAMMING code,but color is  reverse
ar.js can  track this?
thank you 
![2](https://user-images.githubusercontent.com/1400571/63657224-91d10e00-c7d1-11e9-9c08-37538ec3123f.jpg)

**Comment by nicolocarpignoli** [comment]
it seems a barcode to me. it's hard to tell which matrix has been used to generate it. maybe a 5x5?

you can check my repo with barcode generator URL and also a lot of generated barcode markers. maybe it can help

https://github.com/nicolocarpignoli/artoolkit-barcode-markers-collection
