### ISSUE TITLE
How to use markers other than Hiro

### ISSUE THREAD

**Issue by curtello** [jeromeetienne/AR.js#58]

**Comment by tcwyjno1** [comment]
I also faced the same issue.... keep watching...

**Comment by jeromeetienne** [comment]
? there is no issue described ?

**Comment by tcwyjno1** [comment]
@jeromeetienne ,maybe he wanted to change Hiro to another picture

**Comment by curtello** [comment]
exactly
that was what I meant actually. Maybe have an asset folder for loading the marker image from

**Comment by jeromeetienne** [comment]
oh ok - here is the documentation on how to create new parttern marker - https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training

**Comment by curtello** [comment]
thanks for the article

**Comment by curtello** [comment]
Hello. I wanted to know if it is possible to have two (physical) cameras
relaying live video using AR.js


I wanted to create a scene that uses multiple cameras for different angles
and I wanted to know if there's a way I can go about it

**Comment by hugobros** [comment]
The links has been change, now it points to this web: https://daqri.com/
Does someone know where to find this tutorial, i can't find the way to make my own markers or use other presets.

Thanks
