### ISSUE TITLE
The model is not aligned to the marker below 500px screen width when embedded.

### ISSUE THREAD

**Issue by ghost** [jeromeetienne/AR.js#580]
**Describe the bug**
(Currently can't test on V1.7.8)
I need to have the AR element embedded into a separate page as it currently causes performance issues for other javascript elements and embedding makes it work smooth (Performance is fixed in V1.7.8 but #579 ). The problem is when the window is resized below 500px width on the embedded page, the objects no longer aligns with the marker.

The object usually goes out of line once the page is refreshed but you can see it if you keep resizing below on responsive

**To Reproduce**
```
<!doctype HTML>
<html>
<script src="Scripts/aframe.min.js"></script>
<script src="Scripts/aframe-ar.js"></script>
  <body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs>
      <a-marker preset="hiro">
          <a-box position='0 0.5 0' material='color: yellow;'></a-box>
      </a-marker>
      <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>

-----------------

<!doctype HTML>
<html style="width: 100%; height:100%;">
    <body style="width: 100%; height:100%;">
        <iframe src="test.html"style="width: 100%; height: 100%"></iframe>
    </body>
</html>
```

1. Copy paste code into 2 HTML files
2. Open 2nd one in chrome
3. F12 and resize width to less than 500px or select iphone x
4. Hit refresh
5. The object should be out of line

**Expected behavior**
The object should stay aligned with the marker

**Screenshots**
***NOT EMBEDDED***
![NotEmbedded](https://user-images.githubusercontent.com/32132360/63932481-2b592380-ca4f-11e9-8f7e-f0fb1d7da437.PNG)

***EMBEDDED***
![Embedded](https://user-images.githubusercontent.com/32132360/63932487-2eecaa80-ca4f-11e9-9c06-3004a66dcd3c.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: ARJS V1.7.7

**Smartphone (Also Tested on my mobile):**
 - Device: Huawei Mate 20 pro
 - OS: Android 9
 - Browser: Chrome

**Additional context**
It stays aligned with the marker until the page is refreshed usually.
Only happens once embedded

**Comment by nicolocarpignoli** [comment]
This is not a bug introduced on version 1.7.7 I guess. Can you please check if it's always present with older version like 1.7.5 or for example 1.7.1? Thank you

**Comment by cconnor12345** [comment]
This seems like an old bug as I have tested with with different versions going back to 1.7.1 and it is still present

**Comment by cconnor12345** [comment]
Have also tried different ways of embedding and still the same issue.

```
        <object data="test.html"style="width: 100%; height: 100%"></object>
        <iframe src="test.html"style="width: 100%; height: 100%"></iframe>
        <embed src="test.html"width="100%" height="100%"style="width: 100%; height: 100">
```

**Comment by allestaire** [comment]
Does anyone have a solution on this?
This issue occurs when using NextJS, still finding the cause
But when using plain html, it works fine

Versions:
- 1.4.2-aframe.min.js
- 3.4.5-aframe-ar.js
