### ISSUE TITLE
Getting error message WebRTC Issue - Navigator.MediaDevice is not presented in your device. when using ar.js on iPad crome browser 

### ISSUE THREAD

**Issue by madlearn** [jeromeetienne/AR.js#583]
Hi 
I was trying to open a HTML page which is using AR.js to render 3D objects.Its working fine on iPad Safari browser but when I was trying with iPad Chrome browser its getting error: WebRTC Issue - Navigator.MediaDevice is not presented in your device.
 How I can resolve this error?
 Should I include any other js library to support/open my camera popup?

**Comment by madlearn** [comment]
I am using iPad with iOS 12.4.1 and crome 76.0.3809.81

**Comment by nicolocarpignoli** [comment]
Chrome on iOS does not have access to the camera. We cannot do anything about that.

**Comment by nicolocarpignoli** [comment]
Use safari on ios

**Comment by bhupichauhan** [comment]
Thanks @nicolocarpignoli

**Comment by roons** [comment]
Safari on iOS has the same issue but it's not consistent.
