### ISSUE TITLE
Multiple markers for the same object

### ISSUE THREAD

**Issue by Seluj78** [jeromeetienne/AR.js#587]
Hi,

I'd like to know if it is possible to have the same object for multiple markers ?

The idea being that I have a marker that is black on white but due to different lighting situations, I'd like to have multiple markers with different white values

Is it possible?

**Comment by meizano** [comment]
Use a-mixin in a-assets will allow you to have this. For example:
`````
<a-assets>
            <a-mixin id="cube" geometry="primitive: box"></a-mixin>
            <a-mixin id="red" material="color: red"></a-mixin>
            <a-mixin id="green" material="color: green"></a-mixin>
        </a-assets>
        <a-entity position="-3.5 1 0">
            <a-entity mixin="cube red"></a-entity>
        </a-entity>

        <a-entity position="3 3 -4">
            <a-entity mixin="cube green"></a-entity>
        </a-entity>
