### ISSUE TITLE
[Coming Soon] Location Based AR on AR.js

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#589]
Hi everybody!

As you can see on the top of the page, I created a very basic 'Project' on AR.js repository: https://github.com/jeromeetienne/AR.js/projects.

I basically have in mind to enhance AR.js with the features you can read in there.
First one that is ready to be merged on AR.js is **Location Based AR.**

I prefer not to describe again what is it and how it works, I already wrote [a Medium article](https://medium.com/chialab-open-source/location-based-gps-augmented-reality-on-the-web-7a540c515b3c) that I suggest you to read if you're interested :) It contains explanation and also working examples.

The library that will be merged is called GeoAR.js, and it's available at this repository: https://github.com/nicolocarpignoli/GeoAR.js.

Soon I will prepare a PR to merge this into AR.js, thus making it multiple AR-type for the first time! 🚀

It is not perfect nor production ready: I'd hope to receive feedback but also PRs for fixes, tips and features. Hope you guys from the community will help me enhance it.

So, in a matter of few weeks, expect to see this new feature on master AR.js version: **this will not break anything, because I will simply add a-frame components that you can use on your app or just ignore**. I will add new documentation too, of course. 

You can still continue using AR.js only with marker based or start experimenting with location based AR (or use even both together!).

See you soon! 🌍

Nicolò

**Comment by kalwalt** [comment]
@nicolocarpignoli yes it will not break anything but instead it will enhance **AR.js**.  It will also needs a lot of testing, finding bugs or other issues. Personally i will try to give my contribution to this project. I hope also a nice feedback from the open source community.

**Comment by nicolocarpignoli** [comment]
It is now merged! 🍻

**Comment by qaribhaider** [comment]
@nicolocarpignoli Good work mate, do we have support for the altitude in this, or just lat/long?

**Comment by nicolocarpignoli** [comment]
For now only long lat, maybe altitude in the future
