### ISSUE TITLE
How do I overlay text on top of a <a-plane> with AR.js and A-Frame?

### ISSUE THREAD

**Issue by hsj63** [jeromeetienne/AR.js#590]
I am in a webAR project with AR.js and A-Frame and I am trying to overlay text on a plane or box, at first I thought the text was behind the plane but after I give an opacity of 0.5 to plane, I realized that the text is not really coexisting with the plane where the two intersect. What am I doing wrong?

I appreciate any help!

![preview](https://user-images.githubusercontent.com/55613289/65368132-18cba780-dc13-11e9-94a9-d232636e612d.png)

My code:

<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

<title></title>

    <script src="js/aframe-0.9.0.min.js"></script>
    <script src="js/aframe-ar-1.7.1.min.js"></script>
    
</head>

<body style='margin : 0px; overflow: hidden;'>

      <a-scene vr-mode-ui="enabled: false" embedded arjs='debugUIEnabled:false; sourceType:webcam; detectionMode: mono_and_matrix; matrixCodeType: 3x3; cameraParametersUrl: camera_para.dat; maxDetectionRate: 10;' renderer="logarithmicDepthBuffer: true; precision: high;">

		<a-assets>
 
            <a-mixin id="text"
				text="align: center; width: 3;
                font: https://cdn.aframe.io/fonts/Aileron-Semibold.fnt;
				value: Some text.">
			</a-mixin>
            
        </a-assets>

        <a-marker type="barcode" value="51" smooth="true" smoothCount="10" smoothTolerance="0.005" smoothThreshold="1">
            <a-plane rotation="-90 0 0" position="0 0 0" material="opacity: 0.7" color="red"></a-plane>
            <a-text mixin="text" position="0 1 0" wrap-count="15" rotation="-90 0 0" color="blue"></a-text>
		</a-marker>
        
    <a-light type="ambient" color="#fff"></a-light>
    <a-light type="directional" color="#fff" intensity="0.3" position="-0.5 1 1"></a-light>
    
    <a-entity camera></a-entity>
    
  </a-scene>

</body>
</html>

**Comment by Seluj78** [comment]
Hey man, have you tried with a `z-index` value superior to 1 ?

**Comment by nicolocarpignoli** [comment]
you should change position of the entities of aframe.

change the `z` axis value in https://aframe.io/docs/1.0.0/components/position.html

**Comment by stemkoski** [comment]
For an example, you could look at:
https://stemkoski.github.io/AR.js-examples/text.html
