### ISSUE TITLE
Image or Video sourceType not working as expected

### ISSUE THREAD

**Issue by jonasjohansson** [jeromeetienne/AR.js#593]
**Describe the bug**
Using Image or Video as sourceType not rendering expected results.

**To Reproduce**
Try: arjs="sourceType: image;  sourceUrl: https://cdn.glitch.com/c9111e7d-1d31-41a0-8e15-78b57caa9816%2Fhiro.jpg?v=1569447311795;

and:  <a-marker type="pattern" preset="hiro">
		    <a-box color="red" position="0 0 -0.5"></a-box>
		</a-marker>	

**Expected behavior**
A red box to appear on top of the image.

**Screenshots**

**Desktop (please complete the following information):**
Chrome, Mac
https://rawgit.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js

**Comment by nicolocarpignoli** [comment]
moved to new repository: https://github.com/AR-js-org/AR.js
