### ISSUE TITLE
how does ARjs get "marker_transform_mat " variable that is showed in code ?

### ISSUE THREAD

**Issue by pans0ul** [jeromeetienne/AR.js#595]
`/**
	 * Populates the provided float array with the current transformation for the specified marker. After 
	 * a call to detectMarker, all marker information will be current. Marker transformations can then be 
	 * checked.
	 * @param {number} markerUID	The unique identifier (UID) of the marker to query
	 * @param {number} markerWidth	The width of the marker
	 * @param {Float64Array} dst	The float array to populate with the 3x4 marker transformation matrix
	 * @return	{Float64Array} The dst array.
	 */

	ARController.prototype.getTransMatSquare = function(markerIndex, markerWidth, dst) {
		artoolkit.getTransMatSquare(this.id, markerIndex, markerWidth);
		dst.set(this.marker_transform_mat);
		return dst;
	};
	`

Hi .
how does ARjs get "marker_transform_mat " variable that is showed in code (  source file : ar.js) ?
It seems there is no detail function to show about getting  'this.marker_transform_mat '

if others  know about this ,please tell me ,thanks a lot

**Comment by kalwalt** [comment]
You should read in the jsartoolkit5 code. https://github.com/artoolkit/jsartoolkit5 function call the Emscripten compiled code: 
artoolkit.getTransMatSquare
Look in the ARtoolkitJS.cpp function: https://github.com/artoolkit/jsartoolkit5/blob/b02f2b8ae94d0e4e45ffad0a05222199b3801962/emscripten/ARToolKitJS.cpp#L512

**Comment by kalwalt** [comment]
And of of i am not wrong this.marker_transform_mat should be filler by marker_info in the C++ code with em_asm call. Sorry but i' m writing by my Smartphone, cannot help more than this.

**Comment by pans0ul** [comment]
@kalwalt  
Thank you for your response!  
is that means we cant read details and modify function  to get  " this.marker_transform_mat "?

I try to make markless AR(viewmatrix changed by image rather than black white grid mark  ) using modified ARjs. 
I read link : 
https://github.com/jeromeetienne/AR.js/issues/503
https://github.com/jeromeetienne/AR.js/issues/190


if we can get transform matrix from image like get "this.marker_transform_mat" from mark ,then replace the "this.marker_transform_mat"  variable and convey imaged matrix into "post-process " of ARjs or ARtoolkit .So the finally effect could be same .

To get transform matrix from image, we can extract feature from image and use PNP method to estimate camera pose .however ,I don't know what is relationship between mark coordinate and camera pose .But I know these are relative .

So the pipeline is that : 

extract feature from image --> camera pose estimation using PnP --> respect to mark coordinate --> convey marker_transform_mat  --> post-process of ARjs 

That's my assumption .

**Comment by pans0ul** [comment]
I don't know if can be achieved or not 

I will appreciate 
If others ever did about this and to discuss this .

and 

Good guy tell me what is relationship between mark coordinate and camera pose .
