### ISSUE TITLE
Zoom / sizing issues on certain Android Devices (Pixel 2 XL)

### ISSUE THREAD

**Issue by peterhintondesign** [jeromeetienne/AR.js#596]
My AR.js project contains other HTML elements that are activated via marker/hiro detection. It works as expected on all iOS devices I've tested and most of the Android devices.

However the Pixel 2 XL (and I assume other XL devices) is showing the same problem identified halfway down the #369 thread (https://github.com/jeromeetienne/AR.js/issues/369#issuecomment-401005144) by curtisboylan. The website resolution appears too large and the AR markers are out-of-scale and out of position.

I don't have a screenshot of my project on the Pixel 2XL (as it's a colleagues device) but I've annotated curtisboylan's screenshot which shows the same issues.

![image](https://user-images.githubusercontent.com/2861604/65833700-df5a0280-e2ca-11e9-95dd-4f14fd029421.png)

I've set the viewport meta to **content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0** as recommended.

For some reason the issue is resolved on the Pixel 2 XL if I change the orientation to landscape mode and refresh the webpage. If I change the orientation back to portrait the issue returns.

Link/ Source code: https://www.itgl.com/ar/demo13.html
Hiros:
![pattern-itgl-hiro-01-white](https://user-images.githubusercontent.com/2861604/65833603-f815e880-e2c9-11e9-8757-ba388fd85ef6.png)
![pattern-itgl-hiro-02-white](https://user-images.githubusercontent.com/2861604/65833604-f815e880-e2c9-11e9-8520-cd060858d329.png)
![pattern-itgl-hiro-03-white](https://user-images.githubusercontent.com/2861604/65833606-f815e880-e2c9-11e9-80db-b49603b89b12.png)

**Comment by Darrel-Collinsworth** [comment]
I'm experiencing a very similar issue, and yeah, it's specifically happening on a pixel XL 2. Did you figure out a way to make the aframe objects appear where they're supposed to be?

**Comment by peterhintondesign** [comment]
Unfortunately I didn't find a fix for this issue.

As a temporary workaround I've got a message prompting users with display issues to use their device in landscape mode - not ideal.

**Comment by nicolocarpignoli** [comment]
If relevant, please re-open issue in the new AR.js repo: https://github.com/AR-js-org/AR.js
