### ISSUE TITLE
Change y-position (height) of gps-entity-place

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#600]
see https://github.com/nicolocarpignoli/GeoAR.js/issues/10

**Comment by jacobjordan94** [comment]
Hey, was just about to open my own feature request but saw that this issue was already opened.
Any timeline when this feature may be added? Some of the gps-entity-place components overlap in my application since their lat/lngs are so close together. Having control over the y-axis would be great.  
Great library by the way, currently using it to replace Wikitude! 😄

**Comment by nicolocarpignoli** [comment]
Hi, 
it's not in the top of priorities but It will definitely be a nice addition.

**Comment by wreszelewski** [comment]
Hi,
@nicolocarpignoli I need this one as well and I can place a PR. How do you think y-axis value should be defined? Would this be ok:
`<a-box color="yellow" gps-entity-place="latitude: <your-latitude>; longitude: <your-longitude>; yPosition: <your-y-axis-value>"/>` ?

**Comment by nicolocarpignoli** [comment]
Hi @wreszelewski, I was thinking of something like: 

<a-box color="yellow" gps-entity-place="latitude: <your-latitude>; longitude: <your-longitude>; altitude: <your-y-axis-value>"/>

Altitude (a.k.a. y axis value) will be handled as optional, instead of latitude/longitude that are required.

**Comment by wreszelewski** [comment]
Does "altitude" should consider current altitude of user from GPS? Or it should be just value that is set without any modifications as y parameter of position?

I can imagine that altitude relative to GPS can be used to create some AR mountain panorama, but it doesn't solve problem described by @jacobjordan94 .

**Comment by nicolocarpignoli** [comment]
makes sense. It's better to keep them separated, as concept and names.

So yPosition sound good.

```
<a-box color="yellow" gps-entity-place="latitude: <your-latitude>; longitude: <your-longitude>; yPosition: 3;"/>

```

It will practically means 'i want to see that object 3 meters high from the ground' where the ground is the default value, not a real estimation of the ground (of course).

**Comment by nicolocarpignoli** [comment]
On version 2.1.8, it is now possible to specify an height! 

Just add the position property of AFRAME using, for example:

`<a-box position="0 200 0"></a-box>`

Now the system will handle that.
