### ISSUE TITLE
Add a demo with possibility to make the user add 3D models on specified GPS locations examples

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#601]
The idea is to add another example for the location based. Basically:

* detect the user coordinates in the real world
* give the user a basic UI in order to choose between some 3D models
* clicking on one of them, the object will be placed at the same position of the user.

Additionally:

We have to investigate the possibility to add objects with a RELATIVE distance from user position. This in my opinion requires modifies on the AR.js location based core, but it may not be difficult to do.

**Comment by nicolocarpignoli** [comment]
@kalwalt this is the demo you were working on :)

**Comment by dmtrs** [comment]
Link in comment https://github.com/jeromeetienne/AR.js/issues/601#issue-504616191 is broken.

Is there any resources on the topic?

**Comment by kalwalt** [comment]
@dmtrs i think it is broken because the issue page does not exist anymore but you can see the PR https://github.com/nicolocarpignoli/GeoAR.js/pull/9

**Comment by nicolocarpignoli** [comment]
@dmtrs exactly as kalwalt said. The page is lost because I removed issue section on GeoAR.js and moved them here on AR.js.

I will add a better description on the main post, sorry about that

**Comment by nicolocarpignoli** [comment]
Not a priority right now. Will open new issues about examples when needed.
