### ISSUE TITLE
Integrate altitude data

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#603]
see https://github.com/nicolocarpignoli/GeoAR.js/issues/6

**Comment by Wulff2099** [comment]
The link is broken someone have an example?

**Comment by nicolocarpignoli** [comment]
No, the issue here is to integrate altitude in AR.js location based. Actually this feature is just not available, it has to be integrated.

**Comment by Wulff2099** [comment]
Ok, Thanks a lot.

**Comment by nicolocarpignoli** [comment]
We have already added a simulateAltitude, that work along with y-Position of AFRAMe, if provided. New details will be available at new AR.js repository: https://github.com/AR-js-org/AR.js/

**Comment by Wulff2099** [comment]
Hello Nicolo,
Thanks foto te update. I hope you and your family are ok tener in Italy.

**Comment by nicolocarpignoli** [comment]
Yes we are ok, thank you so much for asking 😊
