### ISSUE TITLE
Adding Maker and 3dModel

### ISSUE THREAD

**Issue by Kumaresh-Rajalingam** [jeromeetienne/AR.js#61]
Hello 
How to add my own maker and 3dmodels in webAR using A-Frame 

Thanks in advance

**Comment by chisaipete** [comment]
Check out the A-Frame documentation on how to load a model.  I basically used the <a-obj-model> tag as documented [here](https://aframe.io/docs/0.5.0/primitives/a-obj-model.html). Also, I'm working on the "own marker" bit, but I was trying to use barcode markers and they are currently broken.  The theory for one of the other markers is that you'd probably have to add the training pattern for the marker (not Hiro or Kanji) and ensure it's loaded into jsartoolkit properly, but I haven't done that yet.

**Comment by darasat** [comment]
for use my own pattern I did the following:

1. I create my own github data --> https://github.com/darasat/data ( I trained the pattern with 
 http://flash.tarotaro.org/blog/2009/07/12/mgo2/)

2. I create a variable in the aframe-ar.js called darasatURL
THREEx.ArToolkitContext.darasatURL = 'https://raw.githubusercontent.com/darasat/data/'

3.  Following in the parameters section

THREEx.ArToolkitProfile.prototype.reset = function () {
	this.sourceParameters = {
		// to read from the webcam 
		sourceType : 'webcam',
	}

	this.contextParameters = {
		cameraParametersUrl: THREEx.ArToolkitContext.baseURL + '../data/data/camera_para.dat',
		detectionMode: 'mono',
	}
	this.defaultMarkerParameters = {
		type : 'pattern',
		patternUrl : THREEx.ArToolkitContext.darasatURL + 'master/tiger.patt'
	}
	return this
};

4. After this in the markers section

THREEx.ArToolkitProfile.prototype.tigerMarker = function () {
	this.contextParameters.detectionMode = 'mono'

	this.defaultMarkerParameters.type = 'pattern'
	this.defaultMarkerParameters.patternUrl = THREEx.ArToolkitContext.darasatURL + 'master/tiger.patt'
	return this

}

6. Finally in the init function add the comparison with the new marker created

init: function () {
		// honor this.data.preset
		if( this.data.preset === 'tiger' ){
			this.data.type = 'pattern'
			this.data.patternUrl = THREEx.ArToolkitContext.darasatURL+'master/tiger.patt'
		}

7. In the HTML add a aframe scene with the assets from the model and new preset pattern in this case tiger

	<a-scene embedded artoolkit='sourceType: webcam'>
	

		<a-assets>
         <a-asset-item id="tree" src="../modelos/meowth/meowth.dae"></a-asset-item>
		</a-assets>

		  <a-entity collada-model="#tree"  scale="0.2 0.2 0.2" ></a-entity>
		  
		 
		  
		  

		<a-marker-camera preset='tiger'></a-marker-camera>
	</a-scene>

and this works!


I hope this solves the problem of the own marker with custom 3d Model, greetings from Colombia.

**Comment by gundanx10** [comment]
custom marker #
