### ISSUE TITLE
iOS 13 access to Motion Sensors

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#611]
This issue was originally opened on GeoAR.js repo, now merged into this with v2.0.0. See following PDF attached for thread. Images were too heavy to attach.

[iOS 13 removed "Motion & Orientation Access" · Issue #12 · nicolocarpignoli:GeoAR.pdf](https://github.com/jeromeetienne/AR.js/files/3725742/iOS.13.removed.Motion.Orientation.Access.Issue.12.nicolocarpignoli.GeoAR.pdf)

**Comment by chrismatthieu** [comment]
That worked. Thank you!
