### ISSUE TITLE
I can't read two (or more) markers at the same time if they are the same.

### ISSUE THREAD

**Issue by thiagolopess** [jeromeetienne/AR.js#613]
**The bug**
While poiting to equal markers, instead of showing the same 3d figure on top of all of them, they compete to see which one will keep it.

**To reproduce** it, just point to two (or more) equal markers at the same time.

**Expected behavior**
It is expected that equal markers don't conflict with which other.

**Desktop:**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [77.0.3865.90 (64 bits)]

**Obs.:**
I don't really know if this is a bug or if it is meant to be that way, but is kinda holding me down.

**Comment by surya-trv-13** [comment]
> As far as I know, it has always behaving this way: can recognize two markers at the same time if different, otherwise it tries to render one content if the marker are multiple but the same.

So is there any way to get this thing working. I am also having same problem.

**Comment by nicolocarpignoli** [comment]
Nope. https://github.com/jeromeetienne/AR.js/issues/656

I suggest you all, in order to show the same content, to connect the same content for different markers, and show them at the same time. That will work.
