### ISSUE TITLE
Check if mobile before activating camera.

### ISSUE THREAD

**Issue by chrismatthieu** [jeromeetienne/AR.js#615]
I am using this library in a WebXR app that is also being used by VR devices (no camera) as well as AR capable devices. It would be nice to add a flag or condition to check if the device is AR or VR before trying to activate camera. Perhaps checking for mobile device would be good enough for now.

if (AFRAME.utils.device.isMobile()){ activate camera }

**Comment by nicolocarpignoli** [comment]
Hi, I have a question: what's the point to check if camera is present, if AR.js usage makes sense only if camera is enabled?

I see this as an useful check only if it is causing a break of the entire app, and you want clearly to avoid this

**Comment by chrismatthieu** [comment]
Perhaps my use case is not a normal one but I have 1 web app that can be run on mobile (AR), PC (VR), and VR HMDs. Even though my PC has a camera, my use case wants the PC to act as-if in WebVR mode (no camera activated). Mobile use case is traditional AR only mode. The camera is coming on for the PC which is not intended. I tried loading ARjs after page load if device is mobile but the camera doesn't activate after page load. This is why I was suggesting a flag or detection in your script.

**Comment by nicolocarpignoli** [comment]
Ok, this could be done, and this condition could be activated explicitly via attributes of `arjs` on the a-scene component. When I have time I will give it a look, but there are other priorities right now regarding bugs :)

I will update here when in case.

**Comment by nicolocarpignoli** [comment]
added on new repository issues
