### ISSUE TITLE
Error Camer IOS Ionic with WKWEBVIEW and WEBRTC , also using cordova-plugin-iosrtc

### ISSUE THREAD

**Issue by Ciro99678** [jeromeetienne/AR.js#618]
Hi, everyone.
I know that WKWEBVIEW used in Ionic webviews doesn't work with WEBRTC but i found this cordova plugin called cordova-plugin-iosrtc, that will reference to the webrtc api.
So i'm asking if there is some type of integration between ar.js and this cordova-plugin.

i'm trying to get this plugin work with ARJS but i get stucked in the WEBRTC navigator.getUserMedia error.

So, anyone has some help or suggestion?
Thanks.

**Comment by smuddy** [comment]
Hi Ciro,

did you get any solutions?
In my project I sed the cordova registration from the plugin as described in the readme.md. 
The navigator.getUserMedia-Error is gone, but I still have no video image.

**Comment by Ciro99678** [comment]
Hi smuddy,
I didn't get any solution.
i think that we just need to wait for Apple to implement WEB-Rtc on WKWebView.

**Comment by smuddy** [comment]
step-by-step: the videostream is attached to the video-element and if I attach it to the DOM, it shows the camera stream - so basicly the webrtc adapter works.

I think, its a Problem with the inititialisation of AR.js.

**Comment by Ciro99678** [comment]
If the video stream is working, i think you can implement from AR.js source code , to a specific camera stream it has to manipulate and effect.
I still didn't get the video-stream from the cordova-webrtc adapter. (also cause i stopped to work with it, but i am  still interested in it).

**Comment by smuddy** [comment]
did you run the API preparation code from the Plugin?
``` 
// Just for Cordova apps.
document.addEventListener('deviceready', function () {
  // Just for iOS devices.
  if (window.device.platform === 'iOS') {
    cordova.plugins.iosrtc.registerGlobals();
 
    // load adapter.js
    var adapterVersion = 'latest';
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "https://webrtc.github.io/adapter/adapter-" + adapterVersion + ".js";
    script.async = false;
    document.getElementsByTagName("head")[0].appendChild(script);
  }
});
```
Also a little linke in the aframe-ar.js hast to be removed: `if(!domElement.videoWidth) return;`, this property is probably not set by the cordova plugin.
Et voila: the video works.
Still the wrong camera is used but I think thats another issue.
