### ISSUE TITLE
Object is jittery the first time when using Safari on an iOs Device

### ISSUE THREAD

**Issue by BaermediaKN** [jeromeetienne/AR.js#621]
I tried to get something to work with ar.js and it works rather great on my PC and on my Android phone, when I test it on an iPad Pro with Safari however it the object just disappears and reappeares very frequently and jittery.
If I reload the page it works fluently. 
If I empty the cache and reload the problem emerges again. So I would assume Safari has issues with loading the objects?
Anybody else experienced those problems and has an idea on how to fix it?

**Comment by nicolocarpignoli** [comment]
Yes, I experienced that. I get it's a problem with loading model, but never had the time to investigate further, also why only on iOS. btw, you could try using the following script, and add 'markerhandler' attribute on the a-scene element:

```
AFRAME.registerComponent('markerhandler', {
    init: function() {
        const model = document.querySelector('a-entity[animation-mixer]')
        const asset = document.querySelector('#animated-asset');
        const src = asset.getAttribute('src');
        model.addEventListener('model-loaded', () => {
            if (!THREE.Cache.files || !THREE.Cache.files[src]) {
                location.reload();
            }
        });
}});
```

change the first query selector in order to select the a-entity that shows the jitter, and change the second query selector in order to select the 3D asset (assuming you are using asset-item entities, if not, I suggest to do that).

Let me know if it works or if you need further help

**Comment by BaermediaKN** [comment]
Sadly it did not work. 
I think I might do a workaround where I reload the page once, when somebody accesses it. Maybe that will work.

**Comment by redbrushz** [comment]
I have a same problem. I tested on IOS13.2 ipad pro too. I open website its so lack camera and show just one second model.
And then I lock my screen for 2-3 hours when I come back again I found it work is fine. Camera not lack and animation is good same on android.
So I dont know position for put those code , can you share some exsample please?
Thanks.

**Comment by nicolocarpignoli** [comment]
it's strange, I have also found that bug, two times at least. I used the workaround that I posted above, and it works. The thing is, on Safari, sometimes, for heavy models, the scene is rendered before the model is fully loaded and then it works badly as you have seen. If you reload the page, `three.js` keeps in cache the model and re-use it: that time the model is ready so the problem won't occur.

EDIT: I think that the fact that does not make it work for you is that maybe you are not using a-asset of aframe https://aframe.io/docs/0.9.0/core/asset-management-system.html

it's always better to load your assets on the HTML this way:

```
 <a-assets>
    <a-asset-item id="horse-obj" src="horse.obj"></a-asset-item>
    <a-asset-item id="horse-mtl" src="horse.mtl"></a-asset-item>
    ....
  </a-assets>
```

and refer them using `#<asset-it>` on the a-entity. 

So, try use a-assets/a-asset-item and the code I posted above for cache check and reload. It should work on Safari

**Comment by BaermediaKN** [comment]
`
<!doctype HTML>
<html>
  <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>           
  <script src="https://raw.githack.com/jeromeetienne/AR.js/1.7.7/aframe/build/aframe-ar.js"></script>          
  <script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>

  <script>
    AFRAME.registerComponent('markerhandler', {
      init: function() {
        debug.log("test");
          const model = document.querySelector('a-entity[testing]')
          const asset = document.querySelector('#asset');
          const src = asset.getAttribute('src');
          model.addEventListener('model-loaded', () => {
              if (!THREE.Cache.files || !THREE.Cache.files[src]) {
                  location.reload();
              }
          });
    }});
  </script>

  <body style="margin : 0px; overflow: hidden;">   
    <a-scene embedded arjs="debugUIEnabled: false" vr-mode-ui="enabled: false" >  

      <a-assets>  
        <a-asset-item id="asset" src="https://raw.githubusercontent.com/nicolocarpignoli/nicolocarpignoli.github.io/master/ar-playground/models/CesiumMan.gltf"></a-asset-item>
      </a-assets>
    <a-marker preset = "hiro" markerhandler registerevents = "true">  

      <a-entity
      id="testing";
      gltf-model="#asset"
      position="0 0 0"
      rotation="0 0 0"
      scale="0.5 0.5 0.5"
      animation-mixer="loop:repeat"></a-entity>
  	</a-marker>
  	<a-entity camera></a-entity>   
    </a-scene>
  </body>
</html>
`

This is my current full code & the one that isn't working. I feel like it disappears/reappears every other frame now, but not sure if that is different than before.
 I think i am using it correctly? Or what am I doing wrong :D

**Comment by commentatorboy** [comment]
It is a longshot, but try and add the following as an attribute in the a-scene tag.
`renderer="colorManagement: true; precision: medium"`

**Comment by taime** [comment]
Have the same Issue. Catching it only on iPhoneX and only if load page the first time (need to clear all safari data to reproduce issue).

**Comment by nicolocarpignoli** [comment]
we can continue discussing this at new repo address: https://github.com/AR-js-org/AR.js/
