### ISSUE TITLE
Use location based indoor

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#623]
Actually using location based indoor works but only if GPS signal is good and even so, results is good only using one place for building. 

This because GPS signal is not precise enough to rely on that. It's possible to be indoor and see AR content that is bound to the actual place the user is (the building) but adding more content per location is not reliable.

In order to do that, the idea is to use different kind of data instead of GPS, or combine more (GPS + Wifi, Wifi signals power, and so on).

I'm not an expert on this, maybe someone can propose something.
Keep in mind that data has to be acquired from smartphones, so ideally we can only rely on smartphone's common sensors, and not specific embedded hardware.

**Comment by an0rak-dev** [comment]
Hi @nicolocarpignoli 

Maybe GPS datas are enough. I'm currently trying to display several AR objects in a room, separated by few meters only. I've done some tests with the `navigator.geolocation.getCurrentPosition` function which returns really precise datas on my phone (iPhone 6s), it detect the coords after I moved of 1m.

I think a way to implement this, is to change (or adapt) the algorithm of `computeDistanceMeters` in `gps-camera`. Actually it use the great-circle distance algorithm, which is precise enough for most of the case. But for cases where distances between objects are small, I think we should use the Vincenty's inverse formulae (cf : https://www.movable-type.co.uk/scripts/latlong-vincenty.html ), which can be precise to the millimetre level. I'll try with my use case, and will let you know 😄 

Anyway, thanks for your work on AR.js 👍

**Comment by nicolocarpignoli** [comment]
@an0rak-dev It will be a great enhancement to the library. Please let me know when you have some first test on this! thank you so much.

**Comment by nicolocarpignoli** [comment]
we can continue discussing this at new repo address: https://github.com/AR-js-org/AR.js/
