### ISSUE TITLE
add some mutual

### ISSUE THREAD

**Issue by he-jiahao** [jeromeetienne/AR.js#624]
How do I rotate the model with my finger。
How can I achieve it

**Comment by Rmuli** [comment]
你是不是发错人了？




| |
muli_bupt
|
|
邮箱：muli_bupt@163.com
|

Signature is customized by Netease Mail Master

On 10/23/2019 14:38, he-jiahao wrote:

How do I rotate the model with my finger。
How can I achieve it

**Comment by he-jiahao** [comment]
> 你是不是发错人了？| | muli_bupt | | 邮箱：muli_bupt@163.com | 签名由网易邮件管理员定制，他在10/23/2019 14:38写道：他如何用手指旋转模型。我如何实现它-因为您已订阅此线程，因此您将收到它。直接回复此电子邮件，在GitHub上查看或取消订阅。

啥？我也不知道呀

**Comment by nicolocarpignoli** [comment]
Please guys the 'official' language in Open Source is english, and it's the same for this repository, so everyone can understand. Thanks

**Comment by nicolocarpignoli** [comment]
@he-jiahao rotate the model with the finger is something achievable using click/touch events on a-frame entities. Is not easy to do this now. Please take a look at this:

https://github.com/jeromeetienne/AR.js/issues/249

also can help: https://medium.com/swlh/how-to-handle-click-events-on-ar-js-f397ea5994d

these are for click events, you should handle 'touch' instead.
