### ISSUE TITLE
[Bug?] Extra space on the right side of the screen on iOS safari in portrait orientation

### ISSUE THREAD

**Issue by yu-takada** [jeromeetienne/AR.js#625]
Hi, I found that in the portrait mode of iOS safari, there is some extra white space on the right side of the screen(outside of the screen) ,that means you can accidentaly scroll to the white space.

You can see the problem on this sample site as well, so it seems not to be the problem of my code.
https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html

Any solution to this?
Thank you!

**Comment by gordoncooke** [comment]
I'm on Chrome 80 on Android 10. I have seen the same- a white border about as wide as the VR icon. But it's only there sometimes (less often than not). Feels random, I can't always reprodice it, but seems related to change of screen- either rotate from landscape back to portrait, or VR headset mode back to screen based AR.
