### ISSUE TITLE
How do I use 3x3 artoolkit markers for multi-marker area learning.

### ISSUE THREAD

**Issue by usama-ghufran** [jeromeetienne/AR.js#627]
As the title suggests, how do I use 3x3 artoolkit markers for multi-marker area learning.

I've been able to use 3x3 markers by themselves but the area training seem to use different source files. 

My training json looks like this
```
{
  "backURL": "https://192.168.1.123:8125/api/AR.js-2.0.0/three.js/examples/multi-markers/examples/player.html#%7B%22trackingBackend%22%3A%22artoolkit%22%7D",
  "trackingBackend": "artoolkit",
  "detectionMode": "mono_and_matrix",
  "markersControlsParameters": [
    {
      "type": "barcode",
      "barcodeValue": "0"
    },
    {
      "type": "barcode",
      "barcodeValue": "1"
    },
    {
      "type": "barcode",
      "barcodeValue": "2"
    },
]}
```
When I set debug to true I can see that the markers are detected.
![image](https://user-images.githubusercontent.com/11594918/67507194-071d6a00-f6c1-11e9-89f0-8d4ec88edb70.png)

However I can't seem to get them to detect normally. What am I doing wrong?
![image](https://user-images.githubusercontent.com/11594918/67507282-2e743700-f6c1-11e9-9b46-dbc43294a66c.png)

**Comment by Ryuno-Ki** [comment]
Hint: Put three back ticks before and after code (a so called code fence).

**Comment by Rmuli** [comment]
能不能别给我发邮件了？真的打扰我的生活了...




| |
muli_bupt
|
|
邮箱：muli_bupt@163.com
|

Signature is customized by Netease Mail Master

On 10/25/2019 00:54, André Jaenisch wrote:

Hint: Put three back ticks before and after code (a so called code fence).

**Comment by usama-ghufran** [comment]
@Ryuno-Ki I know. It was removing the whitespaces and new lines from the json file. 
@Rmuli , just unsubscribe!

**Comment by Ryuno-Ki** [comment]
Not sure, whether you can apply [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) via reply-by-mail.

It would look like this via Web UI:

```json
{
  "backURL": "https://192.168.1.123:8125/api/AR.js-2.0.0/three.js/examples/multi-markers/examples/player.html#%7B%22trackingBackend%22%3A%22artoolkit%22%7D",
  "trackingBackend": "artoolkit",
  "detectionMode": "mono_and_matrix",
  "markersControlsParameters": [
    {
      "type": "barcode",
      "barcodeValue": "0"
    },
    {
      "type": "barcode",
      "barcodeValue": "1"
    },
    {
      "type": "barcode",
      "barcodeValue": "2"
    },
]}
```
Google Translate gives me some weird translation by @Rmuli. I assume for now that it was not inserted manually.

**Comment by usama-ghufran** [comment]
Umm guys, can we please get back to the problem at hand ? 😅

**Comment by nicolocarpignoli** [comment]
we can continue discussing this at new repo address: https://github.com/AR-js-org/AR.js/

feel free to re-open there
