### ISSUE TITLE
Pre-processing of camera image

### ISSUE THREAD

**Issue by mcallistertyler95** [jeromeetienne/AR.js#630]
Is there a way to pre-process the camera stream sent to the marker detection? For example cropping the size or applying a filter?

Thanks

**Comment by nicolocarpignoli** [comment]
Relates to https://github.com/jeromeetienne/AR.js/issues/571

The possibility to manipulate the stream and give it back to AR.js processing will able a lot of different use case.

If someone has time and will to help, a PR is welcome!

The flow can be:

* intercept video stream of camera 
* trigger an event with the stream as payload. If an option is active (from a-scene, for example), the stream is preprocessed 
* anyway, handle the event, and pass it to AR.js to start the application

**Comment by nicolocarpignoli** [comment]
see in new AR.js repository (automatically linked on this issue)
