### ISSUE TITLE
GeoAR: How to start?

### ISSUE THREAD

**Issue by Zanzak123** [jeromeetienne/AR.js#632]
Hello!

I can’t start using GeoAR! Examples do not work.
I am trying to place an object next to me.
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>GeoAR.js start</title>
    <script src='https://aframe.io/releases/0.9.2/aframe.min.js'></script>
    <script src='../../build/aframe-ar.js'></script>
    <script>
        THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/AR.js/master/three.js/'
    </script>
</head>
<body style='margin: 0; overflow: hidden;'>
	<a-scene gps-camera-debug embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
        <a-box color="yellow" gps-entity-place="latitude: 52.228999; longitude: 21.149128"/>
        <a-camera gps-camera rotation-reader></a-camera>
    </a-scene>
</body>
</html>
```
I see only a white screen.

**Comment by nicolocarpignoli** [comment]
Hi, please fill the issue with more details:

- your device, OS, browser version
- what problem did you get? only white screen - but you get prompt for camera and gps permissions?

**Comment by Zanzak123** [comment]
> Hi, please fill the issue with more details:
> 
> * your device, OS, browser version
> * what problem did you get? only white screen - but you get prompt for camera and gps permissions?

1. Device: Honor 9 Lite, Android 7.1.1.
2.  a. Оnly white screen without text;
     b. No requests for camera and GPS data.

**Comment by nicolocarpignoli** [comment]
Very strange, I need to see the log console of your devtools. A screenshot would do

**Comment by Zanzak123** [comment]
![image](https://user-images.githubusercontent.com/57169529/67858524-6f89a280-fb2a-11e9-9e80-a1d2b3bfbeca.png)


> Very strange, I need to see the log console of your devtools. A screenshot would do

![image](https://user-images.githubusercontent.com/57169529/67858539-787a7400-fb2a-11e9-81f4-992347f896ba.png)

**Comment by nicolocarpignoli** [comment]
@Zanzak123 I think you have activated WebXR API flag on Chrome (maybe for experimenting). try to disable it

https://www.w3.org/TR/webxr/

**Comment by jonaspetersorensen** [comment]
@Zanzak123  Just wondering, this file, it is present in _your_ web app?
```
<script src='../../build/aframe-ar.js'></script>
```

**Comment by Zanzak123** [comment]
> @Zanzak123 I think you have activated WebXR API flag on Chrome (maybe for experimenting). try to disable it
> 
> https://www.w3.org/TR/webxr/

Thanks. It fixed.
