### ISSUE TITLE
How can i use ar.js without A-Frame? use a three.js 3D canvas created with another library.

### ISSUE THREAD

**Issue by EPurpl3** [jeromeetienne/AR.js#633]
Hi, first of all thank you for this great library. I am still amazed that it exist and that is so easy to start with it.

I have found many examples of how to use ar.js with aframe.js but i have a three.js canvas/scene/object created with 3d-forced-graph.js (https://github.com/vasturiano/3d-force-graph) and i want to use that canvas/scene/object in a AR environment. I couldn't find any example of how to integrate a three.js canvas with ar.js without using aframe.js.

Any tips about how to add ar.js to the code below?

THE 3D FORCE GRAPH SCENE
https://vasturiano.github.io/3d-force-graph/example/basic/

THE CODE

          <head>
          <style> body { margin: 0; } </style>
          <script src="//unpkg.com/3d-force-graph"></script>
          </head>

          <body>
          <div id="3d-graph"></div>

          <script>
          // Random tree
          const N = 300;
          const gData = {
          nodes: [...Array(N).keys()].map(i => ({ id: i })),
          links: [...Array(N).keys()]
          .filter(id => id)
          .map(id => ({
          source: id,
          target: Math.round(Math.random() * (id-1))
          }))
           };

          const Graph = ForceGraph3D()
          (document.getElementById('3d-graph'))
          .graphData(gData).nodeThreeObjectExtend(true);

          </script>
          </body>

Thanks

**Comment by kalwalt** [comment]
Interesting @EPurpl3 ! IMO If it is based on Three.js of course it is possible to use with ar.js, you should look at the three part of [AR.js](https://github.com/jeromeetienne/AR.js/tree/master/three.js) examples [here](https://github.com/jeromeetienne/AR.js/tree/master/three.js/examples). Probably you should create an extra layer to fill the Ar.js canvas with the https://github.com/vasturiano/3d-force-graph canvas and to take the matrix transform from the 3dgraph to artoolkit ( that ar.js is based) I think that it not so simple but it can be done. Look at  https://github.com/jeromeetienne/AR.js/blob/master/three.js/src/threex/threex-artoolkitcontext.js to have an idea. I would help more but i have a limited time...

**Comment by EPurpl3** [comment]
@kalwalt Hi, thanks for the tips. Meanwhile i have found out that 3D Force Graph has a AFrame library https://github.com/vasturiano/aframe-forcegraph-component and a VR library https://github.com/vasturiano/3d-force-graph-vr . With all this i am certain that i will be able to do it when i will have a bit of free time. I will return with a link. Thanks.

**Comment by kalwalt** [comment]
Yes probably with that aframe library will be easier to port to aframe-ar.js, good luck! :smile:
