### ISSUE TITLE
Prepare for Chrome 79 release (web XR in navigator by default)

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#635]
It's necessary to handle new Web XR Device API default support on chrome from version 79+.

https://www.chromestatus.com/features/schedule

XR APIs will be present by default on the browser, this can potentially break AR.js based applications. 

Before 10 of December, it's required - until a WebXR support will not ship for AR.js - to NOT use default XR API but current one (polyfill).

**Comment by spartalisdigital** [comment]
What can we do to advance this? I will study about the update to collaborate.

**Comment by nicolocarpignoli** [comment]
Hi and thanks to be willing to help!
@spartalisdigital install chrome canary (version 79) and try to launch any AR.js based example.
 If it's not working, see in console what's the error and please post here screenshots

**Comment by nicolocarpignoli** [comment]
this is a bug coming from imported aframe.

I opened an issue on their repo: https://github.com/aframevr/aframe/issues/4317

**Comment by commentatorboy** [comment]
I am also taking a look at this.
Right now it works on my phone. Will check on PC later.

**Comment by kalwalt** [comment]
It seems that version 79 is out... What next? May i help in some way?

**Comment by joseccnet** [comment]
2019-12-14. Aframe 1.0.0 is out and it's working with AR.js 2.0.8 on Android 8.0 and Chrome 79(webXR enable by default).

**Comment by nicolocarpignoli** [comment]
No action is required on AR.js side. 
A-frame (which gave problems with web xr spec in beta) now works. 

If you find problems with AR.js based apps and are using a-frame, please use the v1.0.0 to avoid problems with WebXR device API
