### ISSUE TITLE
Location-based AR shows 3D object at viewer's origin.

### ISSUE THREAD

**Issue by 7h30n3** [jeromeetienne/AR.js#639]
**Describe the bug**
Using a minimal example to get location-based AR to work always shows the example 3D objects at "viewer-origin" even though the GPS coordinates are set many meters away from the current viewers position.
To describe it in another way, when I load the website the 3D objects spawns at my current location. I can move away from this initial position and the object gets smaller. I think that's also the reason why I only see one of the two objects, because they spawn on top of each other.

**To Reproduce**
```<html>
<head>
    <script src="thirdparty/aframe/aframe.min.js"></script>
    <script src="thirdparty/aframe/aframe-ar.min.js"></script>

    <script charset="utf-8">
        THREEx.ArToolkitContext.baseURL = 'thirdparty/three/build/';
    </script>
</head>

<body style='margin: 0; overflow: hidden;'>
	<a-scene gps-camera-debug embedded arjs='sourceType: webcam; debugUIEnabled: false;'>
            <a-box color="red" gps-entity-place="latitude: 50.813540; longitude: 12.926963" material scale geometry position/>
           <a-box color="blue" gps-entity-place="latitude: 50.815512; longitude: 12.926447" material scale geometry position/>
    <a-camera gps-camera rotation-reader camera="" position="" rotation=""></a-camera>
   </a-scene>  
 </body>
</html>
```

**Expected behavior**
The object should appear further away.

**Smartphone (please complete the following information):**
 - Device: BQ X2
 - OS: Android 9
 - Browser Chrome
 - Version 78.0.3904.62

**Additional context**
I also get the following error:
``` 
Failed to recalculate device parameters. @ aframe.min.js:140
Using fallback Android device measurements. 
```
But I don't think that's the problem.

**Comment by nicolocarpignoli** [comment]
Hi
the log in the 'additional context' is not a problem.

To understand better, to launch this example in your local environment and see if it works (of course, you have to change longitude/latitude according to your position)

https://github.com/nicolocarpignoli/location-based-ar-tutorial/tree/master/static-on-html

**Comment by 7h30n3** [comment]
Unfortunately the problem persists. However, this demo: https://nicolo-carpignoli.herokuapp.com/examples/basic.html places the images on the right position.

**Comment by nicolocarpignoli** [comment]
Which version of AR.js are you using? try to import remotely the last one on the master branch. Tell you this because there was a bug like yours in version 2.0.0 and some versions later, but now it's fixed.

**Comment by 7h30n3** [comment]
According to the console log I have
```
AR.js 2.0.5 - trackingBackend: artoolkit
A-Frame Version: 0.9.2 (Date 2019-05-06, Commit #f57a1fa) 
three Version (https://github.com/supermedium/three.js): ^0.102.2
WebVR Polyfill Version: ^0.10.10
```

**Comment by nicolocarpignoli** [comment]
ok, so loading places statically, using an array, with Javascript, works.

But you found problems loading with HTML?

It's strange as I have not encountered problems with this example, similar: https://github.com/nicolocarpignoli/location-based-ar-tutorial/tree/master/static-on-html

**Comment by 7h30n3** [comment]
> ok, so loading places statically, using an array, with Javascript, works.
> 
> But you still have problems loading with HTML?

That's correct.

**Comment by nicolocarpignoli** [comment]
Ok, I guess the answer is that the problem still persist (it was a temporary fix as stated).

Probably you are using an a-box that loads fast and causes the bug to appear.

I have to investigate it.

**Comment by nicolocarpignoli** [comment]
I will re-open the bug, thanks

**Comment by nicolocarpignoli** [comment]
We continue in the 'original' issue. thanks a lot
