### ISSUE TITLE
Create an AR.js Github organization

### ISSUE THREAD

**Issue by cwervo** [jeromeetienne/AR.js#641]
Now that the maintainer isn't Jerome it's a tad confusing that this project is tied to his personal GitHub account. It would be free & pretty easy to transfer ownership of this repo to [a new `ARjs` Github organization](https://github.com/pricing) and would also make it easier for other to contribute & find this project.

@jeromeetienne would you be fine with this?

In order to solve the GH pages issue in #253 I'd proposed instead of transferring ownership the new ARjs organization clones jerome's personal copy & the personal copy is updated with something like:

# ⚠️ This is no longer the most up-to-date Github repo for AR.js, please go to AR.js/AR.js⚠️

to reflect it's not actively maintained anymore [but! Jerome _should not_ [archive](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories) the copy on his personal account because this would remove the GH Pages, as I found out recently archiving some of my old projects.]

**Comment by nicolocarpignoli** [comment]
Hi,
we have already argued about this in a lot of issues (you can find them by searching on the issues sections).

Jerome is not answering from a long time. 

As for now, I - along with other wonderful guys - are concentrating our efforts and time in deliver new kind of AR to AR.js (like I did with location-based).

You're right, this is something that we should do, but to be done properly it will need jerome will and most of all his access to transfer some resources. I cannot do that, I have no total permission on the repo.

you can see also we have discussed this here https://trello.com/b/63F7JlvD/arjs
