### ISSUE TITLE
Add browser support information

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#643]
we should think of adding this table (although not definitive at all): https://docs.google.com/spreadsheets/d/1e5YimbF_D1Sou2bx2vdBH58s1WdB_LgzBVYYD_uQLJk/edit#gid=318398375

but it will be a tiny but nice improvements to AR.js doc

**Comment by commentatorboy** [comment]
How should we add it?
Just copy paste? or condensed?

**Comment by nicolocarpignoli** [comment]
Just make a PR to modify the readme, we will link the spreadsheet I guess

**Comment by commentatorboy** [comment]
Should this be closed then?
