### ISSUE TITLE
Raytrace misses positions after entering fullscreen mode (not vr-mode)

### ISSUE THREAD

**Issue by felipenmoura** [jeromeetienne/AR.js#644]
**Describe the bug**
After aframe has started with ar.js, if you enter in fullscreen, click events loose the coordinates!

**To Reproduce**

1 - This is the basics of the code

```
<button onclick="requestFullScreen()">FULLSCREEN</button>
<a-scene
        arjs="debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 3x3;"
        vr-mode-ui="enabled: false"
        cursor="fuse: false; rayOrigin: mouse"
        raycaster="objects: [data-clickable]"
>
    <a-marker preset="kanji">
        <a-box ... data-clickable></a-box>
    </a-marker>
</a-scene>
```

2 - Set the event listeners for the `data-clickable` element
3 - Set the `requestFullScreen` function
4 - Open the page and see it working normally with markers and all
5 - Click the box and see its listener working normally
5 - Click in a button that requests fullscreen (to eliminate the browser address bar and tools)
6 - Now click in the box, and the "click position" has changed...the coordinates for the click are not precise with the box

**Expected behavior**
Weirdly enough, it works on my computer using its webcam, but does not work on my cellphones.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome, Brave, Safari, Firefox
 - Version: Catalina

**Smartphone (please complete the following information):**
 - Device: Xiaomi Note 7
 - OS: Android 9
 - Browser Chrome, Brave, Firefox
 - Version: 9

**Additional context**
I'm currently using AR.js version 2.0.6
In this situation, also...if I enable the `vr-mode`, when clicking it, I only see a black screen. Not sure why (not my intention either, though).

**Additional ideas**
 - You could add a version to it. So we could use `ARjs.version` in the browser console and see which version is currently running.
 - We could be able to hold the startup of ARjs (and its request for the camera). I want a few buttons with options *before* the user starts the navigation.

Thanks, keep the great work :)

**Comment by felipenmoura** [comment]
I actually believe this is caused whenever the screen size changes (either by entering/exiting fullscreen, or by changing orientation after arjs has started).

I have a few clickable elements and I noticed the click/touch in them is out of sync with the coordinates.
I touch the last item, for example, and it triggers the click in the third item.

**Comment by nicolocarpignoli** [comment]
This fall back on a bigger discussion about non-reliability of clicks on AFRAME w/AR.js.

You can look in that issue: https://github.com/jeromeetienne/AR.js/issues/249

If still relevant, feel free to re-open on new repository => https://github.com/AR-js-org/AR.js/issues?q=is%3Aissue+is%3Aopen+
