### ISSUE TITLE
<a-marker  cursor="rayOrigin: mouse"> dramatically reduce fps

### ISSUE THREAD

**Issue by taime** [jeromeetienne/AR.js#646]
I'm using aframe-particle-system-component (https://github.com/IdeaSpaceVR/aframe-particle-system-component) and find out that combination of 
1) aframe-particle-system-component
and
2) `<a-marker  cursor="rayOrigin: mouse"> `
dramatically decrease fps.

**It's very strange because `particle-system-component` is set in <scene> and doesn't belong to marker, so it should not affect to what i've set on marker...**

You can check it by yourself here (you don't need marker to check it):
https://ar.rownarts.com/test/issue_slow.html
https://ar.rownarts.com/test/issue_fast.html

I'm not sure is it problem of participles or a-marker, so I posted bug in both repository
Here is full example:

````
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name='viewport' content='width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0'>
    <script src='https://aframe.io/releases/0.9.2/aframe.min.js'></script>
    <script src="https://unpkg.com/aframe-particle-system-component@1.0.x/dist/aframe-particle-system-component.min.js">
    </script>
    <script src="https://raw.githack.com/jeromeetienne/AR.js/2.0.8/aframe/build/aframe-ar.js"></script>
</head>


<body style='margin : 0px; overflow: hidden;'>
    <a-scene stats vr-mode-ui='enabled: false' embedded
        arjs='sourceType: webcam; sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: true;'>

        <!-- SNOW  -->
        <a-entity position="0 2.25 -15" particle-system="preset: snow; particleCount: 10000"></a-entity>

        <!-- MARKER -->
        <a-marker id="animated-marker" emitevents="true" cursor="fuse: false; rayOrigin: mouse" type='barcode'
            value='6'>
            <a-cone color="tomato" radius-bottom="1" radius-top="0.5"></a-cone>
        </a-marker>

        <a-camera>
        </a-camera>
    </a-scene>
</body>

</html>
````

**Comment by nicolocarpignoli** [comment]
Hi,
https://aframe.io/docs/0.9.0/components/cursor.html#configuring-the-cursor-through-the-raycaster-component

try to configure the raycast the way above, in particular use the 'objects' property that specify to a-frame to listen to events only for those elements that match the selector. This should increase performances.
