### ISSUE TITLE
marker.position() in pixel of image

### ISSUE THREAD

**Issue by TobiasBenz** [jeromeetienne/AR.js#647]
Hello everyone,

maybe I just do not get the right way or workaround but I really would like to get marker position in pixel. In my case, I want to integrate hand tracking to identify if a person clicked (like the mouse click event) on a marker or object.

**Is your feature request related to a problem? Please describe.**
To integrate the possibility of gesture interaction it would be beneficial to have a unit that can be integrated into other frameworks like opencvjs

**Describe the solution you'd like**
The return value of position values could be in pixel of the image incl. bounding box height and width

**Comment by nicolocarpignoli** [comment]
Closing this issue due to dismission of this repository. New repository of AR.js will be up at https://github.com/AR-js-org/AR.js/

Feel free to re-open the issue there if still valid.
