### ISSUE TITLE
Small "clickable" area

### ISSUE THREAD

**Issue by scorpile** [jeromeetienne/AR.js#648]
![issue](https://user-images.githubusercontent.com/5796446/69023709-c34f1500-098d-11ea-8449-d45a21403641.png)

I think the image explain everything.

You can see a demo on:  https://reddevilstudios.com/AR/testar.html
Use the following marker:  https://reddevilstudios.com/AR/pattern-3dtc.png

Also, using mobile auto-rotation makes everything a lot worse.

**Comment by nicolocarpignoli** [comment]
as I said on twitter to you, it is related to https://github.com/jeromeetienne/AR.js/issues/249

as you can see, this is an open issue, it's obviously possible to make enhancements but it's not easy.

as for now, clicks are reliable only on the center of the screen.

please ask more on the thread I posted above if you have more questions, it's basically a duplicate
