### ISSUE TITLE
Possible to link THREEx.ArToolkitContext.baseURL to local three.js folder

### ISSUE THREAD

**Issue by jamess922** [jeromeetienne/AR.js#649]
Is that possible to link THREEx.ArToolkitContext.baseURL to local three.js folder
`  THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/'`

**Comment by nicolocarpignoli** [comment]
Hi, just add a script on your HTML on top of the body element:

```
<script>
    THREEx.ArToolkitContext.baseURL = <your-file-local-path>
</script>
```

**Comment by nicolocarpignoli** [comment]
@jamess922 is fixed?

**Comment by jamess922** [comment]
yes i got the model

**Comment by commentatorboy** [comment]
@jamess922 You have to delete the "<" and ">".
and link it to your folder.
