### ISSUE TITLE
Error when viewing demo on iPhone7 - WebRTC issue! navigator.getUserMedia not present in your browser

### ISSUE THREAD

**Issue by jordan112** [jeromeetienne/AR.js#65]
If you navigate here, i get the following errors and nothing renders:

https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html

This was tested both on Safari and Chrome on the phone with the latest updates.

    WebRTC issue! navigator.getUserMedia not present in your browser

getUserMedia() is deprecated and probably dropped:  https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

I also get this error that looks like it might not be available in all browsers yet?

    WebRTC issue! navigator.mediaDevices.enumerateDevices

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices

**Comment by jeromeetienne** [comment]
At the moment, IOS doesnt support WebRTC, so i cant access the webcam :(

see details at https://github.com/jeromeetienne/AR.js#try-it-on-mobile

**Comment by jordan112** [comment]
ah, now i see where you mentioned it.  Thanks.

**Comment by loki-one** [comment]
IOS 11 will be supporting this feature. Can't wait for the IOS11 update. Thank you jeromeetienne for such an amazing library.
I

**Comment by justincavery** [comment]
IOS11 hasn't seemed to fix this issue :(

**Comment by KevinEverywhere** [comment]
Wait!!! Hold the caterwauling! As of November 15th, and who knows since how long, Safari on iOS 11.1 does support AR.js! I also tested on current Firefox and Chrome builds, and in both cases they failed. I was using an iPad Pro 10.5. Great work, and I am sure that Firefox and Chrome will not be far behind Apple's brand browser.

http://everyvu.com/iOS-webkit.jpg

**Comment by fabfischer** [comment]
@KevinEverywhere you're correct. But it just works for web pages within Safari only. If you make a shortlink to your home screen and set "apple-mobile-web-app-capable" to yes (<meta name="apple-mobile-web-app-capable" content="yes">) and open this website as a "app", it doesn't work: "navigator.getUserMedia not present in your browser" :(

**Comment by madsenfr** [comment]
Since 19 september 2017 iOS Safari support WebRTC, see https://caniuse.com/#feat=stream
I have tested it.

**Comment by slowizzm** [comment]
tested on ios11.2.5 and failed. neither safari or chrome work for me.

**Comment by zerkla** [comment]
me too , my phone show signe that camera work , but nothing happen !!?

**Comment by lambda100** [comment]
This is frustrating. Knowing iOS 11 works, I worked on developing mine on one Android phone and one iOS 11 phone. Both test phones work. But when I expand my test devices to another iOS 11 phone, it does not work.

**Comment by rentox** [comment]
works for me when i use ssl https connection

**Comment by iviasensio** [comment]
works for me too, the right combination is safari + https + iOS12 (I didn't test iOS11), and then allow using the camera when requested
