### ISSUE TITLE
GeoAR demo doesn't work on Samsung S9

### ISSUE THREAD

**Issue by steven0702** [jeromeetienne/AR.js#650]
**Describe the bug**
On Samsung S9, the GeoAR demos produce only a white empty page (Chrome 78). The current Firefox version produces an error: "
Webcam Error
Name: NotAllowedError, 
Message: The requeset is not allowed by the user agent or the platform in the current context.

But camera access is granted to Firefox and Chrome, also GPS usage.

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - OS: Android 9
 - Browser Chrome 78, Firefox 68.2.1

**Comment by nicolocarpignoli** [comment]
pelase fill the issue with more details. this way i can't understand.

add your full code, and screenshots of dev tool console.

re-open the issue with these details, please. thanks
