### ISSUE TITLE
Cannot use gltf-model in Location Marker

### ISSUE THREAD

**Issue by framptoncp** [jeromeetienne/AR.js#652]
**Describe the bug**
I cannot add a gltf-model when a user is at a certain location. In this case its a coffee mug close to a coffee shop.  You click on the coffee mug and it shows you prices, and menu without going inside.  I merged Locations example, and A-Frame example.

**To Reproduce**
I do not get any obvious error, but when I point the phone in the direction of said coffee shop, nothing happens

**Expected behavior**
When you point to the location a coffee cup should show on the screen, as you walk past the coffee shop, the mug should look as if you are walking past/around it.

**Screenshots**
I do not have any screen shots

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari

**Smartphone (please complete the following information):**
 - Device: iPhone7, and 5
 - OS: Latest
 - Browser safari
 - Version latest

**Additional context**
I could not find any examples, only place names, or a marker.  I am sure I have the code wrong, but as I don't know really what to look at its difficult.

**Comment by framptoncp** [comment]
This is the code:

index.html:

`
<script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
<script src="https://rawgit.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js"></script>
    <script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
    <script>
        THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/'
    </script>
<a-scene
        cursor='rayOrigin: mouse; fuse: true; fuseTimeout: 0;'
        raycaster="objects: [gps-entity-place];"
        vr-mode-ui="enabled: false"
        embedded
        arjs='sourceType: webcam; sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: false;'>

    <a-assets>
        <a-asset-item id="animated-asset" src="coffee_cup/scene.gltf"></a-asset-item>
    </a-assets>

    <a-camera gps-camera="minDistance: 20;" rotation-reader>

    </a-camera>
</a-scene>`

Javascript:

`places.forEach((place) => {
            const latitude = place.location.lat;
            const longitude = place.location.lng;
            // add place icon
            const icon = document.createElement('a-entity');
            icon.setAttribute('gps-entity-place', `latitude: ${latitude}; longitude: ${longitude}`);
            icon.setAttribute('gltf-model', "#animated-asset");
            // for debug purposes, just show in a bigger scale, otherwise I have to personally go on places...
            icon.setAttribute('scale', '0.21 0.21 0.21');
            icon.addEventListener('loaded', () => window.dispatchEvent(new CustomEvent('gps-entity-place-loaded')));
}`

**Comment by nicolocarpignoli** [comment]
Hi,
can you please format correctly the code? I can't understand if there are syntax errors otherwise.

Also, do you have errors on chrome dev tool console? if so, please provide a screenshot

**Comment by framptoncp** [comment]
Hi, I as mentioned I actually do not get any errors relating to this. By this I mean I get the screenshot no matter what code I put in 'onload'.
![Screen Shot 2019-11-19 at 08 57 50](https://user-images.githubusercontent.com/51384085/69131965-12d73300-0aab-11ea-850a-8fdc59512733.png)

**Comment by nicolocarpignoli** [comment]
code seems ok, but that error it's not (i mean the not found error).

also, those events before that are not built in right?

I have to know if you have modified the lib or added events. The log shows error that are potentially causing the problem. For me without know more it's impossible to debug.
 I need FULL code, and also, if you have done modifies to lib (even little). Thanks

**Comment by framptoncp** [comment]
Hiya, I have not changed or altered any library, they are all held on GitHub.

The full HTML code:

    <!DOCTYPE html>
    <html>
    <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        <title>GeoAR.js demo</title>
        <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
        <script src="https://rawgit.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js"> </script>
        <script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
        <script>
            THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/'
        </script>
    </head>
    <link rel="stylesheet" href="index.css">
    
    <script src="places.js"></script>
    <body style='margin: 0; overflow: hidden;'>
        <a-scene
            cursor='rayOrigin: mouse; fuse: true; fuseTimeout: 0;'
            raycaster="objects: [gps-entity-place];"
            vr-mode-ui="enabled: false"
            embedded
            arjs='sourceType: webcam; sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: false;'>
                <a-assets>
                    <a-asset-item id="animated-asset" src="coffee_cup/scene.gltf"></a-asset-item>
                </a-assets>
                <a-camera gps-camera="minDistance: 20;" rotation-reader>
                </a-camera>
            </a-scene>
        </body>
    </html>

Javascript:

    window.onload = () => {
        let places = staticLoadPlaces();
        return renderPlaces(places);
    };

    function staticLoadPlaces() {
        return [
            {
                name: "FCP",
                location: {
                    lat: 1.23456,
                    lng: -7.891011
                }
            }
        ];
    }

        function renderPlaces(places) {
            let scene = document.querySelector('a-scene');
            places.forEach((place) => {
                const latitude = place.location.lat;
                const longitude = place.location.lng;
                // add place icon
                const icon = document.createElement('a-entity');
                icon.setAttribute('gps-entity-place', `latitude: ${latitude}; longitude: ${longitude}`);
                icon.setAttribute('gltf-model', "#animated-asset");
                // for debug purposes, just show in a bigger scale, otherwise I have to personally go on places...
                icon.setAttribute('scale', '0.21 0.21 0.21');
                icon.addEventListener('loaded', () => window.dispatchEvent(new CustomEvent('gps-entity-place-loaded')));
                const clickListener = function (ev) {
                   ev.stopPropagation();
                    ev.preventDefault();
                    console.log('Clicked');
                    const name = ev.target.getAttribute('name');
                    const el = ev.detail.intersection && ev.detail.intersection.object.el;
                    if (el && el === ev.target) {
                        const label = document.createElement('span');
                        const container = document.createElement('div');
                        container.setAttribute('id', 'place-label');
                        label.innerText = name;
                        container.appendChild(label);
                        document.body.appendChild(container);
                        setTimeout(() => {
                            container.parentElement.removeChild(container);
                        }, 1500);
                    }
                };
                icon.addEventListener('click', clickListener);
                scene.appendChild(icon);
            });
    }

**Comment by nicolocarpignoli** [comment]
latitude and longitude values inserted by you are not valid: try here, you will see it's a non-valid location

https://www.latlong.net/Show-Latitude-Longitude.html

```
lat: 1.23456,
lng: -7.891011
``

**Comment by framptoncp** [comment]
I didn’t use the real ones as it was my home address while testing.  But if you put the coordinates close to you, it still didn’t work. 

With someone in a different country it wouldn’t work :)

**Comment by nicolocarpignoli** [comment]
try to remove minDistance from html. Maybe the position is near you. Remove that property that tells 'hide every object in 20 meters'.

**Comment by framptoncp** [comment]
@nicolocarpignoli That did the trick, I didn't realise that attribute was in meters.  But thank you for your help!   Now to add some animation :)
