### ISSUE TITLE
Example vr-camera-controls no longer working?

### ISSUE THREAD

**Issue by framptoncp** [jeromeetienne/AR.js#654]
**Describe the bug**
This example is now 2 years old.  I cannot seem to find if the scripts used have been merged. I have tried a few mix and match without success.

Is there a new example, or documentation under another name which will do the same thing?

**To Reproduce**
1. copy code into editor, upload to site, review on mobile device: https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/vr-camera-controls.html

**Expected behavior**
https://www.youtube.com/watch?v=DoR7usCBHNM

**Comment by nicolocarpignoli** [comment]
tango project has been closed by google. I have prepared, some days ago, a PR to clean AR.js repository, including tango examples. They are outdated. https://github.com/jeromeetienne/AR.js/pull/653

From what I see, you can replicate that example by using only a-frame, without AR.js layer. It will be easier and will make more sense: AR.js is for Augmented Reality (AR), it just does not have so much sense to tweak it to try to use it for VR :)
