### ISSUE TITLE
Multiple Identical Markers

### ISSUE THREAD

**Issue by hwsiew** [jeromeetienne/AR.js#656]
Hi, does AR.js support multiple identical markers? I tried it out but it seems to be only detect one marker(identical markers) at a time.

Anyways i can make ar js to detect multiple identical markers?

Thanks for your advice :)

**Comment by nicolocarpignoli** [comment]
Hi

you can register multiple content for the same marker. But artoolkit (the system used for detection of markers by AR.js) will recognize the same marker one by one. 
You can user several markers at the same time but they have to be different markers.
