### ISSUE TITLE
AR.js GLTF relative info based on 3D objects

### ISSUE THREAD

**Issue by sureshwisdom** [jeromeetienne/AR.js#657]
Hello everyone,
 I have created my own gltf 3d object and makes own marker and render on screen, I have seen some interesting things in Vuforia AR which relevant details are shown based on 3D object located area. Any one could help me how this could be achieved this in AR.js 
![ARjs](https://user-images.githubusercontent.com/18713981/69496919-53530880-0f12-11ea-9727-e8699135ae5a.png)

**Comment by nicolocarpignoli** [comment]
> I have seen some interesting things in Vuforia AR which relevant details are shown based on 3D object located area.

hi, can you please explain better? thanks

**Comment by sureshwisdom** [comment]
> > I have seen some interesting things in Vuforia AR which relevant details are shown based on 3D object located area.
> 
> hi, can you please explain better? thanks
Here I can explain simply, Right now I am able to load HTML elements while clicking on my object. I would like to do when my gltf object rendered after Camara scanned the markers, I need to show the details like the image which I attached.
![Capture1](https://user-images.githubusercontent.com/18713981/69504676-fd0cb680-0f5f-11ea-82a9-f1311aa85c65.JPG)

**Comment by nicolocarpignoli** [comment]
@sureshwisdom not possible at the moment. AR.js is web based. Vuforia and other desktop/mobile native frameworks allow more features that as for now, at least on web open source, are not available.

But: you can tweak that and create an arbitrary built in animation, where those dialogs pop up when the user do some actions. Maybe they can be a built in animation (you can start/stop an animation using animation-mixer from aframe-extras).
If they were part of the model you can show/hide them. It's not possible to make them appear if they are standalone dialogs that appear in a relative position to the model.

**Comment by sureshwisdom** [comment]
Thank you very much Nicolò.
Is there any possible way to show HTML elements that are relative or absolute  (like HTML element which is displayed nearby the marker area ). I will load HTML while clicking on a 3D object or load it after 3D object loaded on the screen.

![321](https://user-images.githubusercontent.com/18713981/69524470-15e98c00-0fa1-11ea-8931-f404865314a5.JPG)

**Comment by nicolocarpignoli** [comment]
i suggest you to add those text as built in in the 3D model, maybe with animation.
 you can also show it relatively to the 3D model but you will need an 'a-text' from a frame, because you are in the 3D space. 

You can try to show a classic div of HTML placing it on a specific x,y position, but it will be though. You can inspect the a-entity property and the object3D (e.g. document.querySelector('a-scene').object3D;) or search for other properties like the position in order to know the a-entity position. And then place the text relatively to it.
I don't know if it can work, you have to try.

**Comment by sureshwisdom** [comment]
@nicolocarpignoli sure, I will try it and let update asap
