### ISSUE TITLE
Failing to add object titles

### ISSUE THREAD

**Issue by shakye** [jeromeetienne/AR.js#659]
Hi,
I'm trying to add a small feature to my site where the users can see actual locations using AR.js. I'm using <a-entity> as the A-frame component and a custom 3D model but I cannot get it to display a title/text above the model. I tried this with <a-link> but it doesn't seem to work, it works with the default ring object.

I'm using the places-name sample code to get everything working before merging it to the main project.

Is there any workaround or a solution for this?

**Comment by nicolocarpignoli** [comment]
Hi,
this is a very very strange problem that I found myself. I will ask to aframe maintainers because it's very interesting.

**Comment by nicolocarpignoli** [comment]
it does occur *only* when showing text alone. with geometries, gltf, images, and also a-link (which has text above the default ring) it works like charm. have to investigate

**Comment by shakye** [comment]
Hi @nicolocarpignoli ,
Thanks for getting back. Unfortunately it doesn't work with any of the components you mentioned, it only works with a-link. Also if we change the default ring to a custom model the text disappears. I'm using a gtlf model which would be nice with a text above it.

**Comment by nicolocarpignoli** [comment]
I mean that works with other a-entitity that does not contain text. you can try with a-box, it will work. I have asked on aframe slack but don't know honestly if you can get an answer. You can open an issue about this on official aframe repository on github, it will surely be of help

**Comment by shakye** [comment]
I tried with boxes, entities, images and all sort but only the ring works (referring to A-Frame Doc).
If you can provide me with an example code snippet will help me a lot :)

Here is my code,
`<a-box gps-entity-place="latitude: 6.840874; longitude: 79.991616" scale="15 15 15" material="color: red" text="hello world"/>`

![image](https://user-images.githubusercontent.com/32597626/69536782-ac6b7c80-0fa4-11ea-941b-639ab1d08741.png)

**Comment by nicolocarpignoli** [comment]
yes, it's the same thing I meant: only 'objects' are rendered, not text.

**Comment by shakye** [comment]
Oh ok, I'll post an issue in the a-frame repo.

**Comment by 7h30n3** [comment]
I got the same issue and I could narrow it down to the rotation parameter. When I define `rotation="0 180 0` it works in some cases.

**Comment by nicolocarpignoli** [comment]
can someone try using this? https://aframe.io/docs/master/introduction/visual-inspector-and-dev-tools.html

https://github.com/aframevr/aframe-inspector

and see if it's possible to understand where the text is

**Comment by 7h30n3** [comment]
I used this tool and I in contrast to `<a-image>` `<a-text>` is just rendered single-sided, which means you can't see the text if you look from "behind".

**Comment by nicolocarpignoli** [comment]
so the a-text is present but not rotate? makes sense the rotation trick posted above so

**Comment by kalwalt** [comment]
For testing you could try adding two texte with opposite rotation in this way you should see in theory thé text.

**Comment by nicolocarpignoli** [comment]
I confirm the rotation trick works.
I mean, if you use the default rotation, it shows text for element only on 'one direction' (I have object at east, they are showing text).

If i change rotation to 0 180 0, as posted above, now it shows text for entities on west and not east anymore.

I'm looking for a way to understand the direction and make a general solution.

**Comment by nicolocarpignoli** [comment]
> I used this tool and I in contrast to `<a-image>` `<a-text>` is just rendered single-sided, which means you can't see the text if you look from "behind".
> 
> It would be nice if `<a-text>` had a parameter `target` like the light-component to always face the user.

that is the problem, exactly

**Comment by nicolocarpignoli** [comment]
Found a solution!
There is a similar property, called 'side' that can render the text 'double', so front and rear.

You just have to set `side: 'double'` on the `a-text` component and it's solved!

**Comment by nicolocarpignoli** [comment]
There is a similar property, called 'side' that can render the text 'double', so front and rear.

I thought the value: 'double' was solving this, but unfortunately no.

**Comment by nicolocarpignoli** [comment]
this can be solved making the direction of the elements facing the user. It's a problem that is present with all content but becomes very visible with the text.

I will open a separate issue.
