### ISSUE TITLE
Failed to recalculated device parameter (No DPDB device match) due to dpdb.json connection refused

### ISSUE THREAD

**Issue by sureshwisdom** [jeromeetienne/AR.js#662]
For me it's weird I have tried so many ways to place a simple box on mobile but it's not showing.
I am running my folder in the IIS server and accessing through my wifi on mobile.
The Steps I followed 
- Enabled SSL on my IIS and android mobile (chrome(checked with version 74 to 78-IOS Chrome also checked ), firefox) have detected my camera, after loading the object will not be shown, parallel I tested it on my **computer it works well**.(**there is no error on console**). And I have referenced previous github issues raised by others. MIME configured well. 
- Then I tested https://codepen.io/sureshwisdom/pen/NWWZZMj - on my mobile it works well.

This is my simple code below
`<!doctype HTML>
<html>
<script src="./js/aframe/aframe.min.js"></script>
<script src="./js/build/aframe-ar.js"></script>
  <body style='margin : 0px; overflow: hidden;'>
    <a-scene>
  	<a-marker preset="hiro">
            <a-box position='0 0 0' material='color: green;'></a-box>
  	</a-marker>
  	<a-entity camera></a-entity>
    </a-scene>
  </body>
</html>`

![Screenshot_2019-11-27-14-23-56-204_com android](https://user-images.githubusercontent.com/18713981/69722739-cc40a300-1152-11ea-98d0-fd68e0ef6370.jpg)
![Screenshot_2019-11-27-13-54-47-124_com android chrome](https://user-images.githubusercontent.com/18713981/69722756-d5317480-1152-11ea-954a-db44fb5980cd.jpg)
![Screenshot_2019-11-27-16-10-26-033_org mozilla firefox](https://user-images.githubusercontent.com/18713981/69722777-e8dcdb00-1152-11ea-9f13-cee0936f2eec.jpg)
![Screenshot_2019-11-27-18-49-56-823_com android chrome](https://user-images.githubusercontent.com/18713981/69722790-f1cdac80-1152-11ea-8831-21bb0c64376c.jpg)

**Comment by sureshwisdom** [comment]
I inspected in mobile chrome via remote debugging, I am getting some errors. @nicolocarpignoli 
![edit](https://user-images.githubusercontent.com/18713981/69772693-a1466580-11cb-11ea-81aa-047ce730b1b0.jpg)

**Comment by nicolocarpignoli** [comment]
Try using latest AR.js, so version 2.0.8

Also,which phone do you have? Which os version?

**Comment by sureshwisdom** [comment]
@nicolocarpignoli I have loaded camera_para.dat file in <a-scene> and added it MIME Types, Then I checked It works well.
My Android version is 9, Device modal Redmi 6A
Do I need to add my device on the **dpdb.json file**?. How to configure it locally?

**Comment by sureshwisdom** [comment]
@nicolocarpignoli I Followed [https://github.com/jeromeetienne/AR.js/issues/465#issuecomment-505354686](url) and it works on mobile.
Mobile Model: Redmi 6A, Android Version 9'P'.
Do I need to add my mobile configuration dpdb.json and Is any way to configure on the local machine (offline).

**Comment by sureshwisdom** [comment]
@nicolocarpignoli I Followed this solution  https://github.com/jeromeetienne/AR.js/issues/465#issuecomment-505354686 and it works on mobile.
Mobile Model: Redmi 6A, Android Version 9'P'.
Do I need to add my mobile configuration dpdb.json and Is any way to configure on the local machine (offline).

**Comment by nicolocarpignoli** [comment]
what is No DPDB ? never saw that problem. Are you sure you do not have custom code on the .html, or loaded external scripts?

**Comment by sureshwisdom** [comment]
Aframe says no DPDB device match, Its due to non-configuration of my android device. Here I am running on my own IIS server. So it's refusing the **https://dpdb.webvr.rocks/dpdb.json **. For that, I am getting the following errors on my console. 
***

- ***Failed to recalculated device parameter** 
- **Sensor Could not be read**
- Failed to Load Resources https://dpdb.webvr.rocks/dpdb.json.**

**
Is there any way of resolving this issue. My server will not connect to the Internet.

**Comment by janpio** [comment]
Please stop mentioning random people - that is spam @sureshwisdom

**Comment by sureshwisdom** [comment]
@nicolocarpignoli  For mobile browser and desktop, the rendered model works well. When I have seen in tablet the model not showing with the light property. Pls refer my issue [https://github.com/jeromeetienne/AR.js/issues/662#issuecomment-559899948
![desktop](https://user-images.githubusercontent.com/18713981/69952383-02569c00-1532-11ea-81f5-a9e56921a044.png)
![tablet](https://user-images.githubusercontent.com/18713981/69952443-2914d280-1532-11ea-8b4b-289b305016d3.png)

](url)
