### ISSUE TITLE
Barcode Markers Still not working - Get the value of a barcode on recognition?

### ISSUE THREAD

**Issue by hillj8** [jeromeetienne/AR.js#664]
**Describe the bug**
Barcode markers are recognised by the system but no visual is displayed for them (no overlay)

**To Reproduce**

![image](https://user-images.githubusercontent.com/37069297/69919346-c6f59800-1473-11ea-9db4-b0d627fb795f.png)

**Expected behavior**
A Yellow box should be displayed over the marker but it is not

![image](https://user-images.githubusercontent.com/37069297/69919471-feb10f80-1474-11ea-899f-353b7961099f.png)

The console output shows 
numMarkers()
getMarker.id, getMarker.idMatrix ,getMarker.pos - pulled from the marker info struct

**Additional context**
Is there a way to return the barcode value when it is recognised - i.e to display the value of the marker as the overlay for example - show the camera a barcode marker 6 and the number 6 appears, show the camera a barcode marker 25 then number 25 is shown. - the ID or idMatrix from the marker info struct seems to return just a -1 and 0 for all barcode markers respectively.

**Comment by nicolocarpignoli** [comment]
Hi

to the a-scene add 'detectionMode: mono_and_matrix;' in the same place of matrixCodeType. it should work

**Comment by hillj8** [comment]
Hi,
Thanks for the quick reply!

I’ll give it a go :)

**Comment by nicolocarpignoli** [comment]
you can register an aframe component on the marker entity (e.g. eventhandler) and then register the eventhandler component on a js script. On that, you can listen to 'markerFound' events. that tells you when the marker is recognized.

so you can first set a data-* attribute with the value number on the HTML and then, knowing which marker has triggered the events, retrieve that data with entity.getAttribute(...)

example on how to use markerFound events:

https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/marker-events.html
