### ISSUE TITLE
Is there a way to identify barcode value, and render objects based on that value?

### ISSUE THREAD

**Issue by adityanaag3** [jeromeetienne/AR.js#667]
**Is your feature request related to a problem? Please describe.**
When using a 4x4 barcode marker, I want to show different text entities based on the marker value.

**Describe the solution you'd like**
Ideally there should be an ondetected event on the camera that will return the value of the barcode, and then we should be able to dynamically inject entities into the scene.

**Comment by nicolocarpignoli** [comment]
duplicate: https://github.com/jeromeetienne/AR.js/issues/664
