### ISSUE TITLE
Location marker not refreshing

### ISSUE THREAD

**Issue by evelynchang0819** [jeromeetienne/AR.js#668]
**Describe the bug**
I am statically adding longitude and latitude coordinates in the places.js script and trying to demo the click-places example. The markers appear correctly, but do not disappear when I move the camera past the coordinate. 

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 11.4.1
 - Browser Safari

**Additional context**

**Comment by nicolocarpignoli** [comment]
Hi,
check if you have granted permissions to device motion sensors on Settings of Safari, on iphone

**Comment by nicolocarpignoli** [comment]
Hi @evelynchang0819 can you please describe the problem a little more or tell me if what I suggested worked for you?
