### ISSUE TITLE
Type of Marker Query

### ISSUE THREAD

**Issue by Jaysonvdw** [jeromeetienne/AR.js#67]
Hello,

I just had 2 quick questions relating to markers.

Firstly, can one only use the hiro and kanji markers or can one use a custom image as a marker? If so, how would I go about incorporating this on the marker-camera preset?

Also, can one add a pre-rigged and animated model (from TurboSquid for example) and if so, how would I do this? Would the files need to be converted to JSON in Blender or something?

**Comment by jeromeetienne** [comment]
- on adding a model, use the usual three.js/aframe technic - ar.js doesnt enter in this
- to learn a new markers, see 
  - marker generator http://jeromeetienne.github.io/AR.js/three.js/examples/markerGenerator/examples/generator.html
  - detail https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training
- to change the preset=''. 
  - remove the preset=''
  - add type='pattern' and patternUrl='http://your/markers'

i hoipe this helps

**Comment by curtello** [comment]
http://jeromeetienne.github.io/AR.js/three.js/examples/markerGenerator/examples/generator.html

The link is not working

**Comment by jeromeetienne** [comment]
where did you get it ?

**Comment by curtello** [comment]
You have just used it when you commented up there on this issue

**Comment by jeromeetienne** [comment]
oh ok my bad. Stuff are moving fast, so backward compatibility isnt easy. i always try to maintain the proper links in the README.md tho, in [the examples section](https://github.com/jeromeetienne/ar.js#examples)

here is the new location for marker training https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html
