### ISSUE TITLE
Why is AR.js waitin for domElement.videoWidth before adding video element to DOM?

### ISSUE THREAD

**Issue by smuddy** [jeromeetienne/AR.js#670]
**Describe the bug**
Because iOS does not allow getUserMedia in third party apps using the WkWebView (p.e. Cordova) there is a native mock that hooks the `navigator.getUserMedia` function and provides the camera stream.
Unfortunately the property `element.videoWidth` is not set.

So my questsion is: why does AR.js wait for the stream inisitialisation inside `ARjs.Source.protoype._initSourceWebcam`? If I directly show the video element after assigning the stream, is see no side effects. Imho there is no need to wait.

**To Reproduce**
- setup cordova iOS project
- install plugin cordova-plugin-iosrtc and register the golbal hooks
- copy AR.js project into ww folder
- run cordova app

**Expected behavior**
App should initialize AR.js and show the camera image.
But it waits with an interval for `element.videoWidth` as trigger for adding video element to the DOM.

**Smartphone (please complete the following information):**
 - Device: iPhone 7 & XR
 - OS: 13.2.2
 - Browser WkWebView

**Comment by nicolocarpignoli** [comment]
hi!
Please provide a PR for this, we will look into that, do tests, and if no problems are added but only enhancements, we will merge it

**Comment by ongeo-dev** [comment]
PR is on the way...

**Comment by benallfree** [comment]
@smuddy Do you have a demo repo? I'm working on iosrtc+AR.js too.
