### ISSUE TITLE
Redirect if user didn't give camera permission!

### ISSUE THREAD

**Issue by taime** [jeromeetienne/AR.js#672]
How to make redirect to another page if user didn't give permission to camera?

(And also, how make redirect if any other error happen? I want to show special page instead of alert message!  Is it possible?)

**Comment by nicolocarpignoli** [comment]
yes, it's possible.

try to listen to the event `camera-error`, it's dispatch from `window` element when occurs an error during camera initialization.

See more athttps://github.com/jeromeetienne/AR.js/blob/08a720e359a18ba7bf6cac6077c3d9472aa40d28/three.js/src/threex/threex-artoolkitsource.js for other custom events triggered by AR.js (search for 'CustomEvent' keyword)
