### ISSUE TITLE
click doesnt work with aframe-v1.0.0

### ISSUE THREAD

**Issue by MichaelVonB** [jeromeetienne/AR.js#677]
**Describe the bug**
I recently updated to aframe-v1.0.0 because I had troubles with chrome, which I dont have under v1.0.0. 
If I find a marker with my camcera I attach a click listener to the entity displayed and under aframe-0.9.2 I had no trobules with executing any function I put inside the click listner and I further got a pointer when hovered over the entity. Now after the upgrade I have no pointer and and there is no reaction to a click anywhere on the screen. 

I am using aframe alone in the same app and I tried whether there occours the same problem, but this is not the case. I can use the same syntax with no problem. 

**To Reproduce**
html: 
<a-scene ...>
<a-entity class="entity>
<a-entity id="camera" camera="userHeight: 1.6" cursor="rayOrigin: mouse">
</a-scene>

JS:
document.getElementbyId('entity').addEventListener(click, () => { console.log("hi")});

**Expected behavior**
As for aframe v0.9.2

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Firefox
 - Version aframe-v1.0.0, ar.js v2.0.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nicolocarpignoli** [comment]
I also read about this somewhere on aframe github repository. Please open an issue there, as this is a bug from aframe
