### ISSUE TITLE
Cannot set domElement.videoWidth or videoHeight

### ISSUE THREAD

**Issue by stefanluchian** [jeromeetienne/AR.js#678]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I cannot set domElement.videoWidth or videoHeight in order to obtain a squared canvas.

**If the current behavior is a bug, please provide the steps to reproduce.**
I use e.g. the following arjs attribute, hoping that I can set a square canvas:
```html
<a-scene arjs='sourceType: webcam; canvasWidth: 714; canvasHeight: 714; sourceWidth: 720; sourceHeight: 720; displayWidth: 768; displayHeight: 768; debugUIEnabled: false;'>
```
The videoWidth/Height still remains 640x480 or 480x640, depending on the orientation, despite any combination of these params that I tried.

The problem is, that the fixes regarding [orientation](https://github.com/jeromeetienne/AR.js/commit/bf3f7508cf0ece08cadc84d5f9fcde6f8f1cb4c7#comments) introduced a new behaviour for the portrait mode: the horizontally shrinked video is stretched back to normal, but the image into the stretched portrait video corresponds to a smaller frustum than the landscape video for the same device. So the markers are moving faster in portrait mode then in landscape mode. Thus I would need to reduce the dimensions of the generated video in portrait mode, but then I receive transparent bars for top and bottom and I have markers only for the middle of the screen.
That's why I need a square generated video, in order to display it with the same frustum in landscape and in portrait mode.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment]
relates to this: https://github.com/jeromeetienne/AR.js/issues/537

someone found this problem too on that thread

**Comment by stefanluchian** [comment]
Thanks for replying.
My problem is not the integration of ar.js into angular, because that works already fine. We have good results with location-based AR using your package (see our [branch](https://github.com/ongeo-dev/AR.js/)) in landscape mode of our mobile phones.
I only want to solve the differences between portrait mode and landscape mode.
The parameters that I set in < a-scene arjs="..." > do find their way through "AFRAME.registerSystem('arjs'...", "ARjs.Context = THREEx.ArToolkitContext...", "ARjs.Context.prototype._initArtoolkit..." and reach the constructor of ARController.

But when ticking in "ARjs.Source.prototype.onResizeElement", the values of "this.domElement.videoWidth" and "this.domElement.videoHeight" are always 640 and 480 in landscape mode and 480 x 640 in portrait mode.

I am aware of the changes in "ARjs.Source.prototype.copyElementSizeTo", but the code for portrait receives a horizontally shrinked video. That's why you needed to stretch "this.domElement.style.height" back to the original aspect ratio of 4/3, but in fact, imho, you only fix the effects of receiving a shrinked video. And my problem here is that the resulting video is "zoomed" with a factor of about 1.77, because the original height comes from the lanscape mode and is now used as portrait mode, which for a mobile phone is a factor of 16/9. Thus, you recalculate in "ARjs.Source.prototype.copyElementSizeTo" a huge width, that makes the markers move in portrait mode with a greater speed comparing with landscape mode.

If I decrease both height and width for portrait mode in the function "ARjs.Source.prototype.copyElementSizeTo" with a factor of 16/9, then the markers are moving *perfectly* aligned with the background video from the webcam, just like in the landscape mode. This could be a good workaround. Unfortunatelly, the generated image has the aspect ration of 16x9 and the phone in portrait mode has 9x16, so no markers are displayed in the top and buttom areas, but only in the horizontal middle of the screen.

So, until the real problem is solved, I thought I could use a square canvas, something like 640 x 640 and use different portions of it in landscape mode and portrait mode respectively. Is there a way to configure the < a-scene > in order to receive a square canvas despite the aspect ratio of the webcam?

**Comment by stefanluchian** [comment]
A Happy New Year to all of you!

Has any one an idea, how one can configure a square canvas, despite the aspect ratio of the webcam?
