### ISSUE TITLE
webar-playground missing?

### ISSUE THREAD

**Issue by meg32** [jeromeetienne/AR.js#68]
Hi Jerome,

Seems the last update is missing the webar-playground directory.  I see webar-playground-old.
Is it coming soon?  Just wanted to see the demoscenes working again.

Thanks,
Mike

**Comment by jeromeetienne** [comment]
sorry i didnt know anybody were following that. :)

i moved all to its own repo. https://github.com/jeromeetienne/webar-playground

**Comment by meg32** [comment]
Ok.  Thanks for the good work....

**Comment by jeromeetienne** [comment]
Suddently im curious :) how come you are interested ? 

i havent even published it yet

**Comment by meg32** [comment]
I will be attending AWE 2017 next week.  I have built a few experiments based on your AR.js.  Just for fun/learning.  I read the uploadvr article and have been jazzed about webAR for phones.  I have a Lenovo Phab 2 Pro (Tango device), but have been working on simple demos that use all LAN devices to play along.  Good day.

**Comment by FREEZX** [comment]
Hey, looks like that repo is gone again.
I'm trying to get multi-marker running for a project i'm doing, but the three,js learning example in this project is not working for me, it only shows the hiro marker as checked.
