### ISSUE TITLE
QR Scan and poke the url with that data and display as block in the camera itslef

### ISSUE THREAD

**Issue by Lossy18** [jeromeetienne/AR.js#680]
Hi,
I like to implement the AR app in cordova / wepage.
The application Flow is like user has to scan the QR code ,they get the some details like (eg number) and then it should trigger the URL  along with that number appended and show the results in the same camera at one end in a block ..

**Comment by nicolocarpignoli** [comment]
please, fill the issue with more details.

also:

 please feel free to re-open the issue at new AR.js repository: https://github.com/AR-js-org/AR.js

thank you!
