### ISSUE TITLE
How can i load the different gltf file than the example one, i tried to replace src it doesn't work.

### ISSUE THREAD

**Issue by Poojahm3** [jeromeetienne/AR.js#682]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by Poojahm3** [comment]
![Screenshot from 2019-12-20 15-18-37](https://user-images.githubusercontent.com/59049686/71246333-71a6fb00-233c-11ea-87d4-5200b36fee43.png)
this is example code

**Comment by kalwalt** [comment]
hi @Poojahm3 try this example: https://kalwalt.github.io/kalwalt-interactivity-AR/aframe/aframe-ar-gltf.html 
code: https://github.com/kalwalt/kalwalt-interactivity-AR/blob/master/aframe/aframe-ar-gltf.html

**Comment by Poojahm3** [comment]
Thanks. How can i create my own gltf model?

**Comment by kalwalt** [comment]
well, you can create with [Blender](https://www.blender.org/)  and export it with the gltf exporter or you can do this part with the [threejs editor](https://threejs.org/editor/). Anyway i recommend you tp read the kronos gltf page https://www.khronos.org/gltf/ you can find a lot of infos and resources there.

**Comment by nicolocarpignoli** [comment]
@kalwalt answer is perfect. Also, this is not something concerning AR.js. Closing
