### ISSUE TITLE
custom marker is not showing gltf model.

### ISSUE THREAD

**Issue by Poojahm3** [jeromeetienne/AR.js#685]
<html>
  <head>
<script src="https://aframe.io/releases/1.0.0/aframe.min.js"></script>
 
<script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
</head>

<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs='sourceType: webcam;'>
       <a-assets>
  <a-asset id="cesium-manw" src="/sample.gltf"></a-asset>
</a-assets>
 <a-marker preset='custom' type="pattern" url="sample.patt">
  
 <a-entity
                animation-mixer
                gltf-model="#cesium-manw"
                scale="100 100 100">
            </a-entity>
      </a-marker>

    <a-entity camera></a-entity>
  </a-scene>
</body>

</html>

I cant figure out why its not working. I am using the above code and downloading pattern file from marker training

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by Poojahm3** [comment]
![Screenshot from 2019-12-23 18-04-46](https://user-images.githubusercontent.com/59049686/71358386-c3ef5280-25ae-11ea-88f0-410616f65fea.png)

**Comment by nicolocarpignoli** [comment]
Hi, can you please open the developer console of chrome and tell us if you see something? please put the log here, and re-open issue with that information

**Comment by Poojahm3** [comment]
@nicolocarpignoli please find the attachment from google console. I am using photoshop to design the marker.
![Screenshot from 2019-12-25 10-11-10](https://user-images.githubusercontent.com/59049686/71432427-9ebe2980-26ff-11ea-8b48-5f5e37ca3dc5.png)

**Comment by nicolocarpignoli** [comment]
I see errors and warning that are not reflecting your code (e.g. fuse property). Please open a new issue with correct code and detailed problem, thank you
