### ISSUE TITLE
Overconstrained error everywhere

### ISSUE THREAD

**Issue by labriata** [jeromeetienne/AR.js#686]
Hi there,

Suddenly, all my pages using ar.js fail, giving an error on load:

Webcam error
Name: OverconstrainedError
Message: null

This also happens in one of the official examples:

https://jeromeetienne.github.io/AR.js/aframe/examples/basic.html

Happened on different windows, on firefox and chrome. I tried updating the script sourcing tags to the latest ar.js and ar.js a-frame versions, but the problem is still there.

Thanks for any help!

**Comment by kalwalt** [comment]
Thank you @labriata we know this!.. @nicolocarpignoli is  fixing it now. :smile:

**Comment by nicolocarpignoli** [comment]
fixed with version 2.1.1 released just now. Thanks!

**Comment by labriata** [comment]
Thank you!!
