### ISSUE TITLE
Click event on gltf model

### ISSUE THREAD

**Issue by Poojahm3** [jeromeetienne/AR.js#687]
Hi,
I am loading a model which is a box inside some components are there. I want to use click function to open the box.

Should i load a new gtlf model on click or can i change the position of the box on click.

My click event is not working. I am using the example code of click event to check. Not able to figure out the issue. Please find the screenshot of the code below

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by Poojahm3** [comment]
![Screenshot from 2019-12-25 18-13-40](https://user-images.githubusercontent.com/59049686/71445742-5a07b200-2742-11ea-8093-925beb28322b.png)
![Screenshot from 2019-12-25 18-13-44](https://user-images.githubusercontent.com/59049686/71445744-5d9b3900-2742-11ea-8834-e98ef48561c4.png)

**Comment by Poojahm3** [comment]
![Screenshot from 2019-12-25 18-15-36](https://user-images.githubusercontent.com/59049686/71445765-93d8b880-2742-11ea-855b-5868dbd352a3.png)

google console

**Comment by kalwalt** [comment]
@Poojahm3 Please, can you post your code Into thé code tag instead posting thé screenshots??

**Comment by Poojahm3** [comment]
[gltfclick.zip](https://github.com/jeromeetienne/AR.js/files/4001363/gltfclick.zip)
@kalwalt

**Comment by nicolocarpignoli** [comment]
@Poojahm3 plese use this characters ``` (3 backticks) copy and paste your code and then again 3 backtips ```

**Comment by Poojahm3** [comment]
/// 
<html>
  <head>
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
 <script>
 AFRAME.registerComponent('cursor-animator', {
      init: function () {
        this.el.addEventListener('click', function (evt) {
          console.log('click');
          
        });
      }
    });
    
      AFRAME.registerComponent('raycaster-autorefresh', {
  init: function () {
    var el = this.el;
    this.el.addEventListener('model-loaded', function () {
      var cursorEl = el.querySelector('[raycaster]');
      cursorEl.components.raycaster.refreshObjects();
    });
  }
});
 </script>
</head>
<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs='sourceType: webcam;' raycaster-autorefresh>
       <a-assets>
  <a-asset id="cesium-manw" src="/braindesign.gltf" ></a-asset>
</a-assets>
 <a-marker  markerhandler emitevents="true" cursor="fuse: true; rayOrigin: mouse" id="animated-marker" preset='custom' type="pattern"/qq.patt">
   <a-entity id="rotate" gltf-model="#cesium-manw"
                scale="130 130 130"  position="0 -0.5 -0.5" cursor-animator >
   <a-animation begin="click" attribute="rotation" to="0 360 0"  delay="500" dur="10000"></a-animation>
            </a-entity>
      </a-marker>
    <a-entity camera>  <a-cursor></a-cursor> </a-entity>
  </a-scene>
</body>
</html>
///

The above code is working fine and the gltf model is rotating on moving cursor point. I want load a new gltf model on pointing the cursor on the existing model or clicking on the existing gltf model. How  can i do that??

**Comment by Poojahm3** [comment]
///<html>
  <head>
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
 <script>
 AFRAME.registerComponent('cursor-animator', {
      init: function () {
        this.el.addEventListener('click', function (evt) {
          console.log('click');
          
        });
      }
    });
    
      AFRAME.registerComponent('raycaster-autorefresh', {
  init: function () {
    var el = this.el;
    this.el.addEventListener('model-loaded', function () {
      var cursorEl = el.querySelector('[raycaster]');
      cursorEl.components.raycaster.refreshObjects();
    });
  }
});
 </script>
</head>
<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs='sourceType: webcam;' raycaster-autorefresh>
       <a-assets>
  <a-asset id="cesium-manw" src="/braindesign.gltf" ></a-asset>
</a-assets>
 <a-marker  markerhandler emitevents="true" cursor="fuse: true; rayOrigin: mouse" id="animated-marker" preset='custom' type="pattern"/qq.patt">
   <a-entity id="rotate" gltf-model="#cesium-manw"
                scale="130 130 130"  position="0 -0.5 -0.5" cursor-animator >
   <a-animation begin="click" attribute="rotation" to="0 360 0"  delay="500" dur="10000"></a-animation>
            </a-entity>
      </a-marker>
    <a-entity camera>  <a-cursor></a-cursor> </a-entity>
  </a-scene>
</body>
</html>///

The above code is working fine and the gltf model is rotating on moving cursor point. I want load a new gltf model on pointing the cursor on the existing model or clicking on the existing gltf model. How  can i do that??

**Comment by Poojahm3** [comment]
```<html>
  <head>
<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
<script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
 <script>
 AFRAME.registerComponent('cursor-animator', {
      init: function () {
        this.el.addEventListener('click', function (evt) {
          console.log('click');
          
        });
      }
    });
    
      AFRAME.registerComponent('raycaster-autorefresh', {
  init: function () {
    var el = this.el;
    this.el.addEventListener('model-loaded', function () {
      var cursorEl = el.querySelector('[raycaster]');
      cursorEl.components.raycaster.refreshObjects();
    });
  }
});
 </script>
</head>
<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs='sourceType: webcam;' raycaster-autorefresh>
       <a-assets>
  <a-asset id="cesium-manw" src="/braindesign.gltf" ></a-asset>
</a-assets>
 <a-marker  markerhandler emitevents="true" cursor="fuse: true; rayOrigin: mouse" id="animated-marker" preset='custom' type="pattern"/qq.patt">
   <a-entity id="rotate" gltf-model="#cesium-manw"
                scale="130 130 130"  position="0 -0.5 -0.5" cursor-animator >
   <a-animation begin="click" attribute="rotation" to="0 360 0"  delay="500" dur="10000"></a-animation>
            </a-entity>
      </a-marker>
    <a-entity camera>  <a-cursor></a-cursor> </a-entity>
  </a-scene>
</body>
</html>```

The above code is working fine and the gltf model is rotating on moving cursor point. I want load a new gltf model on pointing the cursor on the existing model or clicking on the existing gltf model. How  can i do that??

**Comment by nicolocarpignoli** [comment]
for click events, please see this (duplicate): https://github.com/jeromeetienne/AR.js/issues/249

**Comment by AeroSpring** [comment]
> for click events, please see this (duplicate): #249

This is not the first time I come across your links, but your method does not work. Absolutely. Can you check the work of your method? Clarify it, and only then provide links to it?
