### ISSUE TITLE
Change "Module" to something more specific

### ISSUE THREAD

**Issue by hypothete** [jeromeetienne/AR.js#69]
Hi Jerome,

Just a suggestion - would you consider changing the global variable "Module" in AR.js to be named something more specific? I'm trying to use your library in conjunction with some other THREE.js extensions and I'm running into namespace collisions on that global.

Thanks & thanks for sharing AR!

**Comment by jeromeetienne** [comment]
Module ? im not aware of this one :)

**Comment by jeromeetienne** [comment]
im serious btw

**Comment by hypothete** [comment]
I'm not explaining myself very well, never mind. It's not really that important anyway.
