### ISSUE TITLE
AR Object size to fixed

### ISSUE THREAD

**Issue by daiyadove** [jeromeetienne/AR.js#690]
Marker-based AR changes the size of the displayed AR object in relative to the size of the marker.
Is there a way to fixed size this?

1. Display AR objects on a marker-base
2. change size the marker (as displayed on the monitor)
3. AR objects scale in relative to marker size

**Comment by nicolocarpignoli** [comment]
Using aframe properties, there is the scale attribute for the a-entity component. Something like

`<a-box scale='2 2 2'>`

**Comment by daiyadove** [comment]
@nicolocarpignoli 

yes, I'm using aframe.

try using scale attribute. but not working.
Below is my code

```html
<html>
  <head>
    <meta charset="utf-8">
    <title>WebAR</title>
    <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
    <script src="https://raw.githack.com/jeromeetienne/AR.js/1.7.5/aframe/build/aframe-ar.js"></script>
  </head>

  <body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs>
      <a-assets>
        <img id="nest_mini" src="oitea.png">
      </a-assets>
      <a-marker preset="hiro" type="pattern">
        <!-- <a-image src="#nest_mini" rotation="270 0 0" width="2.6" height="3.22" scale="1 1 1"></a-image> -->
        <a-box scale="2 2 2" rotation="270 0 0" width="1" height="1"></a-box>
      </a-marker>
      <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
```

change size the marker, then AR objects scale in relative to marker size

![want_size_fixed](https://user-images.githubusercontent.com/25363937/71708488-2230f680-2e35-11ea-9fa5-97fb4e4d0f45.gif)

**Comment by nicolocarpignoli** [comment]
The object size Wil be always relative to the marker size. You can use the size attribute to change it, but still relatively. you cannot, as far as I know, decide a specific size that will remain the same and that is not considering the marker size recognized by the camera.
