### ISSUE TITLE
Is there a way to reduce drift on location-based markers?

### ISSUE THREAD

**Issue by chrismatthieu** [jeromeetienne/AR.js#691]
When using iOS/Android device outdoors with GPS/location-based anchors, the anchor seems to follow you around as you walk around. Is there a way (technique or algorithm) to reduce the drift on anchors outdoors? BTW, Great work!

**Comment by nicolocarpignoli** [comment]
Hi, can you please provide a video of that? Just to understand if it's the default behavior of a bug it's happening

**Comment by chrismatthieu** [comment]
Here's a video - https://www.youtube.com/watch?v=kbKAdXON53U&feature=youtu.be

**Comment by nicolocarpignoli** [comment]
Ok, which phone and browser? Also which os version? If it's an iPhone, are you able to run it on a android?

**Comment by chrismatthieu** [comment]
iPhone 11 Pro
OS v13.3
Safari

I don't have an Android phone/tablet available to test but we'll see if any of my friends do...

**Comment by nicolocarpignoli** [comment]
Check if motion sensors access has been given on safari settings

**Comment by chrismatthieu** [comment]
iOS13 no longer has a motion sensor access setting; however, I am granting access through the app. See photo. 

Running:
AFrame - v1.0.3
aframe-ar.min.js - v2.1.4
![IMG_0887](https://user-images.githubusercontent.com/12523/71646544-81610080-2ca7-11ea-83b5-21894a9c5bda.jpeg)

**Comment by nicolocarpignoli** [comment]
Is this one giving you the same problem? https://nicolo-carpignoli.herokuapp.com/examples/places-name/

**Comment by chrismatthieu** [comment]
Yes. See video - https://www.youtube.com/watch?v=pbk1I-EGWZE&feature=youtu.be

**Comment by nicolocarpignoli** [comment]
Thanks. I'm away from pc so can't test right now. If this is happening also with androids,   it might be a problem with updating user position. Let me know when you can test

**Comment by nicolocarpignoli** [comment]
Hey there, I have tried it on android. Same behavior of your iOS. But. It's a wanted behavior. I'm explaining better. GPS has a precision in meters, usually 10 meters or more. Your walking in the video was only  for some meters. Try to walk a little bit far that the video and you should see the Pikachu left behind you after some time. It worked for me with the example with red dots

**Comment by chrismatthieu** [comment]
You're correct. I can walk far enough to see the other side of the model (and behind it as well).

My issue is probably more related to GPS precision rather than an issue with ARjs; however, we may have slightly different use cases. I am trying to create a spatial anchor right in front of me (not far away) and the drift/lack-of-precision is too great to pin the model to a spot that appears right in front of me without it moving significantly as I walk. 

Perhaps this is more of a feature request rather than a bug but I would was wondering if you are right on top of the same GPS coordinates as the model if there was a way to reduce the drift even more. Perhaps we could take into account the 10 meters of precision and half or double our reference points so the model doesn't move so much when you are close to it?

**Comment by nicolocarpignoli** [comment]
What you are asking is a 'relative distance' to the user.

You are saying something like: 'show the content like it is 10 meters from me'.

This kind of behaviour cannot be delivered with current geolocation implementation, that is 'absolute', so it renders content according to their absolute position 'in the world'.

To do what you ask, I would not go with geolocation but instead a different kind of behaviour, but yes it's a new feature.

You could open a new issue for feature request, something that details this use case.

Anyway, it will not be easy to implement: it's not hard to show something in front of the user POV, but it's hard to make it appear always on that position, it would need some kind of anchoring (position or marker or NFT - image based).
I think is something that can be related to 'place an object in front of view' experience like quick look of Apple or Google's Model viewer (https://github.com/GoogleWebComponents/model-viewer).

**Comment by chrismatthieu** [comment]
You're correct. I am thinking something probably more like a VPS (visual positioning system) for this use case. Until these technologies mature, the model viewer in conjunction with ARjs may work as well.  I'll experiment and keep you posted. Thanks for the discussion!
