### ISSUE TITLE
Is it possible to detect planar surface?

### ISSUE THREAD

**Issue by hugo1o1** [jeromeetienne/AR.js#694]
Hello，love your work on ar.js, I want to know can ar.js detect or recognize the planar surface without the marker? if it is not possible , how can I achieve it only using JS？thanks .

**Comment by nicolocarpignoli** [comment]
Hi,
actually no, at least in AR.js.

I'm not aware of any other JS project able to do that, in Open Source/free ecosystem.
May be something in the future.

Using new WebXR Device APIs, you could try this one: https://github.com/GoogleWebComponents/model-viewer.

It's a bit limitative but has the planar surface detection you asked for.
Anyway, support is limited to latest Chrome with flag enabled, so no iOS or other phones/browser.

**Comment by nicolocarpignoli** [comment]
If anyone know something else please left a note :)
