### ISSUE TITLE
Places-name (not working, bug on laptop)

### ISSUE THREAD

**Issue by gabrielsze** [jeromeetienne/AR.js#696]
**Describe the bug**
So my friend and I have been testing the ARJs places-name demo, and even cloned the code to test it on own. We encountered a few interesting bugs with the places-name example (similarly with click-places). The first interesting observation is that while replicating the code in places-name, it **works almost perfectly fine on the phone** (iphone 11 pro, iphone 11, iphone XS, haha it should work on android too)

However, this is when it starts to get real wonky.
We remembered we fired up the ARjs places-name demo a couple of months back (16 October to be exact), and it worked perfectly on the laptop as well. However, we have been facing **quite a few issues when trying to run ARjs places-name demo on the laptop.**

1. The red dots won't appear at times
2. Whenever the red dots appear, they won't move with the camera
3. My friend's laptop doesn't even have the red dots appear

So, we spent a few nights debugging and came across a few insights that we thought may be useful in helping here.

1. This problem seem to be localized on the laptop/desktop behavior, because it always works for our phones
2. The problem with the laptop tends to be time-sensitive. At a particular time, my own code, ARjs demo hosted on heroku, shows the red dots but at the very same time (after a few reloads/refreshes), all doesn't show the red dots, a consistent behavior observed.
3. My friend and I have almost the same laptop versions but the red dots almost doesn't appear on his screen at all (HP-envy), while it appears once awhile for mine (HP-envy, slightly newer version), for ARjs demo places-name likewise.

**To Reproduce**
- git clone the latest repo
- insert foursquare api key
- launch a live server/host on github.io the index.html in places-name

**Expected behavior**
- works on the phone BUT doesn't work on the laptop (and buggy)

**Screenshots**
**When red dot appears**
![image](https://user-images.githubusercontent.com/46477732/71866538-64ae4800-3141-11ea-81c1-f3867a7d9f7f.png)

**When red dot doesn't appear**
![image](https://user-images.githubusercontent.com/46477732/71866558-83acda00-3141-11ea-89e1-f0a8702f9e05.png)

**Desktop (please complete the following information):**
 - iOS (mainly >13)
 - Tried on Chrome, Firefox and Internet Edge, all failed

**Smartphone (please complete the following information):**
 - worked on almost all iPhones tried (11, 11 pro, XS)
 - ios 13.3
 - Safari, works

**Additional context**
- Well, we suspect there may be some dependencies overloaded with calls (especially pertinent to the laptop/desktop), could it be the api calls?
- We console.log the places outputs (in the function renderPlaces(places)) of the api, so places are being detected but none are appearing.
- No significant differences in console when red dots appear and when they don't, but noticeably totally different places output in console.
- **Bug/Issue is still present even when CORS problem is solved**, we removed CORS first to try to solve the base problem

**Comment by gabrielsze** [comment]
Bump?

**Comment by nicolocarpignoli** [comment]
> Bump?

Hi, I saw the issue. Unfortunately I do not have time for this right now. I'm working on other AR.js related feature (NFT and others). 
If you (or somebody) can come up with a solution, please provide a Pull Request. Thanks

**Comment by nicolocarpignoli** [comment]
If bug still persist, please re-open at: https://github.com/jeromeetienne/AR.js
