### ISSUE TITLE
draw markers on webcam video by human

### ISSUE THREAD

**Issue by vovanb** [jeromeetienne/AR.js#697]
is it possible using ar.js to draw arrow markers or other objects on webcam input where two peoples connected using webrtc?
Sample project
https://www.teamviewer.com/en/solutions/augmented-reality-remote-support/#getstarted

**Comment by nicolocarpignoli** [comment]
It is a nice idea, I have already thought myself to something similar. This is not achievable with AR.js for now, but I would suggest to not rely on AR.js that is marker based/ location based/ NFT in the future.

For this kind of project you will need to draw stuff, I don't see much the point to use marker. Or maybe I have mislead :) You could have build such experience without markers, and without AR.js.

**Comment by vovanb** [comment]
Thanks for fast reply... Even don't know where from to start search ... ARCore , Best is to have some js library

**Comment by nicolocarpignoli** [comment]
I'm closing this one as the question has been answered. Solution is not ar.js related :)
