### ISSUE TITLE
Origin of the Red Dot

### ISSUE THREAD

**Issue by gabrielsze** [jeromeetienne/AR.js#698]
Hi all, this is not particularly a bug, but have been searching the code for awhile, really curious about where this red dot comes from in the code, haha.

![photo_2020-01-02_11-21-05](https://user-images.githubusercontent.com/46477732/72166747-c6ea9f80-3404-11ea-9ed9-72b00ca55d07.jpg)

I guess my question is how to further customize this part of the code (eg. change color of the dot, find out how the dot gets its orientation other than the lat long it receives from the api, how to position it, etc)

**Steps to reproduce**
It's in the demo here (https://nicolo-carpignoli.herokuapp.com/examples/places-name/)

Any help is really appreciated!

**Comment by nicolocarpignoli** [comment]
Hi

it's the `link` componente of aframe. It's the default look. https://aframe.io/docs/0.9.0/components/link.html#properties

To modify it, please take a look at this: https://github.com/aframevr/aframe/issues/4276
