### ISSUE TITLE
How can I show different <a-asset-item> with the same marked by changing the id of the <a-entity>

### ISSUE THREAD

**Issue by JhonnyEDM** [jeromeetienne/AR.js#699]
I want to change the 3d model using buttons, change the id of the a-entity with JS but nothing happens, thanks.

**Comment by nicolocarpignoli** [comment]
Hi,
you can do that with Javascript. 
Load a script on your HTML.
On that script, you can retrieve your HTML a-entity element. For example:
With an HTML with this parts:

```
<a-assets>
    <a-asset-item id="id1" src="...">
    <a-asset-item id="id2" src="...">
</a-assets>

(......)
```
<a-marker...>
    <a-entity id="entityID1" gltf="#id1"/>
</....>
```

on the script you will have something like:

```
    var element = document.querySelector('#entityID1');
    element.setAttribute('gltf', '#2');
```

this will switch to the second gltf asset, defined in the a-assets.
