### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by dheavy** [jeromeetienne/AR.js#7]
Hey @jeromeetienne ! Great work!
Is AR.js available on npm? If not, it'd be great for portability (and wider adoption IMHO).
Cheers

**Comment by jeromeetienne** [comment]
Not at the moment, but why not, if it helps people :)

I never did it tho, any good url to suggest on how to do that ?

**Comment by jeromeetienne** [comment]
i did the search myself :) i just published [this](https://www.npmjs.com/package/ar.js)

is that ok ? did i forgot something

**Comment by jeromeetienne** [comment]
it says no README.md.. but there is [one](https://github.com/jeromeetienne/AR.js/blob/master/README.md)

im guessing it is a cache issue somewhere

**Comment by sasha240100** [comment]
@jeromeetienne Just came with the same problem. Already reserved a place for [whs-module-ar.js](https://github.com/WhitestormJS/whs-module-ar.js) but have no idea how can I include AR.js with es6. 
**May I do a pull request here to add npm support?**

**Comment by jeromeetienne** [comment]
@sasha240100 sure go ahead :)

**Comment by sasha240100** [comment]
@jeromeetienne Done. Check please
/ping @dheavy

**Comment by yeyuguo** [comment]
you are amzing !!!  @jeromeetienne

**Comment by craigm26** [comment]
Awesome work thanks

**Comment by sorianog** [comment]
Looks like this link does nothing: https://runkit.com/npm/ar.js
Which was accessed though: 
![image](https://cloud.githubusercontent.com/assets/13261711/23887967/24b82a14-0853-11e7-8928-63c7a766d82b.png)

**Comment by sasha240100** [comment]
@sorianog That's because it's not yet implemented as modules. It will not work from npm yet

**Comment by bunnybones1** [comment]
Hey @jeromeetienne,

Wonderful module! Do you mind updating the npm build with your latest work?

**Comment by jeromeetienne** [comment]
unfortunatly i got no knowledge of npm, so for that to be done, we would
need somebody to do it and contribute :)

**Comment by bastienmoulia** [comment]
@jeromeetienne In order to upgrade your npm package yon can:

- Change the version of the **package.json** file from 1.0.0 to 1.1.0 by exemple
- Log your computer to NPM if you are not already logged (check that with `npm whoami`) : `npm adduser`
- Launch the command `npm publish`

**Comment by svcninja** [comment]
When can we use the npm version of the ar.js?

**Comment by jeromeetienne** [comment]
there is a [contrib](https://github.com/jeromeetienne/AR.js/tree/master/three.js/contribs/npm) for it, but i admit it isnt updated. so the answer is likely 'not now' ?

The things is that i dont use npm for browsers... so i would need somebody either to do it. 

Something clean and standalone would be great

**Comment by ZoltanVeres** [comment]
Further discussions/progress in #251
