### ISSUE TITLE
Aframe integration on AR.js

### ISSUE THREAD

**Issue by hipstermojo** [jeromeetienne/AR.js#70]
What directory am I supposed to use to store newly trained markers and how will I refer to them using 		<a-marker-camera preset='hiro'></a-marker-camera>

Where I have to change hiro with the name of my new marker(s).

And what JS syntax will I use to store these new marker(s) in the back-end

**Comment by svcninja** [comment]
I tried my customized marker, I put the patt file in the same dir as the html, and refer to it as patternUrl='./mymarker.patt'. But it seems still pick up the default, which is the hiro.

**Comment by nicolocarpignoli** [comment]
we are working on making a better Readme.. in the meanwhile you can check this article of mine https://medium.com/chialab-open-source/ar-js-the-simpliest-way-to-get-cross-browser-ar-on-the-web-8f670dd45462 for basic custom marker usage.
