### ISSUE TITLE
Multiple marker - pointer cursor not match and scale problem

### ISSUE THREAD

**Issue by jesmartinez** [jeromeetienne/AR.js#700]
**Describe the bug**
Cursor does not fit well with markers when I try to record cursor events

**To Reproduce**
I have this sample code:
```
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,height=device-height">
  <meta name="apple-mobile-web-app-capable" content="yes">

  <script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@2c5c131dccaab9d449fcd0383e98d027a5bc07f6/dist/aframe-master.min.js"></script>
  <script src="https://raw.githack.com/jeromeetienne/AR.js/2.1.4/aframe/build/aframe-ar.js"></script>

</head>
<body style="margin : 0px; overflow: hidden;">
  <script>
    AFRAME.registerComponent("click-handler", {
      init: function() {
        console.log("I was triggered");
        const marker1 = document.querySelector("#marker1");
        const lBox = document.querySelector("#lbox");

        marker1.addEventListener("click", function(ev, target) {
          const intersectedElement = ev && ev.detail && ev.detail.intersectedEl;
          if (lBox && intersectedElement === lBox) {
              alert("Clicked");
          }
        });
      }
    });
  </script>

  <a-scene id="scene" arjs="trackingMethod: best; debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 3x3;" vr-mode-ui="enabled: false" ar-template>
    <a-marker id="marker1" type="barcode" value="0" emitevents="true" cursor="rayOrigin: mouse" click-handler>
      <a-box  id="lbox" position="0 0 0" material="color: red;"></a-box>
    </a-marker>

    <a-entity camera></a-entity>
  </a-scene>

</body>
```

**Expected behavior**
I should show the scale correctly and be able to click on any part of the object.

**Screenshots**
<img src="https://i.ibb.co/xFrb8PT/bug.jpg">

**Version:**
 - Aframe: v1.0.3 
 - AR.js: v2.1.4

**System information:**
 - Windows and Android
 - Desktop Chrome and Android Chrome

Does anyone else have this problem? 
I think can be two diferent problems

**Comment by kalwalt** [comment]
What happens if you change the meta line? try this:

```diff
- <meta name="viewport" content="width=device-width,height=device-height">
+ <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
```

**Comment by jesmartinez** [comment]
> What happens if you change the meta line? try this:
> 
> ```diff
> - <meta name="viewport" content="width=device-width,height=device-height">
> + <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
> ```

Nothing change, D:

**Comment by Mxlt** [comment]
> > What happens if you change the meta line? try this:
> > ```diff
> > - <meta name="viewport" content="width=device-width,height=device-height">
> > + <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
> > ```
> 
> Nothing change, D:

How did you make the multimarker learner work? I have not figured out how it all works.

**Comment by jesmartinez** [comment]
> How did you make the multimarker learner work? I have not figured out how it all works.
This question is not related to the topic.

Someone can say me if is this a bug?

**Comment by jesmartinez** [comment]
I can solve the scale problem forcing the canvas height at same of the body height. But pointer click event remains erratic.

**Comment by nicolocarpignoli** [comment]
Hi there, please feel free to re-open the issue at new AR.js repository: https://github.com/AR-js-org/AR.js

thank you!
