### ISSUE TITLE
Uncaught RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by akim8** [jeromeetienne/AR.js#701]
**Describe the bug**
Nothing is drawn on the screen.
"Uncaught RangeError: Array buffer allocation failed" from line 2 in aframe-ar.js.

**To Reproduce**
1. Open [Click Places](https://nicolo-carpignoli.herokuapp.com/examples/basic.html) demo in Chrome on Android device.
2. Refresh the page until the error occurs.

**Expected behavior**
Camera feed with location markers overlaid is expected to be displayed. Instead, a white screen is shown.

**Smartphone:**
 - Device: Samsung Galaxy Tab S2
 - OS: Android 7.0
 - Browser: Chrome
 - Version: 78.0.3904.108

**Additional context**
<details>
<summary>Full console log</summary>
<pre>
webvr-polyfill.js:1963 No DPDB device match.
o.calcDeviceParams_ @ webvr-polyfill.js:1963
o.recalculateDeviceParams_ @ webvr-polyfill.js:1908
o @ webvr-polyfill.js:1886
w @ webvr-polyfill.js:3156
e.getPolyfillDisplays @ webvr-polyfill.js:3396
e.getVRDisplays @ webvr-polyfill.js:3442
e @ webvr-polyfill.js:3384
171.../package @ index.js:22
o @ _prelude.js:1
r @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
webvr-polyfill.js:1915 Failed to recalculate device parameters.
o.recalculateDeviceParams_ @ webvr-polyfill.js:1915
o @ webvr-polyfill.js:1886
w @ webvr-polyfill.js:3156
e.getPolyfillDisplays @ webvr-polyfill.js:3396
e.getVRDisplays @ webvr-polyfill.js:3442
e @ webvr-polyfill.js:3384
171.../package @ index.js:22
o @ _prelude.js:1
r @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
webvr-polyfill.js:1699 Using fallback Android device measurements.
s.determineDevice_ @ webvr-polyfill.js:1699
s.updateDeviceParams @ webvr-polyfill.js:1684
s @ webvr-polyfill.js:1676
w @ webvr-polyfill.js:3157
e.getPolyfillDisplays @ webvr-polyfill.js:3396
e.getVRDisplays @ webvr-polyfill.js:3442
e @ webvr-polyfill.js:3384
171.../package @ index.js:22
o @ _prelude.js:1
r @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
a-register-element.js:69 [Deprecation] document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
module.exports.registerElement @ a-register-element.js:69
123.../utils/ @ a-node.js:15
o @ _prelude.js:1
(anonymous) @ _prelude.js:1
124../a-entity @ a-register-element.js:184
o @ _prelude.js:1
(anonymous) @ _prelude.js:1
128.../../lib/three @ a-scene.js:5
o @ _prelude.js:1
(anonymous) @ _prelude.js:1
171.../package @ index.js:63
o @ _prelude.js:1
r @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
index.js:92 A-Frame Version: 0.9.2 (Date 2019-12-09, Commit #c4432e7c)
index.js:93 three Version (https://github.com/supermedium/three.js): ^0.111.3
index.js:95 WebVR Polyfill Version: ^0.10.10
aframe-ar.min.js:1 Uncaught RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at aframe-ar.min.js:1
(anonymous) @ aframe-ar.min.js:1
basic.html:10 Uncaught TypeError: Cannot read property 'ArToolkitContext' of undefined
    at basic.html:10
(anonymous) @ basic.html:10
three.js:15853 THREE.WebGLRenderer: OES_texture_float extension not supported.
get @ three.js:15853
oe @ three.js:15614
n @ three.js:23769
Qt @ three.js:23818
setupRenderer @ a-scene.js:628
value @ a-scene.js:90
attachedCallback @ a-register-element.js:160
three.js:15853 THREE.WebGLRenderer: OES_texture_half_float extension not supported.
get @ three.js:15853
n @ three.js:23775
Qt @ three.js:23818
setupRenderer @ a-scene.js:628
value @ a-scene.js:90
attachedCallback @ a-register-element.js:160
three.js:15853 THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
get @ three.js:15853
n @ three.js:23776
Qt @ three.js:23818
setupRenderer @ a-scene.js:628
value @ a-scene.js:90
attachedCallback @ a-register-element.js:160
three.js:15853 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
get @ three.js:15853
n @ three.js:23783
Qt @ three.js:23818
setupRenderer @ a-scene.js:628
value @ a-scene.js:90
attachedCallback @ a-register-element.js:160
webvr-polyfill.js:1963 No DPDB device match.
o.calcDeviceParams_ @ webvr-polyfill.js:1963
o.recalculateDeviceParams_ @ webvr-polyfill.js:1908
(anonymous) @ webvr-polyfill.js:1896
load (async)
o @ webvr-polyfill.js:1892
w @ webvr-polyfill.js:3156
e.getPolyfillDisplays @ webvr-polyfill.js:3396
e.getVRDisplays @ webvr-polyfill.js:3442
e @ webvr-polyfill.js:3384
171.../package @ index.js:22
o @ _prelude.js:1
r @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
webvr-polyfill.js:1915 Failed to recalculate device parameters.
o.recalculateDeviceParams_ @ webvr-polyfill.js:1915
(anonymous) @ webvr-polyfill.js:1896
load (async)
o @ webvr-polyfill.js:1892
w @ webvr-polyfill.js:3156
e.getPolyfillDisplays @ webvr-polyfill.js:3396
e.getVRDisplays @ webvr-polyfill.js:3442
e @ webvr-polyfill.js:3384
171.../package @ index.js:22
o @ _prelude.js:1
r @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
three.js:15853 THREE.WebGLRenderer: EXT_texture_filter_anisotropic extension not supported.
get @ three.js:15853
E @ three.js:21555
I @ three.js:22077
Qt.setRenderTarget @ three.js:26136
Gt.render @ three.js:19673
Qt.render @ three.js:24702
render @ a-scene.js:768
(anonymous) @ bind.js:12
f @ three.js:24603
e @ three.js:14947
requestAnimationFrame (async)
start @ three.js:14960
Qt.setAnimationLoop @ three.js:24617
(anonymous) @ a-scene.js:673
emit @ a-node.js:263
(anonymous) @ a-node.js:128
Promise.then (async)
load @ a-node.js:125
load @ a-entity.js:245
(anonymous) @ a-scene.js:681
setTimeout (async)
play @ a-scene.js:680
attachedCallbackPostCamera @ a-scene.js:155
(anonymous) @ a-scene.js:129
emit @ a-node.js:263
checkUserCamera @ camera.js:98
(anonymous) @ camera.js:58
emit @ a-node.js:263
setObject3D @ a-entity.js:156
init @ camera.js:28
initComponent @ component.js:320
updateProperties @ component.js:302
module.exports.Component @ component.js:78
i @ component.js:662
initComponent @ a-entity.js:332
updateComponent @ a-entity.js:495
updateComponents @ a-entity.js:463
(anonymous) @ a-entity.js:249
(anonymous) @ a-node.js:127
Promise.then (async)
load @ a-node.js:125
load @ a-entity.js:245
value @ a-entity.js:88
attachedCallback @ a-register-element.js:160
attachedCallback @ a-register-element.js:160
</pre>
</details>

**Comment by deepakgd** [comment]
+ 1 I am also facing same issue in moto g 6

**Comment by nicolocarpignoli** [comment]
Hi there, please feel free to re-open the issue at new AR.js repository: https://github.com/AR-js-org/AR.js

thank you!
