### ISSUE TITLE
Unable to minify the library locally

### ISSUE THREAD

**Issue by an0rak-dev** [jeromeetienne/AR.js#703]
**Describe the bug**
After forking the project and doing a `make build` and a `make minify`, the last command fails with the error : 

```
$ make minify
cd three.js && make minify
echo    > build/ar.js
cat     vendor/jsartoolkit5/build/artoolkit.min.js      \
                vendor/jsartoolkit5/js/artoolkit.api.js         >> build/ar.js
cat     src/threex/*.js                                 \
                src/new-api/*.js                                \
                src/markers-area/*.js                           >> build/ar.js
uglifyjs build/ar.js > build/ar.min.js
/bin/sh: uglifyjs: command not found
make[1]: *** [minify-main] Error 127
make: *** [minify] Error 2
```

**To Reproduce**
1. Checkout the project on master
2. Do a `make build`
3. Do a `make minify`

**Expected behavior**

The project should be correctly minified.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: N/A
 - Version: Catalina

**Additional context**
After checking the `package.json` file, it seems that it declare no dependencies, which explains how it could not use `uglifyjs` since it's not a devDependency.

**Comment by kalwalt** [comment]
@an0rak-dev i will check this. I'm working on another branch so i can' test the master. :smile:

**Comment by an0rak-dev** [comment]
Hi @kalwalt !

I've made a PR about this one if you want to check ;)

**Comment by nicolocarpignoli** [comment]
merged on dev!
