### ISSUE TITLE
Calculate rotation after object is placed in location based mode

### ISSUE THREAD

**Issue by wreszelewski** [jeromeetienne/AR.js#707]
**Is your feature request related to a problem? Please describe.**
I'd like to display objects always facing the user, so he can easily read provided information. To do this I have to calculate rotation basing on position calculated by gps-entity-place. I need to update position after each update of GPS position.

**Describe the solution you'd like**
In my opinion the best way to implement this is to add an event gps-entity-place-position-updated that is fired on element or with element passed as parameter after position is calculated. With that I can easily modify my object after every position update.

**Comment by nicolocarpignoli** [comment]
Good idea! The event is fine to me.

This one should not be so difficult: https://github.com/jeromeetienne/AR.js/blob/master/aframe/src/location-based/gps-entity-place.js#L44

Here's where I update the position of the place.
You can find a similar method (if needed) on the gps-camera, for user position.

You can try, make some attempts and make a PR with a basic example using your modifies. I will be happy to help if you can start this PR.

**Comment by nicolocarpignoli** [comment]
we have done this, sorry to not have update you.

You can just use the 'look-at' component of AFRAME. See the examples on this repository, at aframe/examples/always-face-user
