### ISSUE TITLE
Stop button in player.html not working

### ISSUE THREAD

**Issue by Mxlt** [jeromeetienne/AR.js#708]
**Describe the bug**
When pressing the stop button, it is not working. It says that it failed to load resources in svd.js, posit1.js, cv.js, aruco.js, threex-arucocontext.js, and so on.
Uncaught threex-armultimarkerutils.js SyntaxError:Unexpected token"."
The same with armultimarkercontrols and armultimarkerlearning.

**To Reproduce**
1. Download repo
2. Create server that points to folder.
3. Go to three.js/examples/multi-markers/examples/player.html
4. See error in console

**Expected behavior**
Followed the following instructions. Expected learner to start.
https://github.com/jeromeetienne/AR.js/issues/271#issuecomment-352207305

**Desktop (please complete the following information):**
 - Windows 10 OS build 1832.592
 - Chrome Versión 79.0.3945.130 (Build oficial) (64 bits)

**Comment by kalwalt** [comment]
@Mxlt thanks for reportons this! Aruco supports was removed from Ar.js, that's why you receive that errors, and for this reason i think the multi player/learner code Is broken. Actually we are working to add NFT to Ar.js, and unfortunately i haven't so much time to fix this.

**Comment by Mxlt** [comment]
Thanks for the response!
