### ISSUE TITLE
Location Based issue with a-frame 1.x: content follows the camera when moving phone on y axis

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#710]
Using aframe 1.x versions, on a Location-Based app with AR.js, a problem appears - no problems with versions like 0.9.2 of a-frame:

Moving the camera from right to left and viceversa works ok, so the markers (or more generically, the content) disappear, and re-appear on the same position. Instead, moving the camera vertically, so from top to bottom and vice versa, cause the markers to move, following the camera movement.

to reproduce: 

* **has the problem** (latest aframe from master cdn): https://nicolo-carpignoli.herokuapp.com/examples/basic.html

* **no problem** (aframe 0.9.2) https://nicolo-carpignoli.herokuapp.com/examples/places-name/

**Comment by mazurmazurmazur** [comment]
Unfortunately I also have this problem, using Safari iOS 13.3.1 even though I am using a-frame 0.9.2
On Android Chrome of my co-worker it doesn't seem to be the problem at all. 

There are four different scenarios, listed from most to least common:

1: they follow the camera, and AFTER REFRESHING the browser they stop doing that and are in their right places
2: even when I refresh they follow the y-axis of camera movement for ever
3: they follow the camera, but after couple of seconds they stop it and find themselves in their right places without my intervention
4: the geopoints are placed where they should be from the beginning

but unfortunately i find it impossible to detect any factor that causes it

**Comment by nicolocarpignoli** [comment]
added to new repository, see linked issue
