### ISSUE TITLE
Offset when using a-camera instead of a-entity camera

### ISSUE THREAD

**Issue by jansim** [jeromeetienne/AR.js#712]
**Describe the bug**
During marker based tracking, when using the `<a-camera>` primitve instead of an `<a-entity camera>`, everything is slightly shifted downwards. This shift is of the same amount of pixels as the negative margin applied to the body, yet the canvas' position is shifted correctly, so that is not the problem.

**To Reproduce**
1. Go to https://codepen.io/jansim/pen/NWPmRwp
2. Open the hiro marker (https://jeromeetienne.github.io/AR.js/data/images/HIRO.jpg) on another device 
3. See the wrongly tracked blue cube. Compare this to https://codepen.io/jansim/pen/BayELmL which is working as expected.

**Expected behavior**
The application should behave the same whether using `<a-entity camera>` or `<a-camera>`.

**Screenshots**
![Screenshot 2020-01-27 at 09 03 52](https://user-images.githubusercontent.com/7115629/73181297-f24bda80-40e4-11ea-89ef-bb502ba27e2c.jpg)
![Screenshot 2020-01-27 at 09 03 59](https://user-images.githubusercontent.com/7115629/73181298-f4ae3480-40e4-11ea-8a19-dc91ca615d0b.jpg)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Browser: Firefox Developer Edition (reproducible in Chrome)
 - Version: 73.0b9 (64-Bit)

**Comment by andypotato** [comment]
According to the [A-Frame documentation](https://aframe.io/docs/1.0.0/primitives/a-camera.html): When using `<a-camera>` the camera is situated by default at the average height of human eye level (1.6 meters). This makes sense for VR application but less so for AR.

You can use the `position` parameter to put the camera on the ground, for example with `<a-camera position="0 0 0" ...>`.

**Comment by nicolocarpignoli** [comment]
Hi there, please feel free to re-open the issue at new AR.js repository: https://github.com/AR-js-org/AR.js

thank you!
