### ISSUE TITLE
CORS Issue in While using in Location Feature

### ISSUE THREAD

**Issue by mr-talukdar** [jeromeetienne/AR.js#714]
For some reasons my model isn't loading up as it should at the given coordinates instead it just is stuck in the screen while nothing happens, tried with the default pokemon model of magnemite as described in,

https://medium.com/chialab-open-source/build-your-location-based-augmented-reality-web-app-c2442e716564.

Went on inspecting the Console and found this error.

(index):1 Access to XMLHttpRequest at 'https://raw.githack.com/jeromeetienne/ar.js/master/data/data/camera_para.dat' from origin 'https://snapdragon-boron-u86oljg3n5.glitch.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Here's my code,
<!DOCTYPE` html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>GeoAR.js demo</title>
    <script src='https://aframe.io/releases/0.9.2/aframe.min.js'></script>
    <script src="https://raw.githack.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js"></script>
    <script src="https://raw.githack.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
    <script>
        THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/'
    </script>
</head>

<body style='margin: 0; overflow: hidden;'>
    <a-scene
        vr-mode-ui="enabled: false"
		embedded
        arjs='sourceType: webcam; sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: false;'>
        <a-entity gltf-model="./assets/magnemite/scene.gltf" 
        rotation="0 180 0" 
        scale="0.20 0.20 0.20" 
        gps-entity-place="longitude: 85.820754; latitude: 20.354779  ;" 
        animation-mixer/>
        
        <a-camera gps-camera rotation-reader></a-camera>
	</a-scene>
</body>

**Comment by nicolocarpignoli** [comment]
That CORS error should not be the cause. Try to deploy it on a github pages instead of Glitch that can give problems and let me know

**Comment by AuroraCh** [comment]
I also encountered this error. I don't know how to deal with it. Now, the model can be displayed, but the position of the model is to zoom out at the top of the screen. I can't adjust the position and size to make it all appear in the frequency mode.
The above cods error is not reflected in modifying scale,
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Same code as above，Can you help me

**Comment by AuroraCh** [comment]
I want to know how to make the model smaller, and make the model all appear in the interface, and adjust the distance between the model and the mobile screen，thanks

**Comment by AuroraCh** [comment]
My problem and code are the same as above. The model can't be displayed by coordinates. The error is CORS

**Comment by mr-talukdar** [comment]
GitHub pages give out the same problem. I also tried by hosting it to Firebase it's the same everywhere.

**Comment by nicolocarpignoli** [comment]
try removing 
```
<script> THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/' </script>
```
