### ISSUE TITLE
Bug ArToolKitSource with image and video

### ISSUE THREAD

**Issue by Morzat95** [jeromeetienne/AR.js#716]
**Describe the bug**
Assign an image or video as sourceType not working. Blank screen on browser.

Error:
- Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

**To Reproduce**
Try this code:

```
<!doctype HTML>
<html>
  <script src="https://aframe.io/releases/1.0.3/aframe.min.js"></script>
  <script src="https://raw.githack.com/jeromeetienne/AR.js/2.1.4/aframe/build/aframe-ar.js"></script>

  <body style='margin : 0px; overflow: hidden;'>
    <!-- You can get the same error with 'video' as sourceType -->
    <a-scene embedded arjs='sourceType: image; sourceUrl: path/to/your/image/with/hiro/marker.png'>
      <a-marker preset="hiro">
          <a-box position='0 0.5 0' material='color: yellow;'></a-box>
      </a-marker>
      <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
```

**Expected behavior**
It should show the image/video provided in 'sourceURL' (an image of Hiro marker in this case) in the body of the html and generate a yellow box on top of the marker.

**Screenshots**

Bug
![Bug](https://user-images.githubusercontent.com/20955917/73324329-58417a80-4229-11ea-9856-4197936d655f.png)

Error
![Error](https://user-images.githubusercontent.com/20955917/73324330-58da1100-4229-11ea-8230-e18910f19fa8.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome
- Version: 79.0.3945.130

**Additional context**

Possible duplicate: #593

**Comment by Mxlt** [comment]
I'm not sure if this is what you want. But I did the following:

```
<!doctype HTML>
<html>
  <script src="https://aframe.io/releases/1.0.3/aframe.min.js"></script>
  <script src="https://raw.githack.com/jeromeetienne/AR.js/2.1.4/aframe/build/aframe-ar.js"></script>

  <body style='margin : 0px; overflow: hidden;'>
    <!-- You can get the same error with 'video' as sourceType -->
    <a-scene embedded arjs>
      <a-marker preset="hiro">
          <a-box position='0 0.5 0' material='color: yellow;'></a-box>
      </a-marker>
      <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
```
I removed the parameters in arjs. The hiro marker you show it anywhere else, but the video itself is not supposed to show any marker.

**Comment by nicolocarpignoli** [comment]
fixed with https://github.com/jeromeetienne/AR.js/pull/717
