### ISSUE TITLE
Size attribute on <a-marker> does not have any effect.

### ISSUE THREAD

**Issue by jorgecardoso** [jeromeetienne/AR.js#720]
**Describe the bug**
Size attribute on `<a-marker>` does not have any effect.

**To Reproduce**
1. Run the following code (or go to https://political-elderberry.glitch.me/)
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://aframe.io/releases/1.0.2/aframe.min.js"></script>
    <script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
  </head>
  <body>
    <a-scene embedded arjs='sourceType:image; sourceUrl:Doc1.png;debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 3x3;'>
      <a-camera> 
        <a-marker type="barcode" value="0" size="1" > <a-box color="red"></a-box></a-marker>
        <a-marker type="barcode" value="1" size="0.5" > <a-box color="green"> </a-box></a-marker>
        </a-camera>
    </a-scene>
  </body>
</html>

```

2. The example shows two markers printed on the same page. Marker with code 1 has half the width of marker with code 0.
![Doc1](https://user-images.githubusercontent.com/651618/74022713-02da3b80-4996-11ea-81c4-b428c0d22c5a.png)

3. Run Inspector
![Annotation 2020-02-07 103641](https://user-images.githubusercontent.com/651618/74022664-eb9b4e00-4995-11ea-91e1-476780a14f58.png)

**Expected behavior**
By setting different marker sizes, it should be possible to print on the same surface markers with different sizes. The AR system should take the marker size into account and place virtual objects on the same plane.
In the example above, boxes should have the same calculated distances to the camera.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by andypotato** [comment]
From your report it's not quite clear what kind of behavior you are expecting. Can you describe a bit more what's your expected result and maybe provide a CodePen?

**Comment by jorgecardoso** [comment]
> From your report it's not quite clear what kind of behavior you are expecting. Can you describe a bit more what's your expected result and maybe provide a CodePen?

I have updated my example in glitch so that it uses an image instead of the camera, and I also updated the description of the expected behaviour and added screenshots. I hope it's clearer now.

Thanks!

**Comment by nicolocarpignoli** [comment]
I still don't get what is the 'bug'. Please be more specific.

**Comment by jorgecardoso** [comment]
> I still don't get what is the 'bug'. Please be more specific.

Markers are on the same surface (same 'z'). Virtual objects should also, but they are not.

**Comment by nicolocarpignoli** [comment]
you should use 'scale', not 'size'

scale ="1 1 1" or "0.5 0.5 0.5".

This specify the scaling for all three axis (x, y, z).
see: https://aframe.io/docs/1.0.0/components/scale.html

**Comment by jorgecardoso** [comment]
> you should use 'scale', not 'size'
> 
> scale ="1 1 1" or "0.5 0.5 0.5".
> 
> This specify the scaling for all three axis (x, y, z).
> see: https://aframe.io/docs/1.0.0/components/scale.html

That is a different thing. I'm talking about the 'size' attribute documented here: https://github.com/jeromeetienne/AR.js/blob/master/aframe/README.md

**Comment by kalwalt** [comment]
@jorgecardoso i never tried the size attribute so can not say so much, but i agree with you that is not the same as scale. It should change the MarkedWidth (inside jsartoolkit5 and aruco) that is used in transMat calculations, I will look deeper into it.

**Comment by nicolocarpignoli** [comment]
opened in new AR.js repository, see linked issue
