### ISSUE TITLE
Loading an external .patt file out of memory on maxed out 64gb macbook pro... 

### ISSUE THREAD

**Issue by yosun** [jeromeetienne/AR.js#724]
**Describe the bug**

"loadMarker(): Error loading pattern file /marker_0."
"ARToolKitJS(): Unable to set up AR marker."
"Out of memory!!"

**To Reproduce**

Use a .patt file in lieu of the hiro one

You can use the patt file of hiro https://raw.githubusercontent.com/jeromeetienne/AR.js/master/three.js/examples/marker-training/examples/pattern-files/pattern-hiro.patt

See https://codepen.io/yosunchang/pen/rNVampj 

**Expected behavior**
Marker should load? 

**Screenshots**
"three Version (https://github.com/supermedium/three.js):" "^0.111.4"
"WebVR Polyfill Version:" "^0.10.10"
"%cdevice:error %cWebXR session support error: Failed to execute 'isSessionSupported' on 'XR': Access to the feature 'xr' is disallowed by feature policy.%c " "color: lightseagreen" "color: inherit" "color: lightseagreen"
"AR.js" "1.7.5" "- trackingBackend:" "artoolkit"
"ARjs.Anchor -" "changeMatrixMode:" "modelViewMatrix" "/ markersAreaEnabled:" false
"THREEx.ArMarkerControls: 'markersAreaEnabled' is not a property of this material."
"Allocated videoFrameSize 1228800"
"Pattern detection mode set to 1."
"Pattern ratio size set to 0.500000."
"Pattern Data read error!!"
"loadMarker(): Error loading pattern file /marker_0."
"ARToolKitJS(): Unable to set up AR marker."
"Out of memory!!"

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: 64gb maxed out macbook pro 2019
 - OS: mac os x catalina 10.15.2 (19C57)
 - Browser chrome desktop  79.0.3945.130 (Official Build) (64-bit)
 - Version - latest one on github

**Additional context**

**Comment by nicolocarpignoli** [comment]
Hi there, please feel free to re-open the issue at new AR.js repository: https://github.com/AR-js-org/AR.js

thank you!
