### ISSUE TITLE
Integrating into a mobile app

### ISSUE THREAD

**Issue by ugintl** [jeromeetienne/AR.js#726]
Is it possible to integrate it into a mobile app?

**Comment by benallfree** [comment]
I'm working on this with Cordova (iOS). Is anyone else already working on it?

**Comment by agomezmart** [comment]
Hi guys!
I'm currently trying to integrate AR.js in my current IONIC (v1) application.

For the time being, after installing the [iosrtc plugin](https://github.com/cordova-rtc/cordova-plugin-iosrtc), including the different ".js" and adding the following to the 'deviceReady event' `cordova.plugins.iosrtc.registerGlobals();` i've been able to open the camera (I'm testing in iOS), but I'm struggling when it comes to showing something in a given location.

If anyone has achieved this (to show the camera and an object in a location) in a Cordova application, would be nice to know how to get it

**Comment by benallfree** [comment]
@agomezmart So it seems there are at least 3 of us attempting the same thing. Yesterday I got to the same spot as you, it shows the camera view but does not seem to recognize a Hiro marker. 

Do you want to collaborate a bit?

**Comment by agomezmart** [comment]
@benallfree sure!

Concerning your answer, you are working with the marker-based solution while I'm dealing with the location-based one.

**Comment by benallfree** [comment]
@agomezmart I'm starting with markers but will be adding location too.

Feel free to add your own demo experiment to this repo: https://github.com/benallfree/arjs-mobile-app-samples

**Comment by agomezmart** [comment]
@benallfree nice! I'll prepare the demo, even though it is not working 100%, and upload it to the repo 😃

**Comment by benallfree** [comment]
Child ticket created in aframe https://github.com/aframevr/aframe/issues/4451

**Comment by benallfree** [comment]
aframe fork: https://github.com/aframevr/aframe/pull/4452

**Comment by nicolocarpignoli** [comment]
Hi there, please feel free to re-open the issue at new AR.js repository: https://github.com/AR-js-org/AR.js

thank you!
