### ISSUE TITLE
Show only Nearby Models or Objects

### ISSUE THREAD

**Issue by ctrljs** [jeromeetienne/AR.js#727]
Only the objects which are near (distance in meters) to the user should be rendered. If the latitude and longitude doesn't fall in the radius or is not nearby, the object should not be shown. Is there any property for the same.

**Comment by nicolocarpignoli** [comment]
I have developed something similar outside the AR.js logic. May have senso, actually, to add something like a 'maxDistance' property as the 'minDistance'. Currently is not present. Should be a nice to have feature.

**Comment by ctrljs** [comment]
Yes it would be great property to add 'maxDistance', Actually was confused about minDistance,I had thought it is the minimum distance required between the user and object for it to be displayed, but it is the opposite i guess. So hope you will be adding the new property soon with a example. Thank you for the early response.

**Comment by nicolocarpignoli** [comment]
about minDistance, there should be the documentation. Is not clear enough? Can be enhanced I guess 
https://github.com/jeromeetienne/AR.js/blob/master/aframe/README.md#location-based

**Comment by nicolocarpignoli** [comment]
https://github.com/AR-js-org/AR.js/issues/38
