### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by benallfree** [jeromeetienne/AR.js#728]
[This package](https://www.jsdelivr.com/package/npm/ar.js) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

Would you like me to submit a PR for this?

**Comment by nicolocarpignoli** [comment]
Absolutely, It would be great. Thank you.

**Comment by benallfree** [comment]
@nicolocarpignoli 

1. Is aframe integration the most common use case? I see a three.js build as well, but we can only pick one for the default file. 
2. I was thinking of using `main`, unless you have a different preference?

**Comment by nicolocarpignoli** [comment]
pick aframe one as default, yes.
ok the 'main' for me.

**Comment by nicolocarpignoli** [comment]
fixed with PR https://github.com/jeromeetienne/AR.js/pull/731
