### ISSUE TITLE
aframe demo.html broken with camera

### ISSUE THREAD

**Issue by caseyyee** [jeromeetienne/AR.js#73]
![image](https://cloud.githubusercontent.com/assets/1560884/26514510/2738259c-4227-11e7-96ed-dc9c9a970421.png)

When selecting camera as source, I get a weird split image using my MBP.

**Comment by caseyyee** [comment]
also seems to jump around a bit when I resize the window.

**Comment by jeromeetienne** [comment]
is this still hapenning ?

**Comment by caseyyee** [comment]
Nope should be fixed now :). Thanks.

**Comment by jeromeetienne** [comment]
demo.html has been broken for months. it was supposed exposed the parameters to as button, thus the user can easily try various combinaison

**Comment by jeromeetienne** [comment]
closing demo.html isnt supposed to work anyway :)
