### ISSUE TITLE
Duplicate artoolkit.api.js bundled in three.js/build/ar.js?

### ISSUE THREAD

**Issue by benallfree** [jeromeetienne/AR.js#732]
**Describe the bug**
I was looking at the `ar.js` build and noticed `ARController.prototype.detectMarker` is already included in `vendor/jsartoolkit5/build/artoolkit.min.js`, but the Makefile also appends `vendor/jsartoolkit5/js/artoolkit.api.js`. I believe `artoolkit.api.js` is already in the min bundle, is there a reason it's included again?

**To Reproduce**
1. Open vscode
2. Search `./three.js/build/ar.js` for `ARController.prototype.detectMarker`
3. Observe that it is defined twice

**Expected behavior**

I think the three.js Makefile should not append `artoolkit.api.js` since it's already in the `artoolkit.min.js`  build bundle? If you agree, I'm happy to submit a PR.

```
build-main:
	echo	> build/ar.js
	cat 	vendor/jsartoolkit5/build/artoolkit.min.js	\
		vendor/jsartoolkit5/js/artoolkit.api.js		>> build/ar.js     # << POSSIBLE ERROR?
	cat	src/threex/*.js					\
		src/new-api/*.js 				\
		src/markers-area/*.js 				>> build/ar.js

```

**Screenshots**

![image](https://user-images.githubusercontent.com/1068356/74447046-9647bc80-4e2d-11ea-87e6-c7b675bdf721.png)

**Comment by nicolocarpignoli** [comment]
yes that's absolutely correct. it's an error. artoolkit.min.js is the minified of artoolkit.api.js, it has exactly the same content.

**Comment by benallfree** [comment]
Seems like a one line fix in the makefile, would you like a PR for it?

**Comment by nicolocarpignoli** [comment]
Yes would be better for me to track, thank you! Inviato dal mio telefono Huawei-------- Messaggio originale --------Da: Ben Allfree <notifications@github.com>Data: gio 13 feb 2020, 22:05A: "jeromeetienne/AR.js" <AR.js@noreply.github.com>Cc: Nicolò Carpignoli <carpo23@gmail.com>, Comment <comment@noreply.github.com>Oggetto: Re: [jeromeetienne/AR.js] Duplicate artoolkit.api.js bundled in three.js/build/ar.js? (#732)Seems like a one line fix in the makefile, would you like a PR for it?

**Comment by kalwalt** [comment]
@benallfree I can confirm this, infact in PR #705 we have deleted and also cleaned other parts.

**Comment by nicolocarpignoli** [comment]
right I forgot that. So no PR for now, we will solve that with PR #705
