### ISSUE TITLE
Detect when the user points the camera to a specific location to trigger an event

### ISSUE THREAD

**Issue by masilv4** [jeromeetienne/AR.js#733]
**Is your feature request related to a problem? Please describe.**
I'm developing an app with accessibility features for people with visual impairments. It shows the places around with their names, but for that specific requirement this is not enough.

**Describe the solution you'd like**
I'd like to implement a means of when the user points the camera to a specific place, some event is triggered. That way I could make the app trigger a voice command saying the place's information (like name, description, distance, etc).

**Describe alternatives you've considered**
Because I'm using a webview of Android to show the aframes, I tried to implement that feature inside the android app, using the android's geolocation api, but I had no success.

**Additional context**
As I said i'm using the AR.js within an android app. It's possible to create an interface to comunicate the AR.js with the android app. 

Is there any way to do this feature?

**Comment by nicolocarpignoli** [comment]
we can  continue discussing this on new AR.js repo: https://github.com/AR-js-org/AR.js/
