### ISSUE TITLE
Simulate heading in location based mode

### ISSUE THREAD

**Issue by ThomasRutzer** [jeromeetienne/AR.js#736]
**Is your feature request related to a problem? Please describe.**
Since version [2.2.0](https://github.com/jeromeetienne/AR.js/blob/master/CHANGELOG.md#220) it is possible to simulate position data. Maybe it would be useful to extend this with heading data?

**Describe the solution you'd like**
Extend schema of `gps-camera` with 

`
simulateHeading: {
  type: 'number',
 default: 0
}
`

And on top of function  `_onDeviceOrientation`
 
```
 if (this.data.simulateHeading !== 0) {
     this.heading = this.data.simulateHeading;
     return;
  }
```

**Describe alternatives you've considered**
No alternatives necessary, just decide if this could be useful or not 

**Additional context**

**Comment by nicolocarpignoli** [comment]
Yes, why not. Are you able to make a PR for this?

**Comment by nicolocarpignoli** [comment]
moved this issue in new AR.js repository: https://github.com/AR-js-org/AR.js/
