### ISSUE TITLE
I have some models, and I can't handle event on any of them 

### ISSUE THREAD

**Issue by maxhaice** [jeromeetienne/AR.js#737]
**Describe the bug**
I tried to handle event click on model using your code. And it's not working. How I can handle this event of any my model, or, maybe coordinates of screen (x, y) 
 Waiting for answer, thanx.

**Comment by nicolocarpignoli** [comment]
Please, add more informations. Add:

* code you used, full code
* what it means 'not works', please explain what you are trying to achieve, in detail, and what is the outcome.

Otherwise I have to close this issue.
