### ISSUE TITLE
Using image source instead of webcam causes security error

### ISSUE THREAD

**Issue by hillj8** [jeromeetienne/AR.js#739]
**Describe the bug**

Webcam works great but when I try to use the image source get a security error - operation insecure?

**To Reproduce**
<script src="https://aframe.io/releases/0.9.1/aframe.min.js"></script>
<script src="AR.js-master/aframe/build/aframe-ar_my.js"></script>

<a-scene embedded arjs='sourceType: image; sourceUrl: AR.js-master/data/images/img.jpg; detectionMode: mono_and_matrix; matrixCodeType: 3x3;'>

**Expected behavior**
Image to be run through the detection phase

**Screenshots**

![image](https://user-images.githubusercontent.com/37069297/75339478-8649c700-5888-11ea-840c-b6712ad518a7.png)
![image](https://user-images.githubusercontent.com/37069297/75339515-9497e300-5888-11ea-84aa-0c31c5c508f6.png)
![image](https://user-images.githubusercontent.com/37069297/75339773-0c660d80-5889-11ea-860f-c05780290e5a.png)

**Desktop (please complete the following information):**
Win 10, Firefox (latest)

**Smartphone (please complete the following information):**
Not used

**Additional context**

**Comment by kalwalt** [comment]
Hi @hillj8 which image are you using? Does it is hosted in the same origin or in another place?

**Comment by nicolocarpignoli** [comment]
Hi there, please reopen issue in the new AR.js repository: https://github.com/AR-js-org/AR.js

Thank you.
