### ISSUE TITLE
Select between  selfie/back camera.

### ISSUE THREAD

**Issue by caseyyee** [jeromeetienne/AR.js#74]
three.js examples seem to use the back camera, while A-Frame examples use the front facing camera.  Not sure why the discrepancy, but there should be some kind of option to be able to select between the two.

Using a samsung galaxy note 4.

**Comment by caseyyee** [comment]
https://dev.opera.com/articles/getusermedia-access-camera-privacy-ui/

"Which camera is used is left to the device: "User agents are encouraged to default to using the user's primary or system default camera and/or microphone (as appropriate) to generate the media stream."

So i guess the best case here is to have some kind of camera switch UI.

**Comment by jeromeetienne** [comment]
Thank for reporting and the links. i will read them

honnestly the camera selection is an issue with the new API. i would prefer to avoid the manual selection, to keep the user experience as smooth as possible.

Currently my code is sketchy on that 😢

https://github.com/jeromeetienne/AR.js/blob/master/three.js/threex-artoolkitsource.js#L153

**Comment by curtello** [comment]
Is there a way to set the back camera as default?

**Comment by jeromeetienne** [comment]
If so I would love to hear 😄

**Comment by francesco-marafini** [comment]
@jeromeetienne @curtello friggin' back camera is pretty damn elusive on mobile browsers

**Comment by curtello** [comment]
mozilla prompts it for you, when i tried it locally at least

**Comment by francesco-marafini** [comment]
Yes. The only gentleman on the browser scene.
It does it also when the code is run on the web.

**Comment by jeromeetienne** [comment]
supposedly fix now
