### ISSUE TITLE
Implementation on Vue.js

### ISSUE THREAD

**Issue by mdirir92** [jeromeetienne/AR.js#741]
Hey!

I love this plugin that I have tried on CodePen. 

I'd love to implement it on my Vue.js project, and after a number of attempts, the camera seems to be working fine, however, the camera does not recognise the 'hiro' marker.

Has anyone faced a similar issue? I went through the closed/open issues but unfortunately I could not find a solution to this.

<template>
<html>
<script src="https://aframe.io/releases/1.0.0/aframe.min.js"></script>
<script src="https://raw.githack.com/jeromeetienne/AR.js/1.7.5/aframe/build/aframe-ar.js"></script>
  <body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs>
  	<a-marker preset="hiro">
            <a-box position='0 0.5 0' material='color: yellow;'></a-box>
  	</a-marker>
  	<a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
</template>

**Comment by nicolocarpignoli** [comment]
please write on this one, about integration with JS framework: https://github.com/AR-js-org/AR.js/issues/17

**Comment by marcoiai** [comment]
> Hey!
> 
> I love this plugin that I have tried on CodePen.
> 
> I'd love to implement it on my Vue.js project, and after a number of attempts, the camera seems to be working fine, however, the camera does not recognise the 'hiro' marker.
> 
> Has anyone faced a similar issue? I went through the closed/open issues but unfortunately I could not find a solution to this.
> 
> <script src="https://aframe.io/releases/1.0.0/aframe.min.js"></script> <script src="https://raw.githack.com/jeromeetienne/AR.js/1.7.5/aframe/build/aframe-ar.js"></script>

how did you write it?
