### ISSUE TITLE
Shifted Content on change of device orientation

### ISSUE THREAD

**Issue by Jeggle-s** [jeromeetienne/AR.js#749]
**Describe the bug**
I'm using a custom marker with A-FRAME. If i'm using my phone (Android) in portrait mode the content (e.g. a box) is displayed in the correct position. As soon as i switch to landscape, the content is a bit off. This also happens on an iPad with iOS but in this case, the content appears to be shifted in portrait mode and is correct in landscape.
Even after realoding the page in the orientation where the content is shifted, the content remains shifted.

**To Reproduce**
1. Implement a box with A-Frame
2. Place the box in the coordinates '1 0 0'
3. Run the website in Chrome for Android or Safari for iOS
4. Use it in potrait mode and switch to landscape mode vice versa
5. Reload the page in that mode, in which the content is shifted

**Expected behavior**
The content is in the exaxt same position, no matter if the mobile device is in landscape or portrait mode.

**Screenshots**
<img src="https://user-images.githubusercontent.com/38358202/75547447-2b040a00-5a2b-11ea-988a-e3cc569c2b29.jpg " width="250">
<img src="https://user-images.githubusercontent.com/38358202/75547478-40793400-5a2b-11ea-9c2f-b72ab43aa745.jpg " width="250">

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A3 2017/iPad]
 - OS: [Android O/iOS (latest)]
 - Browser [Chrome/Safari]
 - Version [each latest]

**Additional context**
The first Screenshot is in landscape and the wrong position. Second one is the correct position.

Relevant Code: 

```
<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;' id="page">
<a-marker handletouch size="0.28" smooth="true" emitevents="true" type='pattern' preset="custom" url="./src/go-patt.patt" id="code">
    <a-entity geometry="primitive: box; width: 1; height: 1"
              position="1 0 0"
              material="color: blue"
    ></a-entity>
</a-marker>
  <a-entity camera></a-entity>
</a-scene>

```

**Comment by nicolocarpignoli** [comment]
Closing this issue due to dismission of this repository. New repository of AR.js will be up at https://github.com/AR-js-org/AR.js/

Feel free to re-open the issue there if still valid.
