### ISSUE TITLE
Basic setup not working

### ISSUE THREAD

**Issue by ddesmond** [jeromeetienne/AR.js#753]
Hi,
ive been following lots of guides, but those seem to be outdated.
Adding box as a cube works fine, but as i add obj it gives me headache. The object is loading, but i just cant make it work. Any hint is golden!
Can someone help me out with this basic example? idk where to look anymore.
Thanks!

https://ddesmond.github.io/theatre-ar/
@nicolocarpignoli 

iphone 6, safari

**Comment by ddesmond** [comment]
update:
it seems there is a problem with test model. replacing it from another source seems working as expected.

**Comment by kalwalt** [comment]
@ddesmond The model is in the scene but you need to adjust the position. Also note that we are moving to the new repo here https://github.com/AR-js-org/AR.js this repo will not updated anymore.
