### ISSUE TITLE
documentation website for ar.js with Docusaurus.io

### ISSUE THREAD

**Issue by spartalisdigital** [jeromeetienne/AR.js#754]
**Is your feature request related to a problem? Please describe.**
Currently, the ar.js documentation is only available on github. Github has an unfriendly interface.

**Describe the solution you'd like**
Create a documentation site separate from the github page. Thus having a better visualization and presentation of the library for new users. For example, a-Frame that has its own website and a page on github.

Site:
a-frame.io

Github page:
https://github.com/aframevr/aframe

**Describe alternatives you've considered**
there are tools that help in the creation of documentation pages.
how:
https://docsify.js.org/#/
https://docusaurus.io/

**Additional context**
I believe that we can use docusaurus.io to solve this problem and make the AR.js documentation more accessible and presentable.
From what I've seen, docusaurus has been used by several successful frameworks.

I hope it was clear! I have difficulties with English.

**Comment by kalwalt** [comment]
Hi @spartalisdigital thank you for the ideas! We are moving to a new organization https://github.com/AR-js-org/AR.js Please may we continue the discussion [here](https://github.com/AR-js-org/AR.js/issues)?

**Comment by nicolocarpignoli** [comment]
Yes please open an issue on the new repository linked above. Thank you (nice idea btw)
