### ISSUE TITLE
View width and height not correct. But if you resize it gets fixed.

### ISSUE THREAD

**Issue by max-koa** [jeromeetienne/AR.js#755]
**Do you want to request a *feature* or report a *bug*?**
Possible bug

**What is the current behavior?**
Sometimes, not always, when I open in the browser, the camera view will be small. If I open and close the console, then it will cover the whole browser (as it was supposed to). A small fix that works some times, is to set a timer, around 2 seconds, and resize after the 2 seconds.

**If the current behavior is a bug, please provide the steps to reproduce.**
I am using wamp as a server. By opening the browser it happens.

**What is the expected behavior?**
It is expected that the camera view will be the size of the complete view width and height from the beginning.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Chrome Version 80.0.3987.132
Windows 10.
Also tried in Mozilla latest version and it happens the same.

**Comment by nicolocarpignoli** [comment]
thanks for opening. can you please open here? https://github.com/AR-js-org/AR.js/issues

see the readme :)
