### ISSUE TITLE
Mouse click/touch on object not working with Aframe 1.0.0 (working with 0.8.0)

### ISSUE THREAD

**Issue by yannklein** [jeromeetienne/AR.js#756]
**Describe the bug**

Mouse click/touch on object using `<a-marker preset="hiro" cursor='rayOrigin: mouse;'>` was working okay with aframe v.0.8.0 as we can see it in [this simple example](https://github.com/yannklein/aframe-ar-workshop/blob/master/steps/Step-4%20Links%20and%20video%20with%20AR.html)

With aframe v1.0.0 it doesn't work anymore. 
You can try to replace: `<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>` 
by `<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>`
in the script above to test it.

Tested on Laptop (Mac) with Chrome/Firefox and Mobile (iPhone), with Safari.

[Edit] I gave a try to aframe v0.9.0: despite the fact that it doesn't work on Mac Chrome for non-related bug reasons, the click works on Firefox. I am investigating further...

**Comment by kalwalt** [comment]
Hi @yannklein we are moving to the new [Ar.js org](https://github.com/AR-js-org/AR.js) may we discuss this on the [issue tracker](https://github.com/AR-js-org/AR.js/issues) there? Thank you! :slightly_smiling_face:

**Comment by nicolocarpignoli** [comment]
thanks for opening. can you please open here? https://github.com/AR-js-org/AR.js/issues

see the readme :)
