### ISSUE TITLE
Need to implement AR for online apparel website

### ISSUE THREAD

**Issue by amalraj2** [jeromeetienne/AR.js#757]
I need to implement AR feature for my apparel website. It is not available as a mobile app,but only web application. User need to try the apparels using AR. Can it be possible using AR.js

**Comment by karanganesan** [comment]
@amalraj2 

the project has been moved to a new place
https://github.com/AR-js-org/AR.js/issues

please post the issue there

**Comment by nicolocarpignoli** [comment]
please open issue here: https://github.com/AR-js-org/AR.js/
this repo is deprecated
