### ISSUE TITLE
3D objects on markers

### ISSUE THREAD

**Issue by oninross** [jeromeetienne/AR.js#758]
**To Reproduce**
Since the upgrade of aframe to 1.0.4, the 3D objects that are being projected on the marker are off center and does not behave as expected.  See screenshot below: 
![Screen_Shot_2020-04-07_at_3_38_43_pm__2_](https://user-images.githubusercontent.com/2233813/78633997-41cd3480-78e6-11ea-9398-8118a3877779.png)

**Expected behavior**
The screenshot below says it all
![Screen_Shot_2020-04-07_at_3_42_40_pm__2_](https://user-images.githubusercontent.com/2233813/78634112-8a84ed80-78e6-11ea-9185-7d03966e976a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Chrome Version 80.0.3987.149 

**Additional context**
It would be nice just to use 1 version of the plugin and not 2 different versions.  I have a small project that uses AR markers and AR Geolocation

**Comment by nicolocarpignoli** [comment]
please open issue here: https://github.com/AR-js-org/AR.js/
this repo is deprecated
