### ISSUE TITLE
AR with Two custom Markers doesn't work

### ISSUE THREAD

**Issue by GaT11** [jeromeetienne/AR.js#759]
Hello, can one of you help me?
When I try to use two or more different pattern my code doesn't work because by both of the pattern the red cube appears and not by one of the pattern the green one and by the other the red one. 

This is my code (without the right url):
 
<body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs="sourceType: webcam;">

        <a-box color="green"></a-box>
  

        <a-marker-camera  preset="custom" type="pattern"
            url="....patt">
        </a-marker-camera>

        <a-box color="red"></a-box>
        <a-marker-camera preset="custom" type="pattern"
            url="...patt">
        </a-marker-camera>
    </a-scene>

**Comment by nicolocarpignoli** [comment]
Please, open your issues on https://github.com/AR-js-org/AR.js
This repo is deprecated. Also for troubleshooting, you should use https://gitter.im/AR-js/Lobby
