### ISSUE TITLE
Multiple markers implementation

### ISSUE THREAD

**Issue by curtello** [jeromeetienne/AR.js#76]
How can I render different meshes for different markers in the same scene

**Comment by jeromeetienne** [comment]
yes, it is fully supported, look at the independant marker examples. i hope this helps.


https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/measure-it.html

https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/multiple-independant-markers.html

**Comment by curtello** [comment]
Is it possible to DRY the process of adding newer markers?
Because if I have like 50 markers, that will take me a while

**Comment by jeromeetienne** [comment]
sorry i dont understand. what 'to dry' means ?

**Comment by curtello** [comment]
**D**on't **R**epeat **Y**ourself (DRY) . I mean... Is there a non repetitive method for implementing multiple markers in the js file.Maybe by making the marker an object with new prototype functions... like abstract classes in Java

**Comment by jeromeetienne** [comment]
sorry i dont understand what you want to do

**Comment by curtello** [comment]
I want to use about 70 markers and I wanted to know if there's a less repetitive way of making these `markerroot` variables as compared to writing markerroot1, markerroot2 .... markerroot(n)

**Comment by Angelo8828** [comment]
Hello @jeromeetienne, the second link is not working (https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/multiple-independant-markers.html), is there another example for this implementation? Thanks!

**Comment by jeromeetienne** [comment]
https://github.com/jeromeetienne/AR.js/blob/master/aframe/examples/multiple-independent-markers.html

here is the correct link

**Comment by Angelo8828** [comment]
@jeromeetienne, SLR. Thanks for this one!

**Comment by ghonche-yqr** [comment]
hello
i am using ar.js and have defined my own markers like this:
`var markerControls = new THREEx.ArMarkerControls(arToolkitContext, camera, {
          type: 'pattern',
          patternUrl: './my_marker.patt',
          changeMatrixMode: 'cameraTransformMatrix'
      })`

but i want to define more markers and have different augmented reality for each one. can you help me out?? thank you

**Comment by traysiMay** [comment]
@ghonche-yqr 

this link: https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/measure-it.html that jerome commented has your answer

**Comment by ghonche-yqr** [comment]
@traysiMay 
thank you very much. my issue solved.

**Comment by yashank09** [comment]
@hipstermojo were you able to figure it out? Im also trying to use multiple markers and there's no way im manually feeding all the markers. Im thinking of using some algorithm to get the name of image and pass it to jsar but not sure if that's possible.
