### ISSUE TITLE
gltf-modell does not animating 

### ISSUE THREAD

**Issue by GaT11** [jeromeetienne/AR.js#760]
And i have another issue.
My gltf-modell isn't animating like it should but the 3D-Model appears on screen.
Can you please help me an write another Code that works into this Chat?

Here my code:

               <a-entity 
               gltf-model="url(bilder_ar/steve-gltf/scene.gltf)"  
               animation-mixer="clip:Armature.001; loop:2; timeScale: 5; 
               crossFadeDuration: 1">
               </a-entity>

**Comment by nicolocarpignoli** [comment]
Please, open your issues on https://github.com/AR-js-org/AR.js
This repo is deprecated. Also for troubleshooting, you should use https://gitter.im/AR-js/Lobby

**Comment by kalwalt** [comment]
First, for this kind of support,  make a research on this subject on stackoverflow with tag [ar.js](https://stackoverflow.com/questions/tagged/ar.js), if you not find your answer post a question there.

**Comment by GaT11** [comment]
Thanks, I try it!
