### ISSUE TITLE
black screen instead of video screen

### ISSUE THREAD

**Issue by GaT11** [jeromeetienne/AR.js#761]
Hello I have a probleme. When I'll insert a video in Augmented Reality only a black screen appears on the display.
Can you help me, please?

There's my code:
     
    <!doctype HTML>
    <html>
    <script src="https://aframe.io/releases/0.6.1/aframe.min.js"></script>
    <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js">
    </script>

    <body style='margin : 0px; overflow: hidden;'>
        <a-scene embedded arjs>
            <a-marker preset="hiro">
                <a-video position='0 0.1 0' rotation='270 0 0' scale='1 0.5 1' src='/sv.mp4'></a-video>
            </a-marker>
            <a-entity camera></a-entity>
        </a-scene>
    </body>

    </html>
I am just getting a black screen instead of video.

**Comment by nicolocarpignoli** [comment]
Please, open your issues on https://github.com/AR-js-org/AR.js
This repo is deprecated. Also for troubleshooting, you should use https://gitter.im/AR-js/Lobby
