### ISSUE TITLE
Use vertical marker

### ISSUE THREAD

**Issue by taime** [jeromeetienne/AR.js#762]
Some times I want to use marker on the wall, so it would be placed vertically! 
Is it possible to place all objects for this case?
Of course I can rotate the model, but it's not the same. For example I can not use native `look-controls` and any other features!

And also when I have a lot of objects, it would be better to rotate the whole scene, but not every 3d-object...

**Comment by evaristoc** [comment]
Hi @taime the project moved to this new repo: https://github.com/AR-js-org/AR.js

**Comment by bhushanj221** [comment]
<script src="AR.js-master/aframe/build/aframe-ar.js"></script>

this script is missing in new repo also

**Comment by nicolocarpignoli** [comment]
This repo has been migrated. Please re-open here: https://github.com/AR-js-org/AR.js/issues
