### ISSUE TITLE
AR canvas render black color- important

### ISSUE THREAD

**Issue by MG-Development42** [jeromeetienne/AR.js#763]
AR canvas renders black color after importing the dat.gui and stats.min module...

Code:https://github.com/vannanmani42/threejs_arjs/blob/master/index.html
<img width="1680" alt="Screenshot 2020-04-20 at 6 24 44 PM" src="https://user-images.githubusercontent.com/63099808/79763794-27fa0b80-8342-11ea-8426-5065572218c0.png">

<!DOCTYPE html>
<html>
	<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
	<head>
		<title>three.js webgl - skinning and morphing</title>
		
	</head>

	<body>
		
	<script src='https://cors.x7.workers.dev/https://vannanmani42.github.io/threejs_arjs/three.js'></script>
	<script src='https://cors.x7.workers.dev/https://vannanmani42.github.io/threejs_arjs/stats.min.js'></script>
	<script src='https://cors.x7.workers.dev/https://vannanmani42.github.io/threejs_arjs/dat.gui.min.js'></script>
	<script src='https://cors.x7.workers.dev/https://vannanmani42.github.io/threejs_arjs/GLTFLoader.js'></script>
	<script src='https://cors.x7.workers.dev/https://vannanmani42.github.io/threejs_arjs/ar.js'></script>
	<script>

			var container, stats, clock, gui, mixer, actions, activeAction, previousAction;
			var camera, scene, renderer, model, face;
			var arToolkitSource,arToolkitContext;

			var api = { state: 'Walking' };

			init();
			animate();

			function init() {

				//container = document.createElement( 'div' );
				//document.body.appendChild( container );
				
				renderer = new THREE.WebGLRenderer( { 
					antialias: true,
					truealpha: true,
            				precision: 'mediump', } );
				
				renderer.setClearColor(new THREE.Color('lightgrey'), 0)
        			renderer.setSize( window.innerWidth, window.innerHeight );
        			renderer.domElement.style.position = 'absolute'
        			renderer.domElement.style.top = '0px'
        			renderer.domElement.style.left = '0px'
        			document.body.appendChild( renderer.domElement );
				
				

				//window.addEventListener( 'resize1', onWindowResize, false );

				//camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 0.25, 100 );
				//camera.position.set( - 5, 3, 10 );
				//camera.lookAt( new THREE.Vector3( 0, 2, 0 ) );
					
				scene = new THREE.Scene();
				camera = new THREE.Camera();
        			scene.add(camera);
				
				
				//scene.background = new THREE.Color( 0xe0e0e0 );
				//scene.fog = new THREE.Fog( 0xe0e0e0, 20, 100 );

				clock = new THREE.Clock();

				// lights

				//var light = new THREE.HemisphereLight( 0xffffff, 0x444444 );
				//light.position.set( 0, 20, 0 );
				//scene.add( light );

				//light = new THREE.DirectionalLight( 0xffffff );
				//light.position.set( 0, 20, 10 );
				//scene.add( light );

			 light = new THREE.AmbientLight(0xffffff);
        		 scene.add(light);
	////////////////////////////////////////////////////////////////////////////////
        //          handle arToolkitSource
        ////////////////////////////////////////////////////////////////////////////////

         arToolkitSource = new THREEx.ArToolkitSource({
            sourceType : 'webcam',
            sourceWidth: 480,
            sourceHeight: 640,
        })

        arToolkitSource.init(function onReady(){
            // use a resize to fullscreen mobile devices
            setTimeout(function() {
                onResize()
            }, 1000);
        })

        // handle resize
        window.addEventListener('resize', function(){
            onResize()
        })

        function onResize(){
            arToolkitSource.onResizeElement()
            arToolkitSource.copyElementSizeTo(renderer.domElement)
            if( arToolkitContext.arController !== null ){
                arToolkitSource.copyElementSizeTo(arToolkitContext.arController.canvas)
            }
        }

        ////////////////////////////////////////////////////////////////////////////////
        //          initialize arToolkitContext
        ////////////////////////////////////////////////////////////////////////////////

        // create atToolkitContext
        arToolkitContext = new THREEx.ArToolkitContext({
            detectionMode: 'mono',
            canvasWidth: 480,
            canvasHeight: 640,
        }, {
            sourceWidth: 480,
            sourceHeight: 640,
        })

        // initialize it
        arToolkitContext.init(function onCompleted(){
            // copy projection matrix to camera
            camera.projectionMatrix.copy( arToolkitContext.getProjectionMatrix() );
        })

        ////////////////////////////////////////////////////////////////////////////////
        //          Create a ArMarkerControls
        ////////////////////////////////////////////////////////////////////////////////

        // init controls for camera
        var markerControls = new THREEx.ArMarkerControls(arToolkitContext, camera, {
           type : 'pattern',
		patternUrl : 'https://cors.x7.workers.dev/https://vannanmani42.github.io/threejs_arjs/testbosch.patt',
		// patternUrl : THREEx.ArToolkitContext.baseURL + '../data/data/patt.kanji',
		// as we controls the camera, set changeMatrixMode: 'cameraTransformMatrix'
		changeMatrixMode: 'cameraTransformMatrix'
	})

        scene.visible = false
				// ground

				//var mesh = new THREE.Mesh( new THREE.PlaneBufferGeometry( 2000, 2000 ), new THREE.MeshPhongMaterial( { color: 0x999999, depthWrite: false } ) );
				//mesh.rotation.x = - Math.PI / 2;
				//scene.add( mesh );

				//var grid = new THREE.GridHelper( 200, 40, 0x000000, 0x000000 );
				//grid.material.opacity = 0.2;
				//grid.material.transparent = true;
				//scene.add( grid );

				// model

				var loader = new THREE.GLTFLoader();
				loader.load( 'https://cors.x7.workers.dev/https://vannanmani42.github.io/threejs_arjs/RobotExpressive.glb', function ( gltf ) {

					model = gltf.scene;
					
					model.position.z = 0;
            				model.position.x = 0;
            				model.position.y = 0;
	    				model.scale.set(1,1,1);
					
					scene.add( model );

					createGUI( model, gltf.animations );

				}, undefined, function ( e ) {

					console.error( e );

				} );

				

				// stats
				stats = new Stats();
				document.body.appendChild( stats.domElement );

			}

			function createGUI( model, animations ) {

				var states = [ 'Idle', 'Walking', 'Running', 'Dance', 'Death', 'Sitting', 'Standing' ];
				var emotes = [ 'Jump', 'Yes', 'No', 'Wave', 'Punch', 'ThumbsUp' ];

				gui = new dat.GUI();

				mixer = new THREE.AnimationMixer( model );

				actions = {};

				for ( var i = 0; i < animations.length; i ++ ) {

					var clip = animations[ i ];
					var action = mixer.clipAction( clip );
					actions[ clip.name ] = action;

					if ( emotes.indexOf( clip.name ) >= 0 || states.indexOf( clip.name ) >= 4 ) {

						action.clampWhenFinished = true;
						action.loop = THREE.LoopOnce;

					}

				}

				// states

				var statesFolder = gui.addFolder( 'States' );

				var clipCtrl = statesFolder.add( api, 'state' ).options( states );

				clipCtrl.onChange( function () {

					fadeToAction( api.state, 0.5 );

				} );

				statesFolder.open();

				// emotes

				var emoteFolder = gui.addFolder( 'Emotes' );

				function createEmoteCallback( name ) {

					api[ name ] = function () {

						fadeToAction( name, 0.2 );

						mixer.addEventListener( 'finished', restoreState );

					};

					emoteFolder.add( api, name );

				}

				function restoreState() {

					mixer.removeEventListener( 'finished', restoreState );

					fadeToAction( api.state, 0.2 );

				}

				for ( var i = 0; i < emotes.length; i ++ ) {

					createEmoteCallback( emotes[ i ] );

				}

				emoteFolder.open();

				// expressions

				face = model.getObjectByName( 'Head_2' );

				var expressions = Object.keys( face.morphTargetDictionary );
				var expressionFolder = gui.addFolder( 'Expressions' );

				for ( var i = 0; i < expressions.length; i ++ ) {

					expressionFolder.add( face.morphTargetInfluences, i, 0, 1, 0.01 ).name( expressions[ i ] );

				}

				activeAction = actions[ 'Walking' ];
				activeAction.play();

				expressionFolder.open();

			}

			function fadeToAction( name, duration ) {

				previousAction = activeAction;
				activeAction = actions[ name ];

				if ( previousAction !== activeAction ) {

					previousAction.fadeOut( duration );

				}

				activeAction
					.reset()
					.setEffectiveTimeScale( 1 )
					.setEffectiveWeight( 1 )
					.fadeIn( duration )
					.play();

			}

			//function onWindowResize() {

				//camera.aspect = window.innerWidth / window.innerHeight;
				//camera.updateProjectionMatrix();

				//renderer.setSize( window.innerWidth, window.innerHeight );

			//}

			//

			function animate() {

				var dt = clock.getDelta();

				if ( mixer ) mixer.update( dt );

				requestAnimationFrame( animate );
				
				if (!arToolkitSource.ready) {
                    		return;
                		}

               			 arToolkitContext.update( arToolkitSource.domElement )

              			  // update scene.visible if the marker is seen
              			  scene.visible = camera.visible;

				renderer.render( scene, camera );

				stats.update();

			}

		</script>

	</body>
</html>

**Comment by nicolocarpignoli** [comment]
This repo has been migrated. Please re-open here: https://github.com/AR-js-org/AR.js/issues
