### ISSUE TITLE
Image Descriptors or NFT data loaded event

### ISSUE THREAD

**Issue by codeisindna** [jeromeetienne/AR.js#764]
Any custom event is there for completion of the loading of NFT data?, the camera-init custom event will fire when the camera is initialized, but there is no event when loading of NFT data is complete.
In colsole I can see "**d40fd298-7299-42a3-910e-48f6310d242f:5 [info] Loading of NFT data complete**" but how to listen for this event using javascript?

**Features to be added**
We want some custom event that will fire when the loading of NFT data is completed.

**Comment by kalwalt** [comment]
Hi @codeisindna this repository is outdated, please repost you issue at the new repository [issue tracker](https://github.com/AR-js-org/AR.js/issue) and close this one, I will happy to answer there...Thank you! :slightly_smiling_face:

**Comment by codeisindna** [comment]
Ok sure, thank you for your replay
