### ISSUE TITLE
Problem with ar.js location based in angular

### ISSUE THREAD

**Issue by gemece** [jeromeetienne/AR.js#765]
**Describe the bug**
i'm trying to use ar.js location based in angular but it doesn t appear the marker in the gps position. i dont know which is the problem.

**To Reproduce**
1. I had created a new project angular
2. I installed libraries aframe with npm "npm install aframe"
3. I imported the libraries in index.html
4. In the file polyfills.ts i imported aframe;
5. In src/app/app.component.html i put the code

**Expected behavior**
I hope the marker appears in the gps position but the marker doesn t appear

**Screenshots**
This is index.html:
![indexhtml](https://user-images.githubusercontent.com/30463151/80832177-6e762280-8bec-11ea-9322-e2f9ebf05cfd.png)

This is app.component.html:
![appcomponenthtml](https://user-images.githubusercontent.com/30463151/80832247-95ccef80-8bec-11ea-9745-dadd90b964d8.png)

This is module.ts:
![modulets](https://user-images.githubusercontent.com/30463151/80832277-a3827500-8bec-11ea-81f5-09d0e38b5deb.png)

This is pollyfils.ts
![pollyfilsts](https://user-images.githubusercontent.com/30463151/80832299-ad0bdd00-8bec-11ea-9f4e-c44646ea6834.png)

**Additional context**
I hope somebody can help me please. Thanks for the help. I dont know why  this doesn't works. i'm looking for information on internet but i didn't find anything.

**Comment by kalwalt** [comment]
We moved to a new org https://github.com/AR-js-org/AR.js, this repository is deprecated and will not receive other updates and support. If you can, Please re-post your issue at  https://github.com/AR-js-org/AR.js/issues and close this one.
