### ISSUE TITLE
Help with redirect to a certain URL

### ISSUE THREAD

**Issue by agora-futura** [jeromeetienne/AR.js#766]
hi
i'm new to ar.js and i can't use redirect to a certain URL on static code
This is my code
`window.onload = () => {

    // if you want to statically add places, de-comment following line
    method = 'static';
    if (method === 'static') {
        let places = staticLoadPlaces();
        renderPlaces(places);
    }

    if (method !== 'static') {
        // first get current user location
        return navigator.geolocation.getCurrentPosition(function (position) {

            // than use it to load from remote APIs some places nearby
            dynamicLoadPlaces(position.coords)
                .then((places) => {
                    renderPlaces(places);
                })
        },
            (err) => console.error('Error in retrieving position', err),
            {
                enableHighAccuracy: true,
                maximumAge: 0,
                timeout: 27000,
            }
        );
    }
};

function staticLoadPlaces() {
    return [
        {
            name: "Teatro Blu",
            location: {
                lat: 45.497591, // add here latitude if using static data
                lng: 9.200883, // add here longitude if using static data
            },
			src: "./imgpoi/ristorante.png"
        },
        {
            name: 'Martesana',
            location: {
                lat: 45.496564,
                lng: 9.201103,
            },
			src: "./imgpoi/venini.png"
        },
        {
            name: 'Gelateria Artigianale',
            location: {
                lat: 45.448992,
                lng: 9.206862,
            },
			src: "./imgpoi/gelateria.jpg"
        }
    ];
}

function renderPlaces(places) {
    let scene = document.querySelector('a-scene');

    places.forEach((place) => {
        const latitude = place.location.lat;
        const longitude = place.location.lng;

        // add place icon
        const icon = document.createElement('a-image');
        icon.setAttribute('gps-entity-place', `latitude: ${latitude}; longitude: ${longitude}`);
        icon.setAttribute('name', place.name);
        icon.setAttribute('src', place.src);

        // for debug purposes, just show in a bigger scale, otherwise I have to personally go on places...
        icon.setAttribute('scale', '20, 20');

        icon.addEventListener('loaded', () => window.dispatchEvent(new CustomEvent('gps-entity-place-loaded')));

        const clickListener = function (ev) {
            ev.stopPropagation();
            ev.preventDefault();

            const name = ev.target.getAttribute('name');

            const el = ev.detail.intersection && ev.detail.intersection.object.el;

            if (el && el === ev.target) {
                const label = document.createElement('span');
                const container = document.createElement('div');
                container.setAttribute('id', 'place-label');
                label.innerText = name;
                container.appendChild(label);
                document.body.appendChild(container);

                setTimeout(() => {
                    container.parentElement.removeChild(container);
                }, 1500);
            }
        };

        icon.addEventListener('click', clickListener);

        scene.appendChild(icon);
    });
}
`

I have looked for some examples but I have not found.
Can anyone help me?
Thanks

**Comment by nicolocarpignoli** [comment]
This repo has been migrated. Please re-open here: https://github.com/AR-js-org/AR.js/issues
