### ISSUE TITLE
dynamic-body doesnt work

### ISSUE THREAD

**Issue by ventoline** [jeromeetienne/AR.js#767]
@nicolocarpignoli  I am trying  to apply gravity to objects. Whenever I assign a dynamic-body the object disappears
 I tried as well with  the ammo driver to no avail.
 see here: https://www.inalgorithmwetrust.com/MAMA/index

**Comment by nicolocarpignoli** [comment]
This repo has been migrated. Please re-open here: https://github.com/AR-js-org/AR.js/issues
