### ISSUE TITLE
Camera not opening in ios and android both

### ISSUE THREAD

**Issue by atulgupta13** [jeromeetienne/AR.js#768]
Works fine on the laptop browser but when tried to run it on phones IOS and Android both it is showing error
**WebRTC issue-! navigator.mediaDevices not present in your browser**

**Devices used: iPhone X, iPhone 7, OnePlus 7
Browser: Safari, Chrome**
![IMG_512753E3A8F9-1](https://user-images.githubusercontent.com/65738108/82608292-02c61a80-9bd8-11ea-85c4-49e4c94c9132.jpeg)
![WhatsApp Image 2020-05-21 at 1 43 01 PM](https://user-images.githubusercontent.com/65738108/82608329-11accd00-9bd8-11ea-9ce7-6bfdf4281dd0.jpeg)

**Comment by kalwalt** [comment]
Which version are you using? Consider also that we moved to a new GitHub org. https://github.com/ar-js-org/AR.js this repository Is not mantained anymore.

**Comment by atulgupta13** [comment]
Tried both the repos bt still having same camera issue

**Comment by jeffrey-lunaon** [comment]
Hi, I guss this is not a https service, we can open the camera only https.

**Comment by nicolocarpignoli** [comment]
This repo has been migrated. Please re-open here: https://github.com/AR-js-org/AR.js/issues
