### ISSUE TITLE
Ipad does not work correctly

### ISSUE THREAD

**Issue by Teityan** [jeromeetienne/AR.js#769]
**Describe the bug**

**To Reproduce**
https://ar-js-org.github.io/AR.js-Docs/#requirements
I used this sample, but it doesn't work.
The model appears to be successfully loaded, but there is no error log.

**Smartphone (please complete the following information):**
 - Device:Ipad(gen6)
 - OS: IOS13.5(IpadOS13)
 - Browser:safari

**Comment by kalwalt** [comment]
,@Teityan please close this and re-post the issue on the AR-js-org repository. Thank you. 🙂

**Comment by Teityan** [comment]
Excuse me.
Thank you.
