### ISSUE TITLE
Did the AR.js can do markerless tracing?

### ISSUE THREAD

**Issue by segatecm** [jeromeetienne/AR.js#77]
Such as take a picture, use the picture as a marker. Then open the camera, tracing the picture center position and draw same 3D stuff on it ?

**Comment by jeromeetienne** [comment]
unfortuntatly not :( AR.js doesnt support image based marker at the moment

**Comment by segatecm** [comment]
Hi  jeromeetienne, thank you. 
Perhaps you can give me some advice to do this with AR.js!
