### ISSUE TITLE
Link to Marker Training Docs does not work

### ISSUE THREAD

**Issue by jrDev1** [jeromeetienne/AR.js#770]
**Describe the bug**
Clicking link to get info on Marker Training gives error
**To Reproduce**
1. Go to 'https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training'
2. See error

**Expected behavior**
Take to page with the info
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Macbook
 - Browser: Safari

**Comment by nicolocarpignoli** [comment]
This repo has been migrated. Please re-open here: https://github.com/AR-js-org/AR.js/issues
