### ISSUE TITLE
readme.md references need updating

### ISSUE THREAD

**Issue by WazzaMo** [jeromeetienne/AR.js#774]
# Problem
References to jsartoolkit no longer help as the project is no longer available on GitHub.

# To Reproduce
Click links in slides or readme.md for jsartoolkit and watch GitHub cry 404

# Expected behavior
See useful information

# Screenshots
Not needed - I won't bore you with a 404 screenshot.

**Comment by nicolocarpignoli** [comment]
Repo has been moved. Please open issue here: https://github.com/AR-js-org/AR.js/issues
