### ISSUE TITLE
Plane detection/tracking similar to ARCore

### ISSUE THREAD

**Issue by whatisor** [jeromeetienne/AR.js#775]
**Is your feature request related to a problem? Please describe.**
Markerless AR is very important for user. Detecting and tracking plane such as floor, wall,... is very usefull to develop markless AR application.
Please refer to ARCore as reference

**Describe the solution you'd like**
https://iopscience.iop.org/article/10.1088/1742-6596/1566/1/012018/pdf

**Describe alternatives you've considered**
NA

**Additional context**
Mobile device

**Comment by nicolocarpignoli** [comment]
Repo has been moved. Please open issue here: https://github.com/AR-js-org/AR.js/issues
