### ISSUE TITLE
AR.js Slam or markerless

### ISSUE THREAD

**Issue by ourbuziness** [jeromeetienne/AR.js#777]
I have reviewed many issues or feature requests , and followed your progress on documenting and adding slam feature in your trello . but no where found any solutions for this .
Is this feature ( slam ) or markerless tracking developed and usable in AR.js ?

thank you very much for your supporting

**Comment by bonisaputra** [comment]
you can use goelocation tracking AR.js
or just show the object according to your scale and position

``

**Comment by nicolocarpignoli** [comment]
Repo has been moved. Please open issue here: https://github.com/AR-js-org/AR.js/issues
