### ISSUE TITLE
Video not playing on iOS safari 

### ISSUE THREAD

**Issue by Gaurav-chopra** [jeromeetienne/AR.js#778]
The video plays on android but doesn't play in iOS safari. It just display a single paused screen. Below is my code:
(All i need is to autoplay video with audio on both android and iOS. On android it is working perfect!)
`<!doctype html>
<html>
    <head>
        <meta name="apple-mobile-web-app-capable" content="yes">
        <script src="scripts/play-on-window-click.js"></script>
        <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
        <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>
        <script src="https://raw.githack.com/AR-js-org/studio-backend/master/src/modules/marker/tools/gesture-detector.js"></script>
        <script src="https://raw.githack.com/AR-js-org/studio-backend/master/src/modules/marker/tools/gesture-handler.js"></script>
        <script>
            AFRAME.registerComponent('videohandler', {
                init: function () {
                    var marker = this.el;
                    this.vid = document.querySelector("#vid");

                    marker.addEventListener('markerFound', function () {
                        this.toggle = true;
                        this.vid.play();
                    }.bind(this));

                    marker.addEventListener('markerLost', function () {
                        this.toggle = false;
                        this.vid.pause();
                    }.bind(this));
                },
            });
        </script>
    </head>

    <body style="margin: 0; overflow: hidden;">
        <a-scene
            vr-mode-ui="enabled: false"
            loading-screen="enabled: false;"
            arjs='sourceType: webcam; debugUIEnabled: false;'
            id="scene"
            embedded
            gesture-detector
        >
            <a-assets>
                <video
                    id="vid"
                    src="assets/asset.mp4"
                    preload="auto"
                    response-type="arraybuffer"
                    loop
                    
                    crossorigin
                    autoplay
                    webkit-playsinline
                    playsinline
                ></video>
            </a-assets>

            <a-marker
                type="pattern"
                preset="custom"
                url="assets/marker.patt"
                videohandler
                smooth="true"
                smoothCount="10"
                smoothTolerance="0.01"
                smoothThreshold="5"
                raycaster="objects: .clickable"
                emitevents="true"
                cursor="fuse: false; rayOrigin: mouse;"
                id="markerA"
            >
                
                <a-video play-on-window-click src="#vid" scale="5 5 5" rotation="90 180 0" position="0 0 0" material="" geometry="" gesture-handler></a-video>
                
                
            </a-marker>

            <a-entity camera></a-entity>
        </a-scene>
    </body>
</html>
`

**Comment by mttetc** [comment]
I have the same issue with an image, not working on iOS

**Comment by anilachary** [comment]
According to the latest policies we cant autoplay a video without muting . If you want to make the video auto play then you need to enable mute by default or else you need to enable hand geusture on touch or on hover events to enabel autoplay with audio.
