### ISSUE TITLE
How can i make marker without border, please?

### ISSUE THREAD

**Issue by rifatwahid** [jeromeetienne/AR.js#795]
How can i make marker without border, please?

**Comment by jrDev1** [comment]
Unless you are talking about an Image Marker, you can't.

**Comment by rifatwahid** [comment]
I want to use the simple "Image Tracking", I saw in the "AR.js Marker Training" creates marker with border. I just need to create market without border, that's it.

is it possible, please?

**Comment by nicolocarpignoli** [comment]
Please, open issue in the new repository, this one is not maintained anymore. You can find references on the readme.

**Comment by kalwalt** [comment]
Please for this kind of questions use the [help discussions board](https://github.com/AR-js-org/AR.js/discussions/categories/help)
