### ISSUE TITLE
AR.JS (A Frame) not working on Chrome Mobile - WebRTC Issue

### ISSUE THREAD

**Issue by spikethea** [jeromeetienne/AR.js#796]
My problem is that the AR.js example I'm running doesn't work on my Pixel 3a. I have it running on a node express server, and it works on Chrome Desktop through both localhost:3000 and 192.168.1.70:3000.

But every time I access it on Chrome Mobile I get the error:

'Webcam Error
Name:
Message: WebRTC issue-!
navigator.mediaDevices not present in your browser'

I did try to load the page through https as reccomended but it says "This site cant provide a secure connection", apparently that also requires a SSL certificate too when this is just simply dev testing? Hopefully someone who also had this issue may be able to help me out.

 - Device: Google Pixel 3a
 - OS: Android 11
 - Browser: Chrome Mobile
 - Version: 91.0.4472.120

**Comment by Radlad-io** [comment]
@spikethea I'm really new to AR.JS & A-Frame but I'm pretty sure WebRTC requires SSL / TLS encryption to work. Did you setup SSL locally with your node server?

I'm pretty sure Github Pages offers free SSL hosting for static pages ( https://pages.github.com/ ). Having said that its a terrible developer experience having to push changes to a remote server to test on the main platform. I'm wondering if someone else has figured out a better workaround. 8th Wall seems to provide a much better developer experience at a very hefty price tag.

**Comment by spikethea** [comment]
upon further inspection, it does seem like I do need SSL, and can use OpenSSL to get a ticket. thanks @radlad-io
