### ISSUE TITLE
maxDistance not working?

### ISSUE THREAD

**Issue by everythingability** [jeromeetienne/AR.js#797]
Hello,

I am trying to load a list of points but only display the ones about 5 to 10m away. I have 20-ish points and they are all displaying, some a good few 100m away.

I have a Glitch project:
 [here](https://glitch.com/edit/#!/gps-based-ar?path=index.html%3A50%3A32)
Viewable here:
https://gps-based-ar.glitch.me/

...but the part I suspect I may be getting wrong is setting the camera settings...

`  <a-camera id="camera1"            
               arjs-look-controls="smoothingFactor: 0.05;"
               gps-camera="maxDistance:5;"
               gpsMinDistance="4"
               maxDistance="5"
               positionMinAccuracy="5"
               far="10"
               near="0.5"
               rotation-reader> `

Do I add maxDistance to the gps-camera, as above or as an attribute of a-camera (slightly below that) or am I doing something else wrong? I also tried using the far/near/fov controls on the camera AND the a-scene... 

Do I have to poll each point, get its distance, and then show/hide it? That seems a lot of work when I suspect this does it for me.

Thank you for any help.

Tom
p.s the Inspector is loaded if anyone wants to take a look...

Sometimes, my "Hello World" panel doesn't load, sometimes it does. This may be related.

**Comment by nicolocarpignoli** [comment]
Please, read the README before opening pull requests. This repo is not maintained anymore. Please open issues on the new repository: https://github.com/AR-js-org/AR.js. Thank you!
