### ISSUE TITLE
Attribute value disappearing

### ISSUE THREAD

**Issue by DevDom05** [jeromeetienne/AR.js#799]
I try the examples and the attribute value disappear

For example =  `<a-box material="color: red;" scale="300 300 300" position="0 0 0" gps-entity-place="latitude: 47.8483622; longitude: 2.7739893;"></a-box>`

became 
`<a-box material="" scale="" position="" gps-entity-place="" geometry=""></a-box>`
after the page loading

**Comment by nicolocarpignoli** [comment]
Please, read the README before opening pull requests. This repo is not maintained anymore. Please open issues on the new repository: https://github.com/AR-js-org/AR.js. Thank you!
