### ISSUE TITLE
Marker Generator.

### ISSUE THREAD

**Issue by curtello** [jeromeetienne/AR.js#80]
Is it possible to make an .exe of the marker generator?

**Comment by kevinkraus92** [comment]
You can use http://flashplayer.fullstacks.net/ with http://flash.tarotaro.org/blog/2009/07/12/mgo2/comment-page-1/ 
It does not work for loading img but recording the pattern from the webcam works ok

**Comment by jeromeetienne** [comment]
HEre is the url for the marker-training

https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html

It is a bunch of static file in a webpage. So you can build an exe out of it with electron https://electron.atom.io

Im not sure i understand why it may be usefull to build an .exe tho, can you elaborate onyour particular use case ?

**Comment by curtello** [comment]
I wanted to train markers on a very regular basis and it requires internet to upload pictures and download .patt files. So I was just wondering if I could get an .exe so that the process can be more autonomous. But it's fine
