### ISSUE TITLE
Camera zoomed in on HUWEI MATE 40 PRO And MATE30

### ISSUE THREAD

**Issue by zmc1212** [jeromeetienne/AR.js#801]
**Describe the bug**
When the camera is opened on Huawei mate 40 pro and mate 30, it will be enlarged

**To Reproduce**
<a-camera gps-camera rotation-reader></a-camera>

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/29799586/148336556-76801b17-00ce-4955-9680-bc34a508ec61.png)

**Smartphone (please complete the following information):**
 - Device:  HUWEI MATE 40 PRO And MATE30
 - OS: HarmonyOS 2.0.0

**Additional context**

**Comment by popkingcorn** [comment]
I fixed it by adding 
`<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">`
to my html file

**Comment by ZephyrAndMoon** [comment]
> I fixed it by adding `<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">` to my html file

it doesn't work

**Comment by nicolocarpignoli** [comment]
Please, read the README before opening pull requests. This repo is not maintained anymore. Please open issues on the new repository: https://github.com/AR-js-org/AR.js. Thank you!
