### ISSUE TITLE
What's the diffenence between image tracking and marker tracking?

### ISSUE THREAD

**Issue by wxdut** [jeromeetienne/AR.js#802]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nicolocarpignoli** [comment]
Please, read the README before opening pull requests. This repo is not maintained anymore. Please open issues on the new repository: https://github.com/AR-js-org/AR.js. Thank you!
