### ISSUE TITLE
Marker Based ArJS implementation issue for cross platforms

### ISSUE THREAD

**Issue by abirahsan007** [jeromeetienne/AR.js#804]
So recently i get to know about ARJS. Then i implemented it on one of my website following your github repo.
But I am facing an only issue which is blocking me to deliver this project to my client. The video plays fine on android phones but it doesn't autoplay on iphones. I know this is a very old issue but i could not find any proper documented solutions. 

So this will be very helpful for me and other newbies if you can provide a simple documented solution on how this autoplay issue on ios can be resolved. How i can add user interaction to play the video.

This project is very important for me so please response !

**Comment by sorawitw** [comment]
This may help you
https://github.com/aframevr/aframe/blob/master/examples/test/video/index.html

Live Demo
https://aframe.io/examples/showcase/360-video/

**Comment by nicolocarpignoli** [comment]
Please, read the README before opening pull requests. This repo is not maintained anymore. Please open issues on the new repository: https://github.com/AR-js-org/AR.js. Thank you!
