### ISSUE TITLE
NFT (fset) Data Not Loading

### ISSUE THREAD

**Issue by mehmeterk-computethis** [jeromeetienne/AR.js#807]
Since the relocation of the _aframe-ar-nft.js_ relevant repository, nft data from is not loading.
The warning log which depicts the fset data loading progress is not initiated.
Any nft markers created are not scanable.

This is a universal issue across all platforms and browswers.

Problem seems to be with the _aframe-ar-nft.js_ script.

I've attempted the following solutions with negative results:
- Hosting _aframe-ar-nft.js_ via aws (which is where the active project is located)
- Hosting the example nft project to aws 
- All URL's and directory architecture have been tripple checked 

Further more the example NFT project is also presenting the same issue.

If any one knows a resolve for this issue please post the solution.

**Comment by nicolocarpignoli** [comment]
Please, read the README before opening pull requests. This repo is not maintained anymore. Please open issues on the new repository: https://github.com/AR-js-org/AR.js. Thank you!
