### ISSUE TITLE
Possible to create an ar marker scanner? 

### ISSUE THREAD

**Issue by ecg-code** [jeromeetienne/AR.js#811]
I am currently working on a aframe project and want to enhance UX. 
I am wondering if anyone has created a custom marker reader that enables users to focus their camera on the marker that is supposed to be scanned? Like https://minhazav.medium.com/qr-code-scanner-using-html-and-javascript-3895a0c110cd but for a-marker specifically? 
Looking forward for your help and support !

**Comment by nicolocarpignoli** [comment]
Please, read the README before opening pull requests. This repo is not maintained anymore. Please open issues on the new repository: https://github.com/AR-js-org/AR.js. Thank you!
