### ISSUE TITLE
SLAM, Can it support plane detection?

### ISSUE THREAD

**Issue by kenchikuliu** [jeromeetienne/AR.js#812]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nicolocarpignoli** [comment]
Please, read the README before opening pull requests. This repo is not maintained anymore. Please open issues on the new repository: https://github.com/AR-js-org/AR.js. Thank you!
