### ISSUE TITLE
Aframe nft image tracking not working on mobile device. all time show loading please wait........

### ISSUE THREAD

**Issue by moshiuzzaman** [jeromeetienne/AR.js#814]
**Describe the bug**
Aframe nft image tracking working on my laptop () but its not working on android. I checked it 4 different devices. output show 
loading please wait...….. . 

https://ar-js-org.github.io/AR.js-Docs/image-tracking
I copy code from here .

I need a solution with example.

**Comment by makakrap** [comment]
I have the same problem. 
Work on laptop but not on mobile (iphone 12).
From mobile i cant see error logs 
I used Ar.js studio with a .zip format for the 3d object (glTF). 30mb file

**Comment by denisemendez007** [comment]
I have the same problem on an android Pixel 5a.  It doesn't work on my windows 11 machine on either chrome or edge browsers.

**Comment by BaayaD** [comment]
> I have the same problem on an android Pixel 5a. It doesn't work on my windows 11 machine on either chrome or edge browsers.

Doesn't work on windows 11, iOS or android now. :(

**Comment by Pavel05091984** [comment]
So what's the reason?

**Comment by ardenschager** [comment]
I am also having this issue

**Comment by julienbfabre** [comment]
Same issue, looking at the console i see:

`WebAssembly.instantiate(): Out of memory`

Any ideas?

**Comment by weiness** [comment]
Don't use demo, clone github, got it

**Comment by Pavel05091984** [comment]
Good time of day
Tell me how to do it?

Отправлено из приложения "Почта<https://go.microsoft.com/fwlink/?LinkId=550986>" для Windows

От: ***@***.***>
Отправлено: 11 января 2023 г. в 9:13
Кому: ***@***.***>
Копия: ***@***.***>; ***@***.***>
Тема: Re: [jeromeetienne/AR.js] Aframe nft image tracking not working on mobile device. all time show loading please wait........ (Issue #814)


Don't use demo, clone github, got it
