### ISSUE TITLE
phonegap implementation

### ISSUE THREAD

**Issue by darasat** [jeromeetienne/AR.js#82]
Good day Jerome, 

I am doing the implementation of this project with aframe , aframe ar in an application with cordova, it's possible to do this with typecam source or the phonegap camara plugin.

I will do some tests for the concept.

Greetings.

**Comment by jeromeetienne** [comment]
excelent. i would love AR.js to be able to run on IOS 👍

So many people asks about this!

**Comment by jeromeetienne** [comment]
relevant tweets
- https://twitter.com/leemayren/status/871040767258710016


- https://github.com/revolunet/ios-webrtc a sample apps is working!! by @revolunet

**Comment by darasat** [comment]
Good day, 

I could do the implementation with this plugin  https://github.com/alongubkin/phonertc

and visual studio tools for apache cordova

https://www.visualstudio.com/vs/cordova/

and the demo that you created

https://dev.to/andraconnect/augmented-reality-in-10-lines-of-html


thank you very much for this library!

greetings.

**Comment by jeromeetienne** [comment]
@darasat seriously ??? i would be so great! please share a a screenshot :)

**Comment by darasat** [comment]
Hello again Jerome,
 
I experienced some kind of black screen with the new version of aframe-ar.js , reason for I cannot share in this moment an screenshot.

However I created a dropbox link with the app in phonegap for visual studio 2015

https://www.dropbox.com/s/t11nze6eaqjjtc5/test-ar.7z?dl=0

The app has been tested in Android 6 using crosswalk plugin (check this forum https://phonegap.com/blog/2016/11/17/webvr-and-phonegap/)


for build the app we have to consider  this.


1. Include the neccesary plugins like crosswalk webengine , phone rtc.

2. Read the guide of microsoft 
http://taco.visualstudio.com/en-us/docs/tutorial-package-publish-readme/
 for build the app the respective environment like (android, ios)

3. Install android emulator from this link  https://www.visualstudio.com/es/vs/msft-android-emulator/?rr=https%3A%2F%2Fwww.google.com.co%2F 

greetings!

**Comment by jeromeetienne** [comment]
The blackscreen issue may be related to a mistake i did this weekend. I fixed it today tho :)
https://github.com/jeromeetienne/AR.js/commit/8b0397c3cab4edde20f18101b00c0629af160983#diff-0aeecb818036feb4553895dffbc874ef

**Comment by jeromeetienne** [comment]
we included all the modifiation to get AR.js running on IOS11

**Comment by jeromeetienne** [comment]
"IDEA: make a phonegap plugin which read ARKit and export it as WebVR #AR"

i just got this idea, and this seems a good things to do for people with phonegap knowledge, hint :)

https://twitter.com/jerome_etienne/status/875733380847079430

**Comment by darasat** [comment]
Oh sounds interesting, 

I am goint to take a look this weekend

greetings!

**Comment by jeromeetienne** [comment]
i can help with the webvr part :)

**Comment by jeromeetienne** [comment]
Apparently it is opssible :) https://twitter.com/albn/status/875339136785362945

**Comment by jeromeetienne** [comment]
@darasat closing this one as it was mostly on webrtc.

Lets go on phonegap+arkit on #104 :)
