### ISSUE TITLE
Dead links to examples in the README

### ISSUE THREAD

**Issue by chrisuehlinger** [jeromeetienne/AR.js#83]
Hey, so I was trying to check out some of the examples and noticed that a lot of the links in the README (to both demos and source) are 404s. I cloned the repo and found that some of the HTML files were in directories that had been renamed (eg. webar-playground -> webar-playground-old) and others were either hard to find or missing. Can you please correct the links in the README?

Thanks in advance!

**Comment by jeromeetienne** [comment]
can you please give which link you found broken ? thanks :)

**Comment by jeromeetienne** [comment]
i would be happy to fix them :)
