### ISSUE TITLE
Doing markers cube

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#84]
with multi marker implementation, it should be possible to do markers cubes similar to the one below. We need to try and see if it is possible.  

this is a nice input + allow nice effect [here](https://twitter.com/BlendMedia_360/status/869646404305567744). it is inspired by [this twitter thread](https://twitter.com/jerome_etienne/status/869765239356747776)

![cube_marker_axes](https://cloud.githubusercontent.com/assets/252962/26627125/452b691a-45f1-11e7-82ef-89af5f1d6010.png)

**Comment by jeromeetienne** [comment]
this is a nice input + allow nice effect [here](https://twitter.com/BlendMedia_360/status/869646404305567744)

**Comment by jeromeetienne** [comment]
# Way to try that with AR.js
- print 6 markers - all the image are available [here](https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/marker-generator/examples/pattern-images/pattern-arjs.png) 
- use those markers hiro/kanji/a/b/c/f, and glue them on a cube 
- one marker on each face. no special order needed
- then go to the multimarkers learner page and learn the marker cube (aka put it on camera and move it around until each marker is learned
- you can use [webar-playground](https://jeromeetienne.github.io/webar-playground/) for that

**Comment by jeromeetienne** [comment]
# Source of markers cube
- https://github.com/artoolkit/artoolkit5/tree/master/doc/patterns/Cubes

**Comment by nicolocarpignoli** [comment]
not a real "issue". closing
