### ISSUE TITLE
Is it posibble to create custom pattern?

### ISSUE THREAD

**Issue by ookangzheng** [jeromeetienne/AR.js#87]
I want to use ARjs from mobile web to scan the T-shirt Logo ( Zara, h&m, Forever 21) something
or I have to connect with Vuforia SDK (unity) ?

thanks

**Comment by jeromeetienne** [comment]
unfrotunatly, image based marker arent supported by AR.js at the moment.

**Comment by carllx** [comment]
now it support Image tracking！This project repository has been moved to a [Github organization account](https://github.com/AR-js-org/AR.js)
