### ISSUE TITLE
Issue with local deployment

### ISSUE THREAD

**Issue by hipstermojo** [jeromeetienne/AR.js#88]
I served the code locally and it was showing nicely on the computer but it gives an error on the mobile. It says "can't access media"

**Comment by darioodiaz** [comment]
If you are using localhost as server you must use and https connection because Chrome dont give accesss to camera on insecured hosts.

https://stackoverflow.com/questions/35127383/npm-http-server-with-ssl

There is a solucion using a ssl certificate with openssl and http-server module if you are using express or browser-sync or other server find how to use ssl on in and try again

**Comment by curtello** [comment]
funny enough I am using both browser-sync and express. 

I have tried it on Mozilla on the phone and it doesn't display a thing

**Comment by jeromeetienne** [comment]
try to server it over localhost, just to be sure this is not a webrtc-https thing

**Comment by curtello** [comment]
I deployed it on Heroku. When I use Chrome on Mobile it still doesn't work

**Comment by jeromeetienne** [comment]
maybe you should contact heroku then

**Comment by darioodiaz** [comment]
Android version? I have the same problem but was because Chrome on some older android versions dont work, when I use Chrome Canary of Firefox it works (again, check your browser options and see that camera permission is available)

**Comment by curtello** [comment]
When I launch the examples from this repo, they work fine. But my own project isn't working on mobile browsers. It's working on Mozilla though.

**Comment by darioodiaz** [comment]
mmm so maybe is a Chrome issue or some miss configuracion when running it local

**Comment by darioodiaz** [comment]
besides that the error "Cant access user media :(", if you see the code, is raising when cant use the camera (permissions problems 99% times)

**Comment by curtello** [comment]
It still shows the same error when I run it over Heroku, so it's not an SSL issue.

**Comment by scapicIntern** [comment]
Sometimes when you run over heroku open your browser and see if it's https if not change it to https my give your a security warning but that's fine. 
and sometimes it doesn't work on the chrome app try chrome beta.

**Comment by pratiksampat** [comment]
Sometimes when you run over heroku open your browser and see if it's https if not change it to https my give your a security warning but that's fine. 
and sometimes it doesn't work on the chrome app try chrome beta.

**Comment by darioodiaz** [comment]
try to do that, go to ar.js code and search "cant access user media" (or the alert box that you see) put a breakdown point near there and refesh the browser then debug it to find if its something related to permissions or other issue

**Comment by hmenonv** [comment]
same here , cant access user media in chrome but works on mobile firefox browser running locally..
![screenshot_2017-07-02-17-56-28](https://user-images.githubusercontent.com/4978733/27769841-a26e9372-5f50-11e7-9bda-cfd962b774ec.jpg)

**Comment by hmenonv** [comment]
same here , cant access user media in chrome but works on mobile firefox browser running locally..
![screenshot_2017-07-02-17-56-28](https://user-images.githubusercontent.com/4978733/27769857-f7a32d80-5f50-11e7-82f9-d0867b1b3097.jpg)

**Comment by jeromeetienne** [comment]
Here is a answer about the https getUserMedia. i hope it helps

https://jeromeetienne.github.io/AR.js/docs/misc/FAQ.html#cant-access-user-media-error

**Comment by aasisodiya** [comment]
I'm trying to host a code on hostinger.
But it gives error(can't access user media :())
Hostinger use http and not https
What can I do to make it work on http???

**Comment by pratiksampat** [comment]
It will not work on http as the browser disables the access of media decides on http with isn't considered secure

**Comment by aasisodiya** [comment]
So isn't there any other way around?

**Comment by TonyButterfield** [comment]
Same here. Our IT manager set up a https web page for me to test and he wasn't able to get it to work.
We saw the fps graph and the text at the top of the page. We pulled down everything from github.
Still stuck.
Tony B.

**Comment by pratiksampat** [comment]
For hosting make sure you acquire the required certificates from the vendor 
But for locally I would suggest you read this 
https://deliciousbrains.com/https-locally-without-browser-privacy-errors/

**Comment by sourabh2k15** [comment]
If your website is http , consider cloudflare to get a free https along
with other benefits, as for local deploy you could use ngrok tunnels which
are https .
https://www.cloudflare.com
https://ngrok.com
