### ISSUE TITLE
Sending too many useless resize on aframe.js

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#91]
see this tweet https://twitter.com/fr3ino/status/872516862025838592

**Comment by jeromeetienne** [comment]
cc @freinbichler easier for me to track here :)

**Comment by jeromeetienne** [comment]
60 time per seconds is surely silly :)

**Comment by ZoltanVeres** [comment]
A PR is very welcomed!

**Comment by nicolocarpignoli** [comment]
obsolete

**Comment by nicolocarpignoli** [comment]
the bug is still open. we will use this issue => https://github.com/jeromeetienne/AR.js/issues/574
