### ISSUE TITLE
A-Frame mode - Blank screen on web server

### ISSUE THREAD

**Issue by lucacattide** [jeromeetienne/AR.js#92]
Hi everyone.
Just tried this great utility on localhost, and it works well.
Later, I tried to upload my demo project online, hosting it on a web server, to try the mobile camera mode. But it returns blank screen. 
On the console, I read a warning about the suggestion to use SSL. I googled it and found the policy about the use of ```UserMedia``` via HTTPS, and so on.
It should be the that? Actually I didn't tried it yet via HTTPS but I'll do it.

Thanks in advance.

**Comment by jeromeetienne** [comment]
Hi @lucacattide 

yep, getusermedia require a secure source and it may be a pain during deployement. see this section of the FAQ about it

https://github.com/jeromeetienne/AR.js#how-to-run-arjs-locally

i hope this help
