### ISSUE TITLE
Resize Windows/Scene

### ISSUE THREAD

**Issue by zhadowz99** [jeromeetienne/AR.js#95]
How can I resize the windows or the scene to a fixed size?

**Comment by jeromeetienne** [comment]
i think the easiest would be to handle the 3d in a iframe. 

i hope this help

**Comment by zhadowz99** [comment]
um... do you mean like this?
https://pastebin.com/GW5Q7QUU
if it's like that I always get an error cannot access usermedia...

**Comment by zhadowz99** [comment]
And done...
Well I can't resize the screen but I can put a div in front of the scene like you did in your div contact.
Well in the end it works for me.
Thanks Jerome.
