### ISSUE TITLE
[Help] Making an AR game using aframe-physics-system

### ISSUE THREAD

**Issue by darioodiaz** [jeromeetienne/AR.js#97]
Hi ! I was trying to do an AR game like ps vita or your ideas section, but I have problems, my idea is use a flat plane as static-body and the markers as dynamic bodies, so when markers make visible objects then interact and move them, but the I have a miss concept, AR.js (ARtooklit or AR in general), change the camera perspective or object rotation? because when markers are visible it is not colliding with the plane and the plane looks fixed in the 3d scene, If I want to use aframe-physics is any code snippet to help me? or I have to do that idea with pure three.js ?

I hope your understand my problem

**Comment by jeromeetienne** [comment]
@darioodiaz sorry i m not sure i understand the questions. 

I dont think you would need three.js for that. you can likely do it in a-frame with some js on top. i never tried tho.

I would love to see more AR.js game

**Comment by darioodiaz** [comment]
Sorry I have some troubles writting complex situations or ideas haha (my english needs more practice) I want to do a simple game, using aframe-physics, I add a plane on the scene (as static body) and the markers will be dynamic body, but I'm dont undestaning what AR.js does, because the marker has dynamic-body attribute but isn't collide with the plane, it falls down.

Now, my question xD , AR.js track the marker, put the 3d object for that marker visible right? and modify the rotation or position of the 3d object inside the marker? or only make it visible or not? Today I'll upload a few examples to show you (If you have time to check it) but I'll read more about how AR works or artoolkit works, because maybe I have some missconcepts and thats why I'm not understanding.

Thank you and if you dont understand me, please let me know to do a better comment :p

**Comment by darioodiaz** [comment]
By the way, I was making another more simple game using AR.js and aframe-physics, when I have a beta I'll show you :)

**Comment by catatonix** [comment]
Any progress with any of this? I've been having some hiccups getting physics (specifically gravity) working with ar.js and a-frame.

**Comment by nicolocarpignoli** [comment]
any update on this? if this is obsolete i will close it
