### ISSUE TITLE
Custom marker size

### ISSUE THREAD

**Issue by dirathea** [jeromeetienne/AR.js#98]
According to [this page](https://aframe.io/docs/0.5.0/introduction/faq.html#what-type-of-units-does-a-frame-use), the units that used is on meters for each unit on `a-frame`.
But it's slightly different in AR.js. A unit is equal to marker width, so when we tried to make a bigger object than the marker, we must convert the size into "marker width" unit, rather than meters.

I tried to tweak this by set the `size` properties on `a-marker-camera` to match the real life marker size, but there's no luck. Here's my code : https://codepen.io/dirathea/pen/qjaPQX
I've set the size to `0.15` because my marker is printed 15cm on the paper. but the object is never displayed.

Please help :)

**Comment by nicolocarpignoli** [comment]
please if help is still needed, ask on the official https://gitter.im/AR-js/Lobby
