### ISSUE TITLE
When a marker/pattern is visible, does it return a value?

### ISSUE THREAD

**Issue by memidgety** [jeromeetienne/AR.js#99]
My question is when the marker is visible, is there a property or method that can return whether or not the marker is visible?

For instance, in the multiple pattern example, if one of the markers is not detected, does it return a value that you can use to script with?

I am currently playing video on one marker, and I want to play a video on another marker, but I need to mute the sound when one of the markers is not detected.

Cheers

**Comment by jeromeetienne** [comment]
yes, the marker object3d will be .visible or not. This is directly inherited directly by three.js

When you attach a object3d to a marker, you attach it to a THREE.Group. it is called markerRoot in most of my sources

if markerRoot.visible === false then the marker isnt seen
if markerRoot.visible === true then the marker isnt seen

There are some events too, but it is still unclear - see event ```markerFound```

https://github.com/jeromeetienne/AR.js/blob/master/three.js/threex-armarkercontrols.js#L166

i hope this helps

**Comment by memidgety** [comment]
Thanks!
Lastly though, how would I access the markerRoot from `<a-marker>` ?

**Comment by memidgety** [comment]
Thanks! Great work by the way!
